### ISSUE TITLE
Email address detection in markdown faulty

### ISSUE THREAD

**Issue by andreasabel** [haskell/hackage-server#1001]
See e.g. [hackage.haskell.org/package/BNFC-2.9.4/candidate](https://hackage.haskell.org/package/BNFC-2.9.4/candidate):
The email bnfc-dev@googlegroups.com (under Support) is rendered wrongly as bnfc[-dev@googlegroups.com](mailto:-dev@googlegroups.com).

**Comment by gbaz** [comment]
I believe this issue is with `commonmark` that hackage uses for markdown.

**Comment by andreasabel** [comment]
Installing the latest version, with `commonmark -x autolinks README.md` I get the correct rendering:
> ... our mailing list <a href="mailto:bnfc-dev@googlegroups.com">bnfc-dev@googlegroups.com</a>.

Without the `autolinks` extension, I get no rendering of the mail address:
> ... our mailing list bnfc-dev@googlegroups.com.

**Comment by andreasabel** [comment]
@gbaz Could it be the ordering of syntax specifications, see comment https://github.com/haskell/hackage-server/pull/904/files#r804234727 ?
