### ISSUE TITLE
Support CSS feature `prefers-color-scheme`

### ISSUE THREAD

**Issue by peterbecich** [haskell/hackage-server#1007]
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme
> The prefers-color-scheme [CSS](https://developer.mozilla.org/en-US/docs/Web/CSS) [media feature](https://developer.mozilla.org/en-US/docs/Web/CSS/Media_Queries/Using_media_queries#media_features) is used to detect if the user has requested a light or dark color theme.

GitHub and Google support this feature.

**Comment by kandji-edwin** [comment]
Are there color palettes for light and dark themes that would be used for this?

**Comment by peterbecich** [comment]
@kandji-edwin , I haven't found any so I took the existing colors and guessed: https://github.com/haskell/hackage-server/pull/1008#issuecomment-1041057801

**Comment by peterbecich** [comment]
Improvement: https://github.com/haskell/hackage-server/pull/1281
