### ISSUE TITLE
[Missing redirect] Data.Eq is missing source redirects

### ISSUE THREAD

**Issue by KristianBalaj** [haskell/hackage-server#1015]
All the source redirects in the `Data.Eq` are missing the redirects. This results in 404 pages.

https://hackage.haskell.org/package/base-4.16.0.0/docs/Data-Eq.html

**Comment by andreasabel** [comment]
Correct: https://hackage.haskell.org/package/ghc-prim-0.8.0/docs/src/GHC.Classes.html#Eq
Linked: https://hackage.haskell.org/package/base-4.16.0.0/ghc-prim-0.8.0/src/GHC-Classes.html#Eq

**Comment by gbaz** [comment]
This is not a docbuilder issue -- the base and ghc- packages are uploaded manually by the ghc team.

**Comment by gbaz** [comment]
For the same reason we cannot reinstall base, we also cannot ask the docbuilder to haddock it :-)

**Comment by andreasabel** [comment]
Do we have to report this upstream to the GHC team then?

**Comment by sjakobi** [comment]
I have already reported this in https://gitlab.haskell.org/ghc/ghc/-/issues/20698.
