### ISSUE TITLE
GHC 9.0 and Cabal 3.4

### ISSUE THREAD

**Issue by andreasabel** [haskell/hackage-server#1016]
This issue tracks progress of building with GHC 9.0.  Add blockers to the list:
- [x] `hackage-security` (https://github.com/haskell/hackage-security/pull/265, https://github.com/haskell/hackage-security/pull/266)
- [x] `acid-state` (https://github.com/acid-state/acid-state/issues/137)

Building can now be started with:
```
$ cabal build -w ghc-9.0.2 --allow-newer=Cabal --constraint='Cabal==3.4.*'
```
TODO:
- [ ] migrate to `Cabal-3.4`

**Comment by ysangkok** [comment]
@andreasabel The second check box can be checked.

**Comment by andreasabel** [comment]
Upgrading `Cabal` is becoming more urgent now, see #1030.
