### ISSUE TITLE
Hackage is down - error 503

### ISSUE THREAD

**Issue by brunoczim** [haskell/hackage-server#1028]
![image](https://user-images.githubusercontent.com/18701450/157054337-5661a209-6a9e-477b-8ef0-fd83bd0db135.png)

**Comment by sjakobi** [comment]
Works fine for me in Germany.

**Comment by brunoczim** [comment]
I tested it on my phone, and it curiously it worked. I first thought this was a DNS problem. But chaning DNS won't work and my PC with Linux still can't acess hackage. I tried rebooting too.

I am in Brazil btw

**Comment by brunoczim** [comment]
The problem is also not the browser, the same thing happens on both Firefox and Chromium

**Comment by andreasabel** [comment]
Works fine from Sweden.
