### ISSUE TITLE
Recent uploads barely covers 2 days

### ISSUE THREAD

**Issue by andreasabel** [haskell/hackage-server#1029]
Owing to the popularity of Haskell and Hackage, the page https://hackage.haskell.org/packages/recent , listing the 25 most recent uploads, barely covers two days of uploads.

Possible improvements:
1. (Easy but not great:) Show uploads of last 2 weeks.
2. (More work:) Make page configurable with
    a. # per page option
    b. jump to next page button

**Comment by gbaz** [comment]
In the rss description it says it is 20 most recent or the last 48 hours, whichever is greater.
