### ISSUE TITLE
Packages with GHC 9.2 language extensions rejected

### ISSUE THREAD

**Issue by georgefst** [haskell/hackage-server#1030]
I can't upload a package to Hackage that uses recent extensions:

```
cabal upload --publish /home/gthomas/code/lifx-lan/dist-newstyle/sdist/lifx-lan-0.7.tar.gz
Uploading
/home/gthomas/code/lifx-lan/dist-newstyle/sdist/lifx-lan-0.7.tar.gz...
Error uploading
/home/gthomas/code/lifx-lan/dist-newstyle/sdist/lifx-lan-0.7.tar.gz: http code
400
Error: Invalid package

Unknown extensions: NoFieldSelectors, OverloadedRecordDot
```

Possibly related to #1016?

**Comment by georgefst** [comment]
(I was pointed here by https://www.reddit.com/r/haskell/comments/shmn9z/comment/hxu8sfq/?utm_source=share&utm_medium=web2x&context=3)

**Comment by phadej** [comment]
Not related to #1016. `hackage-server` can be built against `Cabal-3.6` with old GHCs as well. The upgrades are better done separately. (GHC is somewhat straight-forward, upgrading used `Cabal` is often more complicated).

**Comment by andreasabel** [comment]
A first stab is at 
- #1031.  This would at least allow GHC 9.0 language extensions.

**Comment by andreasabel** [comment]
OP may be fixed by:
- #1038

**Comment by georgefst** [comment]
I am still getting the same error. Is that just because the fix hasn't yet been deployed?

**Comment by gbaz** [comment]
Yes, we're planning a redeploy tomorrow, tentatively.

**Comment by georgefst** [comment]
Awesome! I managed to upload the package.

Although building [fails](https://hackage.haskell.org/package/lifx-lan-0.7/reports/1) because the server appears to be running GHC 8.10.7. Does that mean https://github.com/haskell/hackage-server/issues/1040 wasn't deployed simultaneously?

**Comment by georgefst** [comment]
> Does that mean #1040 wasn't deployed simultaneously?

Ah, just noticed #1040 is an issue, not a PR. Was that closed erroneously?

**Comment by gbaz** [comment]
No -- that is about being able to build hackage server itself with ghc 9.2. Moving the hackage-builder to build haddocks using another version of ghc is something else entirely.
