### ISSUE TITLE
Make Banners clickable

### ISSUE THREAD

**Issue by andreasabel** [haskell/hackage-server#1035]
E.g. https://hackage.haskell.org/package/bytestring shows banners:
![Screenshot 2022-03-24 at 18 49 23](https://user-images.githubusercontent.com/1155218/159978955-fafd4706-9236-445d-a513-b336a1be66c6.png)
It would be nice if:
- clicking on the Build banner would take me to the build report
- clicking on the Documentation banner would take me to the doc build report
- ...

(The other banners do not seem to have matching reports yet.)

**Comment by ysangkok** [comment]
I don't think the 'doc build report' is exposed. For the linked bytestring package, I see only a single report. What did you mean by 'doc build report' and do you have a link for it?

**Comment by andreasabel** [comment]
Ah, sorry, I didn't look closely.  Indeed there is just one report for all, which could be the target of both of these banners.
<img width="873" alt="Screenshot 2022-03-25 at 08 21 25" src="https://user-images.githubusercontent.com/1155218/160073685-70f6aafc-5c91-426c-9ef2-521366a5504e.png">
