### ISSUE TITLE
vendor snowball to remove text-icu dep

### ISSUE THREAD

**Issue by gbaz** [haskell/hackage-server#1036]
The text-icu dep is just needed for some encoding stuff that can be done in pure haskell, and snowball can easily be modified to not use it.

Since it causes so much pain on various systems, i'd prefer if we vendored the (effectively unmaintained) snowball package to avoid having to deal with this.

**Comment by AliasQli** [comment]
I'd like to work on this, and have removed snowball's text-icu dep locally. However, I don't know how to contribute: I forked the original repo, but it has some updates and is unable to build now.
