### ISSUE TITLE
Some recent change broke formatting (Firefox 98.0.2 / Linux)

### ISSUE THREAD

**Issue by sol** [haskell/hackage-server#1048]
Versions / Dependencies are not shown to the main content.  Instead they are shown at the bottom-right.

This wasn't the case until very recently.

Screen (30%):

![screen](https://user-images.githubusercontent.com/461132/161414755-13c9c822-7dad-45ab-9089-14936ea0677c.png)

**Comment by gbaz** [comment]
The css was upgraded but you may still have an old css in your browser cache. doing a hard reload should clear this up.
