### ISSUE TITLE
remove cabal > 2.0 restriction on files in the 00-index file?

### ISSUE THREAD

**Issue by gbaz** [haskell/hackage-server#1063]
This is a pretty ancient hack and imho there's no need to support cabal 1.x any more:

https://github.com/haskell/hackage-server/commit/9a6be09342095dda621c39ed3189904240a458e4

**Comment by andreasabel** [comment]
> no need to support cabal 1.x any more

Ubuntu LTS 18.04 ships with cabal-install 1.24: https://packages.ubuntu.com/bionic/cabal-install

Will the `00-index` be removed eventually altogether?  Maybe that will be the right time to also dispose of the hack...

**Comment by gbaz** [comment]
LTS 18.04 is eol on april 30 2023, i think we can go ahead now.

I tend to think we need 00-index around for the "not setting up hackage security" option as there's no way to do an 01-index without jumping thru those hoops.
