### ISSUE TITLE
Doc builder fails for bzlib-conduit (Missing C library: bz2)

### ISSUE THREAD

**Issue by jappeace** [haskell/hackage-server#1064]
It says it needs the bz2 c library installed:

```
Failed to install bzlib-conduit-0.3.0.2
Build log ( /home/builder/.cabal/logs/ghc-8.6.3/bzlib-conduit-0.3.0.2-L7ReoiiYQc8FcUoKYamZN.log ):
cabal: Entering directory '/tmp/cabal-tmp-24972/bzlib-conduit-0.3.0.2'
Configuring bzlib-conduit-0.3.0.2...
cabal: Missing dependency on a foreign library:
* Missing (or bad) C library: bz2
This problem can usually be solved by installing the system package that
provides this library (you may need the "-dev" version). If the library is
already installed but in a non-standard location then you can use the flags
--extra-include-dirs= and --extra-lib-dirs= to specify where it is.If the
library file does exist, it may contain errors that are caught by the C
compiler at the preprocessing stage. In this case you can re-run configure
with the verbosity flag -v3 to see the error messages.

cabal: Leaving directory '/tmp/cabal-tmp-24972/bzlib-conduit-0.3.0.2'
cabal: Error: some packages failed to install:
bzlib-conduit-0.3.0.2-L7ReoiiYQc8FcUoKYamZN failed during the configure step.
The exception was:
ExitFailure 1
```

https://hackage.haskell.org/package/bzlib-conduit-0.3.0.2/reports/3

**Comment by qrilka** [comment]
@andreasabel I have a suspicion that adding a proper `pkgconfig-depends` entry could fix this, is there any documentation(or source code?) for the Hackage builder where I could check that?

**Comment by gbaz** [comment]
That won't fix this. pkg-config depends won't auto-install c libraries.

It needs installing on the docbuilder machine (I just did this) -- we try to track that process with PRs to https://github.com/haskell-infra/hackage-doc-builder-config (which I also just did).

Other tickets (https://github.com/haskell/hackage-server/issues/595) discuss trying to highlight this process more prominently.
