### ISSUE TITLE
`cabal upload --documentation --publish` doesn't seem to work

### ISSUE THREAD

**Issue by mitchellwrosen** [haskell/hackage-server#1069]
Hi,

I'm trying to publish haddocks manually to fix a typo.

I ran `cabal upload --documentation`, then `cabal upload --documentation --publish`. Both reported successful uploads on the command-line.

The "candidate" docs seem to have been uploaded fine:

https://hackage.haskell.org/package/termbox-banana-0.3.1/candidate/docs/Termbox-Banana.html

yet the non-candidate docs haven't changed:

https://hackage.haskell.org/package/termbox-banana-0.3.1/docs/Termbox-Banana.html

Am I able to publish haddocks manually, or do I need to upload a new version?

Thanks!

**Comment by mitchellwrosen** [comment]
Thanks. ...but I tried that, and no dice. Then I tried just deleting the docs, but not re-uploading anything, and nothing happened: 

https://hackage.haskell.org/package/termbox-banana-0.3.1/docs/Termbox-Banana.html

(Maybe when this comment is a certain age, the above link will no longer work?)

**Comment by mitchellwrosen** [comment]
Huh. The link does work, but I see you can no longer get there from the main package page, so that's promising. One moment...

**Comment by mitchellwrosen** [comment]
Uploading new docs seems to just restore a clickable link to the old docs. Does that sound right to you? Is there anything else I need to do? (Perhaps wait for some garbage collection process to run on the Hackage server, or something?)

**Comment by mitchellwrosen** [comment]
Everything seems fine, now. 😅

**Comment by gbaz** [comment]
Hackage server runs behind a cdn. So you can add a query string like ?foo to the end of a url to bypass it (or hit hackage-origin.haskell.org).

Which leads me to wonder if the initial reupload of docs worked too, but it was just the cdn preventing noticing this.
