### ISSUE TITLE
Show signatures in index page

### ISSUE THREAD

**Issue by ffaf1** [haskell/hackage-server#1071]
See as an example [this index page on hackage](https://hackage.haskell.org/package/xml-1.3.14/docs/doc-index-A.html). Having:

    attrib :: LString -> (String, LString)

would be better than current layout (plain `attrib`, no sig, just module link).

**Comment by gbaz** [comment]
Please file this against haddock -- the index pages on hackage are simply generated by the haddock tool. (that said, I am dubious this would be an improvement for many packages which can already have very unwieldy index pages with many things defined, and also for which type signatures might be quite large themselves).
