### ISSUE TITLE
Search does not work well

### ISSUE THREAD

**Issue by dschrempf** [haskell/hackage-server#1072]
Hi!

For a few weeks now, I have the following (weird) problem:

Hackage search and clicking the "Advanced options" button:

- Works fine with Chromium.
- Does not work at all with Qutebrowser.
- With Firefox, and when the `?terms=` inquiry is left empty (which is the default when clicking "Search" on the top row), it takes around 10 seconds until the table is rendered and the  "Advanced options" becomes responsive.

Does anybody else experience problems with Hackage search?

**Comment by gbaz** [comment]
With a new hackage redeploy (soon, I promise!) the responsiveness should be fixed: https://github.com/haskell/hackage-server/pull/1049

qutebrowser will be fixed by: https://github.com/haskell/hackage-server/pull/1062

**Comment by gbaz** [comment]
ok, redeploy done.

**Comment by MichelBoucey** [comment]
At the moment search requests are still broken.
```
https://hackage.haskell.org/packages/search?terms=lens`
```
gives :
```
Error with Hackage server: Unexpected content-type: For this resource the content-type was expected to be application/json, rather than multipart/form-data; boundary=---------------------------55663260525875955564249068061
```

**Comment by andreasabel** [comment]
I don't get this error.

**Comment by noughtmare** [comment]
If I open e.g. https://hackage.haskell.org/packages/search?terms=lens I get this message in red:

```
Error with Hackage server: Unexpected content-type: For this resource the content-type was expected to be application/json, rather than multipart/form-data; boundary=---------------------------363225731826631620603428404 
```

![image](https://user-images.githubusercontent.com/2665074/168474368-6870c2ab-d735-43c7-a5cf-d0aaa9ba1f92.png)

**Comment by dschrempf** [comment]
On Qutebrowser and Firefox, search works for me now! I don't get any error messages. Thank you!

**Comment by tfausak** [comment]
Search is also broken for me. I've tried Firefox, Chrome, and Edge on Windows 10. I've also tried Safari on iOS 15.4.

![image](https://user-images.githubusercontent.com/408753/168475796-6ace53aa-bf19-44e5-a762-e74d0858d30a.png)

**Comment by tfausak** [comment]
It seems to be working now for me.

**Comment by gbaz** [comment]
When we redeployed the server, we needed to force fastly to purge the cached search script in favor of the new one. Apologies for not realizing this after the deploy. Should now be resolved for everyone.

**Comment by gbaz** [comment]
Closing as the redeploy _should_ have improved the above linked issues as well.

**Comment by gbaz** [comment]
(a hard refresh of the page to clear the cache may be necessary for end-users as well, sorry!)
