### ISSUE TITLE
Cannot register new accounts

### ISSUE THREAD

**Issue by tochicool** [haskell/hackage-server#1073]
Hi,

When trying to register a new account on Hackage with a valid email address, you are redirected to the following error page:

_Problem with email address
Oops, that doesn't look like an email address._

![Screenshot_20220515_164917](https://user-images.githubusercontent.com/4491786/168481689-0730be68-cd38-4614-9bbe-5df3759b7e57.png)

This looks like an error in the email address validation logic.

**Comment by gbaz** [comment]
Thanks for the quick notification and fix! Currently redeploying
