### ISSUE TITLE
Improve "Deprecated. in favor of foo-bar"

### ISSUE THREAD

**Issue by andreasabel** [haskell/hackage-server#1102]
E.g. see https://hackage.haskell.org/package/regex-tdfa-unittest

<img width="694" alt="Screenshot 2022-07-15 at 11 17 50" src="https://user-images.githubusercontent.com/1155218/179193996-1723becb-1dbe-4278-a186-79adeb476c0b.png">

This has bad punctuation.

Also, I think this information should be more prominent, e.g. printed in __bold__ and/or red.

**Comment by andreasabel** [comment]
> Also, I think this information should be more prominent, e.g. printed in **bold** and/or red.

As of today, it is already printed in red.  (However, I think this red does not harmonize with the other colors:)
<img width="718" alt="Screenshot 2023-04-12 at 22 01 53" src="https://user-images.githubusercontent.com/1155218/231571588-ba5a105a-6860-4d4b-bc53-55607721ecec.png">

**Comment by ulysses4ever** [comment]
+1; for adding bold. Some styling to make it more prominent could help too. But I have no idea how to do it...

**Comment by andreasabel** [comment]
Red color was added here: https://github.com/haskell/hackage-server/commit/8b2be1824bbf1cbc6cbc1a66be7e9ee85a501d62
