### ISSUE TITLE
Possible security issue with user name-contact page

### ISSUE THREAD

**Issue by AliasQli** [haskell/hackage-server#1106]
Page `https://hackage.haskell.org/user/:username/name-contact` can be visited without authorization where `:username` can be *any* username, and user's full name and email can be viewed on that page. This seems to be a security issue.

**Comment by AliasQli** [comment]
Quick fix: add `guardAuthorised_ [IsUserId uid, InGroup adminGroup]` to `Distribution.Server.Features.UserDetails.handlerGetUserNameContactHtml`.

**Comment by gbaz** [comment]
I don't think that we ever considered names and emails to require security -- the users are primarily package uploaders, and their contact information is expected to be public.

**Comment by phadej** [comment]
@gbaz that's plain wrong

On https://hackage.haskell.org/users/register-request it's very clearly stated that

> Your email address will be used to confirm your account (and if you ever need to reset your password). It will also be used if one of the site administrators ever needs to contact you. It will not be displayed on the website (but note that email addresses in .cabal files that you upload are public).

**Comment by gbaz** [comment]
Oh fair 'nuff. In that case a pr changing this is welcome.
