### ISSUE TITLE
Hackage synopsis menu is broken

### ISSUE THREAD

**Issue by why-not-try-calmer** [haskell/hackage-server#1112]
The Hackage website's yellowish "synopsis" css menu is broken on my browser. That is, it fails to scroll me up or down to the target href while also intercepting page search keywords. For you as well? (I am surprised I couldn't find a similar Issue pending so perhaps it's just me...)

Flipping through Hackage users to be a joy but now it's sheer annoyance.

**Comment by gbaz** [comment]
For now I'll close with a reference to https://github.com/haskell/haddock/issues/1451

Once that haddock is released, not sure what can be done outside of trying to regenerate a ton of old docs.

**Comment by gbaz** [comment]
Actually -- hmm. It simply requires making sure the following little bit is in the css of the bundled haddocks:

https://github.com/haskell/haddock/pull/1486/files

I think we can try to dynamically rewrite the haddocks to insert that css.

**Comment by gbaz** [comment]
There's some rough code here that shows how to do it: https://github.com/haskell/hackage-server/commit/bc903d36955b52656ea4db246e000710c3c00709

**Comment by why-not-try-calmer** [comment]
Okay thanks for stepping in. Just to be clear, from the label you've added and from your reply I take it that the maintainers are not interested in doing this? (Not trying to be patronizing here, just to clarify).

**Comment by gbaz** [comment]
On the contrary, we have ongoing gsoc work right now and I was hoping that @AliasQli would find time to look at this.

**Comment by why-not-try-calmer** [comment]
> On the contrary, we have ongoing gsoc work right now and I was hoping that @AliasQli would find time to look at this. 

Ah that's great, sorry for misreading

**Comment by why-not-try-calmer** [comment]
It still fails to work on my machine. Did the change hit production already?

**Comment by gbaz** [comment]
not yet, no

**Comment by MathiasSven** [comment]
In the meanwhile, something like `Stylebot` extension with the CSS given in the commit fixes the issue:
```css
#synopsis details:not([open]) > ul {  
  visibility: hidden; 
}
```
