### ISSUE TITLE
Can't build with updated dependency

### ISSUE THREAD

**Issue by AliasQli** [haskell/hackage-server#1125]
The dependency `haddock-library` updated from 1.10.0 to 1.11.0, and made an uncompatible change. The type signature of `DocMarkUpH`'s field `markupOrderedList` changed from `[a] -> a` to `[(Int, a)] -> a`. The version bound for `haddock-library` is `> 1.7 && < 2`, and as a result, the repo can't build with the latest dependencies.

Should we tighten the version bound for this library?

**Comment by gbaz** [comment]
I think it would be better to update to work with the latest `haddock-library` and use a bound to cut off prior versions, if possible.

**Comment by AliasQli** [comment]
And there's another one: `hackage-security` updated to 0.6.2.2, which depends on `Cabal-syntax-3.8.1.0`, which is incompatible with our current dependency `Cabal ^>= 3.6`. Should we also move to `Cabal-3.8.1.0`? If so, a few changes need to be made.

**Comment by gbaz** [comment]
Moving to the latest cabal is absolutely on the to-do list. If you're up to take that on, that would be great!

**Comment by andreasabel** [comment]
Oops, I independently did the tightening in:
- #1128 
- #1130
- #1131
