### ISSUE TITLE
Inconsistencies in Content-Type returned for /readme.txt

### ISSUE THREAD

**Issue by Kleidukos** [haskell/hackage-server#1127]
Some package have their `/readme.txt` content returned as `text/plain; charset=utf-8`, like [text-show](https://hackage.haskell.org/package/text-show/readme.txt), and others have the content type set as `text/plain`, like [cpsa](https://hackage.haskell.org/package/cpsa/readme.txt).

I have two questions:

1. Where would this difference come from;
2. Couldn't we force all `.txt` files to be sent as `text/plain; charset=utf-8`?

Cheers

**Comment by gbaz** [comment]
mime matching is done here: https://github.com/haskell/hackage-server/blob/b4ea1c73ba85f24985259fd1df4664747ceb0159/src/Distribution/Server/Framework/HappstackUtils.hs#L68

txt falls through to the mimeTypes map from happstack, which should be just "text/plain" -- for some reason one of those readmes doesn't match that (not sure why!) so we get the default which also has the utf8.

We could add "txt" and "text" directly to customMimeTypes to override them and always ensure the utf8. A pr doing so would be welcome.

**Comment by Kleidukos** [comment]
Got it!
