### ISSUE TITLE
Upgrade happy?

### ISSUE THREAD

**Issue by brandonchinn178** [haskell/hackage-server#1132]
It seems like the Hackage server has an outdated version of Happy. `ghc-lib-parser` seems to be bundling `Parser.y` from the [GHC repo](https://gitlab.haskell.org/ghc/ghc/-/blob/master/compiler/GHC/Parser.y), which uses Happy 1.20 features, like `%shift`, which seems to be the cause of failures like:
* https://hackage.haskell.org/package/ghc-lib-parser-9.2.3.20220709/reports/2
* https://hackage.haskell.org/package/fourmolu-0.8.2.0/reports/1

**Comment by gbaz** [comment]
upgraded to a newer happy on the buildbox, and to ghc 9.2.4

**Comment by brandonchinn178** [comment]
Thanks! Is it possible to manually rerun these failing builds?

**Comment by gbaz** [comment]
Just go to "maintainers corner" and click "trigger rebuild" for that package. I just did so for the latest version of fourmolu.

**Comment by brandonchinn178** [comment]
Thanks!

**Comment by brandonchinn178** [comment]
I clicked "trigger rebuild" again for Fourmolu, but it hasn't seemed to start a new build

**Comment by gbaz** [comment]
There's some quirk I don't understand causing the logs of the new fourmolu builds to fail on upload. That said, there's a failure on building Lexer.hs in ghc-lib-parser regarding "couldn't match expected type Int16# with actual type Int#". Perhaps alex needs an update as well?

**Comment by brandonchinn178** [comment]
@gbaz did you upgrade alex as well? If so, can you trigger another rebuild for Fourmolu?

> causing the logs of the new fourmolu builds to fail on upload

Is that an issue we need to fix on our end, or is that a Hackage issue?
