### ISSUE TITLE
No test coverage reports for recent uploads

### ISSUE THREAD

**Issue by sol** [haskell/hackage-server#1135]
Hey there 👋 
I noticed that for recent uploads of [`hspec-core`](https://hackage.haskell.org/package/hspec-core-2.10.5) I am not getting test coverage reports anymore.

Is there something I can do to fix that?

#### Before:
![777CFB64-A79F-4A17-B258-D70E4DC2D0E3](https://user-images.githubusercontent.com/461132/189509047-7204895c-7bdc-4f7f-98a0-8e47eda5e4ae.jpeg)

#### Now:
![06C80646-4461-481B-B861-A7A0D8115E76](https://user-images.githubusercontent.com/461132/189509046-d0809e3c-9ff0-4ed3-bdbc-851a553c8ea5.jpeg)

**Comment by gbaz** [comment]
Thanks for the report! I think this occurred with our update to a newer ghc for building, but I can't say why offhand. I don't think I can investigate until next week.

**Comment by gbaz** [comment]
looks like the command that drives `cabal test` no longer works the same with the latest cabals (in the presence of a project file)

```
Downloading
http://hackage-origin.haskell.org/package/hspec-core-2.10.6/hspec-core-2.10.6.tar.gz
Resolving dependencies...
Error: cabal: Cannot test all the packages in the project because none of them
contain any components at all. Check the .cabal files for the packages and
make sure that they properly declare the components that you expect.
```

We'll need to debug and tweak the code. If you want to jump in, you can download hackage-server's repo, run the builder locally, and investigate how the command line goes wrong.

**Comment by gbaz** [comment]
Ok, this is now fixed by https://github.com/haskell/hackage-server/commit/e72ee4fc7044b6a2c4627262540f8a6942343a31

Packages which were built in the interim won't automatically get tests and coverage re-run. (I manually deleted the docs and reset the count for https://hackage.haskell.org/package/hspec-core-2.10.5 to confirm things work).

**Comment by gbaz** [comment]
Thanks again for the report, and sorry for the gap in (ahem) coverage.

**Comment by sol** [comment]
Thanks @gbaz 🙏
