### ISSUE TITLE
Support Cabal-3.8 & 3.10 innovations

### ISSUE THREAD

**Issue by andreasabel** [haskell/hackage-server#1146]
`hackage-server` now builds with `Cabal-3.8.1.0`, but does not support any `Cabal-3.8` specific features yet.  This is an umbrella issue to collect and discuss new features that `hackage-server` should get to fully support `Cabal-3.8`.

Lifted from https://github.com/haskell/hackage-server/pull/1141#issuecomment-1295262536:
- @ulysses4ever: multi-lib packages ?

**Comment by phadej** [comment]
As far as I understood, as soon as central `hackage-server` is deployed, it would be possible to upload packages with `cabal-version: 3.8`... making this issue more about user interface supporting them? (module listings & documentation in case of multi-lib packages etc.?)

**Comment by andreasabel** [comment]
After update to GHC 9.6 and Cabal-3.10 in #1186, the scope of this issue extends to Cabal-3.10:
- #1186

**Comment by gbaz** [comment]
version vs 3.10 deployed.
