### ISSUE TITLE
remove `LegacyPasswd` code and dependency on `crypt`

### ISSUE THREAD

**Issue by peterbecich** [haskell/hackage-server#1153]
`hackage-server` has a dependency on the `extra-library` `crypt`:
https://github.com/haskell/hackage-server/blob/5f5b8144ead7476f6c8af89844d84f9771106221/hackage-server.cabal#L443-L444

I believe that refers to this function: https://en.wikipedia.org/wiki/Crypt_(C)

It appears that `crypt` is deprecated:
https://www.gentoo.org/support/news-items/2021-10-18-libxcrypt-migration-stable.html

> The implementation of libcrypt.so within glibc has been deprecated
for a long time and will be removed in the near future.

> For this reason, we are following other distributions (where
this has been tested for years already) and switching to the 
external libxcrypt implementation, now also in stable installations.

It also looks like Nix is moving away from `libcrypt` to a different library `libxcrypt`: https://github.com/NixOS/nixpkgs/pull/181764

-------------------

The usage of the library in `hackage-server` is here:
https://github.com/haskell/hackage-server/blob/c3312b05eae311584e6fbbbc7201e742d87b6b9e/src/Distribution/Server/Features/LegacyPasswds/Auth.hs#L49

Can we replace `libcrypt` with `libxcrypt` , or replace this `foreign import ccall` with some other library like
- https://hackage.haskell.org/package/cryptonite
- https://hackage.haskell.org/package/crypt-sha512
- https://hackage.haskell.org/package/bcrypt-0.0.11/docs/Crypto-BCrypt.html#v:hashPassword

**Comment by peterbecich** [comment]
Maybe
> libmcrypt
> Replacement for the old crypt() package and crypt(1) command, with extensions

 https://search.nixos.org/packages?channel=unstable&show=libmcrypt&from=50&size=50&sort=relevance&type=packages&query=crypt

**Comment by peterbecich** [comment]
The easiest way to solve this is by deleting the "old-style crypt() auth", if possible:
https://github.com/haskell/hackage-server/blob/5f5b8144ead7476f6c8af89844d84f9771106221/src/Distribution/Server/Features/LegacyPasswds/Auth.hs#L29-L43

**Comment by gbaz** [comment]
At this point I think just ripping out the legacypasswd stuff is acceptable -- the migration has been over for a long time now. PR welcome.
