### ISSUE TITLE
Local generation of hackage documentation is broken.

### ISSUE THREAD

**Issue by amano-kenji** [haskell/hackage-server#1181]
`cabal haddock --haddock-for-hackage --enable-doc` command fails with the following error message.

```
haddock: internal error: /home/user/.cabal/store/ghc-9.0.2/brick-1.6-7a9d021dddc682bb18a00db0ed485b27a7a0b4f1361b817490465c5fa6106b7a/share/doc/html/doc-index.json: openBinaryFile: does not exist (No such file or directory)
cabal: Failed to build documentation for brick-tabular-list-0.1.0.1.
```

If I omit `--enable-documentation`, it builds hackage documentation without links to other hackage packages.

**Comment by gbaz** [comment]
Upstream tooling issue. Was either resolved in https://github.com/haskell/cabal/issues/8104 or continues to be tracked in https://github.com/haskell/cabal/issues/8326
