### ISSUE TITLE
"Latest version" field is not up to date

### ISSUE THREAD

**Issue by Lysxia** [haskell/hackage-server#1188]
For example the latest version of aeson is 2.1.2.1, but the search results say 2.1.1.0, even though the "Last U/L" date is correct.

![Screenshot 2023-02-28 at 11-53-34 Browse and search packages Hackage](https://user-images.githubusercontent.com/2515201/221847641-20dc86f9-0ceb-4bf8-b81d-b01c07833444.png)

**Comment by ulysses4ever** [comment]
Was fixed in #1184 (allegedly), just hasn't been released yet.

**Comment by gbaz** [comment]
should be released now.
