### ISSUE TITLE
suggestion: replace `hs-captcha` with `recaptcha`

### ISSUE THREAD

**Issue by peterbecich** [haskell/hackage-server#1190]
This package is newer
https://hackage.haskell.org/package/recaptcha

I assume it uses the free Google service https://developers.google.com/recaptcha

The package currently used is https://hackage.haskell.org/package/hs-captcha, which depends on `gd` https://hackage.haskell.org/package/gd-3000.7.3

I am trying to remove the dependency on the `gd` library; I am having difficulty getting this library to work in a Nix Flake: https://search.nixos.org/packages?channel=unstable&show=gd&from=0&size=50&sort=relevance&type=packages&query=gd

 https://github.com/haskell/hackage-server/pull/1154#issuecomment-1445834524

**Comment by gbaz** [comment]
Recapcha indeed uses the service, which requires much more work to coordinate and maintain than something fully self-contained. Hs-captcha and gd seem to mainly work fine, and I'm much prefer we try to figure out why that doesn't work.
