### ISSUE TITLE
MacOS GitHub Action minutes

### ISSUE THREAD

**Issue by peterbecich** [haskell/hackage-server#1193]
MacOS GitHub Actions cost more: https://docs.github.com/en/billing/managing-billing-for-github-actions/about-billing-for-github-actions#minute-multipliers

What is our allocation for GitHub Actions? Can we afford to build this `flake.nix` for Mac?

The benefit of enabling the Mac build is that Mac artifacts will be pushed to Cachix and save time for these developers:
https://github.com/haskell/hackage-server/blob/7d357fc874aaced1e7d2aa4061bd333560c12c85/.github/workflows/nix-flake.yml#L14-L16

These initial GitHub Actions builds took 25 minutes: https://github.com/haskell/hackage-server/actions/workflows/nix-flake.yml I think the cache was not yet populated. I expect future builds will be faster. Nonetheless, the 10x multiplier on the Mac build is quite a bit.

**Comment by andreasabel** [comment]
Are we paying for actions @gbaz ?  (I was assuming this was a free service for us.)

**Comment by gbaz** [comment]
We're not paying for actions, but we may have limits to our shared free plan. I confess I do not know the details and would have to dig in to figure that out.

That said, I'm a macos developer but I don't use nix. We have very few developers, and I think fewer still use nix, of which I don't know how many would use cachix. I wouldn't necessarily think that it would be important in general to have this.

**Comment by gbaz** [comment]
As a followup, having dug in, I think we have the action minutes to spare for now -- so while I personally wouldn't get any use out it at the moment, if there are people who would, I think it's fine, and if we start to run into limits I didn't expect, we can reconsider.

**Comment by andreasabel** [comment]
> having dug in, I think we have the action minutes to spare for now

Are these minutes accounted for all of @haskell or just this repo?

**Comment by srid** [comment]
> The benefit of enabling the Mac build is that Mac artifacts will be pushed to Cachix and save time for these developers

Only for Intel macs, though; see https://github.com/actions/runner-images/issues/2187
