### ISSUE TITLE
Can't publish a candidate

### ISSUE THREAD

**Issue by brandonchinn178** [haskell/hackage-server#1196]
Navigating to https://hackage.haskell.org/package/fourmolu-0.11.0.0/candidate works, but clicking on "Maintain" or "Publish" hangs

**Comment by brandonchinn178** [comment]
Never mind, working now

**Comment by gbaz** [comment]
Whew! glad its fixed. I was just about to start digging in, and worried it would be something scary. I'll instead for now treat it as mysterious, transient, and hopefully network-related, unless it reoccurs.

**Comment by brandonchinn178** [comment]
@gbaz seems like it's happening again :(
