### ISSUE TITLE
Problems upgrading account with Opera and Internet Explorer

### ISSUE THREAD

**Issue by HJvT** [haskell/hackage-server#120]
I was trying to upload a package candidate (a new revision of wxAsteroids),
but after typing userid and password, I got the message "No authorization
provided". This was with the Opera browser.

Then I tried Internet Explorer: this resulted in a browser freeze, after 
pressing the "upgrade account" button.

Firefox had no problems.

**Comment by gbaz** [comment]
Since there was no further followup (and I don't think we have other reports of same), I'm going to close this. I strongly suspect that if there were browser-specific issues they are no longer the same as they were five years ago.
