### ISSUE TITLE
Unnecessary email notification

### ISSUE THREAD

**Issue by Vlix** [haskell/hackage-server#1205]
`[If this is the wrong repo, do tell, I'll move it to the correct one]`

I've received an email notification because I've signed up to the new notification functionality on hackage (good change, very nice), but as with new funtionality, we're bound to get some bugs, and this is something I feel is important to get right, because sending unnecessary notifications can quickly become counterproductive.

Said email:
```
The dependency network-3.1.3.0 has been updated.

You have requested to be notified when a dependency isn't accepted by any of your maintained packages.

These are your packages that require network but don't accept [3.1.3.0](http://3.1.3.0/):

warp-3.3.25
```

But this is the part in the `.cabal` file that decides the version limit for `network`:
```cabal
  if flag(network-bytestring)
      Build-Depends: network                   >= 2.2.1.5  && < 2.2.3
                   , network-bytestring        >= 0.1.3    && < 0.1.4
  else
      Build-Depends: network               >= 2.3
```

And the `network-bytestring` flag is as follows:
```cabal
Flag network-bytestring
    Default: False
```

So I feel this should not have resulted in a notification, and I guess there's probably some internal logic that might not interpret flags desirably (or at all)?

**Comment by gbaz** [comment]
cc @ysangkok who I think noticed this for one of their packages as well, and was considering how to look into it.

**Comment by gbaz** [comment]
I think we should use cabal's conditional processing to extract a generous out-of-bounds interpretation for "candidate" notifications before sending them -- there's a way to fold maximal version intervals across logical branches in the cabal lib. Too expensive to do for every package always, but certainly feasible only for candidate notifications.

**Comment by ysangkok** [comment]
I got the notification for http-client:

```
These are your packages that require network but don't accept 3.1.3.0:

http-client-0.7.13.1
```

which is a bit different, since it is only out of bounds if the `network-uri` flag is *off* opposed to in @Vlix example above, where it is out of bounds when the flag is *on*.

I'll debug more over the weekend, thanks for the report!

@gbaz Would the currently sent notifications then be the 'candidate' you talk about? That is, you're just suggesting we add an additional filter to what we currently have? It seems to me that the current notifications are already generous, which is why I ask this.

**Comment by Vlix** [comment]
> which is a bit different, since it is only out of bounds if the `network-uri` flag is _off_ opposed to in @Vlix example above, where it is out of bounds when the flag is _on_.

Yes, but the `network-uri` flag is _on_ by default, and the flag for `warp` is _off_ by default. So if you take the default values, it's still in bounds. 🤔

**Comment by Vlix** [comment]
> I think we should use cabal's conditional processing to extract a generous out-of-bounds interpretation for "candidate" notifications before sending them -- there's a way to fold maximal version intervals across logical branches in the cabal lib. Too expensive to do for every package always, but certainly feasible only for candidate notifications.

Do you have to do any conditional processing? If _any_ of the possibilities accepts the correct bounds, I'd opt for accepting it as "in-bounds".

**Comment by gbaz** [comment]
Good point. On inspecting the last pr, my guess is that if `foo` appears in both branches of a conditional, I think it just gets added to the depList twice -- which is fine for revdep calculation, but not for the out-of-bounds calculation. So when we do the out of bounds calculation, we should maybe just "condense" the deplist by merging duplicate entries for the same dep.

**Comment by ysangkok** [comment]
> we should maybe just "condense" the deplist by merging duplicate entries for the same dep

If we take the warp example, I suppose this would mean merging these two edges:

```
Build-Depends: network                   >= 2.2.1.5  && < 2.2.3
Build-Depends: network               >= 2.3
```

What is the desired merge of these? Just a logical or?

```
Build-Depends: network (>= 2.2.1.5  && < 2.2.3) || (>= 2.3)
```

That seems like it would work.

I was considering using the flag defaults previously mentioned, but I don't think it would work, since you can also branch on e.g. the GHC version. So it seems to me that this problem isn't really about flags, it is about conditionals in general.

**Comment by ysangkok** [comment]
I have developed a test that currently breaks and would get fixed if we added the OR collapsing, see below.

I will develop a patch to do the actual collapsing and submit that tomorrow.

```diff
diff --git a/tests/RevDepCommon.hs b/tests/RevDepCommon.hs
index a7f79ff9..9a9ac333 100644
--- a/tests/RevDepCommon.hs
+++ b/tests/RevDepCommon.hs
@@ -31,6 +31,13 @@ packToPkgInfo Package {pName, pVersion, pDeps} =
 
 mkPackage :: PackageName -> [Int] -> [BSL.ByteString] -> PkgInfo
 mkPackage name intVersion depends =
+  mkPackageWithCabalFileSuffix name intVersion $
+    if depends /= []
+      then "library\n  build-depends: " <> BSL.intercalate "," depends
+      else ""
+
+mkPackageWithCabalFileSuffix :: PackageName -> [Int] -> BSL.ByteString -> PkgInfo
+mkPackageWithCabalFileSuffix name intVersion cabalFileSuffix =
   let
     version = mkVersion intVersion
     -- e.g. "2.3" for [2,3]
@@ -41,7 +48,7 @@ mkPackage name intVersion depends =
 \name: " <> BSL.fromStrict (Char8.pack $ unPackageName name) <> "\n\
 \version: " <> dotVersion <> "\n"
     cabalFile :: CabalFileText
-    cabalFile = CabalFileText $ cabalFilePrefix <> if depends /= [] then "library\n  build-depends: " <> BSL.intercalate "," depends else ""
+    cabalFile = CabalFileText $ cabalFilePrefix <> cabalFileSuffix
   in
   PkgInfo
   (PackageIdentifier name version)
diff --git a/tests/ReverseDependenciesTest.hs b/tests/ReverseDependenciesTest.hs
index 0e74a8d8..030eb8d0 100644
--- a/tests/ReverseDependenciesTest.hs
+++ b/tests/ReverseDependenciesTest.hs
@@ -31,7 +31,7 @@ import qualified Hedgehog.Range as Range
 import qualified Hedgehog.Gen as Gen
 import           Hedgehog ((===), Group(Group), MonadGen, Property, PropertyT, checkSequential, forAll, property)
 
-import RevDepCommon (Package(..), TestPackage(..), mkPackage, packToPkgInfo)
+import RevDepCommon (Package(..), TestPackage(..), mkPackage, mkPackageWithCabalFileSuffix, packToPkgInfo)
 
 mtlBeelineLens :: [PkgInfo]
 mtlBeelineLens =
@@ -214,6 +214,22 @@ allTests = testGroup "ReverseDependenciesTest"
         "dependencyReleaseEmails(trigger=BoundsOutOfRange) shouldn't generate a notification when the new package is for an old release series"
         mempty
         (runWithPref (pref BoundsOutOfRange) (PackageIndex.fromList newVersionOfOldBase) base4_14_1)
+      assertEqual
+        "dependencyReleaseEmails(trigger=BoundsOutOfRange) should only generate a notification when the new version is forbidden across all branches"
+        mempty -- The two branches below should get OR'd and therefore the dependency is not out of bounds
+        (runWithPref
+          (pref BoundsOutOfRange)
+          (PackageIndex.fromList
+            [ mkPackage "base" [4,14] []
+            , mkPackage "base" [4,15] []
+            , mkPackageWithCabalFileSuffix "mtl" [2,3]
+                "library\n\
+                \  if arch(arm)\n\
+                \    build-depends: base >= 4.14 && < 4.15\n\
+                \  else\n\
+                \    build-depends: base >= 4.15 && < 4.16"
+            ])
+          base4_15)
   , testCase "hedgehogTests" $ do
       res <- hedgehogTests
       assertEqual "hedgehog test pass" True res
```
