### ISSUE TITLE
Public package repositories best practice

### ISSUE THREAD

**Issue by glyn** [haskell/hackage-server#1222]
I think it would be best practice to make any repository associated with a Hackage package public. This would help users see current issues (e.g. to avoid bothering package maintainers with dups), explore version history, etc.

For example, the [sliceofpy](https://hackage.haskell.org/package/sliceofpy) package points to a private repository for its home page, issue tracker, and source repo. (Please note I have no complaints with this package - it was just an example I came across.)

I wonder if it would therefore be helpful to document such a best practice in the Hackage docs?

Please note I am not suggesting any kind of policy change; private repositories or tarballs with no repository would still be totally acceptable. But a docs change would gently encourage maintainers to open up their repositories.

I'll submit a PR with some suggested text.

**Comment by gbaz** [comment]
should be resolved by above linked pr.
