### ISSUE TITLE
Admin logs are visible?

### ISSUE THREAD

**Issue by DxsSucuk** [haskell/hackage-server#1229]
I am unfamiliar with this project.
While researching something I have found that Google has Indexed the Admin Log page.
And that it is visible without any authorization?

**Comment by ysangkok** [comment]
I don't see the issue. It could be nice for users to understand what admins are up to. Many of these actions are changing group memberships, that are publicly available on the package page anyway. Why should changes to these groups be hidden?

**Comment by DxsSucuk** [comment]
As said I am unfamiliar with the Haskell project.
I only randomly found out about the admin log page by googling a specific iso date.
Just looked weird having a admin url path which requires authorization for then the log to be publicly available?

**Comment by gbaz** [comment]
The admin log page is visible by design -- it is intended to be a publicly auditable log of admin actions so that users of the site can determine when and how community-appointed administrators used their powers.
