### ISSUE TITLE
LaTeX in README is not rendered properly

### ISSUE THREAD

**Issue by Bodigrim** [haskell/hackage-server#1231]
I have the following piece in `README.md`:
```md
## Statistical model

Here is a procedure used by `tasty-bench` to measure execution time:

1. Set $n \leftarrow 1$.
2. Measure execution time $t_n$ of $n$ iterations
   and execution time $t_{2n}$ of $2n$ iterations.
3. Find $t$ which minimizes deviation of $(nt,2nt)$ from $(t_n,t_{2n})$,
   namely $t \leftarrow (t_n + 2t_{2n}) / 5n$.
4. If deviation is small enough (see `--stdev` below)
   or time is running out soon (see `--timeout` below),
   return $t$ as a mean execution time.
5. Otherwise set $n \leftarrow 2n$ and jump back to Step 2.
```

GitHub agrees that this is a valid LaTeX syntax in Markdown, see https://github.com/Bodigrim/tasty-bench/tree/latex#statistical-model.

However, Hackage fails to render it correctly: https://hackage.haskell.org/package/tasty-bench-0.3.4.1/candidate#statistical-model

A cursory glance suggests that Hackage enables required extensions in `commonmark-extensions`:
https://github.com/haskell/hackage-server/blob/7c2b32b91028c84d2843ed7da5309094e89ea088/src/Distribution/Server/Util/Markdown.hs#L200-L201

Not sure what is missing then.

**Comment by gbaz** [comment]
maybe a commonmark issue?

**Comment by gbaz** [comment]
Ah, I see the issue. I think the MathJAX JS isn't imported properly in candidate pages, but is on proper pages (you can see it render properly at https://hackage.haskell.org/package/tasty-bench-0.3.4#statistical-model)

So that would be a lightweight change to our html templates I believe.

**Comment by gbaz** [comment]
Fair nuff. I think the issues is as I describe however -- the normal page imports some mathjax js and the candidate page does not. Further, on the candidate page, the intended math is generated with some html tags marking it with math spans, so one assumes that were the. mathjax indeed imported (as it would be on the regular page) then this would work.
