### ISSUE TITLE
Nix-workflow broken

### ISSUE THREAD

**Issue by andreasabel** [haskell/hackage-server#1237]
Possibly due to the addition of dependency `attoparsec-aeson`, the nix workflow is broken:
https://github.com/haskell/hackage-server/actions/runs/5769695862/job/15642001016#step:5:94
```
building '/nix/store/bia6q1zrmnqx405bx3q54gh0sr7vjcrp-cabal2nix-hackage-server.drv'...
error:
 ...
       error: function 'anonymous lambda' called without required argument 'attoparsec-aeson'

       at /nix/store/p5xpdv1kr2kdwp1cga6ss7cxmfzdb43v-cabal2nix-hackage-server/default.nix:1:1:

            1| { mkDerivation, acid-state, aeson, array, async, attoparsec
             | ^
            2| , attoparsec-aeson, attoparsec-iso[86](https://github.com/haskell/hackage-server/actions/runs/5769695862/job/15642001016#step:5:87)01, base, base16-bytestring
Error: Process completed with exit code 1.
```
ATTN: @peterbecich

**Comment by peterbecich** [comment]
Need to get `attoparsec-aeson` into NixPkgs: https://github.com/NixOS/nixpkgs/issues/247406
I will also try to provide this packages is a Flake Input.

**Comment by peterbecich** [comment]
Facing an issue with overriding `attoparsec-aeson`, asked for help: https://github.com/srid/haskell-flake/discussions/188

**Comment by peterbecich** [comment]
Fixed for Linux: https://github.com/haskell/hackage-server/pull/1241
But need to fix Mac separately

**Comment by peterbecich** [comment]
Mac Flake fixed here: https://github.com/haskell/hackage-server/pull/1244

**Comment by peterbecich** [comment]
Closing this issue. `nix develop` on Mac TODO: https://github.com/haskell/hackage-server/issues/1247
