### ISSUE TITLE
The order of modules in which they are specified in the code isn't respected.

### ISSUE THREAD

**Issue by sepiabrown** [haskell/hackage-server#1239]
I want to understand how the documentation in Hackage is formulated. Especially for re-exported modules, the order in which they are specified isn't respected. I don't know whether this is due to the hackage-server building the documentation or the library author uploading the wrong documentation files. 

[Options-Applicative-Help-Pretty](https://hackage.haskell.org/package/optparse-applicative-0.18.1.0/docs/Options-Applicative-Help-Pretty.html) lists `(<>), pipe, equal, ...` in the beginning.The [source code](https://hackage.haskell.org/package/optparse-applicative-0.18.1.0/docs/src/Options.Applicative.Help.Pretty.html) begins as follows.

    {-# LANGUAGE CPP #-}
    module Options.Applicative.Help.Pretty
      ( module Prettyprinter ,
        module Prettyprinter.Render.Terminal
        ...

But [Prettyprinter](https://hackage.haskell.org/package/prettyprinter-1.7.1/docs/src/Prettyprinter.html) module begins as follows.

    module Prettyprinter (
        -- * Documents
        Doc,
    
        -- * Basic functionality
        Pretty(..),
        viaShow, unsafeViaShow,
        emptyDoc, nest, line, line', softline, softline', hardline,
    
        -- ** Primitives for alternative layouts
        group, flatAlt,
    
        -- * Alignment functions
        --
        -- | The functions in this section cannot be described by Wadler's original
        -- functions. They align their output relative to the current output
        -- position - in contrast to @'nest'@ which always aligns to the current
        -- nesting level. This deprives these functions from being \'optimal\'. In
        -- practice however they prove to be very useful. The functions in this
        -- section should be used with care, since they are more expensive than the
        -- other functions. For example, @'align'@ shouldn't be used to pretty print
        -- all top-level declarations of a language, but using @'hang'@ for let
        -- expressions is fine.
        align, hang, indent, encloseSep, list, tupled,
    
        -- * Binary functions
        (<>), (<+>),
        ...

As you can see, it begins with `Doc, Pretty, viaShow` but they not in the beginning part of [Options-Applicative-Help-Pretty](https://hackage.haskell.org/package/optparse-applicative-0.18.1.0/docs/Options-Applicative-Help-Pretty.html). Also, as you can see from the above excerpt, (<>) in the middle but in [Options-Applicative-Help-Pretty](https://hackage.haskell.org/package/optparse-applicative-0.18.1.0/docs/Options-Applicative-Help-Pretty.html), it is at the beginning. What am I getting wrong?

Reference : [Haddock documentation](https://haskell-haddock.readthedocs.io/en/latest/markup.html#controlling-the-documentation-structure)

**Comment by gbaz** [comment]
This is something that would need to be fixed (if it could be) in haddock. Hackage just displays the haddock generated documentation.
