### ISSUE TITLE
Mark packages as unmaintained

### ISSUE THREAD

**Issue by jappeace** [haskell/hackage-server#1240]
I'm currently maintaining https://hackage.haskell.org/package/haskell-xmpp
However I wish to mark it as "unmaintained"
so that anyone with an interest in that package can take it over without having to go trough me first.

I already tried finding an alternative maintainer but no-one replied to [my post](https://discourse.haskell.org/t/maintainer-wanted-haskell-xmpp/6440).

**Comment by gbaz** [comment]
You may mark it as unmaintained by first deprecating it (if you wish) and second removing yourself from the maintainer group. Any package with an empty maintainer group will be able to be uploaded to by any approved uploader, at which point they become the new maintainer.

**Comment by jappeace** [comment]
so I should delete all other maintainers as well?

**Comment by gbaz** [comment]
It looks like the you already did -- the maintainers group appears empty to me :-)

**Comment by jappeace** [comment]
yes, I removed myself and a bunch of others from several packages:

+ voicebase
+ speechmatics
+ reflex-dom-helpers
+ bulmex
+ servant-fiat-content
+ heavy-log-shortcuts

and of course haskell-xmpp
