### ISSUE TITLE
Dependency notifications has incorrect link

### ISSUE THREAD

**Issue by brandonchinn178** [haskell/hackage-server#1242]
An email I got yesterday:

> The dependency bytestring-0.12.0.2 has been updated.
>
> You have requested to be notified when a dependency isn't accepted by any of your maintained packages.
>
> These are your packages that require bytestring but don't accept [0.12.0.2](http://0.12.0.2/):
>
> github-rest-1.1.4

The `0.12.0.2` link gets linked to http://0.12.0.2, which seems... wrong. Instead of linking `0.12.0.2`, it'd be great if `bytestring-0.12.0.2` + `github-rest-1.1.4` could be linked to https://hackage.haskell.org/package/bytestring-0.12.0.2 + https://hackage.haskell.org/package/github-rest-1.1.4

**Comment by ysangkok** [comment]
The email is plain text, and the concept of links doesn't exist. The links were probably added by your email client. I know it is in mine, which is Gmail.

But I do agree it would be nice to avoid this problem. One approach would be to send a multi-part email with both HTML and plain text content.

**Comment by brandonchinn178** [comment]
@ysangkok Makes sense. Maybe I could take a stab at implementing it?

**Comment by ysangkok** [comment]
Sure! If you'd like to avoid the refactoring that multi-part would require, you could also just modify the text to make the auto-detection work better.

In any case, I'd happily help you if you have any issues. Or if you prefer, we can also pair on it.
