### ISSUE TITLE
`cpphs` can no longer be found on the build-server

### ISSUE THREAD

**Issue by j-mie6** [haskell/hackage-server#1246]
Ok, cpphs should be installed directly on the machine now (I tested out a build requiring it and it worked).

_Originally posted by @gbaz in https://github.com/haskell/hackage-server/issues/944#issuecomment-859147278_
            

This was fixed in #944, but seems to have regressed: the reports of https://hackage.haskell.org/package/parsley-2.0.0.1/reports/2 show that `cpphs` is again missing

**Comment by gbaz** [comment]
Thanks for the report. We moved boxes and didn't reinstall cpphs when we did so. Fixed now, and tested.

**Comment by gbaz** [comment]
(note: if we finish the cutover of the builder to v2-build, finally, then this won't be a problem because build-tools-depends will work as it should)
