### ISSUE TITLE
"curl: (56) Failure when receiving data from the peer" when trying to upload

### ISSUE THREAD

**Issue by Kleidukos** [haskell/hackage-server#1263]
I have been getting upload errors with cabal-head on Hackage lately:

```
Error: cabal: '/usr/bin/curl' exited with an error:
curl: (56) Failure when receiving data from the peer
```

I have curl 8.2.1 installed on my machine.

**Comment by gbaz** [comment]
Is this always, or just sometimes? Does the same error occur on the web interface to hackage? How big is the file?

**Comment by Kleidukos** [comment]
It's always, and no the web interface works perfectly well. The file is 36K.

**Comment by gbaz** [comment]
perhaps try running with a high verbosity flag? i suspect this may be a localized error (bad cert store? funny hackage url in the cabal config? unsure...) as otherwise I imagine there would be many more reports.

**Comment by Kleidukos** [comment]
Ok so, apparently cabal is trying to contact the cardano packages repository:

```
Running: /usr/bin/curl --config - 'https://input-output-hk.github.io/cardano-haskell-packages/packages/candidates' --form 'package=@/home/hecate/Projects/haskell-cryptography/libsodium-bindings/dist-newstyle/sdist/libsodium-bindings-0.0.1.0.tar.gz' --write-out '
%{http_code}' --user-agent 'cabal-install/3.11.0.0 (linux; x86_64)' --silent --show-error --header 'Accept: text/plain' --location
```

And indeed, in my ~/.cabal/config I have the following:

```
repository hackage.haskell.org
  url: https://hackage.haskell.org/
  secure: True
  -- root-keys:
  -- key-threshold: 3

repository cardano
  url: https://input-output-hk.github.io/cardano-haskell-packages
  secure: True
  root-keys:
    3e0cce471cf09815f930210f7827266fd09045445d65923e6d0238a6cd15126f
```

**Comment by Kleidukos** [comment]
Weirdly, specifying `active-repositories: hackage.haskell.org` in the cabal.project file doesn't seem to change this behaviour.

**Comment by gbaz** [comment]
Going to close this issue, but this is probably something to be opened as an ergonomics issue in cabal -- upload noting the repo that is being uploaded to, and perhaps also having some sort of better defaulting as to which is picked.

**Comment by Kleidukos** [comment]
Yep
