### ISSUE TITLE
Hackage search showing package version inconsistency

### ISSUE THREAD

**Issue by praduca** [haskell/hackage-server#1264]
When using the search on hackage, the resulting package list can show the incorrect package version (apparently it shows the most recent uploaded package).

I noticed that behaviour with the BNFC package. Recently the version 2.9.5 was uploaded, and after that version 2.5.0.1 was also uploaded.

The problem is that searching for BNFC now list the last version as 2.5.0.1, but links correctly for the (last) default version (2.9.5).
This is not really serious issue , but is a bit confusing...

**Comment by ysangkok** [comment]
Is this distinct from #1188 ? I see "Fix lastVersion" by @blackheaven in the [commit log for central-server](https://github.com/haskell/hackage-server/commits/central-server), so that suggests it was fixed. But I can reproduce the problem and it seems to be exactly what was reported in #1188. Are we sure that this branch is the one deployed @gbaz ?

It seems that the Fastly cache can't be the problem:
```
% curl 'https://hackage.haskell.org/packages/search' \
  -H 'content-type: application/json' -H "Fastly-Debug:1" -D /dev/stderr --silent \
  --data-raw '{"page":0,"sortColumn":"default","sortDirection":"ascending","searchQuery":"BNFC"}' | jq '.pageContents[].lastVersion'
HTTP/1.1 200 OK
Connection: keep-alive
Server: nginx/1.18.0 (Ubuntu)
Content-Type: application/json
Accept-Ranges: bytes
Date: Mon, 27 Nov 2023 20:29:24 GMT
Via: 1.1 varnish
Fastly-Debug-Path: (D cache-dfw-kdfw8210116-DFW 1701116964) (F cache-dfw-kdfw8210116-DFW 1701116964)
Fastly-Debug-TTL: (M cache-dfw-kdfw8210116-DFW - - -)
Fastly-Debug-Digest: 33944001b24b41f0d0ff63df0b0a6d2538c75b3a4fb4fd34515413903c9bb375
X-Served-By: cache-dfw-kdfw8210116-DFW
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1701116964.085098,VS0,VE10
Vary: Accept-Encoding
transfer-encoding: chunked

"2.5.0.1" # This shows the bug
"0.6.1"
```

**Comment by ysangkok** [comment]
Oh, I see, this is not the same issue. The 2.5.0.1 actually *is* the version that was last uploaded. We don't do any comparison of version numbers. We simply just show the last upload. I am not sure what the intended behavior is here? @blackheaven authored this feature, he might opine.

**Comment by gbaz** [comment]
Hrm, yeah, I think its probably best to take highest non-deprecated version. (there's a few packages where they accidentally uploaded a super-high version accidentally then deprecated it, so important to have the non-deprecated bit).

**Comment by blackheaven** [comment]
It was the expected behavior, but yes, this is a misleading behavior.

I think, setting the highest, non-deprecated version on new version or deprecation to `latestVersion` (which should be renamed `referenceVersion`) seems good to me.

Do you want me to try a to come up with a PR?

**Comment by ysangkok** [comment]
> Do you want me to try a to come up with a PR?

 Yes please

**Comment by blackheaven** [comment]
I have started #1268

**Comment by gbaz** [comment]
Hope to deploy this weekend

**Comment by gbaz** [comment]
deployed, but it looks like this didn't work. instead i see every reference version as "undefined" on the deployed hackage now. yikes.

**Comment by gbaz** [comment]
nevermind, needed to purge a cdn cache. done!

**Comment by praduca** [comment]
@gbaz all i see is undefined on the reference version collumn... there is something that need to be done at the client side?

**Comment by blackheaven** [comment]
> nevermind, needed to purge a cdn cache. done!

You scared me :)

**Comment by blackheaven** [comment]
> @gbaz all i see is undefined on the reference version collumn... there is something that need to be done at the client side?

Same thing here, I think the JavaScript is outdated.

**Comment by ysangkok** [comment]
It seems that the cache-control makes the browser cache it for 1 day: 

`curl -D /dev/stderr -Ls "https://hackage.haskell.org/static/browse.js" | grep -E 'referenceVersion|lastVersion'`

This is independent of the fastly cache, which I suppose was already flushed.

**Comment by praduca** [comment]
ah yes, just clearing the cache did it.

**Comment by blackheaven** [comment]
I think we might want to switch to immutable assets at some point.
