### ISSUE TITLE
Cannot run shell script as a preprocessor

### ISSUE THREAD

**Issue by augustss** [haskell/hackage-server#1266]
I have a problem with my package [MicroHs](https://github.com/augustss/MicroHs)
I need to run a preprocessor on all Haskell files.  The command line has the following
`... -F -pgmF ./Tools/convertX.sh ...`
This works locally when I do `cabal build`, but fails on the hackage build server.
Is there something I can do to make it work?
I don't mind rewriting the preprocessor in C if that makes it viable (it will be <10 lines).

**Comment by andreasabel** [comment]
No action to be taken here.
