### ISSUE TITLE
package checking with "cabal upload -c" gives error 404

### ISSUE THREAD

**Issue by choener** [haskell/hackage-server#128]
cabal upload -c dist/PrimitiveArray-0.5.2.0.tar.gz
Checking dist/PrimitiveArray-0.5.2.0.tar.gz...
Error: dist/PrimitiveArray-0.5.2.0.tar.gz: 404 Not Found

This could also be a cabal-install problem.

**Comment by gbaz** [comment]
Resolved as with #1823
