### ISSUE TITLE
Use newer GHC version to compile?

### ISSUE THREAD

**Issue by brandonchinn178** [haskell/hackage-server#1282]
The Haddocks for my packages are no longer built on Hackage because I dropped support for GHC < 9.4 (per my preference of only supporting the last three GHC releases), and Hackage builds docs with GHC 9.2. Is it possible to upgrade the version of GHC used in Hackage build?

**Comment by ulysses4ever** [comment]
You could work around by manually uploading the docs, perhaps? But I agree that routinely upgrading GHC is a good thing.

**Comment by gbaz** [comment]
Upgraded to ghc 9.6.3
