### ISSUE TITLE
Package on Hackage not being built

### ISSUE THREAD

**Issue by danielrolls** [haskell/hackage-server#1338]
I uploaded two revisions to https://hackage.haskell.org/package/shellify and in both cases I see:
`Docs pending`
`Build status unknown [[no reports yet]`
and 
`Status: Not yet tried.`

Since I'm not getting an error it's not obvious how to fix it on the package end (if that's the problem). I've tried waiting days, and tried deleting docs and requesting a rebuild. 

When trying to trigger a rebuild I get the error `Build report does not exist`.

**Comment by Bodigrim** [comment]
Apparently something is off with the doc builder. In the meantime you can build and upload docs yourself: `cabal haddock --haddock-for-hackage` and then `cabal upload --documentation`.

**Comment by danielrolls** [comment]
Thanks @Bodigrim for confirming.

**Comment by gbaz** [comment]
Thanks for the report. I fixed the builder -- it was stuck on a (deliberately) unremovable file in the `directory` test suite. Maybe we should do something about that.

**Comment by gbaz** [comment]
Vis a vis the documentation upload command -- one needs to pass the `--publish` flag to specify that they are uploading documentation _not_ as a candidate but to the released package.

**Comment by danielrolls** [comment]
@gbaz, thanks for help with the upload command and for resolving the issue. I can see builds coming through again so I'll close this.
