### ISSUE TITLE
Cannot upload `cabal-version: 3.8` package to Hackage

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/hackage-server#1351]
When I attempt to upload [`singletons-base`](https://github.com/goldfirere/singletons/blob/326e0e9d6490cd6100cc430773296322a883b6a9/singletons-base/singletons-base.cabal) (which needs [`cabal-version: 3.8`](https://github.com/goldfirere/singletons/blob/326e0e9d6490cd6100cc430773296322a883b6a9/singletons-base/singletons-base.cabal#L1)) to Hackage, it fails with:

```
$ cabal upload --publish dist-newstyle/sdist/singletons-base-code-generator-0.1.tar.gz 
<snip>
Uploading dist-newstyle/sdist/singletons-base-code-generator-0.1.tar.gz...
Error uploading dist-newstyle/sdist/singletons-base-code-generator-0.1.tar.gz:
http code 400
Error: Invalid package

'cabal-version' must be at most 3.6
```

Is there something that needs to change on Hackage's end to support this? I require `cabal-version: 3.8` due to the package's use of a [`cabal` code generator](https://cabal.readthedocs.io/en/stable/cabal-package-description-file.html#pkg-field-test-suite-code-generators).

I am using the latest stable release of `cabal` (`cabal-install version 3.12.1.0`) as of the time of writing.

**Comment by RyanGlScott** [comment]
Thanks! Let me know if there is anything I can do to help.

**Comment by RyanGlScott** [comment]
Any update on this, @gbaz?

**Comment by RyanGlScott** [comment]
In the meantime, I am going to [revert the use of a code generator](https://github.com/goldfirere/singletons/pull/624), as it is effectively incompatible with Hackage.

**Comment by gbaz** [comment]
Sorry about the delay. Will try to get to this very soon.

**Comment by gbaz** [comment]
And the update is now complete, sorry for the delays.

**Comment by RyanGlScott** [comment]
I am still getting the same error when attempting to upload the package just now. Am I doing something wrong?

**Comment by Bodigrim** [comment]
@gbaz I think 888247675243cf158753d4fec1465bd56142be0a was not backported to `central-server` branch, it still points to
https://github.com/haskell/hackage-server/blob/ec45aabc0a395b93d67fa3cd4bf5a08ba2820c67/src/Distribution/Server/Packages/Unpack.hs#L222-L224

**Comment by ulysses4ever** [comment]
I believe the whole batch hasn't been merged yet but Gershom thought it was? https://github.com/haskell/hackage-server/pull/1352

**Comment by gbaz** [comment]
indeed, doing a new redeploy now. 🤦

**Comment by gbaz** [comment]
and done, hope i got it right this time.

**Comment by RyanGlScott** [comment]
Thank you! I've confirmed that I was able to upload the `cabal-version: 3.8` this time.
