### ISSUE TITLE
missing docs on MANY new packages!!!!

### ISSUE THREAD

**Issue by cartazio** [haskell/hackage-server#145]
Have we fixed this in hackage server head? when is it getting rolled out and haddocked regenerated?

http://hackage.haskell.org/package/cabal-debian-3.8.3 is a new example of this problem i just found :(

**Comment by gbaz** [comment]
I think we can close this now, since we have our builders more carefully manged?

**Comment by gbaz** [comment]
closing in favor of #478 which we've made great strides on
