### ISSUE TITLE
Account confirmation doesn't use HTTPS

### ISSUE THREAD

**Issue by Y-Less** [haskell/hackage-server#156]
I just signed up for an upload account, and got the confirmation email, in which there was a link to a page to enter a password.  Following this took me to an HTTP page, when replacing the protocol manually with "HTTPS" worked fine.

The secure page should be the default for anything asking for a password.  I reported this when emailing an admin for upload permissions and they told me to post an issue here, so I have.

**Comment by gbaz** [comment]
On the main server our account confirmation emails now use https, so I think I can close this for now?

**Comment by asciijungle** [comment]
Seems this got reintroduced. duplicate: #803
