### ISSUE TITLE
Account update page

### ISSUE THREAD

**Issue by hesselink** [haskell/hackage-server#167]
Currently, the only way to update a user's name or, more importantly, email address, seems to be a PUT to /user/<name>/name-contact with the JSON. It would be useful to have an actual html page where users can update their email address (probably with another confirmation email) and user name.

**Comment by gbaz** [comment]
We have http://hackage.haskell.org/user/[User]/manage

What we should do is add this there, and also add a good way to navigate _to_ this page (which is somewhat obscure). Such a page can also handle user notification prefs for https://github.com/haskell/hackage-server/pull/622

My potential idea is that we navigate there from the top-level http://hackage.haskell.org/accounts page, and just have a "Manage Your Account" link to a page that requires a login, then redirects the user to their appropriate page.

**Comment by gbaz** [comment]
we have the account-management redirect page now, but we still need an email-update form on it. (not sure if we want to allow user-name updates?)
