### ISSUE TITLE
404 for "Source" link

### ISSUE THREAD

**Issue by jameshfisher** [haskell/hackage-server#168]
STR:

1. Go to http://hackage.haskell.org/package/base-4.6.0.1/docs/Data-Int.html
2. Click the first "Source" link, which points at http://hackage.haskell.org/packages/archive/%01/%02/doc/html/src/GHC-Types.html#Int

Expected behavior: not sure, but not a 404.

Actual behavior: 404; "Page not found".

**Comment by dcoutts** [comment]
Seems this was done.
