### ISSUE TITLE
hackage has a doc-builder vm that reports pentium-m as its -march

### ISSUE THREAD

**Issue by cartazio** [haskell/hackage-server#169]
see https://github.com/haskell/hackage-server/issues/119#issuecomment-30095730

unless the doc builder is on a very old machine, this seems like a misconfig of the vm. (though the offending package may be simply doing a poor job of handling older microarchitectures... unclear)

**Comment by gbaz** [comment]
is this still an issue @cartazio

**Comment by cartazio** [comment]
I don’t remember what tripped this/ or what this is was in the context of. So closing for now :( 
:)
