### ISSUE TITLE
Question on getting a package many times.

### ISSUE THREAD

**Issue by eccstartup** [haskell/hackage-server#170]
I come across a problem. First, let's open one package page [http://hackage.haskell.org/package/AC-Angle](http://hackage.haskell.org/package/AC-Angle). 

I can see the download link [AC-Angle-1.0.tar.gz](http://hackage.haskell.org/package/AC-Angle-1.0/AC-Angle-1.0.tar.gz). Now if I use `wget` to download it many times, I find something confusing. 

With `wget -c http://hackage.haskell.org/package/AC-Angle-1.0/AC-Angle-1.0.tar.gz`, I find wget will fetch the file again and again, pretending the file on the server is different(or newer) from local. In fact, they have the same `md5sum`.

So, my question is, what information the server provided will prevent the same download? Maybe file size? Time stamp? ...

Thanks

**Comment by dcoutts** [comment]
Server now provides cache control headers and supports etag-conditional gets.
