### ISSUE TITLE
Docs for some packages are mixed up with those of other packages

### ISSUE THREAD

**Issue by ghost** [haskell/hackage-server#172]
I've found two examples of this happening:
- http://hackage.haskell.org/package/gloss-1.8.1.1/docs/ (gloss mixed up with binary)
- http://hackage.haskell.org/package/llvm-general-3.3.8.2/docs/ (llvm-general mixed up with bytestring)

**Comment by gbaz** [comment]
Those old docs no longer display as docs on the main package pages of those two packages (at those versions even). Without any others I see needing to be fixed up, going to close this
