### ISSUE TITLE
Hide deprecated packages

### ISSUE THREAD

**Issue by sol** [haskell/hackage-server#201]
The old Hackage did not show deprecated packages e.g. on the [packages by category](http://hackage.haskell.org/packages/) page.  I think it would be cool to get back that behavior for Hackage 2.

I care for the following places:
- [packages by category](http://hackage.haskell.org/packages/)
- All packages for an author (e.g. http://hackage.haskell.org/user/SimonHengel)

**Comment by hvr** [comment]
Somewhat related to the comments in #112

**Comment by borsboom** [comment]
I'd like to add: hide deprecated package _versions_ on the package page as well (see #382).

**Comment by gbaz** [comment]
The new browse interface hides deprecated by default now.

**Comment by freizl** [comment]
The deprecated version does get additional CSS style but they are not hidden. What did I miss?

<img width="1748" alt="Screen Shot 2022-10-04 at 9 19 16 AM" src="https://user-images.githubusercontent.com/437427/193872330-8811fc25-1664-4b87-90f4-febaa1f88b16.png">

**Comment by freizl** [comment]
oh.. I misinterpreted! Thanks! (I do hope hide those deprecated _versions_ to make the package index page a bit clean given there is nicely built information page under `/package/$PKG_NAME/preferred`)
