### ISSUE TITLE
Server allows uploads of packages that don't have Setup.hs

### ISSUE THREAD

**Issue by peti** [haskell/hackage-server#205]
The [smtps-gmail](http://hackage.haskell.org/package/smtps-gmail) package doesn't have a Setup.{l,}hs file. I seem to recall that it used to be impossible to upload such a tarball to Hackage in earlier versions?

**Comment by gbaz** [comment]
My understanding is that we now allow uploads of packages without Setup.hs as long as build-type is Simple, since the file is trivial.
