### ISSUE TITLE
Search by partial package name

### ISSUE THREAD

**Issue by edsko** [haskell/hackage-server#208]
For example, searching for `diagrams-` finds nothing, while it should find `diagrams-pdf`, `diagrams-postscript`, etc.

**Comment by gbaz** [comment]
The correct thing seems to me to be to consider any word with a matching substring a "keyword" with a score proportional to the ratio substring/string?

**Comment by kanishka-azimi** [comment]
@danchoi What has your experience with indexing documents lead you to conclude about this?

**Comment by gbaz** [comment]
"Searching for diagrams works only by accident (because the various diagrams packages have diagrams in the description)" -- this is not true (at least anymore). It works because we split `diagrams-x` package names and we have exact matches on the diagrams component. This  seems fine to me?
