### ISSUE TITLE
Document the web interface to view build logs

### ISSUE THREAD

**Issue by cirodrig** [haskell/hackage-server#210]
The hackage server has a web interface to view build logs.  The website doesn't mention build logs or link to their URL, making it hard for users to find.  Some documentation would help.  I think it would fit under "Exploring the site" on the main page.

The build logs are useful for examining build failures that lead to missing documentation.  I learned about them from Fuuzetsu's blog via a google search.

**Comment by gbaz** [comment]
When we do have working logs (separate issue) we do have a nice way to see them now :-)
