### ISSUE TITLE
Missing generated Hoogle databases (package.txt) for newer packages

### ISSUE THREAD

**Issue by ppetr** [haskell/hackage-server#224]
There used to be generated Hoogle databases for every package, which were very useful for local Hoogle installations. For example:
- http://hackage.haskell.org/package/lifted-base-0.2.0.1/docs/lifted-base.txt
- https://hackage.haskell.org/package/lens-3.8.5/docs/lens.txt

However, for recent packages they're missing:
- http://hackage.haskell.org/package/lifted-base-0.2.2.1/docs/lifted-base.txt
- https://hackage.haskell.org/package/lens-4.1.2/docs/lens.txt

Would it be possible to generate them again?

**Comment by gbaz** [comment]
I think we're ok sans linter given the new features in cabal that make manually uploading docs with all the proper flags set much more straightforward.
