### ISSUE TITLE
bad rendering of source repo data for hfuse 

### ISSUE THREAD

**Issue by cartazio** [haskell/hackage-server#238]
https://hackage.haskell.org/package/HFuse

```
head: SourceRepo {repoKind = RepoHead, repoType = Just (OtherRepoType "head"), repoLocation = Just "https://github.com/toothbrush/hfuse.git", repoModule = Nothing, repoBranch = Nothing, repoTag = Nothing, repoSubdir = Nothing}
```

**Comment by ttuegel** [comment]
It was also mentioned in haskell/cabal#1028 that unknown or incorrectly specified repository types are mishandled on Hackage.

**Comment by gbaz** [comment]
The relevant code is `sourceRepositoryToHtml` in `Distribution.Server.Packages`

**Comment by gbaz** [comment]
ah -- its fossil! Going to actually fix this now :-)
