### ISSUE TITLE
index.html makes package contents not browseable

### ISSUE THREAD

**Issue by koterpillar** [haskell/hackage-server#239]
I have a package with `index.html` as a data file. It's probably not a good idea to automatically show it to people when they follow a link from "Downloads": http://hackage.haskell.org/package/tianbar -> http://hackage.haskell.org/package/tianbar-0.4.5.0/src/.

Also, the HTML page could probably steal your Hackage cookies (though I'm not sure if there's anything of value there).

**Comment by dcoutts** [comment]
We can leave off index handling for serving the content.
