### ISSUE TITLE
Keep sets of tag aliases

### ISSUE THREAD

**Issue by edsko** [haskell/hackage-server#24]
And we should use these sets when coalescing (see #23). 

With these sets we can actually have a set of tag names that all refer to the same canonical tag name; we would use this in the search feature, when we search on tags. This means we can tidy up the tags and make them useful for organising and searching since at the moment people pick different names for the same thing

**Comment by gbaz** [comment]
should be closed with https://github.com/haskell/hackage-server/pull/551
