### ISSUE TITLE
Documentation not generated

### ISSUE THREAD

**Issue by crockeea** [haskell/hackage-server#244]
I noticed that (for example) [repa-3.3.1.2](https://hackage.haskell.org/package/repa) doesn't have any documentation on hackage. I posted this [on a repa forum](https://groups.google.com/forum/#!topic/haskell-repa/CU_eQATOP0g) and the dev responded with 
    
> "Thanks, I've pushed a new version. We'll see if that triggers Hackage to rebuild the docs. The docs build locally, so if Hackage isn't building them I suppose it's a Hackage bug."

which I am now dutifully reporting. I've noticed this problem with other packages as well; I'll try to post those as I rediscover them.

Now that I've found three pacakges where this is an issue:
  1. What's causing it?
  2. Is there a way to go back and generate docs for missing versions?

**Comment by gbaz** [comment]
closing this as its an old ticket and it doesn't serve to have lots of redundant ones floating around.

**Comment by svenpanne** [comment]
So what's the "master" ticket for all the doc builder problems? Simply closing tickets doesn't make the problem go away... :wink:

**Comment by gbaz** [comment]
https://github.com/haskell/hackage-server/issues/478
