### ISSUE TITLE
Better error on rejecting package with hpc flag

### ISSUE THREAD

**Issue by robdockins** [haskell/hackage-server#249]
Hackage is currently rejecting a package I’d like to upload.  The .cabal file for the package contains the following:

```
flag enable-hpc
  Description: Collect HPC coverage information.
  Default: False

if flag(enable-hpc)
  ghc-options: -fhpc -hpcdir .hpc
```

But Hackage (and “cabal check”) complain:

> The following errors will cause portability problems on other environments:
> - 'ghc-options: -fhpc' is not appropriate for a distributed package.

I don’t quite understand why the “fhpc” option is singled out for special rejection, and regardless, it seems like troublesome options should be allowed if they are guarded by flags, especially flags with false defaults.  (As an aside, the “reject all ghc-options that start with d” rule is quite the blunt instrument.)

Obviously, I can edit my .cabal file to make the problem go away, but I’d rather not have to.

**Comment by gbaz** [comment]
The cabal check message now reads

> * 'ghc-options: -fhpc' is not not necessary. Use the configure flag --enable-coverage instead.

👍
