### ISSUE TITLE
Handling "OPTIONS_HADDOCK hide"

### ISSUE THREAD

**Issue by crockeea** [haskell/hackage-server#256]
For files marked with the pragma `{-# OPTIONS_HADDOCK hide #-}`, Hackage currently creates a dead link on project pages. An example is [Data.Vector.Generic.Base](http://hackage.haskell.org/package/vector-0.10.11.0/docs/Data-Vector-Generic-Base.html), linked from [Data.Vector](http://hackage.haskell.org/package/vector). Another package where this is handled incorrectly is [GHC.Base](http://hackage.haskell.org/package/base), for the module [GHC.Word](http://hackage.haskell.org/package/base-4.7.0.1/docs/GHC-Word.html) (to name just one).

Instead of creating a dead link, no link should be generated.

**Comment by crockeea** [comment]
Any updates on this?

**Comment by dcoutts** [comment]
Now fixed, we only link to the ones that exist.
