### ISSUE TITLE
Doesn't build with GHC 7.8.3

### ISSUE THREAD

**Issue by thsutton** [haskell/hackage-server#260]
I was unable to build 489df240266f2b3066cf6e99304e704c53c8e04f on Debian testing (or jessie or whatever it's supposed to be called) with GHC 7.8.3 (from the bindist), but using GHC 7.6.3 (also from the bindist) did work:

``` shell
cabal install --dependencies-only -w ghc-7.6.3
cabal configure -w ghc-7.6.3
cabal build
```

The actual errors reported were in `Distribution/Server/Features/Search/DocIdSet.hs` and `Distribution/Server/Features/DownloadCount/State.hs` and all are "Could not coerce" type errors. I'll add an error log in a few minutes.

**Comment by bergmark** [comment]
This has been fixed, please close.
