### ISSUE TITLE
Add first-class support for README files

### ISSUE THREAD

**Issue by snoyberg** [haskell/hackage-server#262]
The idea would be to copy the Github approach as much as possible, and have support for various different README file formats (plain text, Markdown, Haddock, HTML, etc). This would allow projects that already have a README to simply get that file available from a Hackage package description, thereby reducing the need for duplicated documentation between cabal's description field and READMEs which need to be written anyway.

Implementation would be fairly similar to the changelog feature: a package author can add the file via `extra-source-files`, and once Hackage sees the file, it will display it. (Question: should it display inline on the main package page, or via a link to another page?)

Original mailing list discussion: http://www.haskell.org/pipermail/haskell-cafe/2014-September/116009.html

**Comment by jberryman** [comment]
#279 was closed, so I assume this can be closed too
