### ISSUE TITLE
Documentation building broken/off?

### ISSUE THREAD

**Issue by conal** [haskell/hackage-server#265]
Is Haddock documentation building on Hackage broken (or turned off)? I released [Boolean-0.2.2](http://hackage.haskell.org/package/Boolean-0.2.2) last week, and no documentation is showing up, nor any error log.

**Comment by crockeea** [comment]
Has anyone looked into this recently?

**Comment by crockeea** [comment]
This is still a problem. I uploaded a new version of  [lol](https://hackage.haskell.org/package/lol-0.1.0.0) last week, but still no docs. Status is "Docs Pending".

**Comment by crockeea** [comment]
I also "deleted the documentation and triggered a rebuild" on [lol](https://hackage.haskell.org/package/lol-0.1.0.0), to no avail. The differences between the previous version of the library (where Hackage build the documentation fine) is tiny, so I can't imagine what the probem is. Can we get someone to dig through server logs somewhere and figure out what the holdup on doc generation is?

**Comment by gbaz** [comment]
closing this as its an old ticket.

**Comment by gbaz** [comment]
(it would be better to not use this one ticket for all docbuilder issues)

**Comment by crockeea** [comment]
@gbaz Can you link to a newer ticket? I posted #244, and you've also closed this ticket. Both address documentation not being built, which is still a very big problem. Is this issue being addressed somewhere else?

**Comment by gbaz** [comment]
sorry i missed this -- clearing out old emails now. here's the ticket to track the general issue: https://github.com/haskell/hackage-server/issues/478
