### ISSUE TITLE
Cannot access http://hackage.haskell.org/package/xss-sanitize-0.3.5.4/xss-sanitize-0.3.5.4.tar.gz

### ISSUE THREAD

**Issue by sgronblo** [haskell/hackage-server#266]
I am located in Japan. Trying to install dependencies for yesod. Get 301 redirected to this xss-sanitize dependency which just stalls. If I wget the file I can see the 200 OK header, but after that wget gets stuck waiting forever and no data is sent. Other co-workers of mine report the same problem. A user I asked on IRC in #haskell reports being able to access the file without problems. If I change protocol to https I can access the file.

**Comment by gbaz** [comment]
closing as localized network problem...
