### ISSUE TITLE
hackage-server restore is busted at the moment

### ISSUE THREAD

**Issue by thoughtpolice** [haskell/hackage-server#267]
While attempting to restore some backups as a test, I encountered the following error:

```
root@hackage-www:/srv/hackage# ./lib/hackage-server restore --static-dir=/srv/hackage/var/server/datafiles --state-dir=/srv/hackage/var/server/state2 /srv/hackage/var/server/backups/backup-2014-09-25.tar.gz
hackage-server: Error importing
'backup-2014-09-25/reports-core/package/3d-graphics-examples-0.0.0.0/1.txt'
:Missing field flags
```

I imagine this is due to the fact the server state/backup state was changed at one point, while the `restore` codepath was not properly fixed up to deal with it. In any case, working restore would be great. :)

**Comment by gbaz** [comment]
As that is long merged, going to close this out.
