### ISSUE TITLE
"Contents" link broken for some packages

### ISSUE THREAD

**Issue by crockeea** [haskell/hackage-server#268]
When looking at the documentation for a specific package, (say [here](https://hackage.haskell.org/package/type-natural-0.2.3.1/docs/Data-Type-Natural.html)), the `Contents` link at the top ~~left~~ right usually links to `hackage.haskell.org/package/packageName-version`, like [so](https://hackage.haskell.org/package/type-natural-0.2.3.1).

However, for at least the the singletons package, the `Contents` link from [a documentation page](https://hackage.haskell.org/package/singletons-1.0/docs/Data-Singletons-Prelude-Bool.html) goes to [/singletons-version/docs/index.html](https://hackage.haskell.org/package/singletons-1.0/docs/index.html), which is a very different page.

I can't say which link is intended, only that the behavior is different between most packages and singletons. Both pages seem like a reasonable choice for a link labeled "Contents" but the one with version numbers does help [change versions more easily](https://github.com/haskell/hackage-server/issues/198#issuecomment-58853882). The only way I've been able to change the version of this package starting from a doc page is to manually chop the link.

**Comment by goldfirere** [comment]
I believe this is solely Hackage's issue. It's quite true that `singletons` pushes the boundaries of what Haddock can do, and I'll take responsibility for manually uploading the docs. But, unless I'm told otherwise, I don't think there's anything I can do on my end to fix that link.

**Comment by gbaz** [comment]
This happened because the docs were uploaded as built by a user with different settings than we'd like. Other tickets capture trying to get the right default settings into cabal's ability to auto-upload docs, etc. That workflow should resolve this.
