### ISSUE TITLE
Wrong password handling

### ISSUE THREAD

**Issue by yaccz** [haskell/hackage-server#271]
Setting "Dodkeg(OcMesbacokeg1-" (without the quotes) as password results in inability to login with eg. `cabal upload`

**Comment by ocharles** [comment]
I cannot reproduce this problem. I'm using the `master` branch, and I created an account, and then went to http://localhost:8080/packages/upload. I logged in with the account `bug`, password `Dodkeg(OcMesbacokeg1-` and it successfully uploaded my library.
