### ISSUE TITLE
Render README.md in Package pages

### ISSUE THREAD

**Issue by bitemyapp** [haskell/hackage-server#279]
https://www.fpcomplete.com/blog/2014/11/stackage-open-source

**Comment by bgamari** [comment]
@mpickering any news on this?

**Comment by mpickering** [comment]
```
I've been spending a lot of time getting libcmark right.
When the API stabilizes, I (or someone else) can write a Haskell
binding for it, and that could be used in a pandoc reader.

Alternatively, we could try for a pure Haskell implementation,
that copied the parsing strategy.  (Cheapskate is in the vicinity,
because I used lots of ideas from cheapskate, but it would need
substantial revisions.)  That would give more safety guarantees,
and maybe be more portable, at the expense of speed.

(Currently libcmark is more that 80 times faster than pandoc,
and it is much more robust -- pandoc's Markdown parser can be gummed
up by some pathological inputs.)

Best
John
```

**Comment by snoyberg** [comment]
Is there any progress on this issue? Having to duplicate descriptions across multiple places in different formats continues to be a real maintenance burden.

**Comment by conklech** [comment]
Not from my end, sorry; I'm out of commission until after the bar exam in
July. IIRC the branch I was working on "just needs" pandoc/cheapskate/etc.
dropped in, the HTML output spliced into the package page, and of course
testing.

**Comment by snoyberg** [comment]
Looks like this got picked up as a PR in #333.

**Comment by dcoutts** [comment]
The remainder of this, to put the readme inline is now done, pending deployment.

**Comment by cdupont** [comment]
Hello, displaying README in Hackage works great for my package.
However, is it possible to display pictures, with a code like below? It doesn't seem to work.

    ![pic](img/mypic.png)
