### ISSUE TITLE
Add robots.txt to tarballs for old versions of packages so search engines show latest only

### ISSUE THREAD

**Issue by bitemyapp** [haskell/hackage-server#284]
https://twitter.com/maxpow4h/status/539154121685598208

I am proposing this as a *temporary* remedy since mangling the HTML to link to more recent documentation or add SEO metadata is an ordeal.

**Comment by dcoutts** [comment]
So we now include a canonical link to the unversioned page (#321), we'll see how the search engines handle it.

**Comment by bitemyapp** [comment]
@dcoutts it still seems like google shows links to older versions of libraries, but the first result is almost always the unqualified version (latest), so I'm closing this as resolved unless something is noticed.
