### ISSUE TITLE
hackage server seems to complain on cabal files that start with a capital letter

### ISSUE THREAD

**Issue by KasperJanssens** [haskell/hackage-server#285]
Just cloned and compiled hackage server. We use it as a 'proxy' for packages we use at work. It seems to complain on cabal files starting with a capital, and I don't recall this to be the case. For example, I try to upload the docopt package to our local hackage server and I get 
The 'docopt-0.6.0.1/docopt.cabal' file is missing from the package tarball.
Which is true, the file is Docopt.cabal. If I change it to docopt.cabal it seems to work. I don't recall it would be forbidden to have cabal files start with capitals. A config option I missed during setup locally or a real issue?

**Comment by BardurArantsson** [comment]
I think my comments over at https://github.com/haskell/cabal/issues/2253#issuecomment-115307586 might be of interest.

(Not that I have any power over the direction of cabal, but I think it might be a solution that works and will keep working even if hackage-server adds new requirements.)
