### ISSUE TITLE
Add direct link to package LICENSE file on content page

### ISSUE THREAD

**Issue by hvr** [haskell/hackage-server#286]
Similiar to how Hackage adds a link to the changelog file, Hackage could (as an example) turn the `BSD3`-word in

```
...
License	    BSD3
Maintainer	libraries@haskell.org
Category    Control, Parallelism
...
```

into a link to the LICENSE file contained in the tarball.

**Comment by dcoutts** [comment]
5bd5ad039c383349b5ccb294ff13a742eac3e134 fixes this.
