### ISSUE TITLE
Add an indicator of browsing not-latest revision of a library

### ISSUE THREAD

**Issue by bananu7** [haskell/hackage-server#292]
Oftentimes when browsing hackage libraries, especially coming from a google link, I get into an older version of a library. There's no indicator whatsoever that would tell me that this version isn't the latest one.

As an example of a page that does that, look at [Django docs](https://docs.djangoproject.com/en/1.7/intro/tutorial01/). This helps avoid confusions between versions and allows to easily navigate to the latest version of the page.

I am willing to implement that, assuming that there are no reasons I might be not aware of that would make it extremely hard for a new hackager, or any other.

**Comment by ababkin** [comment]
I am sure many have been burnt by this. (I know i was) This seems like an adequate and relatively cheap solution to this annoying problem.

**Comment by gbaz** [comment]
closing in favor of #198

I really would like someone to round that half-PR I have there off...
