### ISSUE TITLE
Hackage is overzealous when checking timestamps

### ISSUE THREAD

**Issue by sol** [haskell/hackage-server#293]
```
$ cabal clean && cabal sdist && cabal upload dist/*.tar.gz
cleaning...
Source tarball created: dist/hspec-core-2.1.2.tar.gz
Uploading dist/hspec-core-2.1.2.tar.gz...
Error: dist/hspec-core-2.1.2.tar.gz: 400 Bad Request
Error: Invalid package

The tarball entry 'hspec-core-2.1.2/' has a file timestamp that is in the
future (2014-12-11 02:19:18 UTC). This tends to cause problems for build
systems and other tools, so hackage does not allow it. This problem can be
caused by having a misconfigured system time, or by bugs in the tools
(tarballs created by 'cabal sdist' on Windows with cabal-install-1.18.0.2 or
older have this problem).
```

**Comment by ekmett** [comment]
I just noted that it had happened again after being "fixed" -- as recently as 3 days ago when I commented.

While I do build and upload fairly quickly, my system time is also ntp'd, and checked the sync on it right after it failed last, and I had less than a second worth of clock drift. 

I merely offer the data point, not a solution.

**Comment by dcoutts** [comment]
Please re-open if anyone can reproduce this.

**Comment by andrewufrank** [comment]
i just had the same problem. the time on my machine seems to be set correctly. 
it may help to debug if you include not only the timestamp in the uploaded file but also the time of the server.

**Comment by hvr** [comment]
@andrewufrank see #501
