### ISSUE TITLE
"There are files missing .." - unexpected build failures

### ISSUE THREAD

**Issue by nikita-volkov** [haskell/hackage-server#294]
Since some recent update I have perfectly fine projects failing to get built by Hackage, all due to some of dependencies failing to install with "There are files missing ..." error. E.g.,
- http://hackage.haskell.org/package/hasql-postgres-0.8.0/reports/1
- http://hackage.haskell.org/package/stm-containers-0.2.6/reports/1

The projects are thoroughly tested to build just fine on Travis.

**Comment by gbaz** [comment]
old docbuilder issue, closing
