### ISSUE TITLE
Impossible to manually upload documentation

### ISSUE THREAD

**Issue by nikita-volkov** [haskell/hackage-server#295]
Since the latest Hackage update, uploading a documentation "tar" thru HTTP fails with:

> File in tar archive is not in the expected directory ...

**Comment by nikita-volkov** [comment]
Hmm... This issue could be related to Cabal. 

The uploads still fail on a system with the following installation:
```
huge-black-box-mac:record mojojojo$ cabal --version
cabal-install version 1.18.0.5
using version 1.18.1.4 of the Cabal library 
```

however they pass fine on the following:

```
mojojojo@ubuntu:~/Dev/record$ cabal --version
cabal-install version 1.20.0.3
using version 1.20.0.0 of the Cabal library 
```

**Comment by gbaz** [comment]
do we want to close this since it seems fine to only work with more recent cabals?

**Comment by goldfirere** [comment]
I think I hit this bug.

I'm trying to upload documentation for `th-desugar-1.6`. Haddock didn't build the docs upon upload, for reasons I don't know. (Where do I even look?) So I tried [this](https://github.com/ekmett/lens/blob/master/scripts/hackage-docs.sh), which uses `cabal upload`. From my terminal window, that looked successful, ending with `Ok`. But I don't see any update on Hackage. So then I tried the [really manual approach](http://fuuzetsu.co.uk/blog/posts/2014-01-06-Fix-your-Hackage-documentation.html), but that failed with the error mentioned in the original post on this issue.

So I'm not sure what's really wrong, but somehow I can't get my documentation up. :(

**Comment by hvr** [comment]
@goldfirere `cabal upload` was already the proper and recommended way to do this. Right now I can see the Haddock documentation. I suspect that what you were experiencing is the CDN in front of Hackage whose caching exhibits a non-negligible TTL... :-/

**Comment by goldfirere** [comment]
Yes, I see it do. I'll stick to `cabal upload` from now on. Thanks!
