### ISSUE TITLE
No way to properly edit invalid `.cabal`  files

### ISSUE THREAD

**Issue by hvr** [haskell/hackage-server#303]
I couldn't find a way to edit `cpphs-1.13` via

http://hackage.haskell.org/package/cpphs-1.13/cpphs.cabal/edit

in such a way that `cabal install cpphs-1.13` would fail to find a valid install-plan

**Comment by hvr** [comment]
@dcoutts maybe a simple workaround would be to allow "new" dependencies on `base` to be added; that way I could add a `build-depends: base <0` in this case (and it may be helpful to simplify other cases as well where just a global `build-depends: base <4.8` constraint is needed)

**Comment by dcoutts** [comment]
Mmm. Tricksy.

**Comment by dcoutts** [comment]
Try it, see if that's enough.

**Comment by hvr** [comment]
almost, here's a case of a syntactically incorrect `.cabal` file I cannot tweak to add an upper bound on `vector` (just click "review" w/o any change)

http://hackage.haskell.org/package/hashtables-1.0.0.0/hashtables.cabal/edit

**Comment by dcoutts** [comment]
I thought we had another ticket about editing .cabal files with actual parse warnings in them.

Mu fix above is about adding constraints on base where there was previously no deps listed at all.

**Comment by dcoutts** [comment]
Ah, #291. @hvr, so can we close this one?

**Comment by hvr** [comment]
yeah, this one issue works well enough for me then... ta
