### ISSUE TITLE
Showing dependencies introduced by manual flags can be misleading.

### ISSUE THREAD

**Issue by grayjay** [haskell/hackage-server#306]
Would it be better to only display the union of dependencies that are possible with manual flags unchanged?  Here is an example that is misleading: https://hackage.haskell.org/package/json-rpc-server-0.1.3.0  This package has a manual flag that builds a demo executable, which depends on happstack-server.  Listing happstack-server as a package dependency hides the fact that the library is more lightweight when built the usual way.

**Comment by dcoutts** [comment]
Yeah, that's probably a good heuristic, to not consider the manual flags as fixed.

**Comment by grayjay** [comment]
I've started working on this change.  Would you like a pull request?

**Comment by snoyberg** [comment]
@grayjay I just opened #357, which may or may not be resolved by your changes. I can't speak for @dcoutts, but I'd certainly be interested in seeing any changes made.

**Comment by grayjay** [comment]
#357 looks like an independent issue.  The change I was considering would only ignore the sections of a .cabal file that are enabled by flipping a manual flag.

**Comment by dcoutts** [comment]
@grayjay BTW, for this issue, some code that might help is: https://github.com/haskell/cabal/blob/cbfea2ada2f2755c81b12b355456a9f411191f22/Cabal/Distribution/PackageDescription/Check.hs#L1388

There's code there to evaluate the conditions, assuming nothing abut the environment except that manual flags have their default values.

**Comment by grayjay** [comment]
Thanks.  I'll take a look.
