### ISSUE TITLE
Upload rejects -dynamic as debug flag

### ISSUE THREAD

**Issue by nh2** [haskell/hackage-server#308]
See https://github.com/haskell/cabal/issues/2329. This is fixed in Cabal 1.22 with [this commit](https://github.com/haskell/cabal/commit/921921619ff69a7b7d524c6e94dd912859dc51f7).

My upload fails with `cabal check`'s `* 'ghc-options: -d*' debug flags are not appropriate for a distributed package` because of Cabal < 1.22 doing this check:

```
  , check (any ("-d" `isPrefixOf`) all_ghc_options) $
      PackageDistInexcusable $
        "'ghc-options: -d*' debug flags are not appropriate for a distributed package."
```

Could hackage-server use newer cabal?

**Comment by angerman** [comment]
What's the state of this? It's also blocking chrisdone/ghci-ng#11, and in turn syl20bnr/spacemacs#346. Who can update cabal on hackage?

**Comment by dcoutts** [comment]
Ok, then we can update the hackage-server to use the new Cabal.

**Comment by snoyberg** [comment]
This is also blocking ide-backend-server. Is there any ETA on getting this released?

**Comment by hvr** [comment]
Afaics, 71c7eb094ef231e7c1cbf5b8ba02903a8abf009d already updates hackage-server to use Cabal-1.22. However, afaik @dcoutts is still on holiday...

**Comment by snoyberg** [comment]
Is Duncan the only one who's able to make releases? I have no idea what the
release process is around Hackage.

**Comment by bergmark** [comment]
This seems to be resolved looking at http://hackage.haskell.org/package/ide-backend-server-0.9.0/ide-backend-server.cabal , correct?

**Comment by snoyberg** [comment]
Yes, I believe so, though I can't close the issue (I didn't report it).

**Comment by nh2** [comment]
[Works for me](https://github.com/nh2/call-haskell-from-anything/issues/3#issuecomment-99016339), closing.
