### ISSUE TITLE
add support for Android OS

### ISSUE THREAD

**Issue by capsjac** [haskell/hackage-server#311]
The hackage server does not recognize Android OS in .cabal file.
e.g. `if os(android)`
Would it be possible to add support for Android?
Related issue: https://github.com/haskell/cabal/issues/2348

**Comment by dcoutts** [comment]
Will be done once it's included in a Cabal release, and we update the server to use it.

**Comment by capsjac** [comment]
Great.

2015-03-04 5:56 GMT+09:00 Duncan Coutts <notifications@github.com>:

**Comment by dcoutts** [comment]
Should be done now.
