### ISSUE TITLE
How can I check whether a package is deprecated?

### ISSUE THREAD

**Issue by peti** [haskell/hackage-server#312]
Some packages, like http://hackage.haskell.org/package/deepseq-th, are marked deprecated on Hackage. Is there any way to check that programmatically? I looked into the 00-index.tar tarball, but that doesn't seem to contain this information (which might a nice addition, by the way; maybe in  a `x-status:` header?).

**Comment by hvr** [comment]
try

```
curl -H 'Accept: application/json' http://hackage.haskell.org/packages/deprecated
```

**Comment by dcoutts** [comment]
Or for example http://hackage.haskell.org/package/zlib/deprecated.json

See the http://hackage.haskell.org/api for details.

**Comment by peti** [comment]
Thanks for the quick response!
