### ISSUE TITLE
Quotation Marks Not Displayed In Online Documentation

### ISSUE THREAD

**Issue by eggonabull** [haskell/hackage-server#313]
In the documentation on:

https://hackage.haskell.org/package/HUnit-1.2.5.2/docs/Test-HUnit.html

The quotation marks surrounding strings in code segments are not displayed, and it looks like the wikicode is interpretting what should be strings as links.

**Comment by lfairy** [comment]
That's an issue with HUnit, not Hackage itself.

Try file a bug with the package maintainer instead. There should be an email address on the contents page.

**Comment by dcoutts** [comment]
Yep, they messed up their haddock markup.
