### ISSUE TITLE
Add "src" link to package main page

### ISSUE THREAD

**Issue by crockeea** [haskell/hackage-server#318]
This issue is about how to easily access the source code for *undocumented* (i.e. `{-# HADDOCK_OPTIONS hide #-}`) files. In the past, when I want to see the source code for an undocumented package, I've had to just download the entire package source.
However, I just discovered that you can access the source for any files *without* going to their documentation page first, e.g. via http://hackage.haskell.org/package/base-4.7.0.2/docs/src/
This link above provides a solution to that cumbersome process, but it isn't linked from the package main page. I only found it by doing a google search for source file and working backwards from the url. 

Can we get a link to that page on the main package page (i.e. http://hackage.haskell.org/package/base-4.7.0.2)

Another alternative (since we can already easily access the source code of *documented* files by using the "src" link on the documentation page for that file) is also a way to handle #256: on the main package page, files without documentation could link directly to the source code.

**Comment by dcoutts** [comment]
It is linked. It's the "browse" link next to the .tar.gz download.

Suggestions or pull reqs to make this more obvious are welcome.

**Comment by dcoutts** [comment]
BTW, improved the tarball browser to show the full dir tree.

**Comment by gbaz** [comment]
ok should we close this issue then?

**Comment by crockeea** [comment]
I think you can.
