### ISSUE TITLE
Duplicate anchors in source code

### ISSUE THREAD

**Issue by crockeea** [haskell/hackage-server#319]
Consider the source code for [base](http://hackage.haskell.org/package/base-4.7.0.2/docs/src/GHC-Base.html). I frequently make links to documentation or source code for packages on Hackage, for example, [here](http://stackoverflow.com/a/27883456/925978). I use HTML anchors in my link so that people can easily find what I'm talking about. However, some anchors appear multiple times in the source code for packages. For example, `GHC-base` has several "line-65" anchors, so the link http://hackage.haskell.org/package/base-4.7.0.2/docs/src/GHC-Base.html#line-65 takes me to the first line-65 anchor, which happens to be the *wrong* one.

I'm hoping something can be done with the HTML generation for the source code files that might fix this issue.

**Comment by lfairy** [comment]
That seems to an issue with HsColour, not Hackage, so I don't know what we'd be able to do here.

**Comment by malcolmwallace** [comment]
Yes, this is a bug in HsColour, now solved by version 1.21, which I just uploaded to Hackage.

**Comment by crockeea** [comment]
Assuming the server that builds haddock updates HsColour, this problem should be fixed in all future uploads to Hackage that do not manually generate documentation, right?

**Comment by malcolmwallace** [comment]
I can't speak for the maintainers for Hackage, neither how quickly they will update their HsColour, nor how they schedule its use in generating docs.

**Comment by lfairy** [comment]
Now that you mention it... the documentation for `base` is uploaded by the GHC folks themselves, so with luck this problem should fix itself with the next GHC release.

**Comment by malcolmwallace** [comment]
If you want the problem to "fix itself", I suggest prompting the GHC devs to upgrade their HsColour.  It is a package that does not change often, so people may not be in the habit of upgrading it, and cabal dependencies will not force its upgrade because it is used as an executable not a library.

**Comment by gbaz** [comment]
Should we close this issue then?

**Comment by crockeea** [comment]
Does hackage server now have the new version?

**Comment by hvr** [comment]
@malcolmwallace btw, would it be possible to include the version information of HsColour into the generated HTML? Currently HsColour generates the following:

```html
<head>
  <!-- Generated by HsColour, http://code.haskell.org/~malcolm/hscolour/ -->
  <title>Control/Applicative.hs</title>
  <link type='text/css' rel='stylesheet' href='hscolour.css' />
</head>
```

and while at it, make use of the `generator` meta-tag, i.e. something along the lines of

```
<head>
  <title>Control/Applicative.hs</title>
  <meta name="generator" content="HsColour 1.22 (http://code.haskell.org/~malcolm/hscolour/)">
  <link type='text/css' rel='stylesheet' href='hscolour.css' />
</head>
```

?

**Comment by gbaz** [comment]
closing as per discussion
