### ISSUE TITLE
Registration email isn't sent on HTTPS

### ISSUE THREAD

**Issue by kbillings** [haskell/hackage-server#323]
When you try to sign up on https://hackage.haskell.org/users/register-request with HTTPS enabled, it will not send the registration email.
It only sends the email when you are on HTTP. But after you get the email you can setup a password with HTTPS enabled and it works correctly.

**Comment by dcoutts** [comment]
Hmm, really? I'm surprised. The backend server doesn't know if you access it by http or https. Can anyone else reproduce this?

**Comment by gbaz** [comment]
tested and it works now.

**Comment by gbaz** [comment]
(note i think the issue was that the form action wasn't itself https, so some browsers block that.)
