### ISSUE TITLE
Hackage builders don't have enough resources

### ISSUE THREAD

**Issue by svenpanne** [haskell/hackage-server#324]
Recent builds of OpenGLRaw (http://hackage.haskell.org/package/OpenGLRaw-2.1.0.0/reports/1) fail because Haddock runs out of memory

    haddock: out of memory (requested 2097152 bytes)

Would it be possible to bump the memory limits for the builders?

**Comment by dcoutts** [comment]
Hmm, I'll check.

**Comment by svenpanne** [comment]
FYI: davean@xkcd.com has already done something, although I don't know what exactly. Haddock's memory usage seems to be very high, shall I open a bug for that?

**Comment by gbaz** [comment]
looks like this is fixed now?

**Comment by svenpanne** [comment]
Yes, seems to be OK now... Thanks!
