### ISSUE TITLE
Hackage does not find custom preprocessors

### ISSUE THREAD

**Issue by ttuegel** [haskell/hackage-server#331]
Originally reported by @niklasbroberg in haskell/cabal#1043:

For my hsp-0.7.1 package, I have a build failure for ghc-7.4. The failure is due to hsp requiring the trhsx preprocessor to parse. That preprocessor is installed in one of the dependencies, but apparently to a location that is not in the path.

Here are the relevant parts of the build failure log:

```
Building hsx-0.10.2...
Preprocessing executable 'trhsx' for hsx-0.10.2...
Building executable trhsx...
...
Installing executable dist/build/trhsx/trhsx to
/usr/local/tmp/archive/install/bin/trhsx
...
ghc: could not execute: trhsx
```

**Comment by dcoutts** [comment]
Installed.

Ultimately this is a missing feature in the cabal-install solver, that it doesn't track build tools yet.
