### ISSUE TITLE
Highlighted source code on hackage.haskell.org mangles Unicode

### ISSUE THREAD

**Issue by andersk** [haskell/hackage-server#334]
(This was auto-imported into the wrong GitHub repository. Moving this here from haskell/cabal#757.)

(Imported from [Trac #767](http://hackage.haskell.org/trac/hackage/ticket/767), reported by andersk on 2010-11-19)

On hackage.haskell.org, when you browse the source of a module that contains Unicode (e.g. [Data.Eq.Unicode](http://hackage.haskell.org/packages/archive/base-unicode-symbols/latest/doc/html/src/Data-Eq-Unicode.html)), it is sent with a `Content-Type: text/html` header with no charset. There is a charset in the XML declaration `<?xml version="1.0" encoding="UTF-8"?>`, but that is ignored by Firefox because of the non-XML `Content-Type`. Therefore, the wrong encoding is detected and the Unicode symbols get mangled.

Possible fixes include sending `Content-Type: text/html; charset=UTF-8`, or sending `Content-Type: application/xhtml+xml` so that the XML declaration is respected, or both (`Content-Type: application/xhtml+xml; charset=utf-8`), or adding equivalent `<meta http-equiv="Content-Type">` tags.

**Comment by dcoutts** [comment]
Changing the reported mime type should be easy.

**Comment by asr** [comment]
Not sure if the following issue is related, but the Unicode symbols also are mangled when browsing a `changelog` file that contains Unicode (e.g. http://hackage.haskell.org/package/Agda-2.4.2.2/changelog).

**Comment by asr** [comment]
Sorry if this is an obvious question. How I know that version of hackage-server is using Hackage?

**Comment by dcoutts** [comment]
I don't think we report it anywhere actually. Probably should do. Anyway, the fix has been deployed now.

**Comment by dcoutts** [comment]
Actually, the fix only covered plain text files, not the .html files. Should change that mime entry too.

**Comment by asr** [comment]
> the fix has been deployed now.

Thanks. I can see Agda's change logs files without Unicode issues.

**Comment by bergmark** [comment]
Is this just a matter of adding entries to the `mimeTypes'` map? If so it's perhaps **too** simple to leave it open as a easy-new-hacker-ticket? :)
