### ISSUE TITLE
Incorrect display of version ranges

### ISSUE THREAD

**Issue by snoyberg** [haskell/hackage-server#335]
Take, for example, the following page:

http://hackage.haskell.org/package/codex-0.2.1.4

It implies that `hackage-db` has no upper bound at all. However, if you look in the cabal file, you'll see:

    hackage-db          >= 1.8        && < 1.12

I believe the issue is that the executable's lack of bounds is being displayed, but it would clearly be superior to show the intersection of version ranges here.

**Comment by amigalemming** [comment]
I encountered the same problem for my packages, like:
https://hackage.haskell.org/package/synthesizer-dimensional

Big +1 for showing the intersection of version ranges instead of the union.

**Comment by dcoutts** [comment]
Fixed and deployed.
