### ISSUE TITLE
Add link to PVP on hackage frontpage

### ISSUE THREAD

**Issue by hvr** [haskell/hackage-server#343]
I just noticed that there's no mention about the PVP on http://hackage.haskell.org/ at all;

we should add a visible mention of the https://wiki.haskell.org/Package_versioning_policy there
(and maybe also on http://hackage.haskell.org/upload -- which alas looks a bit like a wall of text right now...)

**Comment by dcoutts** [comment]
Suggestion or pull req? It's in datafiles/templates/index.html.st in the central-server branch.

**Comment by gbaz** [comment]
@hvr -- if you give some proposed text I'm happy to make the PR. Also, go nuts on the /upload text?

**Comment by mightybyte** [comment]
I think this is a really good idea.  My first thought is that maybe it should be included as part of a broader "guidelines for hackage packages" section.  Maybe we should also mention package candidates here and link to the package candidate upload page.

**Comment by gbaz** [comment]
@mightybyte feel free to edit the template and send it to me. i can do the PR if you want :-)

**Comment by mightybyte** [comment]
How's this to get the conversation started?  https://github.com/haskell/hackage-server/compare/central-server...mightybyte:patch-1
