### ISSUE TITLE
Hackage accepts tarballs with broken permissions

### ISSUE THREAD

**Issue by peti** [haskell/hackage-server#346]
Maybe a release tarball like `bgzf-0.1.0.0.tar.gz` should be rejected from the server?

```
$ tar tfv bgzf/0.1.0.0/bgzf-0.1.0.0.tar.gz 
d--------- rcallahan/None    0 2015-04-19 06:31 bgzf-0.1.0.0/
---------- rcallahan/None  888 2015-04-19 06:31 bgzf-0.1.0.0/bgzf.cabal
---------- rcallahan/None 1490 2015-04-19 06:30 bgzf-0.1.0.0/LICENSE
d--------- rcallahan/None    0 2015-04-19 06:30 bgzf-0.1.0.0/Pipes/
---------- rcallahan/None 2473 2015-04-19 06:30 bgzf-0.1.0.0/Pipes/Bgzf.hs
---------- rcallahan/None   46 2015-04-19 06:30 bgzf-0.1.0.0/Setup.hs
```

`cabal get` will unpack this archive correctly, but everyone who tries to do this with `tar` will end up with a source directory that cannot be accessed (like our build in NixOS at http://hydra.cryp.to/build/781946/log/raw).

Also reported in https://github.com/rcallahan/bgzf/issues/1.

**Comment by dcoutts** [comment]
Good idea.

**Comment by iteratee** [comment]
OK, I have this basically done. What should the minimum umask be?
644 and 755 might be a little too much to ask. 400 and 500 Is probably the bare minimum to be considered not misformed. Thoughts?

**Comment by peti** [comment]
File and directory permissions of 6xx and 7xx should be enforced, IMHO. I wouldn't mind enforcing 644 and 755 either, though. Is there a legitimate use case for distributing a source tarball with permissions that are more restrictive than 644/755? I don't see how that could be useful for anything.

**Comment by iteratee** [comment]
I'd like to write a unit test for this. Is it reasonable to add HUnit to the test dependencies as a part of the change?

**Comment by iteratee** [comment]
Posted a pull request with a fix and a test.

**Comment by chrissound** [comment]
Shall we close this issue?

https://github.com/haskell/hackage-server/pull/409

**Comment by gbaz** [comment]
yep

**Comment by asr** [comment]
When you want to do something with the *latest* version of every package in Hackage the tarball `bgzf-0.1.0.0.tar.gz` is problematic for the reasons mentioned in the OP. @peti filed the issue https://github.com/rcallahan/bgzf/issues/1 almost five years ago, however there is no new version of `bgzf` in Hackage. ¿Could someone fix the permissions of  `bgzf-0.1.0.0.tar.gz` directly in Hackage, please.

**Comment by gbaz** [comment]
We don't mutate uploaded tarballs, sorry. If your code has trouble with that package, it'll need to work around that.

**Comment by asr** [comment]
Ok. Thanks.
