### ISSUE TITLE
Allow revising the cabal-version field

### ISSUE THREAD

**Issue by bergmark** [haskell/hackage-server#350]
Several packages have an unnecessarily high version listed, eg time: http://hackage.haskell.org/package/time-1.5.0.1/time.cabal

**Comment by hvr** [comment]
fwiw, I think it would be even enough to allow only a subset of all possible edits; we're mostly interested about downgrading the unnecessary ones to e.g. `>= 1.10`, specifically there doesn't seem to be any semantics-changing cabal format feature introduced been between 1.10 and 1.20;

so changing e.g. 1.16 to 1.10 should be considered harmless (assuming hackage's Cabal parser still accepts the revised .cabal file)

**Comment by dcoutts** [comment]
Can we pin this down precisely? The concern of course is that there are build system semantic changes with some cabal version changes.

**Comment by bergmark** [comment]
I've seen people use `cabal-version` to mark what cabal version a custom Setup.hs needs. So for a custom Setup.hs we probably need to test.

**Comment by phadej** [comment]
How about allowing `cabal-version: >=vvv` to `cabal-version: >=1.10` edits, if `build-type` is not `Custom` (i.e. `Simple`, `Configure` or `Make`) and where `vvv` is `>=1.10 && <1.21`?

**Comment by bergmark** [comment]
I didn't even know there were `Configure` and `Make`  build types so I can't comment on those :)

For the rest; is it likely that a custom build type can safely have its cabal-version changed? I'm not sure if limiting maintainter/trustee editing rights here will prevent that many mistakes, we already have rights to nefariously add a `base < 0` constraint.

**Comment by gbaz** [comment]
This should be fixed by the above commit.
