### ISSUE TITLE
Corrupted cabal file being served from Hackage?

### ISSUE THREAD

**Issue by snoyberg** [haskell/hackage-server#351]
I discovered this when trying to do a Stackage run, but can reproduce it using just `cabal-install`:

```
vagrant@vagrant-ubuntu-trusty-64:~/haskell/stackage$ cabal --version
cabal-install version 1.22.2.0
using version 1.22.2.0 of the Cabal library
vagrant@vagrant-ubuntu-trusty-64:~/haskell/stackage$ cabal update
Downloading the latest package list from hackage.haskell.org
vagrant@vagrant-ubuntu-trusty-64:~/haskell/stackage$ cabal install Workflow --dry-run
Resolving dependencies...
cabal: internal error when reading package index: failed to parse .cabal
fileThe package index or index cache is probably corrupt. Running cabal update
might fix it.
```

The error message I get from `stackage-curator` is a bit more enlightening:

```
$ stk curator check
Loading default build constraints
Creating build plan
stackage-curator: CabalParseException (FilePath "Workflow/0.8.3/Workflow.cabal") (FromString "unrecognised field or section: \"\\65279\"" (Just 1))
```

Continuing investigation myself, but this looks like a very high-priority issue to resolve.

**Comment by bergmark** [comment]
We just ran across this as well

```
< hvr> it's a crappy UTF8 BOM ;-(
```

@hvr

**Comment by bergmark** [comment]
Seems like hvr managed to fix it :-)

**Comment by snoyberg** [comment]
Thanks for confirming, I was about to bring it up on hackage-trustees. I'll fix this for myself easily (strip BOMs in stackage-curator), but both hackage-server and cabal seem like they need fixes for this.

**Comment by bergmark** [comment]
And i should clarify for anyone else seeing this, hvr fixed this one cabal file. The general issue is still open.

**Comment by dcoutts** [comment]
Cabal ignores the BOM in some places, but clearly cabal-install wasn't when reading the index.

**Comment by dcoutts** [comment]
All BOMs have been removed (afawk) and the server now rejects new ones on upload.
