### ISSUE TITLE
Incorrect dependencies when a dependency listed both with and without flag conditions

### ISSUE THREAD

**Issue by snoyberg** [haskell/hackage-server#357]
This may be a dupe of #306, I'm not certain. If you look at:

http://hackage.haskell.org/package/rss-3000.2.0.4

it will say that `time >= 1.1.2 && < 1.6`. However, if you look in the .cabal file itself, you'll see that it's impossible to compile with time-1.5.*.

Note: this may be modified in the future by a revision, as I opened https://github.com/basvandijk/rss/pull/4 about it.

It seems that the problem is the usage of unions instead of intersection when processing flags, but I'm not certain.

**Comment by grayjay** [comment]
This issue showed me a problem with the simple approach that I used to take the intersection of version ranges for issue #335.  I'll submit a PR for both issues.  I noticed that this change also helps where some packages specify bounds using ```package >=1, package <2```, rather than ```package >=1 && <2```.

**Comment by snoyberg** [comment]
Note that [all-cabal-metadata](https://github.com/commercialhaskell/all-cabal-metadata/blob/master/packages/rs/rss.yaml) gives the version range for time as:

    >=1.1.2 && <1.5 && >=1.5 && <1.6

This is determined using the default values for the flags, which in this case actually happens to be correct: the default flag value does not allow for any install plan. Arguably, Hackage should do some intelligent flag guessing, but honestly I think that's outside the scope of Hackage's display, and showing the default flag's constraints seems right.

**Comment by dcoutts** [comment]
Hmm. Ok, well I've merged #339 however I think this may still need more thought.

In the example at hand, rss-3000.2.0.4, we have:

    build-depends:   time >= 1.1.2 && < 1.5
    if flag(old-locale)
      build-depends: time >= 1.1.2 && < 1.5
    else
      build-depends: time >= 1.5   && < 1.6

So in this case I thinks it's quite right to summarise the situation as `>=1.1.2 && <1.6`. Note also that it is possible to build with time-1.5.*, when !old-locale. The new summary code summarises this as `>=1.1.2 && <1.5` which is clearly wrong.

BTW, what I really want to do with this package deps is have both a summary, and a "click through for all details" thing, that will show all the conditions/flags etc. So we can get away with significant simplifications, if we also make it easy to see all details.

**Comment by dcoutts** [comment]
Reverted for the moment. Needs more thought.

**Comment by dcoutts** [comment]
Should be fixed now. We re-merged the patch from @grayjay.
