### ISSUE TITLE
Changelogs with extension .txt should not be rendered as Markdown

### ISSUE THREAD

**Issue by ndmitchell** [haskell/hackage-server#363]
Compare https://www.stackage.org/snapshot/lts-2.9/package/hlint-1.9.20 and https://hackage.haskell.org/package/hlint-1.9.20/changelog. In the former Stackage has notices my file was called CHANGES.txt and displayed it as text. In the latter, Hackage has incorrectly assumed Markdown. Could Hackage please check the extension first, so it is compatible with what it used to do by default until very recently, when all my changelogs looked nice.

Thanks to @RyanGlScott for pointing this out, and I guess cc @snoyberg as I suspect he might have been involved with Markdowning all the things (as a random guess).

**Comment by snoyberg** [comment]
I'm innocent on this one. This change was added after merging in my PR. Perhaps ironically, that extra commit was put in place out of concern of introducing regressions in the display.

https://github.com/haskell/hackage-server/commit/f8092713f2a17c86b9048e6b5d7dc7192debf319

**Comment by dcoutts** [comment]
Done.
