### ISSUE TITLE
Enabling Sourcegraph access?

### ISSUE THREAD

**Issue by dzackgarza** [haskell/hackage-server#365]
I'm currently trying to familiarize myself with the codebase for this year's GSOC - would anyone be able to enable Sourcegraph for this repository? I believe it can be done through https://sourcegraph.com/github.com/haskell/hackage-server.

Thanks!

**Comment by bitemyapp** [comment]
@dzackgarza It says Haskell isn't supported, so why bother?

![screenshot from 2015-05-28 20 24 28](https://cloud.githubusercontent.com/assets/320177/7874628/a1a0c0b2-0577-11e5-911c-1a7e1232ce21.png)

**Comment by dzackgarza** [comment]
@bitemyapp It seems like a few people have had luck with Haskell on it - I found the advice on haskell-cafe, at https://mail.haskell.org/pipermail/haskell-cafe/2010-June/078915.html

It looks like I can actually enable it on a fork, so I'll try that first.

**Comment by bergmark** [comment]
Homepages says Haskell support is in Beta.

**Comment by gbaz** [comment]
Looks like at this point it is enabled and supported?
