### ISSUE TITLE
Docs not building

### ISSUE THREAD

**Issue by wereHamster** [haskell/hackage-server#368]
https://hackage.haskell.org/package/publicsuffix

I uploaded the package a few days ago and the docs are still not built. Is it an issue with the package or is the hackage server lagging behind?

**Comment by bitemyapp** [comment]
@wereHamster hackage server lagging.

**Comment by wereHamster** [comment]
Is there a more detailed page about the status of hackage doc builders? For example how long the queue is, how many builders are running etc?

**Comment by bitemyapp** [comment]
@wereHamster I don't think there's proper public metrics, but the real person to ask would be @gbaz

**Comment by gbaz** [comment]
There are no proper public metrics, but as the docbuilders have been lagging behind for a while, we did update the page at https://status.haskell.org/ to indicate the degraded performance

**Comment by wereHamster** [comment]
The docs are built now.

Are there any plans to expose more insight into the internals of the hackage server, like the number of jobs in the queue, when they were submitted, when they started being processed, how long each job took etc?

**Comment by gbaz** [comment]
Yep, we're all caught up. It would be good to have better monitoring of the current docbuilder, but I think there are plans more towards a more drastic rewrite of the docbuilder infrastructure.

**Comment by gbaz** [comment]
can we close this ticket?

**Comment by wereHamster** [comment]
yeah, sure.
