### ISSUE TITLE
The admin user isn't in the mirrorers group by default

### ISSUE THREAD

**Issue by dzackgarza** [haskell/hackage-server#370]
I'm not sure if this is something that's changed recently - with the latest build, I tried mirroring as per the instructions in the readme, but got 403 errors with the default admin:admin authentication in servers.cfg.

Adding admin to the mirrorers group (which is empty by default) seems to solve the issue. Not sure if this is related to file system permissions or hackage-server itself, but it may be worth mentioning in the documentation somewhere if anyone else can reproduce it.

**Comment by dcoutts** [comment]
Right, the default admin user isn't in the mirrorers group. I don't think we should change that, but if there's any documentation that needs fixing then we should do that.
