### ISSUE TITLE
Improve search for terms with dashes

### ISSUE THREAD

**Issue by mietek** [haskell/hackage-server#371]
Currently, searching for [`pdf-toolbox`](https://hackage.haskell.org/packages/search?terms=pdf-toolbox)  on Hackage gives 0 results, even though the following packages are available:
- `pdf-toolbox-core`
- `pdf-toolbox-document`
- `pdf-toolbox-content`
- `pdf-toolbox-viewer`

Searching for [`pdf toolbox`](https://hackage.haskell.org/packages/search?terms=pdf+toolbox) (with a space instead of a dash) includes the above packages in the results.

**Comment by dcoutts** [comment]
Should be a matter of splitting the input term on '-' too. We already do a number of these things, to correspond to term extraction from package names.

Alternatively, we could adjust how we do term splitting for package names. For a package name like "pdf-toolbox-core" we would currently index terms: "pdf-toolbox-core", "pdf", "toolbox", "core". But perhaps we should also index two word ones like "pdf-toolbox" or "toolbox-core".

But perhaps splitting the search term would be best, so for "pdf-toolbox" we'd lookup terms "pdf-toolbox", "pdf", "toolbox".

**Comment by gbaz** [comment]
It seems like this line is all that needs to be modified, for whoever wants to tackle it? https://github.com/haskell/hackage-server/blob/master/Distribution/Server/Features/Html.hs#L1571

**Comment by bitemyapp** [comment]
Longer term – may want to consider using a more complete term analysis package or a search engine for Hackage search. Might even enable pitching some code out.
