### ISSUE TITLE
Invalid .cabal file breaking cabal

### ISSUE THREAD

**Issue by snoyberg** [haskell/hackage-server#375]
```
$ cabal unpack dictionary-sharing
Unpacking to dictionary-sharing-0.1.0.0/
cabal: internal error when reading package index: failed to parse .cabal
fileThe package index or index cache is probably corrupt. Running cabal update
might fix it.
```

**Comment by hvr** [comment]
Oh well... UTF8 BOM strikes again... ;-(

In the meantime, I've edited the `dictionary-sharing.cabal` file to remove that pointless BOM prefix.

I wonder if haskell/cabal#526 needs to be reopened

**Comment by JonasDuregard** [comment]
Same issue with https://hackage.haskell.org/package/testing-type-modifiers-0.1.0.0
Interestingly, cabal unpack followed by cabal install works (although cabal unpack gives the same error). 

Is there any way for a maintainer to remove the BOM without uploading a new version? Modifying the cabal file using the maintanance interface does not appear to fix it.

**Comment by hvr** [comment]
@JonasDuregard you can use https://github.com/hvr/hackage-cli to `pull-cabal`, remove the BOM, tweak some whitespace in the `description` or `synopsis` field (to pass the validation step), and then `push-cabal --incr-rev` the fixed files...

**Comment by dcoutts** [comment]
Implemented a check in hackage-server (and now deployed). Could have done it via the check we added in Cabal, but that would have needed a Cabal lib upgrade, so just did one directly.
