### ISSUE TITLE
Wrap Long Lines

### ISSUE THREAD

**Issue by tebe47** [haskell/hackage-server#377]
<html><head><link rel="alternate stylesheet" type="text/css" href="resource://gre-resources/plaintext.css"
<pre>Akun=pare2
Pass=enjoybos
</pre></body></html>

**Comment by dcoutts** [comment]
what is this?

**Comment by lfairy** [comment]
@tebe47, please stop editing the wiki. The changes you made are not helpful.

**Comment by gbaz** [comment]
can we close this?

**Comment by lfairy** [comment]
@gbaz Go for it.
