### ISSUE TITLE
email was blocked as spam by Google

### ISSUE THREAD

**Issue by ChinaXing** [haskell/hackage-server#380]
When I register user on my self created package-server, the mail send failed, as following : 

How can I set the sender address instead of  `noreply@localhost`
```

The original message was received at Wed, 1 Jul 2015 10:30:12 GMT
from localhost [127.0.0.1]

   ----- The following addresses had permanent fatal errors -----
<chen.yack@gmail.com>
    (reason: 550-5.7.1 [106.185.55.152      12] Our system has detected that this message is)

   ----- Transcript of session follows -----
... while talking to gmail-smtp-in.l.google.com.:
>>> DATA
<<< 550-5.7.1 [106.185.55.152      12] Our system has detected that this message is
<<< 550-5.7.1 likely unsolicited mail. To reduce the amount of spam sent to Gmail,
<<< 550-5.7.1 this message has been blocked. Please visit
<<< 550 5.7.1  https://support.google.com/mail/answer/188131 for more information. gm10si2745646pbd.144 - gsmtp


Message-Id: <201507011030.t61AUCEq016444@localhost>
From: =?utf-8?Q?Hackage_website?= <noreply@localhost>
To: =?utf-8?Q?agent?= <chen.yack@gmail.com>

```

**Comment by dzackgarza** [comment]
I think that most email clients will mark any e-mail originating from an IP address (that is, without an associated domain name) as spam. As long as you're using sendmail or postfix, there should be options to set the domain name in their config files.

**Comment by dcoutts** [comment]
Right, the emailing relies on your local mail setup. So for example on hackage.h.o we relay mail for the hackage user to haskell.org, and that machine sends it out.

**Comment by dcoutts** [comment]
Note of course that you don't need to use the email registration system if you're running a small server. As an admin user you can create users directly.

**Comment by dcoutts** [comment]
Closing as this is not a server code issue.
