### ISSUE TITLE
Incorrect display of default flag value

### ISSUE THREAD

**Issue by 3noch** [haskell/hackage-server#381]
You'll [notice](https://github.com/bos/text/blob/b114f2a023823b448bd172beee3ae6d0d7aaceeb/text.cabal#L72) that `text-1.2.1.1` does not specify a default value for its `integer-simple` flag.

Yet for the same version, Hackage says the flag is enabled by default:

![image](https://cloud.githubusercontent.com/assets/882455/8469320/8d83e2aa-2046-11e5-962a-807c25b8cf40.png)

But if you try to build as-is without `integer-gmp`, the build will fail!

**Comment by bergmark** [comment]
Flags default to enabled according to the Cabal User Guide, that might explain it.

**Comment by 3noch** [comment]
How does that explain the fact that the default settings don't build without integer-gmp?

**Comment by bergmark** [comment]
It defaults to True, but it can still toggle to False if deemed necessary. It's not a manual flag. Did you check what flag setting it compiled with (-v2 in most recent cabal-install)?

**Comment by dcoutts** [comment]
@3noch any update on this?

I think hackage is saying the right thing here. As @bergmark says, the default for all flags is True unless specified otherwise, but they're still automatic flags subject to solving (unless marked manual).

Please re-open if you still think there's a bug in what hackage is reporting.

**Comment by 3noch** [comment]
It seems like a strange interop between `integer-gmp` and other packages. If the default is `True`, then how does `text` compile with default GHC distributions? Does `cabal` explicitly call out `False` for this when building it normally?
