### ISSUE TITLE
When choosing a license version, add the "or later version" option.

### ISSUE THREAD

**Issue by yuvallanger** [haskell/hackage-server#385]
For example, if one's preferred license is AGPL-3 or a later version, one would be able to use:

    license:    AGPL-3+

in the `*.cabal` file.

**Comment by lfairy** [comment]
This is really a Cabal issue, not a Hackage one.

In fact haskell/cabal#2547 covers this issue already.

**Comment by gbaz** [comment]
I suggest we close this in favor of that?
