### ISSUE TITLE
Hackage-server should be run with an https:// base uri?

### ISSUE THREAD

**Issue by gbaz** [haskell/hackage-server#387]
If we don't do so, then e.g. generated links in emails, etc. will redirect people from secure to insecure urls.

My only concern is checking that this doesn't interfere with hackage-server providing http:// based urls to the cabal binary when it isn't expecting https:// ones...

I'm fairly confident this is the case :-)

**Comment by aaronlevin** [comment]
:+1: 
I just registered an account and the page where I confirm my registration and set my password was not secured. 
```
Dear Aaron Levin,

We received a request to create a Hackage account
for you. To create a Hackage account, please follow
this link:

  http://hackage.haskell.org/users/register-request/XXXXXXXXXXXXXXX

If you were not expecting this email, our apologies,
please ignore it.

From,
  The Hackage website at http://hackage.haskell.org
  (and on behalf of the site administrators)
______________________________________________
Please do not reply to this email. This email
address is used only for sending email so you
will not receive a response.
```

Unfortunately the token doesn't exist anymore so I can't check if the page is accessible via `https`.

**Comment by aaronlevin** [comment]
Yes, a base uri of https needs to be set. This is where that link is generated: https://github.com/haskell/hackage-server/blob/233265f47ffca50bd42c2c6b029e6dc31dc6033c/Distribution/Server/Features/UserSignup.hs#L468

```haskell
            mailBody = renderTemplate $ templateEmail
              [ "realname"    $= realname
              , "confirmlink" $= serverBaseURI {
                                   uriPath = "/users/register-request/"
                                          ++ renderNonce nonce
                                 }
              , "serverhost"  $= serverBaseURI
              ]
```

**Comment by dcoutts** [comment]
Done.
