### ISSUE TITLE
Received exception: thread killed

### ISSUE THREAD

**Issue by ChinaXing** [haskell/hackage-server#390]
➜  hackage  hackage-server run --port=8088
hackage-server: Guessing public URI as http://localhost:8088
(you can override with the --base-uri= flag)
hackage-server: Ready! Point your browser at http://localhost:8088
hackage-server: WARNING: Received exception: thread killed
hackage-server: WARNING: Received exception: thread killed

**Comment by dcoutts** [comment]
Any other context? Does -v reveal anything. What client requests were going on?

**Comment by Qinka** [comment]
I got the same warning when I try to upload acme-everything-2015.4.15.1 to my package via package-mirror

**Comment by ChinaXing** [comment]
because it eat huge memory. when I open the swap. it works.
