### ISSUE TITLE
Server chokes on packages with READMEs containing invalid unicode

### ISSUE THREAD

**Issue by wereHamster** [haskell/hackage-server#395]
Literally. `Content-Length: 0`.

**Comment by edsko** [comment]
For example, trying to get http://hackage.haskell.org/package/cmdtheline returns an empty page ; the reason is that the README from `cmdlineline` contains an invalid unicode symbol; `iconv` chokes on it too:

```
[tmp/cmdtheline-0.2.2] iconv -t UTF-8 README.md >/dev/null
iconv: README.md:52:10: cannot convert
```

and the corresponding log entry shows

```
HTTP request failed with: Cannot decode byte '\xa9': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
```

**Comment by edsko** [comment]
For example, getting http://hackage.haskell.org/package/cmdtheline returns an empty page. The problem is that the corresponding README contains invalid unicode:

```
[~/tmp/cmdtheline-0.2.2] iconv -t UTF-8 README.md >/dev/null
iconv: README.md:52:10: cannot convert
```

and the corresponding entry from the Hackage log is

```
127.0.0.1 - [27/Jul/2015:06:36:04 +0000] "GET /package/cmdtheline 1.0" 200 -1 "" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36"
HTTP request failed with: Cannot decode byte '\xa9': Data.Text.Internal.Encoding.decodeUtf8: Invalid UTF-8 stream
```

The same goes for `cubical`.
