### ISSUE TITLE
Searching with an exact match

### ISSUE THREAD

**Issue by andrewthad** [haskell/hackage-server#397]
If I [search for pipes](http://hackage.haskell.org/packages/search?terms=pipes) on hackage, I get a long listing of relevant packages. However, it seems like it would make sense for `pipes` itself to be first on the list instead of being about 20 items down. This same behavior happens for `lens` as well.

**Comment by gbaz** [comment]
relevant code appears to be here https://github.com/haskell/hackage-server/blob/master/Distribution/Server/Features/Search/SearchEngine.hs

**Comment by mpickering** [comment]
You can also append `&explain` to a search query in order to get an explanation to the ranking.

**Comment by mpickering** [comment]
Here are the results for `lens`

![image](https://cloud.githubusercontent.com/assets/1216657/11532488/15066d14-98fc-11e5-98ba-d6262b6ef2a5.png)

But I can't work out why the results on my local copy of hackage are so different..

![image](https://cloud.githubusercontent.com/assets/1216657/11532506/26086ad6-98fc-11e5-9c5d-c49d3d2907c2.png)

**Comment by gbaz** [comment]
@dcoutts thoughts?
