### ISSUE TITLE
Reverse dependencies

### ISSUE THREAD

**Issue by edsko** [haskell/hackage-server#40]
This feature was implemented but is currently turned off because it used to much memory. This should be investigated, the data structured adjusted and the feature re-enabled. The number of reverse dependencies should be an important component of a package popularity/quality metric.

**Comment by gbaz** [comment]
should be resolved with the merge of https://github.com/haskell/hackage-server/pull/551

**Comment by l29ah** [comment]
For the record: https://packdeps.haskellers.com/reverse can be used now to figure out the reverse dependencies.

**Comment by gbaz** [comment]
That has existed for eight plus years. Its irrelevant to this ticket.

**Comment by l29ah** [comment]
It is relevant for people like me that find this ticket as their first google hit and want the functionality now.

**Comment by gbaz** [comment]
This ticket is not for that purpose. Its a ticket for tracking hackage issues.

**Comment by gbaz** [comment]
Closing as resolved.
