### ISSUE TITLE
A link to Index from the package page

### ISSUE THREAD

**Issue by Rufflewind** [haskell/hackage-server#400]
It would be useful to have a link to the _Index_ from the main package page on the top right corner, i.e.

```
https://hackage.haskell.org/package/foobar-0.0.0
```

This makes it a little easier to find specific identifiers by reducing the number of mouse-clicks to _doc-index-All.html_ from 3 to 2.

**Comment by gbaz** [comment]
Hmm... note we do have a link to the index now -- at the bottom of the module listings. Perhaps we should just move it to the top?

**Comment by gbaz** [comment]
oh, and ugh of course we should link to doc-index-All.html not just doc-index.
