### ISSUE TITLE
Incorrect CR/LF handling in Changelog rendering

### ISSUE THREAD

**Issue by svenpanne** [haskell/hackage-server#402]
The formatting of https://hackage.haskell.org/package/StateVar-1.1.0.1/changelog is garbled, while the corresponding GitHub page https://github.com/haskell-opengl/StateVar/blob/master/CHANGELOG.md looks OK. It's probably incorrect CR/LF handling (`cabal sdist` was done on Windows), because other LF-only changelogs like https://hackage.haskell.org/package/lens-4.12.3/changelog look correct.

**Comment by dcoutts** [comment]
See discussion in #460.
