### ISSUE TITLE
error about StringTable

### ISSUE THREAD

**Issue by Qinka** [haskell/hackage-server#405]
```
Data/StringTable.hs:34:3:
    Expecting one more argument to ‘StringTable’
    The first argument of ‘safecopy-0.8.2:Data.SafeCopy.SafeCopy.SafeCopy’
      should have kind ‘*’,
      but ‘StringTable’ has kind ‘* -> *’
    In the instance declaration for
      ‘safecopy-0.8.2:Data.SafeCopy.SafeCopy.SafeCopy StringTable’
```

I complied hackage-server with ghc-7.10.2 in openSuse(x86)
and I don't know what to do now.. :(

**Comment by ocharles** [comment]
I have just compiled against 7.10.2 and cannot reproduce this problem. Do you still encounter this with `master`?

**Comment by Qinka** [comment]
Sorry to reply late. I just try to install it in a sandbox, and get this error. But if without sandbox, it (installing) wil be fine.

**Comment by gbaz** [comment]
outdated now that the build instructions and setup have been redone.
