### ISSUE TITLE
Contents of `datafiles/TUF/timestamp.private` ?

### ISSUE THREAD

**Issue by erantapaa** [haskell/hackage-server#413]
After building the server and running:

    dist/build/hackage-server/hackage-server init --static-dir=datafiles/
    mkdir state/tmp
    dist/build/hackage-server/hackage-server run --static-dir=datafiles/

I get the error:

    .../datafiles/TUF/timestamp.private: does not exist

What should I populate this file with to get the server to start?

**Comment by edsko** [comment]
This is explained in the README in my PR (https://github.com/haskell/hackage-server/pull/412).

**Comment by edsko** [comment]
(Closed this issue not because it's invalid but because it's effectively a duplicate of the PR.)

**Comment by erantapaa** [comment]
Thanks!
