### ISSUE TITLE
Do we want a single `preferred-versions` file in the 00-index for backwards compatibility?

### ISSUE THREAD

**Issue by edsko** [haskell/hackage-server#414]
See for instance https://github.com/commercialhaskell/all-cabal-files/issues/8.

**Comment by hvr** [comment]
As we have a separate `01-index.tar.gz` now anyway, I'd suggest we try to keep the legacy `00-index.tar.gz` as backward-compatible as possible

**Comment by snoyberg** [comment]
:+1: from me @hvr

**Comment by gbaz** [comment]
I think based on my understanding of the discussion we may as well close this.
