### ISSUE TITLE
API Keys / Upload-Key

### ISSUE THREAD

**Issue by agrafix** [haskell/hackage-server#416]
I'm running automated deployment to hackage using travis. The problem here is, that I have to provide my password (in an encrypted form). I have no change to revoke this or view who and what exactly has my password. I would suggest to introduce a simple api key based auth that allow package uploads on behalf of a user. Are there any plans in this direction?

**Comment by dcoutts** [comment]
@agrafix if you'd like to work on this then come discuss it with the folks in #hackage.

**Comment by agrafix** [comment]
Fixed in #534
