### ISSUE TITLE
Upgrade ghc to 7.10.2 on hackage?

### ISSUE THREAD

**Issue by LeventErkok** [haskell/hackage-server#419]
It appears that packages uploaded to Hackage are still being compiled with GHC 7.8.3; which is now over a year old. Some of the packages that rely on newer GHC features thus get build-failures.

Would it be possible to upgrade the ghc version used for building the packages?

**Comment by wereHamster** [comment]
Why does hackage need to compile the packages? I'd much rather use [travis](https://travis-ci.org/) to test the builds. Beause on travis I can specify a build matrix, so I can easily build and test against multiple versions of GHC.

**Comment by LeventErkok** [comment]
@wereHamster It's mostly about documents. Browsing online documentation is really what Hackage is really all about (at least for me), so uploading a package and having no docs show up is a bummer.

I understand that there are ways of being able to upload documents manually, but it'd be much nicer if Hackage can just do it automatically.

**Comment by orome** [comment]
Did thus just change? After repeated frustrations trying to upload them, they've magically appeared and the logs show that they built with 7.10.2. Is this change permanent? Can we rely on it?

**Comment by hvr** [comment]
yes, the doc buildbot has been updated to GHC 7.10.2 but won't be permament.. at some point we'll update to GHC 7.10.3 or GHC 8.0 or whatever comes next :-)

**Comment by orome** [comment]
Cool. Thx!

**Comment by LeventErkok** [comment]
Cool. Is it possible to ask hackage to "re-try" building an existing package now so the docs can show up? Or, do we need to do a new upload?

**Comment by bennofs** [comment]
@LeventErkok Yes this is possible (haven't tried it though): go to the package package, click on "edit package information" (under heading "Maintainers corner") and then click on one package version under "Manage documentation for". There is a button "Delete documentation and trigger rebuild". Alternatively, you can also manually upload documentation.

**Comment by LeventErkok** [comment]
@bennofs Yes, that does indeed work.. Thank you!
