### ISSUE TITLE
hackage.h.o fails to generate docs for libinfluxdb

### ISSUE THREAD

**Issue by wereHamster** [haskell/hackage-server#420]
```
Running Haddock for libinfluxdb-0.0.1...
cabal: Haddock's internal GHC version must match the configured GHC version.
The GHC version is 7.10.2 but haddock is using GHC version 7.8.3
```

That's not my fault, is it?

**Comment by hvr** [comment]
@wereHamster no it isn't; it's an incomplete upgrade to GHC 7.10 (re #419) on our end...

/cc @gbaz @davean

**Comment by hvr** [comment]
This should be fixed now. I've triggered a rebuild of the docs of http://hackage.haskell.org/package/libinfluxdb which will hopefully succeed this time
