### ISSUE TITLE
inline-r documentation fails on hackage.haskell.org

### ISSUE THREAD

**Issue by mboes** [haskell/hackage-server#421]
Generating the haddocks for inline-r fails: http://hackage.haskell.org/package/inline-r-0.7.1.0/reports/3, due to the build requiring R to be installed. Any chance R could be installed on the hackage.haskell.org machines? Stock R from the distro should work okay so long as it's >= 3.0, or via the ppa:marutter/rrutter PPA.

cc @fuuzetsu @kryoxide

**Comment by gbaz** [comment]
R seems a bit heavyweight to install on our docbuilder..  Maybe you could just upload your own as per the instructions at the bottom here?

https://hackage.haskell.org/upload

**Comment by mboes** [comment]
This ticket is 2 years old. What we've found as a solution in the meantime is to become part of Stackage. The doc generated there works just fine: https://www.stackage.org/package/inline-r. And like a number of other packages we just point to that in the README.

We don't use cabal-install to build this package and its multiple ancillary ones. It's a bit of a cost that currently the docs can only be uploaded to Hackage using cabal-install (need to rebuild all deps once more etc). But I guess that's a feature request for Stack.
