### ISSUE TITLE
Synopsis is unusable and cannot be closed when a package contains long type signatures

### ISSUE THREAD

**Issue by danse** [haskell/hackage-server#422]
See for example some of [Yesod's packages](https://hackage.haskell.org/package/yesod-form-1.4.4.1/docs/Yesod-Form-Functions.html). The synopsis is too wide, it cannot be read or clicked and cannot be closed, the only way to restore functionality is refresh the page and avoid using the synopsis again

**Comment by Rufflewind** [comment]
This has been [fixed in Haddock a while back](https://github.com/haskell/haddock/pull/373), but it seems that Hackage is not using the latest version.

**Comment by danse** [comment]
I don't get the system used here in order to reuse CSS assets. In other projects i use [Bower](bower.io) for this. Since the file names in the two repos differ, i doubt that any reuse is actually in place

**Comment by gbaz** [comment]
Fixed.

**Comment by danse** [comment]
thanks! :+1:
