### ISSUE TITLE
Add charset info to source html pages

### ISSUE THREAD

**Issue by JustusAdam** [haskell/hackage-server#441]
When requesting the source of a particular file the resulting html does not contain any charset information. 

As a result unicode symbols are not correctly displayed on machines that don't default to unicode/UTF-8.

I propose to either include charset information in the response header or in the html head.

**Comment by treeowl** [comment]
I believe this is a problem with the response header. For example, [this page](http://hackage.haskell.org/package/constraints-0.6/docs/src/Data-Constraint-Forall.html) has `<?xml version="1.0" encoding="UTF-8"?>` at the top, which I imagine is supposed to indicate the encoding. But when I ask my browser for page info, it reports the encoding as `windows-1252`. As a result, the names of Ørjan Johansen and András Kovács are mangled.

**Comment by lfairy** [comment]
There is already logic to declare UTF-8 encoding in the response header, but a simple typo meant that it was never used.

This mistake should be fixed in #443.
