### ISSUE TITLE
Preferred versions should be displayed separately.

### ISSUE THREAD

**Issue by massysett** [haskell/hackage-server#444]
It took me awhile to figure out why some of the package versions for [HSpec](https://hackage.haskell.org/package/hspec) are green.  When I finally figured it out, I realized that the non-preferred versions are green.  Green means good, so it's strange that non-preferred versions would be green while the "better" versions are in a regular font.  Non-preferred ones should be greyed out, stricken through, or (I think this is best) appear in a separate heading "non-preferred versions".  The separate heading would give a much better clue as to what this is all about--much better than having a simple "Info" link.

**Comment by bergmark** [comment]
#373

**Comment by massysett** [comment]
When I saw that the old ones were green and the new ones are the regular color (sort of reddish orange on my system) my first guess was that the old ones are stable and the new ones are somehow "beta" or "unstable" or otherwise not recommended for installation.  I started by clicking on the green versions, but looking at these told me nothing about why they were green.

**Comment by gbaz** [comment]
Updating the ticket title to indicate a proposed solution from the ticket that I think isn't bad...

Most packages don't have preferred versions. I would suggest those that do have a new row for them. The color signaling is confusing otherwise.

**Comment by gbaz** [comment]
We have better colors now, and also the info link. I think that sufficiently resolves this?

**Comment by gbaz** [comment]
seeing the lack of further discussion, closing
