### ISSUE TITLE
New distribution: Arch

### ISSUE THREAD

**Issue by felixonmars** [haskell/hackage-server#447]
Hi, I would like to add Arch as a new distribution. Currently we have only 130+ packages, but it's likely to increase in the future.

I have tried to use the distro API (PUT /distros/Arch), but it doesn't seem to work (404). Please let me know if I missed something. Thank you!

**Comment by gbaz** [comment]
you'll need to POST to add the distro as per: http://hackage.haskell.org/api#distro ?

**Comment by felixonmars** [comment]
It still returns a 404 error for POST request :(

**Comment by gbaz** [comment]
I created it for you. For the record, here is what I did:

> curl --user User:Pass -X PUT http://hackage.haskell.org/distro/Arch

I did this with my admin user/pass but I think it would work with any authorized user for hackage.

This is a tad... undocumented :-P

**Comment by felixonmars** [comment]
Ah, I think I did something wrong in the authentication part. It works fine now, thank you!
