### ISSUE TITLE
Please change "darcs get" into "darcs clone"

### ISSUE THREAD

**Issue by geh** [haskell/hackage-server#449]
Hi, since Darcs 2.10 the default command for cloning repositories is "clone" (instead of "get", which still remains as a hidden alias). The "clone" command is present in darcs since 2009. Please update the following line to reflect this change:

https://github.com/haskell/hackage-server/blob/master/Distribution/Server/Pages/Package.hs#L458

**Comment by neongreen** [comment]
This has already been fixed, so this issue can be closed.
