### ISSUE TITLE
Build fails because the installed mtl package can not be found

### ISSUE THREAD

**Issue by HJvT** [haskell/hackage-server#450]
The [build log for wxcore](https://hackage.haskell.org/package/wxcore-0.92.1.0/reports/2) shows that mtl is installed, but later on, parsec cannot be installed because mtl can not be found.

**Comment by gbaz** [comment]
Its requesting a different hash for mtl, so appears to be a "diamond dependency issue." Also issues with builders aren't the hackage codebase, but can instead be reported on #haskell-infrastructure on freenode.
