### ISSUE TITLE
hackage-mirror - createDirectory: permission denied

### ISSUE THREAD

**Issue by mpickering** [haskell/hackage-server#452]
There seems to have been a few changes to `hackage-mirror` since the last time I used it and now it doesn't work.

```
~/Documents/haskell/hackage-server:./hackage-mirror mirror.cfg zlib
No cached index available for target repo
20 packages to mirror.
mirroring zlib-0.2
hackage-mirror: /package: createDirectory: permission denied (Permission denied
```

Why is it trying to write there? It seems like a bug to me. 

My config file

```
source "name-of-source-repo"
    uri: http://hackage.haskell.org
    type: hackage2

target "name-of-target-repo"
    uri: http://matthews-macbook-pro.local:8080/
    type: local
```

**Comment by bwbaugh** [comment]
I had the same issue. Removing the trailing `/` from the target `uri` (after the port) worked for me.

**Comment by gbaz** [comment]
updated the readme to give explicit instructions here and provide a sample that works properly...
