### ISSUE TITLE
Obfuscate email addresses

### ISSUE THREAD

**Issue by centromere** [haskell/hackage-server#455]
I am getting a lot of spam addressed to my hackage email account. It would be nice if the website  had some type of mechanism to obfuscate email addresses.

**Comment by dcoutts** [comment]
We could do the same tricks that pandoc uses. PR would be accepted.

**Comment by fgaz** [comment]
The effect would be minimal, as a bot can always follow the link to the .cabal file, where the email is always in plaintext

**Comment by hvr** [comment]
Also, I'd expect that by now even the dumbest bots is able to pattern match and reverse-map most obvious obfuscations such as `foo at gmail dot com`. So I don't see any significant benefit to obfuscation either, to the contrary it would make it rather inconvenient for legitimate uses (i.e. being able to click on the email and have my browser open up an email client w/ the To field pre-filled).

**Comment by gbaz** [comment]
i'm going to suggest we close this. i think the prevent-spam-through-email-obfuscation approach really has fallen by the wayside across the internet at this point? additionally the point about raw cabal files having it anyway seems to make the whole thing moot?
