### ISSUE TITLE
Garbled rendering of changelog and readme markdown (with windows line endings?)

### ISSUE THREAD

**Issue by dmcclean** [haskell/hackage-server#460]
The `changelog.md` and (to a lesser extent) `readme.md` files for version 1.0.1.1 (among others, but this is the latest) of the `dimensional` package display cleanly on GitHub (https://github.com/bjornbm/dimensional/blob/v1.0.1.1/CHANGELOG.md) but are garbled on hackage (http://hackage.haskell.org/package/dimensional-1.0.1.1/changelog).

The headers and unordered lists are rendered quite strangely.

(A lesser problem in rendering of the readme file for the same package is that the line breaks in the markdown do not appear to be converted to HTML paragraphs, instead everything runs together.)

I've attempted to diagnose this problem by comparing our changelog and readme files to those of packages that work, like `linear` or `pipes-attoparsec`. At first I thought it might be the extension `.md` vs `linear`'s `.markdown`, but the `pipes-attoparsec` one uses `.md` and works. Then I thought it might be line ending style. The `cabal sdist` file for this package was created on Windows after getting the source with the default git options, and so the files as uploaded have Windows line endings. I believe this is the issue. I will attempt to confirm this by uploading a package candidate that has the same files but with LF-only line endings.

**Comment by dmcclean** [comment]
Line endings are indeed the issue.

I've updated our files to deal with this.

I would like to request support for windows-style line endings as a low priority feature request, because it might trip up other newcomers.

**Comment by dcoutts** [comment]
Easy fix for someone to make a PR for. Look here:

https://github.com/haskell/hackage-server/blob/master/Distribution/Server/Features/PackageContents.hs#L204

Insert a CRLF->LF conversion into that function pipeline, test it, submit a PR.

**Comment by ma489** [comment]
@chrissound and I are going to have a stab at this
