### ISSUE TITLE
containers documentation is broken

### ISSUE THREAD

**Issue by rwbarton** [haskell/hackage-server#463]
(Apparently pressing enter after entering the issue name creates the issue...)

Not sure this is really the right place to report this, but the latest version of containers (http://hackage.haskell.org/package/containers-0.5.7.1) has no documentation despite having been uploaded two weeks ago. This is bad because the Hoogle instance at https://www.haskell.org/hoogle/ links to things like http://hackage.haskell.org/packages/archive/containers/latest/doc/html/Data-Map-Lazy.html#v:intersectionWith, which currently points to the nonexistent containers-0.5.7.1 documentation. Let's not break Hoogle!

**Comment by hvr** [comment]
will do later today unless somebody beats me to it

**Comment by rwbarton** [comment]
Looks like this is done, thanks!
