### ISSUE TITLE
regex-applicative-0.3.3 documentation unavailable

### ISSUE THREAD

**Issue by alogic0** [haskell/hackage-server#464]
Uploaded	        Sun Dec 27 
    Status	            Docs pending
    Build status        unknown [no reports yet]

https://hackage.haskell.org/package/regex-applicative-0.3.3

UPD. It's been more than 10 days from the date of loading, but the documentation has not yet appeared. And even no report about what is broken.

**Comment by gbaz** [comment]
Closing in favor of #478 -- the issue here in particular is that only _certain_ classes of failed builds get reported (those for which there is a plan, but a failure, I believe, not those for which no plan is possible).
