### ISSUE TITLE
Should example security files be part of the source distribution?

### ISSUE THREAD

**Issue by edsko** [haskell/hackage-server#465]
... and automatically be installed in the right places? 

If so, we need to make sure this happens. Right now I have not changed the source distribution at all. 

Note that this means that when people install Hackage, they will basically be running a non-secure server; but that's much as it was before anyway so I think that's ok. If we _don't_ do this then it means that when people `cabal install hackage-server` they will get a server that won't boot up until they install the security files.

**Comment by gbaz** [comment]
I think we decided to ship with example files, and the docs currently explain how to replace them, etc. This seems to be a working approach, so I'll close.
