### ISSUE TITLE
"There are files missing in package..."

### ISSUE THREAD

**Issue by mrkkrp** [haskell/hackage-server#473]
https://hackage.haskell.org/package/plan-b-0.1.0/reports/1

```
Path/IO.hs:96:18:
    Could not find module ‘System.IO.Temp’
    There are files missing in the ‘temporary-1.2.0.4@tempo_FqFHfwaqndW57NYY98FwdF’ package,
```

How is that? Where did the files go?

**Comment by gbaz** [comment]
this is the related ticket https://github.com/haskell/cabal/issues/3093

**Comment by gbaz** [comment]
we think the issue was somehow due to the builder being run from within the same directory in which it was built (in a sandbox) and the sandbox confusing it. appears resolved at the moment.
