### ISSUE TITLE
haddock failing on upload

### ISSUE THREAD

**Issue by andygill** [haskell/hackage-server#475]
haddock is failing when uploading a new package, remote-monad.

<http://hackage.haskell.org/package/remote-monad-0.1.0.0/reports/1>

The problem is that this should trivially work - natural-transformation-0.3 contains the requested module, an is on hackage. And there *is* documentation for natural-transformation-0.3 on hackage. Perhaps there is a stale package somewhere as part of this build.

Please recommend hot to proceed.

````
Resolving dependencies...
Warning: Note that reinstalls are always dangerous. Continuing anyway...
Downloading remote-monad-0.1.0.0...
Configuring remote-monad-0.1.0.0...
Building remote-monad-0.1.0.0...
Preprocessing library remote-monad-0.1.0.0...

src/Control/Remote/Monad/Packet/Applicative.hs:28:8:
    Could not find module ‘Control.Natural’
    There are files missing in the ‘natural-transformation-0.3@natur_AGbatXKIq84BVvitQzuTkB’ package,
    try running 'ghc-pkg check'.
    Use -v to see a list of the files searched for.
Failed to install remote-monad-0.1.0.0
cabal: Error: some packages failed to install:
remote-monad-0.1.0.0 failed during the building phase. The exception was:
ExitFailure 1
````

**Comment by mrkkrp** [comment]
The same thing here, I've reported it in #473.

**Comment by gbaz** [comment]
This is the related ticket: https://github.com/haskell/cabal/issues/3093

**Comment by gbaz** [comment]
builder now working, as evinced by a successful build of 0.2 of this package... http://hackage.haskell.org/package/remote-monad-0.2/reports/
