### ISSUE TITLE
stm-2.4.4.1 docs still pending

### ISSUE THREAD

**Issue by wereHamster** [haskell/hackage-server#476]
The package was uploaded on Dec 22.

**Comment by crockeea** [comment]
Related: #244 #265, and [lol](https://hackage.haskell.org/package/lol).

**Comment by gbaz** [comment]
built now, closing

**Comment by crockeea** [comment]
To be clear, this is not a victory for hackage server: The docs were manually uploaded.

**Comment by gbaz** [comment]
¯\_(ツ)_/¯

This is a ticketing system, not a backgammon scorecard.
