### ISSUE TITLE
Enable raw HTML in markdown for README.md

### ISSUE THREAD

**Issue by afcady** [haskell/hackage-server#477]
So I just filed [a bug against Lens](https://github.com/ekmett/lens/issues/633) because of the errant rendering of README.md on the hackage front page for Lens.  I thought it was some kind of simple error in the markup to be fixed quickly.

Turns out, [the behavior is intentional](https://github.com/haskell/hackage-server/pull/356#issuecomment-102956799): hackage-server explicitly avoids rendering raw HTML.

I propose to reconsider that decision, taking into account the fact that stackage is already rendering raw HTML (e.g., see http://www.stackage.org/package/lens).  It works there, and now lens's page just looks worse on hackage.  It also works on github.  Basically hackage is simply behind.

Is there some compelling benefit?  Security issues?  Seems like a package submitter can only mess up their own page with invalid html,  not anybody else's, so why not?

**Comment by Rufflewind** [comment]
> Seems like a package submitter can only mess up their own page with invalid html, not anybody else's, so why not?

If HTML is enabled indiscriminately, it would make Hackage a vector for malware.  It's best to limit the renderer to some whitelisted ("safe") subset of HTML.

**Comment by afcady** [comment]
You think package submitters are going to choose *html* as a vector for malware?  You realize that compiling a package can execute arbitrary code right?

Maybe whitelisting HTML is **best** but web browsers are already designed not to trust HTML (unlike cabal, which is designed to trust *executable code* on hackage) -- so if the alternative is "unsafe" HTML or *no* HTML, unsafe seems superior to me.  At some point in the future, Cheapskate could be made to sanitize HTML.  There's little reason to hold things up though.

**Comment by sjakobi** [comment]
> Cheapskate could be made to sanitize HTML.

[Cheapskate](http://hackage.haskell.org/package/cheapskate) already sanitizes inline HTML to protect against XSS attacks, according to its package description.

@Rufflewind Do you have any other security concerns?

**Comment by Rufflewind** [comment]
@sjakobi Nope.

**Comment by sjakobi** [comment]
If anyone else has any concerns about allowing inline HTML please share them soon! Otherwise I'm going to make a PR.
