### ISSUE TITLE
Sort out doc building

### ISSUE THREAD

**Issue by silky** [haskell/hackage-server#478]
There are [many issues related building of library docs](https://github.com/haskell/hackage-server/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+docs). Others have been reported on the haskell-cafe and cabal-devel mailing lists.

One seems to outline a plan related to fixing the main system: https://github.com/haskell/hackage-server/issues/282 however it's 2 years old, and no progress for over a year.

can we sort this out?

is there some kind of plan in the works? @hvr ? or should we just get our hands dirty by trying to replicate the problem with local setups of the hackage server? happy to proceed in any direction; but looking for some discussion first.

thanks.

**Comment by gbaz** [comment]
What we need is a volunteer (assistant) doc czar to help out @davean

The issues are partially in building better, more stable docbuilder code (and honestly rewriting some of how the interactions work).

But keeping the builders up and running is also a sysadmin task, and it needs people to mind it.

Note that ongoing discussion of the docbuilder stuff tends to happen slowly via chats in the #haskell-infrastructure irc channel.

If anyone reading this ticket wants to volunteer and offer a commitment of time and attention over a significant span of time to help mind the docbuilders, and in so doing, to understand their failure modes, please speak up!

**Comment by gbaz** [comment]
The current round of failures seems due to this issue going on with a cabal ticket: https://github.com/haskell/cabal/issues/3093

**Comment by silky** [comment]
i'm happy to volunteer, and also to look into rewriting some of the code after getting an understanding for it.

how should i proceed?

**Comment by gbaz** [comment]
The main thing is to idle in #haskell-infrastructure and volunteer there. We'll try to hook you up with an account on the builder boxes in the next few days (you can email admin@haskell.org too). From there, its investigating their logs, and the coming up with a plan of attack that A) makes the builder failures and status more publicly auditable and B) more resilient.

Part of this relates to being able to run multiple builders and have them co-ordinate, which is about managing shared state of built/unbuilt and reasons, in part.

**Comment by silky** [comment]
okay, thanks will do.

**Comment by crockeea** [comment]
Any progress on this? I'd be happy to do (and have been doing) some digging into hackage-build. 

Just today, I was working on [transformers-0.5.2.0](https://hackage.haskell.org/package/transformers-0.5.2.0), which built in seconds on my computer with GHC 7.10.3. 

@gbaz: If the error is related to cabal, why are we not seeing (failed) build-reports? transformers doesn't have one, but my local server created a report, log, and docs without problems.

**Comment by silky** [comment]
i've not gotten anywhere.

last i heard @davean was rebuilding things slowly and was making progress, but i'm not sure since then.

**Comment by gbaz** [comment]
Things got busy, but I'd like to work with @davean 's and your help to just do some interim tweaks to the builder box to at a minimum get better logging and change the queue system to be more inspectable, as an interim step.

**Comment by crockeea** [comment]
@gbaz Docs are _still_ not building reliably: [lol-apps](https://hackage.haskell.org/package/lol-apps). However, they did build successfully for [lol](https://hackage.haskell.org/package/lol).

**Comment by crockeea** [comment]
@erantapaa Thanks for looking into this. I want to point out that the problem has been going on since at least July 2014, as reported in #244.

**Comment by gbaz** [comment]
@bgamari is now taking a look at this on the server as well.

**Comment by Blaisorblade** [comment]
> I want to point out that the problem has been going on since at least July 2014, as reported in #244.

An earlier report is from October 2013 in #145.

**Comment by bgamari** [comment]
I had another look at this today and actually had some trouble finding a failed package. One failure that I was able to find was [`texmath-0.8.6.5`](https://hackage.haskell.org/package/texmath). The log is rather perplexing,
```
Resolving dependencies...
cabal: Could not resolve dependencies:
next goal: texmath (user goal)
rejecting: texmath-0.8.6.4, texmath-0.8.6.3, texmath-0.8.6.2, texmath-0.8.6.1,
texmath-0.8.6, texmath-0.8.5.1, texmath-0.8.5, texmath-0.8.4.2,
texmath-0.8.4.1, texmath-0.8.4, texmath-0.8.3, texmath-0.8.2.2,
texmath-0.8.2.1, texmath-0.8.2, texmath-0.8.1, texmath-0.8.0.2,
texmath-0.8.0.1, texmath-0.8, texmath-0.7.0.2, texmath-0.7.0.1, texmath-0.7,
texmath-0.6.6.3, texmath-0.6.6.2, texmath-0.6.6.1, texmath-0.6.6,
texmath-0.6.5.2, texmath-0.6.5, texmath-0.6.4, texmath-0.6.3, texmath-0.6.1.5,
texmath-0.6.1.4, texmath-0.6.1.3, texmath-0.6.1.2, texmath-0.6.1.1,
texmath-0.6.1, texmath-0.6.0.6, texmath-0.6.0.5, texmath-0.6.0.4,
texmath-0.6.0.3, texmath-0.6.0.2, texmath-0.6.0.1, texmath-0.6,
texmath-0.5.0.4, texmath-0.5.0.3, texmath-0.5.0.2, texmath-0.5.0.1,
texmath-0.5, texmath-0.4, texmath-0.3.1.5, texmath-0.3.1.4, texmath-0.3.1.3,
texmath-0.3.0.3, texmath-0.3.0.2, texmath-0.3.0.1, texmath-0.3,
texmath-0.2.0.4, texmath-0.2.0.3, texmath-0.2.0.2, texmath-0.2.0.1,
texmath-0.2, texmath-0.1.1, texmath-0.1.0.4, texmath-0.1.0.3, texmath-0.1.0.2,
texmath-0.1.0.1, texmath-0.1, texmath-0.6.7, texmath-0.6.5.1 (constraint from
user target requires ==0.8.6.5)
Dependency tree exhaustively searched.
```
It appears that we tried to build the target version, but it was present in the local package list. How could this happen?

**Comment by crockeea** [comment]
@bgamari Where did you find that log file? It doesn't appear to be uploaded on Hackage, so regardless of whether the build should have succeeded or not, that's a bug.

**Comment by bgamari** [comment]
crockeea <notifications@github.com> writes:

> @bgamari Where did you find that log file? It doesn't appear to be
> uploaded on Hackage, so regardless of whether the build should have
> succeeded or not, that's a bug.
>
That is from
`/home/builder/hackage-server/build-cache/results/texmath-0.8.6.5.log`
on the builder itself. I believe @davean once told me that failures to
find a workable install plan indeed weren't handled correctly (resulting
in the package being stuck in "documentation pending" state). This does
seem like a bug, albeit a known bug. I don't yet know why this is the
case.

**Comment by bgamari** [comment]
I've opened #543 to track the issue I mentioned above.

**Comment by gbaz** [comment]
I think the docbuilder has now been running ok for some time thanks to various changes by bgamari and more general oversight of the system. Going to close out this issue now as if new problems arise there should be new issues rather than a general running tally imho.
