### ISSUE TITLE
Builder Error: can't resolve `.data.rel.ro'

### ISSUE THREAD

**Issue by crockeea** [haskell/hackage-server#479]
I uploaded a new version of lol, and to my great [s](https://github.com/haskell/hackage-server/issues/145)[u](https://github.com/haskell/hackage-server/issues/244)[p](https://github.com/haskell/hackage-server/issues/265)[r](https://github.com/haskell/hackage-server/issues/478)[i](https://github.com/haskell/hackage-server/issues/476)[s](https://github.com/haskell/hackage-server/issues/183)[e](https://github.com/haskell/hackage-server/issues/464) (to beat a dead horse), Hackage actually attempted to build the documentation.

Unfortunately, there was some sort of linker/assembler error at the very bottom of [the log](https://hackage.haskell.org/package/lol-0.2.0.0/reports/1). The docs build locally without a problem.

**Comment by gbaz** [comment]
I'm willing to bet that this is because your package forces building via llvm, and the builder machine isn't configured to do that properly.

**Comment by crockeea** [comment]
Thanks for pointing that out! Of course it would be nice if the build machine did, but this isn't especially unreasonable.
