### ISSUE TITLE
Uploading of packages from the future

### ISSUE THREAD

**Issue by magthe** [haskell/hackage-server#480]
I just created a source tar-ball on my system and tried to upload it. I was greeted with this:

![hackage-future-time-error](https://cloud.githubusercontent.com/assets/327270/13520984/497ca4be-e1e5-11e5-887b-7fdfcf7b18af.png)

The time recorded in the tar-ball is completely correct, because well, that *is* the current time. So the question is what time the server thinks it is.

I ended up waiting a few minutes and then retried the upload. That succeeded on the third attempt.

I would have loved if that error page included the time the server has, so I quickly can determine how long I need to wait.

**Comment by dcoutts** [comment]
Good idea. Should be simple to add. Want to submit a PR?
