### ISSUE TITLE
File permissions with hackage-mirror

### ISSUE THREAD

**Issue by crockeea** [haskell/hackage-server#483]
When mirroring, I frequently get the following warning:

```
Warning: Failed to upload package happstack-state-0.5.0.4,
  HTTP error code 400, Bad Request 
  http://admin:...@localhost:8080/package/happstack-state-0.5.0.4/happstack-state-0.5.0.4.tar.gz
  The tarball entry 'happstack-state-0.5.0.4/happstack-state.cabal' has file
  permissions that are broken: 600. Permissions must be 644 at a minimum for
  files and 755 for directories.
```

The message seems to occur on random packages/versions. The result is that the package version is listed on Hackage, but under "Downloads", there is a message stating "Package tarball not uploaded".

**Comment by dcoutts** [comment]
This is a check that the server is doing. There's already a different code path in the server for uploading packages for mirroring that does fewer checks than normal upload for new packages. You can have a look there for where this check is being done, and make sure it's only on the normal upload path and not on the mirroring path.
