### ISSUE TITLE
Enable gzip on pages

### ISSUE THREAD

**Issue by neongreen** [haskell/hackage-server#487]
Currently pages aren't compressed – loading e.g. <http://hackage.haskell.org/packages/> takes 1.4 MB:

![image](https://cloud.githubusercontent.com/assets/1523306/14442426/61b5a50a-0042-11e6-8891-5d23c0fb2fbc.png)

Enabling server-side compression could be nice.

**Comment by neongreen** [comment]
Should be doable with `enableGzip`. I'll try to make a pull request later, if no one else does.

**Comment by dcoutts** [comment]
And/or we could check if our CDN can just do this for us. That might be a better balance of cpu/network.

**Comment by yamadapc** [comment]
It looks like fastly supports this: https://docs.fastly.com/guides/basic-configuration/enabling-automatic-gzipping

**Comment by gbaz** [comment]
closing in favor of #535
