### ISSUE TITLE
Build status unknown [no reports yet]

### ISSUE THREAD

**Issue by asr** [haskell/hackage-server#489]
For Agda [2.4.2.5](http://hackage.haskell.org/package/Agda-2.4.2.5) uploaded five months ago and Agda [2.5.1](http://hackage.haskell.org/package/Agda-2.5.1) uploaded yesterday, Hackage reports "Build status unknown [no reports yet]". Am I missing something when uploading the Agda packages?

**Comment by asr** [comment]
Hackage also reports "Build status unknown [no reports yet]" for  Agda [2.4.2.1](http://hackage.haskell.org/package/Agda-2.4.2.1) and [2.4.2.2](http://hackage.haskell.org/package/Agda-2.4.2.2).

**Comment by gbaz** [comment]
As far as I know it stalls out if a build plan can't be found for whatever reason. see #478

**Comment by gbaz** [comment]
i may as well close in favor of that
