### ISSUE TITLE
Reject "build-type: Configure" if ./configure is missing

### ISSUE THREAD

**Issue by kolmodin** [haskell/hackage-server#490]
See: haskell/directory#49

To be checked when packages are uploaded and validated;
If a package specifies `build-type: Configure` then it must also have a `configure` script.

`cabal check` could also have this check if it doesn't already.

**Comment by gbaz** [comment]
@kolmodin as I recall, the hackage server actually uses a subset of `cabal check` to check for these issues? So I think fixing it in that spot should fix it in both...

**Comment by dcoutts** [comment]
Yes, putting the check in Cabal is the better option.

**Comment by hvr** [comment]
Closely related Cabal issue: https://github.com/haskell/cabal/issues/3361

**Comment by kolmodin** [comment]
Cabal has had this since August 2008. https://github.com/haskell/cabal/blame/master/Cabal/Distribution/PackageDescription/Check.hs#L1636

Indeed, `cabal check` already warns about this. Somehow it didn't stop `directory-1.2.6.1` from being uploaded to hackage.

**Comment by hvr** [comment]
do'h... I even was the one who suggested that checked back in https://github.com/haskell/cabal/issues/2195 :-)

Maybe it's because the severity level is too low. `PackageBuildWarning` rather than `PackageDistInexcusable`

**Comment by kolmodin** [comment]
The checks that require `IO` are not enabled in `hackage-server`. There is a `FIXME` from 2008 at;
https://github.com/haskell/hackage-server/blob/master/Distribution/Server/Packages/Unpack.hs#L187

```
-- FIXME: do the content checks. The dev version of Cabal generalises`
-- checkPackageContent to work in any monad, we just need to provide`
-- a record of ops that will do checks inside the tarball. We should
-- gather a map of files and dirs and have these just to map lookups:
--
-- > checkTarballContents = CheckPackageContentOps {
-- >   doesFileExist      = Set.member fileMap,
-- >   doesDirectoryExist = Set.member dirsMap
-- > }
-- > fileChecks <- checkPackageContent checkTarballContents pkgDesc
```

Looks like several important checks have not been done since 2008, or maybe not ever;
```
  cabalBomError   <- checkCabalFileBOM    ops
  licenseErrors   <- checkLicensesExist   ops pkg
  setupError      <- checkSetupExists     ops pkg
  configureError  <- checkConfigureExists ops pkg
  localPathErrors <- checkLocalPathsExist ops pkg
  vcsLocation     <- checkMissingVcsInfo  ops pkg
```

**Comment by kolmodin** [comment]
I'm working on this...

**Comment by kolmodin** [comment]
I thought being member of the Haskell team would give me some edit rights for the projects governed by that team. I'd like to be assigned this issue - it appears I can assign it myself...

**Comment by gbaz** [comment]
@kolmodin just added you to the hackage-server team, as well as assigned the issue :-)

**Comment by kolmodin** [comment]
@gbaz Thanks! :)

**Comment by hvr** [comment]
@kolmodin I would have assigned you rightaway, but first I needed to invite you to the org... :-)

**Comment by kolmodin** [comment]
@hvr Thanks for inviting me to the org :)
