### ISSUE TITLE
Can't complete 'cabal update': "Unsucessful HTTP code: 502"

### ISSUE THREAD

**Issue by ideruga** [haskell/hackage-server#491]
http://hackage.haskell.org/packages/ is unaccessible (Bad gateway). Something's wrong with the hosting/website.

**Comment by oldmanmike** [comment]
[The site is down](https://www.reddit.com/r/haskell/comments/4gppm8/ann_hackagehaskellorg_is_down/), but you can monitor its status [here](https://status.haskell.org/).
