### ISSUE TITLE
rejects upload with new custom-setup stanza

### ISSUE THREAD

**Issue by joeyh** [haskell/hackage-server#496]
Trying to upload a package with the new custom-setup setup-depends that cabal recently got support for, it's rejected with 400 Bad Request  
Error: Invalid package

On a hunch removed that stanza and the upload went through.

**Comment by hvr** [comment]
yes, this will be fixed soon, once a new `hackage-server` is deployed linked against `Cabal-1.24`, which is planned to happen in time for the official GHC 8.0 release

/cc @bgamari @dcoutts

**Comment by gbaz** [comment]
should be fixed by new deploy just now?

**Comment by dcoutts** [comment]
I believe this now works. At least it works uploading to a test server running the same code as is now deployed.
