### ISSUE TITLE
Hackage is too aggressive about 'ghc-options: -Wall -Werror'

### ISSUE THREAD

**Issue by mrkkrp** [haskell/hackage-server#497]
I have this in my Cabal file:

```
…

flag dev
  description:        Turn on development settings.
  manual:             True
  default:            False

…

if flag(dev)
    ghc-options:      -O2 -Wall -Werror
  else
    ghc-options:      -O2 -Wall

…
```

I keep `dev` flag for CI mainly, but it does not matter because it's not enabled by default. Hackage says that my package is invalid because of this:

```
Error: Invalid package

'ghc-options: -Wall -Werror' makes the package very easy to break with
future GHC versions because new GHC versions often add new warnings. Use
just 'ghc-options: -Wall' instead.
```

Looks like overkill, previously it accepted such packages, can we revert to old behavior?

**Comment by gbaz** [comment]
should be fixed by new deploy just now?

**Comment by mrkkrp** [comment]
I don't know, I already uploaded my package without `-Werror`. Just wanted to let you know about it.

**Comment by dcoutts** [comment]
Yes, this works now (at least in a test server running the same code as is now deployed).
