### ISSUE TITLE
Hackage is down

### ISSUE THREAD

**Issue by mgsloan** [haskell/hackage-server#500]
I was about to update the `store` package's cabal metadata, when suddenly

![2016-05-26-193938_546x387_scrot](https://cloud.githubusercontent.com/assets/22570/15596153/dc453920-2379-11e6-9314-3393efedd077.png)

Others in #haskell also verify 503s on hackage. What gives?

**Comment by snoyberg** [comment]
Funny timing, I came to report the exact same thing, which I noticed from the [all-cabal-packages build](https://travis-ci.org/commercialhaskell/all-cabal-packages/builds/61773604):

> hackage-mirror: StatusCodeException (Status {statusCode = 503, statusMessage = "Connection timed out"}) [("Server","Varnish"),("Retry-After","0"),("Content-Type","text/html; charset=utf-8"),("Content-Length","454"),("Accept-Ranges","bytes"),("Date","Fri, 27 May 2016 02:41:01 GMT"),("Via","1.1 varnish"),("Connection","close"),("X-Served-By","cache-jfk1043-JFK"),("X-Cache","MISS"),("X-Cache-Hits","0"),("X-Timer","S1464316841.684316,VS0,VE20058"),("X-Response-Body-Start","\n<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\"\n \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\n<html>\n  <head>\n    <title>503 Connection timed out</title>\n  </head>\n  <body>\n    <h1>Error 503 Connection timed out</h1>\n    <p>Connection timed out</p>\n    <h3>Guru Mediation:</h3>\n    <p>Details: cache-jfk1043-JFK 1464316861 1032396058</p>\n    <hr>\n    <p>Varnish cache server</p>\n  </body>\n</html>\n"),("X-Request-URL","GET http://hackage.haskell.org:80/00-index.tar.gz")] (CJ {expose = []})

As a meta question: is a Github issue the right place to report Hackage downtime?

**Comment by mgsloan** [comment]
Considering that https://status.haskell.org/ reports everything as "Operational", this seems to be a deeper issue than downtime.

**Comment by gbaz** [comment]
status is updated manually, i'm going to, but i'm in the middle of investigating. this is a fine place. we like admin@haskell.org and irc too.

**Comment by snoyberg** [comment]
Awesome, thanks for the quick response @gbaz

**Comment by robert-blankenship** [comment]
Here are some Cabal mirrors that you can use while Hackage is down:

https://www.fpcomplete.com/blog/2015/03/hackage-mirror (includes instructions for editing Cabal configuration)
http://hdiff.luite.com/cgit/AC-Angle/

**Comment by BardurArantsson** [comment]
Seems that the issue is related to not having version numbers in the "package" portion of the URL:

https://hackage.haskell.org/package/base-4.6.0.1/docs/Data-Foldable.html works whereas https://hackage.haskell.org/package/base/docs/Data-Foldable.html doesn't.

**Comment by gbaz** [comment]
no, the issue is a rackspace host issue as the status page now shows. we're on it.

you can still see some pages due to caching.

**Comment by BardurArantsson** [comment]
Alright, NVM then. (FTR I did try "force-reload", but apparently the CDN doesn't care about that :/ .)

**Comment by gbaz** [comment]
Also FTR, you can force it by doing something like

https://hackage.haskell.org/package/base-4.6.0.1/docs/Data-Foldable.html?foo

**Comment by gbaz** [comment]
resolved after getting support from rackspace to fix up the bad hosting setup as of 430 eastern.

**Comment by gbaz** [comment]
(also thanks to prompting we now have http://auto-status.haskell.org/ which is linked from the main status page and shows auto-generated connectivity/uptime information)
