### ISSUE TITLE
Order matrix versions with newest at top

### ISSUE THREAD

**Issue by danielcompton** [haskell/hackage-server#502]
On http://matrix.hackage.haskell.org/package/yesod the most recent versions are at the bottom of the page. These are most likely to be the versions people are interested in, so it could be good to invert the order and put the newest versions at the top?

I'm not sure whether you'd also want to invert the the order of the Haskell versions so they continue to ascend from left to right.

**Comment by hvr** [comment]
That's a reasonable suggestion! Can you file this at https://github.com/hvr/hackage-matrix-builder/issues please?

**Comment by danielcompton** [comment]
Sure, sorry, didn't realise this was the wrong place for it!
