### ISSUE TITLE
Dependency versions on the webpage do not match with the .cabal file

### ISSUE THREAD

**Issue by wereHamster** [haskell/hackage-server#503]
https://hackage.haskell.org/package/transformers-0.4.3.0

The page shows dependencies `base (>=2 && <4.9)`, but when you download the package and open the .cabal file you'll see that it contains `base >= 2 && < 6`.

**Comment by wereHamster** [comment]
I tried to build a project which has `transformers` as one of its dependencies and the stack failed to find a build plan, this was in the output:

```
rejecting: transformers-0.4.3.0, 0.4.2.0 (conflict:
base==4.9.0.0/installed-4.9..., transformers => base>=2 && <4.9)
```

So then I wanted to check if the package compiles against GHC 8 because according to the hackage page it should not. But then stack found a build plan without me changing the constraints in the cabal file and I was confused. Upon inspecting the cabal file I saw different constraints than on the webpage.

Probably more an issue with stackage, because the repo it uses doesn't properly keep track of metadata changes. https://github.com/commercialhaskell/all-cabal-hashes/blob/hackage/transformers/0.4.3.0/transformers.cabal is the cabal file with the old dependencies.

**Comment by bergmark** [comment]
The link you posted to all-cabal-hashes does contain the new version with `x-revision: 1`. 

Stack also doesn't allow this to build for me on GHC 8:

```
$ stack build transformers-0.4.3.0 --resolver=nightly-2016-06-04
Run from outside a project, using implicit global project config
Using resolver: nightly-2016-06-04 specified on command line
Downloaded nightly-2016-06-04 build plan.
Populated index cache.
While constructing the BuildPlan the following exceptions were encountered:

--  Failure when adding dependencies:
      base: needed (>=2 && <4.9), 4.9.0.0 found (latest applicable is 4.8.2.0)
    needed for package transformers-0.4.3.0
```

**Comment by bergmark** [comment]
Also, tarballs are never modified so if you just download it you will get the first revision of the cabal file. Use `cabal get` instead to unpack it with the latest x-revision

**Comment by wereHamster** [comment]
This works, and successfully builds the package with GHC 8. Note that the URL I'm downloading with `curl` is taken from the bottom of this webpage: https://hackage.haskell.org/package/transformers-0.4.3.0.

```
curl -OL https://hackage.haskell.org/package/transformers-0.4.3.0/transformers-0.4.3.0.tar.gz
tar -xf transformers-0.4.3.0.tar.gz
cd transformers-0.4.3.0
stack init --resolver=nightly
stack build
```

Now if you inspect the cabal file you just downloaded, you'll see that the dependency bounds don't correspond with what you see on the webpage. That is confusing. If one isn't supposed to download the tarball like that, then remove the link and replace with

> To download the source of this package use `cabal get transfomers-0.4.3.0`

**Comment by bergmark** [comment]
Are you sure you are building with GHC 8? Even with the bound lifted i cannot build it:

```
$ stack init --resolver=nightly --force
Looking for .cabal or package.yaml files to use to init the project.
Using cabal packages:
- transformers.cabal

Selected resolver: nightly-2016-06-04
Initialising configuration using resolver: nightly-2016-06-04
Total number of user packages considered: 1
Writing configuration to file: stack.yaml
All done.
$ stack build
Compiler version mismatched, found ghc-7.10.3 (x86_64), but expected minor version match with ghc-8.0.1 (x86_64) (based on resolver setting in /Users/adam/repos/trustee/transformers-0.4.3.0/stack.yaml).
Try running "stack setup" to install the correct GHC into /Users/adam/.stack/programs/x86_64-osx/
$ stack build
transformers-0.4.3.0: configure
Configuring transformers-0.4.3.0...
transformers-0.4.3.0: build
Preprocessing library transformers-0.4.3.0...
[ 1 of 27] Compiling Data.Functor.Classes ( Data/Functor/Classes.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Data/Functor/Classes.o )
[ 2 of 27] Compiling Data.Functor.Compose ( Data/Functor/Compose.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Data/Functor/Compose.o )
[ 3 of 27] Compiling Data.Functor.Product ( Data/Functor/Product.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Data/Functor/Product.o )
[ 4 of 27] Compiling Data.Functor.Sum ( Data/Functor/Sum.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Data/Functor/Sum.o )
[ 5 of 27] Compiling Control.Monad.IO.Class ( Control/Monad/IO/Class.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Control/Monad/IO/Class.o )
[ 6 of 27] Compiling Data.Functor.Constant ( Data/Functor/Constant.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Data/Functor/Constant.o )
[ 7 of 27] Compiling Control.Monad.Trans.Class ( Control/Monad/Trans/Class.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Control/Monad/Trans/Class.o )
[ 8 of 27] Compiling Control.Monad.Trans.Cont ( Control/Monad/Trans/Cont.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Control/Monad/Trans/Cont.o )
[ 9 of 27] Compiling Control.Monad.Signatures ( Control/Monad/Signatures.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Control/Monad/Signatures.o )
[10 of 27] Compiling Control.Monad.Trans.Except ( Control/Monad/Trans/Except.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Control/Monad/Trans/Except.o )
[11 of 27] Compiling Control.Monad.Trans.Error ( Control/Monad/Trans/Error.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Control/Monad/Trans/Error.o )

/Users/adam/repos/trustee/transformers-0.4.3.0/Control/Monad/Trans/Error.hs:69:10: error:
    Duplicate instance declarations:
      instance MonadPlus IO
        -- Defined at Control/Monad/Trans/Error.hs:69:10
      instance MonadPlus IO -- Defined in ‘GHC.Base’

/Users/adam/repos/trustee/transformers-0.4.3.0/Control/Monad/Trans/Error.hs:73:10: error:
    Duplicate instance declarations:
      instance Alternative IO
        -- Defined at Control/Monad/Trans/Error.hs:73:10
      instance Alternative IO -- Defined in ‘GHC.Base’

--  While building package transformers-0.4.3.0 using:
      /Users/adam/.stack/setup-exe-cache/x86_64-osx/setup-Simple-Cabal-1.24.0.0-ghc-8.0.1 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.0.0 build lib:transformers --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
```

**Comment by bergmark** [comment]
> Now if you inspect the cabal file you just downloaded, you'll see that the dependency bounds don't correspond with what you see on the webpage. That is confusing. If one isn't supposed to download the tarball like that, then remove the link and replace with

> > To download the source of this package use cabal get transfomers-0.4.3.0

I agree that the page should say something like that. `Package description (included in the package)` is also misleading.

**Comment by gbaz** [comment]
@bergmark do you have proposed language for the latter?

@dcoutts on the former, what do you think we should do? Maybe keep the link, but with explanatory text?

**Comment by bergmark** [comment]
Something like "Package description (may be a newer revision than what's in the release tarball)"? Would also be nice to link "revision" to an explanation, is there one somewhere?

**Comment by MingdaRui** [comment]
encounter the same issue
