### ISSUE TITLE
Missing viewport meta tag

### ISSUE THREAD

**Issue by Philonous** [haskell/hackage-server#510]
The hackage site is currently nigh unusable on high-dpi mobile devices because of a missing viewport meta tag.

Adding 
```html
 <meta name="viewport" content="width=device-width, initial-scale=1">
```
improves it markedly

**Comment by gbaz** [comment]
Without a high-dpi screen myself (yes I feel old and behind the times) its hard to see what's going on.

Can you provide screenshots or e.g. a way to use a tool like http://www.infobyip.com/testwebsiteresolution.php so I can understand the issue more clearly?

**Comment by Philonous** [comment]
I should have made it clearer that I meant high-dpi _mobile_ devices, sorry.

I've added some screenshots from my mobile phone, illustrating the problem. I've down-sized the images from the native 1440x2560

_Please note_ that the screen of the device is _69mm_ by _113mm_ and at least on my (desktop) screen the images are displayed much larger than that. So in real life the text is _tiny_

### This is before applying the meta tag
On the real device the pages barely legible, hitting links is hard 
#### Hackage home page

![hackage_before](https://cloud.githubusercontent.com/assets/558171/19393747/603c20a6-9236-11e6-8cbf-f71b968dfcd5.png)

#### Servant package page
![servant_before](https://cloud.githubusercontent.com/assets/558171/19393746/60353e30-9236-11e6-82e7-f4a41437de82.png)

### This is after adding the meta tag:
The pages are legible, links are easier to hit. It's not the best mobile experience in the world, but it's usable.

#### Hackage homepage
![hackage_after](https://cloud.githubusercontent.com/assets/558171/19393744/60242938-9236-11e6-9ca6-d43a08b3fc74.png)

#### Servant page
![servant_after](https://cloud.githubusercontent.com/assets/558171/19393745/602b2e0e-9236-11e6-9237-2c18f7f435d2.png)

**Comment by gbaz** [comment]
Thanks! So you'd want this on every page then, not just some subset?

**Comment by Philonous** [comment]
Yes, it would be nice to have on every page

**Comment by gbaz** [comment]
should be addressed by https://github.com/haskell/hackage-server/pull/551/commits/2c3e31cc589687a850cfe2ada66d9121a8412de9

**Comment by Philonous** [comment]
Thanks! This should fix it.
