### ISSUE TITLE
Hackage does not list executables in a package anymore

### ISSUE THREAD

**Issue by amigalemming** [haskell/hackage-server#511]
I remember that in the past Hackage displayed the names of the executables that a package can build.
I miss that list in current Hackage. E.g. this package provides two executables:
https://hackage.haskell.org/package/cabal-sort
but none is shown.

**Comment by gbaz** [comment]
@SooryaN this is a small thing that you may want to tackle in passing sometime this summer.

**Comment by chrissound** [comment]
I think this has been implemented. So this could be closed?

**Comment by gbaz** [comment]
Will be fixed with the merge of #551
