### ISSUE TITLE
Package Information Revisions not mirrored by hackage-mirror tool

### ISSUE THREAD

**Issue by mlongob** [haskell/hackage-server#517]
Edits to cabal metadata on Hackage are not mirrored by the `hackage-mirror` tool.

To reproduce:
- Upload a new package `foo-1.0.1` to Hackage
- Let the `hackage-mirror` tool mirror `foo-1.0.1` on hackage mirror
- Edit `foo-1.0.1` package information (ie relax dependency bounds)
- Run `hackage-mirror` again

**Comment by mlongob** [comment]
Because of this issue, using my 3 month old mirror with the newest stackage lts (7.0) is now broken:

```
WARNING: Ignoring out of range dependency (trusting snapshot over Hackage revisions): tagged-0.8.5. binary-orphans requires: >=0.7.3 && <0.8.5
binary-orphans-0.1.5.1: configure
Progress: 1/2
--  While building package binary-orphans-0.1.5.1 using:
      /home/mlongob1/.stack/setup-exe-cache/x86_64-linux/setup-Simple-Cabal-1.24.0.0-ghc-8.0.1 --builddir=.stack-work/dist/x86_64-linux/Cabal-1.24.0.0 configure --with-ghc=/home/mlongob1/.stack/programs/x86_64-linux/ghc-8.0.1/bin/ghc --with-ghc-pkg=/home/mlongob1/.stack/programs/x86_64-linux/ghc-8.0.1/bin/ghc-pkg --user --package-db=clear --package-db=global --package-db=/home/mlongob1/.stack/snapshots/x86_64-linux/lts-7.0/8.0.1/pkgdb --libdir=/home/mlongob1/.stack/snapshots/x86_64-linux/lts-7.0/8.0.1/lib --bindir=/home/mlongob1/.stack/snapshots/x86_64-linux/lts-7.0/8.0.1/bin --datadir=/home/mlongob1/.stack/snapshots/x86_64-linux/lts-7.0/8.0.1/share --libexecdir=/home/mlongob1/.stack/snapshots/x86_64-linux/lts-7.0/8.0.1/libexec --sysconfdir=/home/mlongob1/.stack/snapshots/x86_64-linux/lts-7.0/8.0.1/etc --docdir=/home/mlongob1/.stack/snapshots/x86_64-linux/lts-7.0/8.0.1/doc/binary-orphans-0.1.5.1 --htmldir=/home/mlongob1/.stack/snapshots/x86_64-linux/lts-7.0/8.0.1/doc/binary-orphans-0.1.5.1 --haddockdir=/home/mlongob1/.stack/snapshots/x86_64-linux/lts-7.0/8.0.1/doc/binary-orphans-0.1.5.1 --dependency=aeson=aeson-0.11.2.1-7upVB3k6XZaETFQEHHKnl --dependency=base=base-4.9.0.0 --dependency=binary=binary-0.8.3.0 --dependency=case-insensitive=case-insensitive-1.2.0.7-FlqweN7AuKj9EdU2arVEt4 --dependency=hashable=hashable-1.2.4.0-EMu4H7FB10MAl6hwKw992G --dependency=scientific=scientific-0.3.4.9-6oTYuCcx6H5BsTGU7D2Gk3 --dependency=tagged=tagged-0.8.5-CtgV6EcN0do8F92i1S6iYx --dependency=text=text-1.2.2.1-5QpmrLQApEZ4Ly9nMHWY0s --dependency=text-binary=text-binary-0.2.1-3sB5oyusVXh7RwaYLmoLsw --dependency=time=time-1.6.0.1 --dependency=unordered-containers=unordered-containers-0.2.7.1-Eo9jd5DMz45DhBLCG8skzW --dependency=vector=vector-0.11.0.0-BEDZb5o2QOhGbIm6ky7rl6 --dependency=vector-binary-instances=vector-binary-instances-0.2.3.2-5646KxzN3hJ80s4tOK0y7f
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/mlongob1/workdir/haskell/mario/.stack-work/logs/binary-orphans-0.1.5.1.log

    Configuring binary-orphans-0.1.5.1...
    setup-Simple-Cabal-1.24.0.0-ghc-8.0.1: Encountered missing dependencies:
    tagged >=0.7.3 && <0.8.5 && ==0.8.5
```

In this case the `binary-orphans` revision to relax the bounds on `tagged` was not mirrored.

**Comment by gbaz** [comment]
Hi! It was good to talk to you tonight. I'm glad you mentioned that you were interested in hacking on this, and perhaps on hackage-mirror more generally. This is just to jot down some broader notes from our conversation (please throw in more).

The question I guess is what is the "remit" of the hackage-mirror tool. We specced out two use cases. A) a "downstream fork" which has the current contents of a "master" hackage server and also additional local internal packages and also perhaps "vendored" revisions of existing ones. B) a "strict clone" along the lines discussed in #525 . At the time, I suggested that there should be a flag that differentiates between the two behaviors to the extent that they end up with different choices. But thinking about it now, its hard to see what might be included in the latter case that should be excluded with the former.

It seems that between #525 #26 and this there's a few things that should be added to the tool. The only difficulty arises if downstream changes then come into conflict with future upstream ones. My proposal has tended to be that upstream should "win" with the caveat that we will need to add to the mirrored hackage some way of viewing a log that documents these cases.

Anyway, just jotting some thoughts for now while things are fresh, and offering to try within the limits of my time to be a receptive person who has worked on the server to help get any changes figured out and then guided through to a proper merge.

**Comment by hvr** [comment]
@gbaz btw, personally I think that A) is better served by having an add-on package repository which holds only the internal packages

and as to "remit"s, there's maybe also C) which is handled by https://travis-ci.org/hvr/hackage-mirror-tool/ which we currently use for syncing secure mirrors; there's still the question whether C) ought to be handled by `hackage-mirror` or be left to `hackage-mirror-tool` which is currently specialised for only that job

**Comment by mlongob** [comment]
@hvr: Having add-on repositories does not play too well with documentation building at the moment. I don't think there's a way to build documentation for the add-on while having links going back to the community repository.

**Comment by gbaz** [comment]
mlongob any advice on actually getting the mirror-tool to work so I can investigate? Not having much luck with it at the moment...

**Comment by gbaz** [comment]
Ok, looks like if we set the mirror type to be from "secure" rather than "hackage2" all the revisions metadata gets cloned properly! (Since "secure" uses the index-01 file that has the full revision history).

**Comment by mlongob** [comment]
@gbaz: thanks for working with Ben on this. Will try to re-build a mirror in "secure" mode this week and get back to you.

**Comment by mlongob** [comment]
@gbaz @hvr: Confirming this works for us in production. Thanks for the help!
