### ISSUE TITLE
zlib-0.6 support

### ISSUE THREAD

**Issue by phadej** [haskell/hackage-server#519]
AFAICS the only thing to be changed is `gzipDecompress :: LBS.ByteString -> ServerPartE LBS.ByteString` which seems to fail gracefully if the error at the beginning of gzipped stream, and throw the exception if the error occurs later. It's a bit the same as in `cabal-install` where we treat errors at beginning specially: https://github.com/haskell/cabal/blob/7d192e5cbdb0b678b62649230139b088e61b8b21/cabal-install/Distribution/Client/GZipUtils.hs#L40-L72

If my understanding is right, I could port `hackage-server` to use `zlib-0.6`. I hope that supporting `zlib-0.5` isn't mandatory?

**Comment by gbaz** [comment]
I'd love for that dep to be upgraded. :+1:

**Comment by hvr** [comment]
@dcoutts knows `zlib` best, so I hope he'll review this one soon... :-)

**Comment by dcoutts** [comment]
@phadej sure, go for it, PR accepted.

**Comment by gbaz** [comment]
This was upgraded along with a bunch of other deps as https://github.com/haskell/hackage-server/commit/30b3e1afd0d8a81e0004c21afb132844eed278bb
