### ISSUE TITLE
Modifying version dependencies doesn't appear to work -- but I like it that way.

### ISSUE THREAD

**Issue by creswick** [haskell/hackage-server#52]
In hackage 2, you can modify the cabal file "...edit certain bits of package metadata after a release...".  Including to change dependencies.

This doesn't appear to work; but I actually think that this is a dangerous feature to enable.

There is significant risk that this will result in non-reproducible builds; particularly when trying to resurrect older software, but also when debugging during new software releases. If a dependency change is made to the cabal file without changing the version (which is specifically disallowed by the current interface) there is no practical way to verify that the software you are building is the same as the software *I* am building -- we end up in a situation worse than the dependency hell we've all worked to avoid with sandboxing.

Years of experience teach us to look at version numbers, and to trust in the version numbers to represent equality across systems, but this feature violates that ingrained assumption.  I can't imagine trying to remotely debug a build failure caused by a difference in the dependency specification of a transitive dependency.

I *strongly* suggest that the cabal file modifications be restricted to non-semantically relevant fields; fixing documentation typos, source repos, authors, maintainers, etc. things that *can not* cause cabal to behave differently.

At the moment, this is easily fixed by changing the explanatory text on the 'Edit package metadata...' page, (although it also appears that modifying descriptions is also broken).

**Comment by gbaz** [comment]
Can we close this ticket? It works now, whatever the controversy :smiley:
