### ISSUE TITLE
Please create distribution "Tumbleweed"

### ISSUE THREAD

**Issue by peti** [haskell/hackage-server#520]
I would like to upload package lists for [openSUSE Tumbleweed](https://en.opensuse.org/Portal:Tumbleweed). Could you please register the distribution "Tumbleweed" so that http://hackage.haskell.org/distro/Tumbleweed/packages.csv becomes available for me (http://hackage.haskell.org/user/PeterSimons)?

**Comment by gbaz** [comment]
As per: https://github.com/haskell/hackage-server/issues/447#issuecomment-160851800

You should be able to do it yourself?

**Comment by peti** [comment]
Oh, cool. Thank you.
