### ISSUE TITLE
PackageIndex will be removed from Cabal 1.26

### ISSUE THREAD

**Issue by ezyang** [haskell/hackage-server#521]
Via this PR https://github.com/haskell/cabal/pull/3525

Out of all the packages in Hackage, hackage-server is the only one using the PackageIndex in a nontrivial way. Will you be able to refactor to use the new `Distribution.Compat.Graph` interface or should I put in a backwards compatibility shim for you?

**Comment by gbaz** [comment]
Are you sure it uses Distribution.Simple.PackageIndex? It looks to me that it defines its own Distribution.Server.PackageIndex, but I may be missing something?

**Comment by ezyang** [comment]
Nope, I just saw PackageIndex. If it defines its own, false alarm!
