### ISSUE TITLE
security: case-squatting on hackage packages

### ISSUE THREAD

**Issue by joeyh** [haskell/hackage-server#522]
Package names in hackage are case sensitive, but "cabal install quickcheck" causes the QuickCheck package to be installed. While hackage does not allow me to upload a new version of QuickCheck (as I am not its maintainer), it seems it would allow me to upload a "quickcheck" package. If I did that, it would change the behavior of "cabal install quickcheck", which would then install my package.

This is rather more troublesome than the package typo-squatting attacks that have been in the news lately (http://incolumitas.com/data/thesis.pdf), because it's not uncommon for users to run "cabal install quickcheck" when they intend to install QuickCheck. Googling for that command line suggests that 1 out of 10 times the lower-case form is used. So, uploading a malicious "quickcheck" package is a very easy target.

Once I've uploaded a malicious quickcheck package, it would also be possible for cabal files to be written that accidentally depend on it, rather than on QuickCheck. I know that I have at least a couple of times written "quickcheck" and "ifelse" in cabal files and only noticed the mistake when cabal complained there was no such package.

There are 60 pairs of packages in Hackage that differ in only case. Probably none of them are currently malicious case-squatting. Some of the pairs have the same maintainer eg Safe and safe. Others appear to be non-malicious cases of competing packages eg BerkeleyDB and berkeleydb, dbus and DBus.

My suggestion: Hackage should not allow me to upload a new package named quickcheck since QuickCheck already exists in hackage. (It could perhaps still allow the maintainers of QuickCheck to upload a new package named quickcheck if they wanted to.) This will close the case-squatting hole, except for in the 60 currently colliding pairs.

**Comment by bergmark** [comment]
#352

**Comment by gbaz** [comment]
I agree with fixing #352 but I also think this is more an issue to file with cabal. @23Skidoo what do you think? (As far as I know you need case-correctness in cabal files, its just that the commandline tries to be too smart?)

**Comment by 23Skidoo** [comment]
@gbaz The relevant `cabal-install` code is https://github.com/haskell/cabal/blob/master/cabal-install/Distribution/Client/Targets.hs#L664 I guess we could print a warning when there are multiple case-insensitive matches or add an `--ignore-ambiguous-targets` flag and refuse to proceed without it in this case.

**Comment by hvr** [comment]
I've been wanting for some time to see `cabal install` be case-sensitive by default. I.e. if I say ` cabal install quickcheck` it should consider it a typo, and possibly show close matches (like GHC does, when you mistype something, showing you possible alternatives with close hamming distances)

**Comment by gbaz** [comment]
Ok, can we close the remainder of this issue now in favor of #352 ?

**Comment by tom-bop** [comment]
cc @joeyh this looks fixed

**Comment by hvr** [comment]
I think we can consider this addressed with #761 having been merged & already deployed last week.
