### ISSUE TITLE
archive for hermes-1.3.4.3 is missing

### ISSUE THREAD

**Issue by erantapaa** [haskell/hackage-server#523]
Trying to download the archive for hermes-1.3.4.3:

https://hackage.haskell.org/package/hermes-1.3.4.3/hermes-1.3.4.3.tar.gz

results in a "410 Gone" page.

It could be restored from hdiff:

http://hdiff.luite.com/cgit/hermes/diff/?id=1.3.4.3

**Comment by gbaz** [comment]
Same history as #524 -- out-of-band deletion of an accidental upload by request.

**Comment by hvr** [comment]
duplicate of #436
