### ISSUE TITLE
archive for tslib-0.1.4 is missing

### ISSUE THREAD

**Issue by erantapaa** [haskell/hackage-server#524]
The archive for tslib-0.1.4:

https://hackage.haskell.org/package/tslib-0.1.4/tslib-0.1.4.tar.gz

results in a "410 Gone" page.

**Comment by gbaz** [comment]
This is on purpose. It was an accidental upload of software that is not properly licensed for hackage and the archive was removed by special request.

**Comment by erantapaa** [comment]
Would it be possible to remove them from the index.tar.gz archive of cabal files?

**Comment by gbaz** [comment]
As far as I know the index.tar.gz is immutable by design, and even moreso with new hackage-security. @dcoutts can confirm. The full removal of source vs. just deprecation is very rare and we've only had to do it a few times. As far as I know this was chosen as the least bad way to do it.

**Comment by hvr** [comment]
Adding to what @gbaz says, downstream systems (including `cabal-install`) would be quite confused if packages started disappearing from the index, and adding support for that would make them more complicated if this invariant isn't there anymore.

On the other hand, there's the idea to add package-removal events to the index tar stream. That would be compatible with the design principles here. This was already mentioned in https://github.com/haskell/hackage-server/issues/436#issuecomment-148658140
