### ISSUE TITLE
Unable to register

### ISSUE THREAD

**Issue by Gurkenglas** [haskell/hackage-server#528]
Trying to register at the [registration form](http://hackage.haskell.org/users/register-request) with the following info:

![](https://i.gyazo.com/7174f4a6c6f43482a5caf12ca5bf812c.png)

Gives me the following message:

![](https://i.gyazo.com/630f9571e493a377fccf92c9537d2995.png)

But I do not receive any email. Tried this about a week ago or so as well, same thing. Not in the spam folder, searching using the web client's search query for "hackage" finds only 3 irrelevant emails, and [someone else also seems unable to register](http://ircbrowse.net/browse/haskell?id=23235237&timestamp=1471531982#t1471531982).

**Comment by gbaz** [comment]
I just sent myself a password reset email so confirmed they're flowing in general.

And I went to the admin page to check pending requests and see that there's two requests pending to you.  The emails must be getting eaten.

**Comment by gbaz** [comment]
I just created an account by hand and sent you a password reset email. Let me know if you get it -- if you don't I can reach out directly and provide you with a temp password.

**Comment by Gurkenglas** [comment]
Did not get an email from you either, also not in the spam folder. Temp password sounds good.

**Comment by gbaz** [comment]
Done :-)

**Comment by Gurkenglas** [comment]
Got the temp password, cant upload packages through the web interface: After inputting credentials, I get 

![](https://i.gyazo.com/87dd9aff1f880441ad6d68a1bbdb4096.png)

Related to https://github.com/haskell/hackage-server/issues/248 ?

**Comment by gbaz** [comment]
Always forget manually created users need to be added to uploaders as well. Done now. Sorry for the runaround!

**Comment by Shadasviar** [comment]
I have this issue in 2019: no registration confirmation mail from hackage. Was it fixed?
