### ISSUE TITLE
Syntax highlighting issue with `as` word 

### ISSUE THREAD

**Issue by chrissound** [haskell/hackage-server#529]
http://hackage.haskell.org/package/base-4.9.0.0/docs/src/GHC.List.html#zipWith

![2016-08-21-14 38 24](https://cloud.githubusercontent.com/assets/1499652/17837508/ff599100-67ac-11e6-9a18-58946a708aab.png)

I'm pretty sure `as` is being highlighted incorrectly

**Comment by hvr** [comment]
@chrissound can you refile this at https://github.com/haskell/haddock/issues please, as this is rather a bug in Haddock rather than `hackage-server` :-)
