### ISSUE TITLE
Don't pull unauthenticated upstreams

### ISSUE THREAD

**Issue by DemiMarie** [haskell/hackage-server#530]
Hackage should refuse to pull unauthenticated upstreams.  This includes the `git://`, `svn://`, `darcs://`, and all other protocols other than `https://` (with a valid TLS certificate on the server and/or a secure hash of the server's public key in the file uploaded to Hackage) and `ssh://` (with a public key fingerprint provided in the package file that can be checked against the server's public key).

**Comment by gbaz** [comment]
what do you mean pull? it doesn't pull anything

**Comment by DemiMarie** [comment]
Oops!  I got confused.  Are packages uploaded to Hackage self-contained?

**Comment by gbaz** [comment]
yes. they're tarballs with no external references.
