### ISSUE TITLE
CDN issue causing 00-index.tar to be out of sync with available tarballs

### ISSUE THREAD

**Issue by snoyberg** [haskell/hackage-server#537]
I've experienced this personally in running the all-cabal-hashes mirror, and have received user reports. Relevant links:

* https://twitter.com/snoyberg/status/773847008721395712
* https://github.com/snoyberg/yaml/issues/97

The idea is: you download the `00-index.tar.gz` file from Hackage (e.g., via `cabal update`), and it includes a `.cabal` file for a certain package/version combo (like `yaml-0.8.18.6.cabal`). But when you try to download `yaml-0.8.18.6.tar.gz` from Hackage, you get a 404 for a while, which eventually corrects itself. I've experienced situations where two different build servers - both in the US - returned a 404, while downloading from my house in Israel worked. This leads me to believe it's a regional caching issue with the CDN.

Just a complete guess here: perhaps it's worth disabling CDN caching for non-200 responses?

**Comment by hvr** [comment]
CC'ing @davean who manages our Fastly CDN

More generally, we may be able reduce the time-window in which a client can experience an inconsistent view of the Hackage repository *temporarily*, but we will never be able to fully eliminate that window, unless the CDN or any cloud storage provides stronger guarantees. IOW, There's now way around Clients needing to be able to cope with transient object access failures as long as the communication path is made up of potentially unreliable components. When `cabal` is used with `hackage-security`'s object retrieval logic this is taken into account to some degree already.

**Comment by dcoutts** [comment]
Yes, can't be eliminated completely but reduced caching of 404s sounds like a good idea.

**Comment by snoyberg** [comment]
Just to give a little more detail of what I'm doing in case it helps: instead of running through the full mirroring scripts every 1/5/10 minutes, I'm moving over to a watch script which respects the `ETag` header, so that less bandwidth/CPU/disk access is used. You can see this script at:

https://github.com/fpco/hackage-mirror/blob/383666ff71c1fcafecd2d0a1a72a47e75d5fcda3/main/Watcher.hs

Due to this issue, I've included an arbitrary 10-run forced synchronization in case the index.tar.gz file got out-of-sync with the sdist tarballs.

**Comment by snoyberg** [comment]
One last detail: it may seem like it would be reasonable to just confirm that all tarballs are available instead of using the arbitrary 10-run cutoff. Unfortunately, there's another issue that prevents that from being possible: #436. Since there are some tarballs which legitimately fail the download (because they have been deleted for copyright purposes, but not removed from the index), and other tarballs that fail due to CDN caching issues, I don't see a way to detect that we should ignore the `ETag` and try synchronizing tarballs again.

**Comment by hvr** [comment]
Re removed package tarballs, we try to return the appropriate HTTP code "410", e.g.:

```
$ curl -v http://hackage.haskell.org/package/tslib-0.1.4/tslib-0.1.4.tar.gz
*   Trying 104.130.241.19...
* Connected to hackage.haskell.org (104.130.241.19) port 80 (#0)
> GET /package/tslib-0.1.4/tslib-0.1.4.tar.gz HTTP/1.1
> Host: hackage.haskell.org
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 410 Gone
< Server: nginx/1.8.1
< Date: Tue, 13 Sep 2016 08:52:15 GMT
< Content-Type: text/html
< Content-Length: 158
< Connection: keep-alive
< 
<html>
<head><title>410 Gone</title></head>
<body bgcolor="white">
<center><h1>410 Gone</h1></center>
<hr><center>nginx/1.8.1</center>
</body>
</html>
* Connection #0 to host hackage.haskell.org left intact
```

**Comment by snoyberg** [comment]
I never noticed that. That could be very useful, thanks!

**Comment by dcoutts** [comment]
@snoyberg since you're running a mirror, it'd be perfectly reasonable to bypass the CDN entirely. Then you get to choose if/how to respect the cache-control hints etc. If you'd like to do that, let us know and we can give you the details (ie IP address etc).

Also, if you'd like to take part in the public mirroring of hackage (ie serving in the same original format) then you may like to use https://github.com/hvr/hackage-mirror-tool and optionally have your mirror added to the public mirror list http://hackage.haskell.org/mirrors.json . If so, just let us know.

**Comment by dcoutts** [comment]
Update: @snoyberg has set up a new mirror and it is now listed as an official public mirror in the upstream http://hackage.haskell.org/mirrors.json

Since the out-of-sync caching/proxying issue does not at appear to be a problem for `cabal` clients at the moment then we'll close this for now. The hackage-security client code has logic to cope with caching proxies but if this proves not enough for our CDN then we can switch things around so that we use our mirrors as primaries for clients rather than only as secondary / backups.

**Comment by snoyberg** [comment]
Just to give one last note on all of this: I put a new page on stackage.org to track the relative up-to-dateness of Hackage vs mirrors and Git repos, you can see it at:

https://ci.stackage.org/status/mirror

I've configured the page to return a status 500 if the lag time is ever more than an hour, so using normal HTTP monitoring tools can give an alert if the mirroring functionality ever stops working.

**Comment by hvr** [comment]
@snoyberg that's coincidentally something similar half-finished (sans the Git repos status) to what I've been hacking on as well, as we needed that for haskell.org as well... except less html'y, just a plain/text .cgi script which validates the TUF meta-data for freshness :-)

**Comment by snoyberg** [comment]
If it would be helpful to add a few more URLs to that table, just say so. It's no big deal for me too track the last-modified of a few more files.

**Comment by hvr** [comment]
@snoyberg it may be interesting to add "http://objects-us-west-1.dream.io/hackage-mirror/01-index.tar.gz" there, as well as the `../timestamp.json` files (since that one's updated last by my tool)

**Comment by snoyberg** [comment]
Cool, commit pushed, should be live in a few minutes.

**Comment by snoyberg** [comment]
The mirror I've been running went down about 8 hours ago (see: https://github.com/commercialhaskell/all-cabal-hashes/issues/13). AFAICT, the problem is that the privately provided IP address for the upstream server (behind the CDN) changed. I've switched the mirror to use hackage-origin.haskell.org, is that correct?

**Comment by gbaz** [comment]
That should be correct, yes.
