### ISSUE TITLE
Incorrect detection of HTTPS connections during package upload

### ISSUE THREAD

**Issue by snoyberg** [haskell/hackage-server#540]
I tried to upload a package just now, and received an error message:

```
Error: Authorization scheme not allowed over plain http

HTTP Basic and X-ApiKey authorization methods leak information when used over plain HTTP. Either use HTTPS or if you must use plain HTTP for authorised requests then use HTTP Digest authentication.
```

This occurs both with `stack upload`, and with the following `curl` line:

    curl -X POST https://hackage.haskell.org/packages/ -H 'Authorization: Basic XXXXX' -H "Accept: text/plain"

Based on reviewing recent commits, this appears to be introduced by 93279da9c0198ddb49b89dda68326c3686a185da.

I consider this a high priority item: this has totally interrupted my normal workflows, and I presume those of many other users.

**Comment by hvr** [comment]
Just for the record, HTTP Digest auth still works (and actually, the error message you get happens to be  accurate even if you connect via https:// given our current CDN setup)

**Comment by dcoutts** [comment]
Current workarounds: `cabal upload` uses curl/wget which will do the Digest auth that the server advertises, or curl/wget directly.

**Comment by Blaisorblade** [comment]
> the error message you get happens to be accurate even if you connect via https:// given our current CDN setup

Is that setup documented anywhere? If the CDN-server connection is still encrypted the keys should not be exposed...
https://github.com/haskell/hackage-server/issues/348#issuecomment-140155169

**Comment by dcoutts** [comment]
Ok, this has been resolved for the moment by adjusting our proxy config. We'll try and re-enable it again after checking our CDN config more carefully.

**Comment by dcoutts** [comment]
@Blaisorblade if you're interested, please join #haskell-infrastructure and talk to the folks there

**Comment by snoyberg** [comment]
Whew, thank you!

**Comment by dcoutts** [comment]
@snoyberg oh and thanks for reporting so promptly :-)

**Comment by dcoutts** [comment]
Re https://twitter.com/snoyberg/status/775270783337857024, I can assure folks that it's a cockup not a conspiracy.

**Comment by gbaz** [comment]
For completeness sake, the decision was to update our proxy config as I understand it (I certainly checked our proxy config and it does use https between proxy and origin at this point). This issue should have been updated with that resolution, so I'm adding it now.
