### ISSUE TITLE
<repo>/root.json does not have enough signatures signed with the appropriate keys

### ISSUE THREAD

**Issue by DemiMarie** [haskell/hackage-server#547]
I get this error when doing `cabal update`:

```
Downloading the latest package list from hackage.haskell.org
<repo>/root.json does not have enough signatures signed with the appropriate
keys
```

This presumably means a problem with Hackage.

This error happens both with cabal git HEAD and with a released version of Cabal (1.25.0.0)

**Comment by hvr** [comment]
@DemiMarie you may have old TUF metadata in  `~/.cabal/packages/hackage.haskell.org/*.json` which was signed with the old test-keys and which became invalid with the new "real" repo keys... if you remove those .json files, the error should go away.

**Comment by DemiMarie** [comment]
That was the problem, thanks!

**Comment by gbaz** [comment]
Ok, I guess I can close this then...
