### ISSUE TITLE
Can't add new maintainer to package

### ISSUE THREAD

**Issue by mboes** [haskell/hackage-server#557]
Action:

Go [here](http://hackage.haskell.org/package/inline-java/maintainers/edit) and click [edit]. Add user `AlexanderVershilov` as maintainer.

Expected:

`AlexanderVershilov` in the list of maintainers.

Actual:

list of maintainers stays unchanged.

**Comment by mboes** [comment]
cc @qnikst

**Comment by gbaz** [comment]
They've been added, as you can see from http://hackage-origin.haskell.org/package/inline-java/maintainers/

Its just our darn CDN caching not reflecting that for who knows how long :-/

**Comment by gbaz** [comment]
This patch https://github.com/haskell/hackage-server/commit/d2008bcc9ec887c766497c77e206e62545c64bea

(assuming its not yet deployed? @dcoutts ?) may help...

**Comment by hesselink** [comment]
Any updates on this? I keep getting confused by it.

**Comment by cdepillabout** [comment]
We got bit by this too:

https://bitbucket.org/robertmassaioli/hailgun/pull-requests/19/bump-aeson-version/diff#comment-31488635

**Comment by chrisdone** [comment]
Confused me too. Good tip here though

> They've been added, as you can see from http://hackage-origin.haskell.org/package/inline-java/maintainers/

Thanks.

**Comment by gbaz** [comment]
Our CDN config now should cache tarballs but not this stuff, so its fine. In general we want to make things more CDN aware, but I think this specific ticket can be closed.
