### ISSUE TITLE
Candidate upload not visible in candidates list for package

### ISSUE THREAD

**Issue by bennofs** [haskell/hackage-server#562]
I recently uploaded a new package candidate for `th-lift-instances`, which can be found here: 
http://hackage.haskell.org/package/th-lift-instances-0.1.11/candidate

However, this candidate is not listed in the "list of candidates" for the package `th-lift-instances`:
http://hackage.haskell.org/package/th-lift-instances/candidates/

It is listed in the list of "All package candidates", though: http://hackage.haskell.org/packages/candidates/

**Comment by gbaz** [comment]
Another instance of stale caching on the CDN.

If I add a suffix so the CDN doesn't give the cached version -- e.g. http://hackage.haskell.org/package/th-lift-instances/candidates/?foo then it appears right away.

**Comment by gbaz** [comment]
Our CDN config now should cache tarballs but not this stuff, so its fine. In general we want to make things more CDN aware, but I think this specific ticket can be closed.
