### ISSUE TITLE
packages.csv upload seems broken

### ISSUE THREAD

**Issue by peti** [haskell/hackage-server#564]
`hackage.haskell.org` responds to my upload with "OK", but the upload has no effect, i.e. it continues to serve old data apparently ignoring the new information I've just uploaded:

~~~
$ perl -p -i -e 'chomp if eof' packages.csv   # remove last '\n'  from file
$ curl -u "PeterSimons:XXXYYYZZZ" --digest -H "Content-type: text/csv" -T packages.csv http://hackage.haskell.org/distro/NixOS/packages.csv
Ok!
$ grep jni packages.csv 
"jni","0.2.2","http://hydra.nixos.org/job/nixpkgs/trunk/haskellPackages.jni.x86_64-linux"
$ curl --silent http://hackage.haskell.org/distro/NixOS/packages.csv | grep jni
"jni","0.1","http://hydra.nixos.org/job/nixpkgs/trunk/haskellPackages.jni.x86_64-linux"
~~~

**Comment by peti** [comment]
Hmm, this gets more confusing by the minute. Now, the web page http://hackage.haskell.org/package/jni contains the updated reference to `jni-0.2.2`, but the API call *still* shows the old version:

~~~
$ curl --silent http://hackage.haskell.org/distro/NixOS/packages.csv | grep jni
"jni","0.1","http://hydra.nixos.org/job/nixpkgs/trunk/haskellPackages.jni.x86_64-linux"
~~~

**Comment by gbaz** [comment]
Three letters: C D N :-)

**Comment by peti** [comment]
OK. Thanks for the information. :-)

**Comment by hvr** [comment]
@peti does `curl -X PURGE http://hackage.haskell.org/distro/NixOS/packages.csv` have any effect?
