### ISSUE TITLE
README/Changelog rendering: Support a larger subset of GitHub-flavored Markdown

### ISSUE THREAD

**Issue by sjakobi** [haskell/hackage-server#565]
As a large part of Haskell packages is hosted on GitHub it would be very convenient if Hackage's Markdown rendering would support a larger subset of Github-flavored Markdown.

These are some features of Github-flavored Markdown that Hackage currently doesn't support:

* Tables (see e.g. [hpack](http://hackage.haskell.org/package/hpack-0.16.0#readme))
* (Sanitized) [Inline HTML](https://github.com/haskell/hackage-server/issues/477)

**Comment by sjakobi** [comment]
Is anyone else interested in this feature request apart from myself?

A few thoughts with regard to possible implementations:

cheapskate already supports inline HTML and seems to do at least basic sanitizing to prevent XSS attacks, but it does not support a syntax for tables. [Support for tables could be added in principle but jgm doesn't seem to be interested in cheapskate anymore](https://github.com/jgm/cheapskate/issues/18), so someone else would have to develop that feature and possibly take over the package.

To me this sounds like it would be more worthwhile to look for an alternative to cheapskate.

What are the **requirement**?

* Be fast and require little memory for any input
* Be robust, i.e. don't segfault or throw exceptions for malformed or malicious input
* Have a compatible license – can someone explain which licences are acceptable, or rather, which ones are not?
* Ideally have an active maintainer
* Ideally support as much of GitHub flavored Markdown as possible without precluding other common Markdown styles. If possible it should support all of CommonMark.

Anything else?

What **libraries** fit these requirements or why do they not fit the requirements?

* I'm sure that **pandoc** has been considered before but why was (and possibly is) it not a good fit?
* There were [plans](https://github.com/bitonic/sundown/issues/5) to make bindings to the C library **hoedown** which allegedly is robust and rich in features, so maybe there's a point in reviving that project. OTOH [hoedown](https://github.com/hoedown/hoedown) doesn't seem to be actively maintained at this point.
* CommonMark and therefore **cmark** doesn't have a syntax for tables

Other contenders?

**Comment by sjakobi** [comment]
> Have a compatible license – can someone explain which licences are acceptable, or rather, which ones are not?

Including a GPL-licensed dependency would [apparently](http://opensource.stackexchange.com/a/39) force this package to change its license to GPL.

---

Regarding possible libraries I've found [an insightful comment](https://github.com/haskell/hackage-server/pull/356#issuecomment-103238446) comparing pandoc, cmark and cheapskate.

Given the size of that discussion I think it would be more worthwile to add table support to cheapskate than to try to use pandoc.

**Comment by ezyang** [comment]
Yes I would be interested in having tables support.

**Comment by gbaz** [comment]
@sjakobi we seem to have a bunch of markdown related issues now collected under the tag. It would be nice to find a way forward.

I see two alternatives. A) extend cheapskate (which someone has to volunteer to do) or B) move to pandoc (which causes license concerns, and has potential performance implications). 

You seem to have indicated that you'd be open to helping out here. If you want to take up the cudgel for extending cheapskate so we can get all these new features, I'd be thrilled.

Alternately, we could consider just using pandoc. I'd suggest we have a compile time flag that lets people revert to the old cheapskate implementation, so that a BSD licensed version of hackage is still compilable. Running the central server as GPL seems no problem to me.

**Comment by jgm** [comment]
+++ gbaz [Jan 28 18 03:45 ]:
>   Actually, I realize that thanks to a pointer from [1]@jgm we should
>   probably just switch to [2]http://hackage.haskell.org/package/cmark-gfm
>
>   That should give a nice superset of markdown, and furthermore be the
>   one that satisfies expectations, as github flavored markdown is what
>   people are authoring their readmes for often anyway.

I'll note one potential drawback:  it's a C library, and
although it's pretty battle-tested, that always comes with
risks.

I'm working on a pure Haskell commonmark parser which you
could switch to later.

**Comment by hvr** [comment]
Tbh, I don't like the idea of relying on C for parsing untrusted input data.

Fwiw, I'm also keeping my eye on  `mmark` (c.f. https://github.com/mmark-md/mmark#performance) as an interesting markdown implementation.

Curiously, cabal's description field may soon support more markup features than the changelog/readme (including tables!) :-)

**Comment by gbaz** [comment]
Hmm.. mmark looks nice too. Is there any reason we shouldn't just cut over to that?

**Comment by sjakobi** [comment]
mmark seems to have a few important differences to GFM: https://github.com/mmark-md/mmark#quick-start-mmark-vs-github-flavored-markdown

It also seems that mmark's strictness would cause some compatibility problems. What about readmes that suddenly fail to parse? Hackage would also have to validate readmes and changelogs on upload.

To me, cmark-gfm sounds like the best currently available option. I'd think that what's sufficiently reliable for Github should also work for Hackage.

**Comment by hvr** [comment]
As @sjakobi points out, `mmark` doesn't yet have support for GFM, but it's on the table that `mmark` may gain such a mode. And what I particularly like about `mmark` is that it's stricter. I don't see why we should aim for bug-compatiblity with whatever github renders, rather than trying best-effort at GFM compat but diverging when github's being too lax.

**Comment by jgm** [comment]
+++ Herbert Valerio Riedel [Jan 29 18 03:10 ]:
>   As [1]@sjakobi points out, mmark doesn't yet have support for GFM, but
>   it's on the table that mmark may gain such a mode. And what I
>   particularly like about mmark is that it's stricter. I don't see why we
>   should aim for bug-compatiblity with whatever github renders, rather
>   than trying best-effort at GFM compat but diverging when github's being
>   too lax.

mmark really diverges quite a lot from longstanding Markdown
traditions.  E.g. according to the readme,

    > foo bar baz foo bar baz foo bar baz
    > foo bar baz foo bar baz foo bar baz

produces two block quotes instead of one! And "block quotes
do not feature 'laziness'."

The readme advertises simpler emphasis parsing rules, but in
fact the 17 CommonMark rules were motivated by lots and lots
of real-world cases. The result is that in mmark, you need
to backslash escape the ) to get emphasis in

    Here goes *(something\)*

The idea that

    *Something * is not right

and

    __foo__bar

produce a parse error also goes against long Markdown
tradition, in which all text is handled.  (*'s and _'s are just
regular textual *'s and _'s if they aren't in the right positions
to cause emphasis.)

I think that if you tried running mmark against the
commonmark test suite, you'd see a huge number of
divergences, each of which might correspond to a later
complaint by a user ("why doesn't my readme render the way
it does on github"?)

Hence, if a wrapped C library is acceptable, I'd advise
using cmark-gfm.  (As I mentioned, I should have a pure
Haskell alternative in a month or so.)

**Comment by jgm** [comment]
+++ John MACFARLANE [Jan 29 18 10:11 ]:
>+++ Herbert Valerio Riedel [Jan 29 18 03:10 ]:
>>  As [1]@sjakobi points out, mmark doesn't yet have support for GFM, but
>>  it's on the table that mmark may gain such a mode. And what I
>>  particularly like about mmark is that it's stricter. I don't see why we
>>  should aim for bug-compatiblity with whatever github renders, rather
>>  than trying best-effort at GFM compat but diverging when github's being
>>  too lax.
>
>mmark really diverges quite a lot from longstanding Markdown
>traditions.

To add one more
---------------

Setext style headers (like the above) are not supported.

**Comment by hvr** [comment]
@jgm Fair enough, and what's the relationship of CommonMark <-> GFM in the context of well defined grammars?

**Comment by jgm** [comment]
GFM is CommonMark with a few extensions.  In fact, the core
of GitHub's GFM rendering engine is the commonmark reference
implementation cmark.

+++ Herbert Valerio Riedel [Jan 30 18 00:10 ]:
>   [1]@jgm Fair enough, and what's the relationship of CommonMark <-> GFM
>   in the context of well defined grammars?

**Comment by asr** [comment]
We have some issues with tables on Agda [CHANGELOG](http://hackage.haskell.org/package/Agda-2.5.3/changelog), so tables support would be great.

**Comment by jgm** [comment]
The pure Haskell commonmark parser I've been working on could be used for this:
https://github.com/jgm/commonmark-hs
I haven't published this yet, and might change the API substantially in the future, but you could simply vendor it for now.  You'd only need [commonmark-core](https://github.com/jgm/commonmark-hs/tree/master/commonmark), which has a tiny dependency footprint.  It currently supports the following optional extensions:  GFM-compatible Pipe tables, Smart quotes, dashes, and ellipses, Strikethrough, LaTeX math, Autolink bare URLs and email addresses, Footnotes, Definition lists, Header attributes.

**Comment by jgm** [comment]
I have released the `commonmark` package on hackage, as well as `commonmark-extensions` (which include the GitHub extensions and more).  With the proper set of extensions, it should render markdown READMEs the same way GitHub does.  I suggest that this be used instead of `cheapskate`, which is more or less an unmaintained package.  Let me know if you have any trouble using the library or suggestions for improving the API.

**Comment by jgm** [comment]
I just noticed that HTML comments in README.md files are rendered verbatim (rather than hidden or omitted): example [here](https://hackage.haskell.org/package/citeproc).  That seems suboptimal, and it reminded me of this issue.  Is there interest in switching to `commonmark` and `commonmark-extensions` to get full gfm compatibility?  If so, perhaps I could help.

**Comment by gbaz** [comment]
Yeah, we'd definitely want to switch over! If you're interested in giving a PR a go it would be welcome. If you run into too many difficulties working on it, I could try to do a basic PR, based on your suggestions as to how to change the code, and then rely on your review to make sure we're using the library optimally.

**Comment by jgm** [comment]
@gbaz can you point me to the part of the code where the markdown processing happens?

**Comment by jgm** [comment]
Of course, I'd be even happier to do it as you propose, if you put together a basic PR, I'll review it.

**Comment by gbaz** [comment]
I think its in a couple spots:

The key one:
https://github.com/haskell/hackage-server/blob/master/Distribution/Server/Pages/Package.hs#L185 

but also
https://github.com/haskell/hackage-server/blob/master/Distribution/Server/Features/PackageFeed.hs#L145
https://github.com/haskell/hackage-server/blob/master/Distribution/Server/Features/PackageContents.hs#L207
https://github.com/haskell/hackage-server/blob/master/Distribution/Server/Features/PackageCandidates.hs#L611

We should probably clean up that duplication while we're at it.

**Comment by jgm** [comment]
What is updateRelativeLinks for?

**Comment by gbaz** [comment]
people construct their `README.md` files so the relative links work in github. But there, the links are relative to the source directory already. When we display markdown README files inline in hackage, they need to link to /src first, or they don't work.

cf https://github.com/haskell/hackage-server/pull/631

I guess it doesn't always work though, as per:  https://github.com/haskell/hackage-server/issues/823

**Comment by jgm** [comment]
I think this will fix part of the problem:
``` diff
diff --git a/Distribution/Server/Pages/Package.hs b/Distribution/Server/Pages/Package.hs
index 0fe88fd..9ff767e 100644
--- a/Distribution/Server/Pages/Package.hs
+++ b/Distribution/Server/Pages/Package.hs
@@ -179,7 +179,7 @@ readmeSection _ _ = []
 updateRelativeLinks :: T.Text -> Markdown.Inline -> Markdown.Inline
 updateRelativeLinks name (Markdown.Link inls url title) =
   Markdown.Link inls url' title
-  where url' = if isRelativeReference $ T.unpack url then name <> T.pack "/src" <> url else url
+  where url' = if isRelativeReference $ T.unpack url then name <> T.pack "/src/" <> url else url
 updateRelativeLinks _ x = x
 
 renderMarkdown :: T.Text -> BS.ByteString -> Html
```
The other part of the problem is that not every file in a GitHub repository gets included in the release tarball; in those cases you'll get broken links, there's nothing you can really do about that.

**Comment by jgm** [comment]
Looks like installing and testing this server is a bit involved, so it would be easiest if you could do the change with my guidance.  I'll provide something you can use to replace the existing markdown conversion function.

**Comment by gbaz** [comment]
Sure, just toss me some example code and I'll try to get it actually working and tested.

for reference, here are the markdown features people seem to have requested, not sure how many that we can/should cover

https://github.com/haskell/hackage-server/issues/825
https://github.com/haskell/hackage-server/issues/650
https://github.com/haskell/hackage-server/issues/567
https://github.com/haskell/hackage-server/issues/545
https://github.com/haskell/hackage-server/issues/477

**Comment by jgm** [comment]
Oh, and I don't understand why you have `name <> T.pack "/src/"` -- when I checked the pandoc README, this led to a case where you got the name doubled. Since the link is already being served at packages/pandoc-2.11, I don't think the name is necessary. Anyway, I'll give you something to try soon.

**Comment by jgm** [comment]
Here's some code that can replace your `renderMarkdown`:
``` haskell
{-# LANGUAGE MultiParamTypeClasses #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE FlexibleContexts #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE UndecidableInstances       #-}
import Commonmark
import Commonmark.Extensions
import qualified Data.Text as T
import qualified Data.Text.Lazy as TL
import qualified Data.ByteString as BS
import Data.Monoid
import Data.Semigroup
import Network.URI (isRelativeReference)
import Control.Monad.Identity
import Text.HTML.SanitizeXSS as XSS

-- HHtml wraps Html, and mostly behaves the same, except that
-- relative links in images and urls have "src/" prepended.
newtype HHtml a = HHtml { unHHtml :: Html a }
  deriving (Show, Semigroup, Monoid)

instance HasAttributes (HHtml a) where
  addAttributes attrs (HHtml x) = HHtml (addAttributes attrs x)

instance ToPlainText (HHtml a) where
  toPlainText (HHtml x) = toPlainText x

instance Rangeable (Html a) => Rangeable (HHtml a) where
  ranged sr (HHtml x) = (HHtml $ ranged sr x)

instance (Rangeable (Html a), Rangeable (HHtml a)) => IsInline (HHtml a) where
  lineBreak = HHtml lineBreak
  softBreak = HHtml softBreak
  str t = HHtml (str t)
  entity t = HHtml (entity t)
  escapedChar c = HHtml (escapedChar c)
  emph ils = HHtml (emph $ unHHtml ils)
  strong ils = HHtml (strong $ unHHtml ils)
  link target title ils = HHtml $
    addAttribute ("href", escapeURI (adjustRelativeLink target)) .
    (if T.null title
        then id
        else addAttribute ("title", title)) $
    htmlInline "a" (Just $ unHHtml ils)
  image target title ils = HHtml $
    addAttribute ("src", escapeURI (adjustRelativeLink target)) .
    addAttribute ("alt", toPlainText ils) .
    (if T.null title
        then id
        else addAttribute ("title", title)) $
    htmlInline "img" Nothing
  code t = HHtml $ code t
  rawInline f t = HHtml (rawInline f t)

instance (Rangeable (Html a), IsInline (HHtml a))
     => IsBlock (HHtml a) (HHtml a) where
  paragraph ils = HHtml $ paragraph $ unHHtml ils
  plain ils = HHtml $ plain (unHHtml ils <> nl)
  thematicBreak = HHtml thematicBreak
  blockQuote bs = HHtml $ blockQuote $ unHHtml bs
  codeBlock info t = HHtml $ codeBlock info t
  heading level ils = HHtml $ heading level $ unHHtml ils
  rawBlock f t = HHtml $ rawBlock f t
  referenceLinkDefinition x y = HHtml $ referenceLinkDefinition x y
  list lType lSpacing items =
    HHtml $ list lType lSpacing $ map unHHtml items

instance HasEmoji (HHtml a) where
  emoji kw cs = HHtml $ emoji kw cs

instance HasStrikethrough (HHtml a) where
  strikethrough ils = HHtml $ strikethrough $ unHHtml ils

instance HasPipeTable (HHtml a) (HHtml a) where
  pipeTable aligns heads rows =
    HHtml $ pipeTable aligns (map unHHtml heads) (map (map unHHtml) rows)

instance (Rangeable (Html a), Rangeable (HHtml a))
         => HasTaskList (HHtml a) (HHtml a) where
  taskList ltype lspacing items =
    HHtml $ taskList ltype lspacing
          $ map (\(done, bl) -> (done, unHHtml bl)) items

nl :: Html a
nl = htmlRaw "\n"

adjustRelativeLink :: T.Text -> T.Text
adjustRelativeLink url
  | isRelativeReference (T.unpack url) &&
    not ("/" `T.isPrefixOf` url)
              = "src/" <> url
  | otherwise = url


renderHHtml :: HHtml () -> TL.Text
renderHHtml (HHtml x) = renderHtml x

renderMarkdown :: T.Text -> T.Text -> T.Text
renderMarkdown name md =
  case runIdentity (commonmarkWith (gfmExtensions <> defaultSyntaxSpec)
                                   (T.unpack name)
                                   md) of
         Left _err   -> mempty
         Right hhtml -> XSS.sanitizeBalance $ TL.toStrict $ renderHHtml hhtml
```

The type is a bit different -- but if you want to take a ByteString as input, you can just UTF8-decode it to a Text.  Similarly, if you want a (blaze) Html as output, you can wrap in primHtml.

This version is a bit different from what you have in that it doesn't omit all raw HTML; instead, it runs the final HTML through a sanitizer.  If you want to omit raw HTML, then the thing to do is to modify the clauses for rawInline and rawBlock so that they just return a mempty.

I only looked at Distribution.Server.Pages.Package; it may be that there are requirements in the other bits of code you cited that this won't serve. If so, let me know.

**Comment by jgm** [comment]
On the other issues:

- #825 and #477 should be handled by the change to raw HTML
- #650 we have an extension for pandoc-style footnotes, but it's not enabled in the code above...it could be added easily enough
- #567 we have an extension for tex math (which works as in pandoc and produces mathjax-compatible HTML output)...it would be easy to add this
- #545 - currently we don't do any syntax highlighting. This could be added in various ways: via a JavaScript highlighting library (client-side), or by depending on skylighting and using it to highlight (this would require some modifications in the clauses for `code` and `codeBlock` above).

**Comment by gbaz** [comment]
Great! do you mind pointers to the footnote stuff and the tex math stuff?

**Comment by jgm** [comment]
Sure.  For math, you'll import <https://hackage.haskell.org/package/commonmark-extensions-0.2.0.1/docs/Commonmark-Extensions-Math.html>.
You'll define an instance of the HasMath typeclass for HHtml a.
These instances should be trivial (warning - untested!):
```haskell
instance HasMath (HHtml a) where
  inlineMath t = HHtml $ inlineMath t
  displayMath t = HHtml $ displayMath t
```
Then, in the code above you'll replace
```
(gfmExtensions <> defaultSyntaxSpec)
```
with
```
(mathSpec <> gfmExtensions <> defaultSyntaxSpec)
```

For footnotes, it's pretty similar.  You'll import <https://hackage.haskell.org/package/commonmark-extensions-0.2.0.1/docs/Commonmark-Extensions-Footnote.html>, define an instance for HasFootnote, and add footnoteSpec to the specification of the syntax.  Here the instances are a bit more complicated; you'll need
```
HasFootnote (HHtml a) (HHtml a) where
```
and you may also need some more constraints.  But the instances are just a matter of packing and unpacking the HHtml wrapper.

Let me know if questions arise.

**Comment by jgm** [comment]
Note: for the math, you'd need to include the MathJax script when you serve the pages:
```html
<script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>
```

**Comment by jgm** [comment]
Actually, I think it may be best to put `defaultSyntaxSpec` first:
`defaultSyntaxSpec <> gfmExtensions`. Otherwise we run into https://github.com/jgm/commonmark-hs/issues/52
