### ISSUE TITLE
Recents not updating?

### ISSUE THREAD

**Issue by LeventErkok** [haskell/hackage-server#566]
This is as of Sun Jan 15 2017, 11AM PST.

Perhaps this is a temporary glitch that'll automatically go away by itself, but I noticed that:

http://hackage.haskell.org/packages/recent

has stopped updating. The top 3 entries are (currently):

```
Sun Jan 15 18:02:41 UTC 2017  	ChristiaanBaaij	  ghc-typelits-extra-0.2.2
Sun Jan 15 18:02:20 UTC 2017  	oleks	          remarks-0.1.0
Sun Jan 15 17:51:26 UTC 2017  	ChristiaanBaaij	  ghc-typelits-knownnat-0.2.3
```

But there have been at least 5 new packages uploaded after this point; possibly more. (According to: http://hdiff.luite.com/)

**Comment by LeventErkok** [comment]
Looks like it was a temp-glitch and it's updating again!

**Comment by gbaz** [comment]
cdn probably :-)
