### ISSUE TITLE
Mathjax in readme's

### ISSUE THREAD

**Issue by noinia** [haskell/hackage-server#567]
In haddock it is now possible to use Mathjax, can we also enable in Hackage as well? In particular, I would like to be able to use tex-style math in the Readme section of my package(s).

**Comment by gbaz** [comment]
This really depends on our choice of markdown engine. We currently use cheapskate, but at this point it is deprecated in favor of cmark: https://github.com/jgm/cheapskate

I'm going to suggest we investigate moving markdown engines at this point.
