### ISSUE TITLE
metadata editing form should be cdn aware

### ISSUE THREAD

**Issue by lspitzner** [haskell/hackage-server#569]
it currently seems to use the original (x-revision 0 or how that is called), even when changes to the metadata have been made already.

**Comment by hvr** [comment]
I haven't noticed this myself yet... does this still occur for you?

**Comment by lspitzner** [comment]
i cannot reproduce this either now. still i wonder if some form of caching might have caused it.

**Comment by gbaz** [comment]
Our CDN config now should cache tarballs but not this stuff, so its fine. In general we want to make things more CDN aware, but I think this specific ticket can be closed.
