### ISSUE TITLE
Missing JSON meta data for gogol-admin-reports-0.2.0 

### ISSUE THREAD

**Issue by peti** [haskell/hackage-server#570]
Both the NixOS and the openSUSE project rely on the information from https://github.com/commercialhaskell/all-cabal-hashes to generate build descriptions for their distribution. Both projects have now run into problems because there is a file called `gogol-admin-reports/0.2.0/gogol-admin-reports.cabal`, but there is no corresponding JSON file. Now, @snoyberg has explained to me in https://github.com/commercialhaskell/all-cabal-hashes/issues/11#issuecomment-279701304 that this issue is due to some problem on the Hackage server, i.e. this JSON file is supposed to be generated by Hackage Security, but it is not.

Is that a known problem?

**Comment by gbaz** [comment]
Here's the relevant issue -- https://github.com/haskell/hackage-server/issues/488

If you don't mind I'll close in favor of that. But yes, this is really upstream with hackage-security where it is also filed. I agree it would be good to try to determine the situation that leads to these anomalies.
