### ISSUE TITLE
Candidates stuck even after removal

### ISSUE THREAD

**Issue by Rufflewind** [haskell/hackage-server#571]
There's two candidates in the list right now for `directory`:

https://hackage.haskell.org/package/directory/candidates/

I went through both and deleted them.  But they are still in the list!

I tried deleting them again, but Hackage complains they no longer exist.  So they seem to be gone, but their ghosts are stuck in the table of contents.

**Comment by gbaz** [comment]
Cdn caching strikes again.

**Comment by gbaz** [comment]
Our CDN config now should cache tarballs but not this stuff, so its fine. In general we want to make things more CDN aware, but I think this specific ticket can be closed.
