### ISSUE TITLE
Strange "dependencies" list

### ISSUE THREAD

**Issue by crockeea** [haskell/hackage-server#572]
What dependencies are listed for a package on Hackage? Just those for the library portion of the cabal file, or also for the tests/benchmarks/random executables? Either way, Hackage seems to be confused in some cases:

The Hackage dependency list for [lol-apps](https://hackage.haskell.org/package/lol-apps) lists `lol-apps` and `lol-cpp` as dependencies, even though the library portion of lol-apps does not depend on either. The tests and benchmarks for lol-apps _does_ depend on `lol-apps` and `lol-cpp`, but _also_ depends on `lol-benches`, which are not listed in the Hackage 'dependency' section. What is the method to this madness, and can we make it more sane? Perhaps having a 'dependencies' section for each section in the cabal file is the right approach.

**Comment by grayjay** [comment]
Hackage displays the union of all dependencies that could be required by a package's library and executables when all manual flags have their default values.  The list includes `lol-apps` and `lol-cpp` because they are dependencies of the executables.  There is a "details" link at the end that lists dependencies by component: https://hackage.haskell.org/package/lol-apps-0.2.0.0/dependencies .  It doesn't include tests or benchmarks, though.

**Comment by crockeea** [comment]
It shouldn't be too hard to show the tests and benchmarks in the "details" link, right?

**Comment by grayjay** [comment]
I don't think it would be too hard to add the other components.  I think it would just involve adding the test and benchmark dependencies to the `PackageRender` here
 https://github.com/haskell/hackage-server/blob/1c1169dba5fd6985d27a3b2cf4ae67ccdcc3b3c3/Distribution/Server/Packages/Render.hs#L77-L78  and then adding them to the list of targets here
 https://github.com/haskell/hackage-server/blob/1c1169dba5fd6985d27a3b2cf4ae67ccdcc3b3c3/Distribution/Server/Pages/Package.hs#L316-L319 .

**Comment by kanishka-azimi** [comment]
IMHO, I usually don't care about the test or benchmark dependencies for libraries that I am using. If I want that level of information, I have already cloned the repository and am I reading the cabal file. Thoughts?

**Comment by gbaz** [comment]
Are we happy with the current behavior or do we want to make a particular change?

**Comment by hvr** [comment]
Fwiw, I consider `test-suites` and `benchmarks` components quite irrelevant in this context,  as you cannot depend upon them anyway (i.e. neither via `build-depends` nor `build-tool-depends`; nor can you `new-install` them), and their deps are often poorly specified anyway. I don't think showing those components in the details would add any practical value, but instead would clutter the details-view with not-so-interesting noisy information.

There may be a slight change in the "union" representation, once we move into a more per-component model (which will involve showing library and executables a bit more saliently w/ per-executable synopsis/descriptions, and then you could easily have per-component flattened/union'ed deps), but for now I think I'm personally content with the current behavior.

**Comment by gbaz** [comment]
ok, i'll close this then.
