### ISSUE TITLE
Render Haddocks in flag descriptions

### ISSUE THREAD

**Issue by RyanGlScott** [haskell/hackage-server#585]
This issue is best illustrated with an example, so take a look at http://hackage.haskell.org/package/accelerate-1.0.0.0#flags:

![accelerate](https://cloud.githubusercontent.com/assets/2364661/25565239/904bb4d6-2d91-11e7-8205-9eb119a71d3b.png)

Sadly, none of the Haddocks are rendered for any of the flags' descriptions, making it quite hard to read. Is it possible for `hackage-server` to render them?

**Comment by hvr** [comment]
I see no fundamental problem why we couldn't, as long as Cabal is able to parse the .cabal file

I was planning on improving/refactoring the current haddock markup handling anyway, as hackage-server has been lagging a bit behind Haddock's more recent markup additions (bold-faced, headings); then I could look into making the flag description haddockable as well.
