### ISSUE TITLE
Docs fail to build for packages that require GHC 8.0.2

### ISSUE THREAD

**Issue by tfausak** [haskell/hackage-server#591]
I uploaded a package that requires `base >= 4.9.1.0` and the docs failed to build because it wants to use `base-4.9.0.0` (GHC 8.0.1). 

https://hackage.haskell.org/package/json-feed-0.0.0/reports/3

**Comment by bgamari** [comment]
The doc builder was previously running an 8.0.2 release candidate, strangely enough. I've updated it to 8.0.2 proper.

**Comment by tfausak** [comment]
Thanks, that worked! https://hackage.haskell.org/package/json-feed-0.0.2/reports/1
