### ISSUE TITLE
Sitemap logic needs to conform to specs.

### ISSUE THREAD

**Issue by chrissound** [haskell/hackage-server#592]
![2017-05-30-22 04 31](https://cloud.githubusercontent.com/assets/1499652/26605353/8c8bd6f8-4585-11e7-9361-cde2668dd1d3.png)

A quick google search for "haskell persistent insert" seems to return the docs for v0.3.1.3 (latest is v2.7). 

I think if we set a higher priority for the latest version in the sitemap.xml - Google will pick this up and have the latest version higher up in the search results.

**Comment by hvr** [comment]
Here's what the sitemap says currently:

```xml
  <url>
    <loc>https://hackage.haskell.org/package/persistent/docs</loc>
    <lastmod>2017-04-17</lastmod>
    <changefreq>daily</changefreq>
    <priority>1.0</priority>
  </url>
```

```xml
  <url>
    <loc>https://hackage.haskell.org/package/persistent-0.3.1.3/docs</loc>
    <lastmod>2017-04-17</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.25</priority>
  </url>
```

So it does already use a higher priority for the unversioned URL which always points to the last version...

**Comment by chrissound** [comment]
Hmm. The v2.7 entry is at a priority of 0.25 though.

(Please excuse the strange formatting).
```
><priority
>0.25</priority
></url
><url
><loc
>https://hackage.haskell.org/package/persistent-2.7.0/docs</loc
```

**Comment by hvr** [comment]
True, but if google already now doesn't appear to prefer `persistent/docs` over `persistent-0.3.1.3/docs`, why would it make a difference if the priority for `persistent-2.7.0/docs` would be inbetweeen?

**Comment by chrissound** [comment]
I'm honestly not too sure, I'm just taking a guess here.

**Comment by gbaz** [comment]
I finally got us set up on the search management console and discovered that our sitemap is rejected by google :-/

"Your Sitemap contains too many URLs. Please create multiple Sitemaps with up to 50000 URLs each and submit all Sitemaps."

So we'll need to rethink some logic here.

**Comment by gbaz** [comment]
actually its not rejected -- it just only accepts that first chunk of urls, which is the majority...

**Comment by gbaz** [comment]
we can do multiple sitemaps as per: https://support.google.com/webmasters/answer/75712

Also sitemaps should have a link for every url, not just subdirectories.
