### ISSUE TITLE
Allow revising `pkgconfig-depends` constraints

### ISSUE THREAD

**Issue by hvr** [haskell/hackage-server#596]
(see https://github.com/fpco/stackage/pull/2597#issuecomment-310978227)

**Comment by hvr** [comment]
@basvandijk fyi, https://hackage.haskell.org/package/opencv-0.0.1.1/revisions/

**Comment by basvandijk** [comment]
Thanks Herbert, I [revised](http://hackage.haskell.org/package/opencv-extra-0.1.0.0/revisions/) `opencv-extra` as well.
