### ISSUE TITLE
Building (with Docker and otherwise) appears broken

### ISSUE THREAD

**Issue by TomLippincott** [haskell/hackage-server#602]
After a fresh clone, I run `docker build --force-rm -t hackage .`, and eventually get the error:

```
Step 8/25 : RUN cabal install --only-dependencies --enable-tests -j
 ---> Running in a6407b845e62
cabal: hackage-server.cabal:86: 'library' expects no argument
Removing intermediate container a6407b845e62
The command '/bin/sh -c cabal install --only-dependencies --enable-tests -j' returned a non-zero code: 1
```

The same error eventually shows up when trying to build outside Docker, e.g. with Stack, but if even the Docker build fails, something is seriously wrong since the build environment is supposed to Just Work (in terms of versioning etc).

**Comment by hvr** [comment]
Yes, the Docker script has most certainly bitrotted. Unfortunately, I've successfully avoided using Docker so far, so I can't help directly. That being said, the error is simply a result of using a too old `cabal-install`. You need at least Cabal 2.0

**Comment by TomLippincott** [comment]
Hmmm, I see that Stack doesn't support the Cabal 2.0 format yet, I guess I'll wait until that lands before trying again...unfortunately I've been hitting lots of problems with Stack generally, most non-trivial packages seem to have corner-case dependencies that are either too old or too new to compile without some serious effort, usually ending with "allow-newer: true" to open the floodgates (this sort of rabbit hole is what I'm seeing when trying to compile an older hackage-server snapshot).  I don't doubt this is mostly due to my nascent understanding of Stack+Cabal, though.  Feel free to close the issue, or I'll check back in once there's a new Stack version to try.

**Comment by siddhanathan** [comment]
We can fix the issue after bumping to GHC 8.2.1 in the Dockerfile, though we need to wait for an upstream patch in https://github.com/freebroccolo/docker-haskell/issues/60

**Comment by hvr** [comment]
@siddhanathan btw, we don't require GHC 8.2.1; hackage-server builds fine with GHC 7.6 through GHC 8.2 (see Travis CI); the only requirement is cabal-install 2.0 or newer.

**Comment by psftw** [comment]
FWIW, I just merged the update for `haskell:8.2.1` which includes cabal 2.0, but it still needs to go through the Official Image review process before getting pushed up to DockerHub (status: https://github.com/docker-library/official-images/pull/3461).  In the meantime, using my local build of `haskell:8.2.1` I noticed a couple of things when attempting to build the `Dockerfile`:  The postfix install forces a manual prompt during the build process (even when specifying `DEBIAN_FRONTEND=noninteractive`).  There are a couple of workaround options to install postfix non-interactively, but I didn't explore further.  Next, the build fails with:
```
cabal: The following packages are likely to be broken by the reinstalls:
haskeline-0.7.4.0
ghc-8.2.1
ghci-8.2.1
directory-1.3.0.2
hpc-0.6.0.3
ghc-boot-8.2.1
Use --force-reinstalls if you want to install anyway.
The command '/bin/sh -c cabal install --only-dependencies --enable-tests -j' returned a non-zero code: 1
```
I'm not entirely sure what it is telling us here, but want to make sure it isn't an issue with the new 8.2.1 Docker image.

**Comment by gbaz** [comment]
Even though I'm not a docker user, I'm going to go ahead and merge https://github.com/haskell/hackage-server/pull/620 since that seems like it'll at least advance the state somewhat forward?

Having done so, does this issue need to stay open, or will it resolve things?

**Comment by siddhanathan** [comment]
> I'm not entirely sure what it is telling us here, but want to make sure it isn't an issue with the new 8.2.1 Docker image.

cabal installs can fail, and they should be handled. Since the Docker setup is isolated, you can add `--force-reinstalls` without any major consequences.

> Having done so, does this issue need to stay open, or will it resolve things?

I believe this issue can be closed. If anyone has issues related to the Docker setup, or if the code bitrots again, feel free to cc me on github or send me an email.

**Comment by gbaz** [comment]
great, closing. thanks!

btw since we have some docker users on thread, does anyone want to comment on https://github.com/haskell/hackage-server/issues/548 ?
