### ISSUE TITLE
getting to latest base package

### ISSUE THREAD

**Issue by gliptak** [haskell/hackage-server#603]
Is there a recommended way to search for latest ```base``` (```Prelude```) package? Searching for ```base``` and ```Prelude``` seems to return lots of links, but not this main one.

From https://hackage.haskell.org/package/base-4.8.1.0/docs/Data-List.html I got to https://hackage.haskell.org/package/base-4.8.1.0 and now to the latest link as https://hackage.haskell.org/package/base-4.10.0.0

Maybe even a link could be added to https://hackage.haskell.org/ ?

Thanks

**Comment by gbaz** [comment]
`base` is the first result when you search for `base` in hackage: http://hackage.haskell.org/packages/search?terms=base

I assume this is about google results in that case, which makes it a dup of: https://github.com/haskell/hackage-server/issues/198

**Comment by gliptak** [comment]
Hmm ... Might have been a glitch. Thank you for looking into this @gbaz
