### ISSUE TITLE
Rendering of source repository broken

### ISSUE THREAD

**Issue by wereHamster** [haskell/hackage-server#605]
https://hackage.haskell.org/package/eddie

Looks like the output of `show`'ing the internal data structure.

**Comment by gbaz** [comment]
I think this is occurring because hackage tries to render nicely the source repository types it knows about, and just dumps the show when it fails.

eddie has:

```
Source-repository head
    Type: fs
    Location: https://chiselapp.com/user/mwm/repository/eddie/
```

And it doesn't know what to do with "fs".

**Comment by hvr** [comment]
I thought I had seen this before, and in fact a quick search resulted in the following past related issues

- #48 
- #62
- #104 
- #238

**Comment by gbaz** [comment]
@wereHamster I'm closing this because we don't know what to do with the `fs` type repo. Feel free to reopen if you have something more concrete here...

**Comment by gbaz** [comment]
ah -- its fossil! going to actually fix this now

**Comment by hvr** [comment]
@sclv how did you figure out that it'd be "fossil"? :-)

**Comment by sclv** [comment]
I went to the link and looked :-)

**Comment by gbaz** [comment]
I went to the link and looked :-)
