### ISSUE TITLE
Install pkg-config package sdl2>=2.0.4 and sdl2-ttf, pretty please?

### ISSUE THREAD

**Issue by Mikolaj** [haskell/hackage-server#608]
On Ubuntu these are libsdl2-dev and libsdl2-ttf-dev. They don't change often and their absence breaks docs for quite a few hackage packages (sadly many maintainers don't upload docs manually).

A log showing too old libsdl2-dev:
http://hackage.haskell.org/package/sdl2-2.3.0/reports/3

Thank you!

**Comment by hvr** [comment]
@Mikolaj is this resolved now?

**Comment by Mikolaj** [comment]
Unfortunately not, because the sdl2 packages are too old now, because the Ubuntu release is 14.04. :) I guess I will close the issue --- there is lots of work involved in managing the infrastructure and so it's not just a matter of a quick `apt-get install`. :(
