### ISSUE TITLE
Inconsistent dependency bounds in many packages

### ISSUE THREAD

**Issue by en-em** [haskell/hackage-server#611]
For example, https://hackage.haskell.org/package/utf8-string-1.0.1.1 says

    Dependencies | base (>=4.3 && <4.11), bytestring (>=0.9)

However, https://hackage.haskell.org/package/utf8-string-1.0.1.1/src/utf8-string.cabal says:

    build-depends: base >= 4.3 && < 4.9, bytestring >= 0.9

**Comment by hvr** [comment]
See https://hackage.haskell.org/package/utf8-string-1.0.1.1/revisions/

**Comment by en-em** [comment]
Should this metadata update cause the actual .cabal file be patched at download/build time? I'm using gentoo hackport and this doesn't happen automatically for me, I have to fix .cabal files by hand.

**Comment by gbaz** [comment]
Cabal will substitute the cabal file at build time, but the original tarfile stays intact as is. Hackport sounds like it should be updated to become revision aware? Added a ticket on their tracker for this, and will close here.
