### ISSUE TITLE
Shoud fuzzy search be supported?

### ISSUE THREAD

**Issue by suzumiyasmith** [haskell/hackage-server#615]
Now, it is obvious that fuzzy search is not supported. e.g. search `rethink` won't get `rethinkdb` package as a result. Sometimes, it can be annoying. :(

Any idea or plan about fuzzy searching?

Thanks.

**Comment by tfausak** [comment]
I would like to see this too. I can't remember the number of times I've searched for a partial string and been surprised by the lack of results. Some recent examples that I remember:

- Searching for `influx` (https://hackage.haskell.org/packages/search?terms=influx) returns no results even though there is an `influxdb` package (https://hackage.haskell.org/package/influxdb).
- Searching for `postgres` (https://hackage.haskell.org/packages/search?terms=postgres) doesn't return `postgresql-simple` (https://hackage.haskell.org/package/postgresql-simple), which is the most popular PostgreSQL package.

That being said, I'm not holding my breath for a fix. Hackage's search appears to be based on keywords and word stems. And search issues tend to stay open for ... a while.

- https://github.com/haskell/hackage-server/issues/474
- https://github.com/haskell/hackage-server/issues/208
- https://github.com/haskell/hackage-server/issues/27
- https://github.com/haskell/hackage-server/issues/21
- https://github.com/haskell/hackage-server/issues/20

Have you tried searching on Stackage? It does a better job for all the queries given here:

- https://www.stackage.org/lts-9.3/hoogle?q=rethink
- https://www.stackage.org/lts-9.3/hoogle?q=influx
- https://www.stackage.org/lts-9.3/hoogle?q=postgres

**Comment by gbaz** [comment]
Hackage is under active development at the moment, and search is definitely a place we want to tackle! thanks for the links to related issues, but I wouldn't be so negative about the possibility for progress. More hands and more hackers are always welcome :-)

**Comment by gbaz** [comment]
So I think the simplest thing to do is ad-hoc improve our stemmer since it seems to work just fine except for "weird" computery stems like dropping "db" or "ql" etc.

**Comment by adamgundry** [comment]
It might be worth switching Hackage to use the `full-text-search` package. This was derived from the Hackage search implementation (so it provides a very similar interface and switching should be fairly trivial), but it has a few extra features, notably autocomplete search.

**Comment by gbaz** [comment]
Good idea. Any volunteers? :-P

**Comment by adamgundry** [comment]
I'm hoping to get a chance to look at the `full-text-search` integration at some point (but no promises, and no objections to someone else jumping in!).

On the original issue, another case I just happened across (see kolmodin/binary#92) is that searching for "serialisation" yields `binary` whereas searching for "serialization" yields `cereal`.

**Comment by gbaz** [comment]
@adamgundry do you think we should always change "z" to "s" in all our stemming? Might be the simplest way to prevent the pitfalls of britishised spellings (or britishized if you prefer).

**Comment by gbaz** [comment]
I do worry about other internationalisation issues that have a different flavour...

**Comment by gbaz** [comment]
Ad-hoc stemming now works. That means `postgres` and `influx` and `rethink` searches work. I think that may suffice to close this issue?

**Comment by gbaz** [comment]
I'll make a different issue for full-text-search
