### ISSUE TITLE
Voting interface is confusing

### ISSUE THREAD

**Issue by cocreature** [haskell/hackage-server#616]
A lot of people seem to be [confused](https://twitter.com/chris__martin/status/905127384634052609) by the new voting interface on Hackage.

### Issues
I’ll try to summarize the different issues people brought up so we have an overview of those before we start looking at solutions:

1. It is unclear that the lambdas are meant for voting. While it seems like a cute idea to use lambdas instead of stars, everybody is used to stars so it is far less intuitive to click on lambdas.
2. The color choices are confusing. If you haven’t voted all three lambdas are filled in but black. Once you vote they turn yellow (the yellow is also too bright).
3. Contrary to other voting interfaces, the score is only displayed numerically. The lambdas don’t show the score.
4. The score calculation is confusing. This is especially true for packages with very few votes. E.g. if there is only a single vote with a score of `3`, the score is `2.0`.

### Potential solutions
1. Use stars instead of lambdas. Lambdas are too cute for their own good and mostly serve to confuse users.
2. Don’t fill in the symbols by default.
3. This ties in with 3. It might be best to just use the lambdas to display the score and then offer a voting interface on hover.
4. I think the main problem here is that this score metric while potentially useful for sorting the output should not be the metric that’s displayed to users. The [blogpost](http://www.evanmiller.org/how-not-to-sort-by-average-rating.html) which has inspired this metric mentions Reddit as example. While Reddit might use this information for sorting, the score that is displayed to users is a simple `upvotes - downvotes` (afaik). Amazon is similar in that their default sorting takes a lot of things into account (I have no idea what exactly they use) but afaik the star rating that’s displayed is still the average (or something relatively close to that)

**Comment by chris-martin** [comment]
Also in the interest of making this feature more conventional, I think the ratings should be out of five stars instead of three.

**Comment by hvr** [comment]
@chris-martin I don't have a strong opinion regarding which voting-range we finally settle on, but I've been told that there's precedents for different choices (also also may subtly differ in whether 0 stars is included in the range), see below for very quick survey

----

## Michelin stars: [1..3] star range 

https://www.theguardian.com/lifeandstyle/2008/jan/24/foodanddrink.travelfoodanddrink, which states

- One star signifies a very good restaurant
- Two stars signify excellent cooking that is worth a detour
- Three stars signify exceptional cuisine that is worth a special journey

## IMDB uses a [1..10] star range

## NYT uses a [0..4] star range

See http://www.nytimes.com/packages/html/dining/info/ratings.html

## Amazon uses [1..5] star range

## Rotten tomatoes seems to use a [0.5,1.0 ... 5] star voting range

this is more or less isomorphic to the IMDB scheme as it also offers 10 voting grades while excluding an explicit 0-vote.

----

Fwiw, numerically, the current 3-star voting offsetted at 1-star (i.e. excluding "0 star" votes) has the property that the ordinary average also maps to the interval [1.0..3.0], so if we wanted to visualise the average by showing the amount of stars via partially filled stars (like I've seen being done on various sites), this would effectively mean that the left-most stars would always be either empty (effectively expressing "N/A") or fully lit (as soon as there's any vote), never partially filled.

**Comment by chris-martin** [comment]
> or fully lit (as soon as there's any vote), never partially filled

Yep, that's what both Amazon and NYT (reader ratings) do. I think 1 out of 5 stars is acceptable as a minimum. I've never felt a desire to berate a package any harder than that.

**Comment by gbaz** [comment]
Ok a PR 625 should have a lot of improvements here. The three lambdas remain, but wording has been cleared up between other ratings and yours, a link to the estimator used is added, and unclicked lambdas are hollow.
