### ISSUE TITLE
Index of all functions does not support inter-package linking

### ISSUE THREAD

**Issue by mrkkrp** [haskell/hackage-server#621]
This is Haddock-related: https://github.com/mrkkrp/megaparsec/issues/249.

Feel free to close if you feel that this belongs to Haddock issue tracker instead.

**Comment by hvr** [comment]
@mrkkrp I'd say this is clearly a Haddock issue and thus needs to be implemented in Haddock first before Hackage can benefit. However, you'll find a dozen issues in Haddock's issue tracker related to reexport-handling... it's an area that definitely needs more work.

**Comment by mrkkrp** [comment]
Thanks! Closing then.

**Comment by hvr** [comment]
@mrkkrp btw, please make sure there is an issue in Haddock's tracker which actually describes your specific problem

**Comment by mrkkrp** [comment]
Yeah, I'll check properly when I get home.
