### ISSUE TITLE
"Modules" section links to non-existing haddock documentation when using cabal flags

### ISSUE THREAD

**Issue by soenkehahn** [haskell/hackage-server#63]
http://beta.hackage.haskell.org/package/tagsoup contains a link to the haddock documentation for Text.HTML.Download, but the documentation for that module does not exist.

The cabal file for this package contains a flag ('download') which controls whether the module in question is exposed by the package or not. This seems to confuse hackage.

**Comment by gbaz** [comment]
looks like we fixed this, even though i can't track down the PR...
