### ISSUE TITLE
Link to Maintainers from each package's hackage page

### ISSUE THREAD

**Issue by ivanperez-keera** [haskell/hackage-server#637]
Each package has a maintainer, declared in the cabal file (e.g. [1]). Each package has a list of maintainers authorised to make changes to it on hackage (e.g. [2]).

It would be a nice small addition if there was a link from the former to the latter (from [1] to [2]).

[1] https://hackage.haskell.org/package/Yampa/
[2] https://hackage.haskell.org/package/Yampa/maintainers/

EDIT: clarification.

**Comment by hvr** [comment]
@ivanperez-keera can you maybe create a mockup of the UI? I've had considered this too, but I couldn't come up with a UI design that wouldn't be somewhat weird, as the maintainer-group and the .cabal declared maintainer(s) have a bit of an impedance mismatch, being in a different format/namespace.

**Comment by ivanperez-keera** [comment]
@hvr What I had in mind was super-simple. For example:
![screenshot from 2017-10-23 01-09-04](https://user-images.githubusercontent.com/1162320/31867396-202c89ae-b78f-11e7-9a5f-1df797f111eb.png)

**Comment by hvr** [comment]
@ivanperez-keera ok, that's easy enough; and you see no problem if the .cabal maintainer field has completely diverged from the hackage-maintainer-group?

**Comment by ivanperez-keera** [comment]
- Sure, it may be a bit confusing that they can diverge. And those being different is not always an indication of a problem. When both are real persons, then a reasonable expectation would be that the intersection of both not be empty. However, maintainers may not be real persons. For example, the "cabal" maintainer email might be a mailing list. And the "hackage" maintainer account might correspond to Travis CI. 

   A possibility to hint that this could happen would be to use a different word instead of details, such as 'official list', 'all', 'list' or 'hackage maintainers'. 

- The other, maybe less confusing option, may be to add it at the bottom, in the current _Maintainer's corner_. It might require renaming the section so that it fits semantically.

**Comment by gbaz** [comment]
I think the bottom is a good idea. That's where I'd expect it, actually.

**Comment by gbaz** [comment]
Note -- there's a little work that needs to be done to thread the data through to where it needs to go, as the maintainers group isn't normally available to that page directly.

**Comment by andreasabel** [comment]
@ivanperez-keera : Are you happy with today's status quo? 
<img width="439" alt="Screenshot 2023-04-12 at 22 04 39" src="https://user-images.githubusercontent.com/1155218/231572072-164d1d17-b7d8-4cf0-887d-eff13237b99c.png">

**Comment by ulysses4ever** [comment]
I find it weird that it goes under "Maintainer's Corner". But at least it's there…

**Comment by ivanperez-keera** [comment]
I agree, the UI/UX could be improved, but at least there is something.

**Comment by andreasabel** [comment]
Fixed by #1098.
