### ISSUE TITLE
Broken revisions link

### ISSUE THREAD

**Issue by snoyberg** [haskell/hackage-server#640]
Actions:

1. Go to http://hackage.haskell.org/package/mtl-2.2.1
2. See that there was 1 revision
3. Click on the revision link to go to https://hackage.haskell.org/package/mtl-2.2.1/mtl-2.2.1/revisions/

Expected: see information on the revision

Actual: get a 404

**Comment by gbaz** [comment]
Weird. The link currently points to http://hackage.haskell.org/package/mtl-2.2.1/revisions/ (note the lack of duplication in the path name) and that does provide rev info...

**Comment by gbaz** [comment]
Ok, I'm told we did deploy briefly with a bad link there, and it was hotfixed rapidly. So I'm going to mark this as resolved...
