### ISSUE TITLE
Registration emails getting caught by spam filters

### ISSUE THREAD

**Issue by quasicomputational** [haskell/hackage-server#641]
I just registered for a Hackage account, and I found that the confirmation email was caught by GMail's spam filter. Mail from Hackage is most definitely not spam, so that's sub-optimal. Maybe there's some misconfiguration (e.g., missing DKIM or SPF) that's making GMail suspicious, or the IPs it's sending from have a bad history?

**Comment by gbaz** [comment]
Is there any information you can provide from gmail as to why i thought it was spam? often there are some details provided...

**Comment by quasicomputational** [comment]
Sorry---there was some, but it didn't survive the clicking of the 'not spam' button. I just tried to reproduce with a test account, but that went straight to inbox (which makes sense, since clicking 'not spam' ought to be a very strong signal).

**Comment by gbaz** [comment]
That's good actually. When things go really wrong, then clicking "not spam"
doesn't suffice to override the filter!

On Tue, Nov 7, 2017 at 2:17 PM, quasicomputational <notifications@github.com

**Comment by gbaz** [comment]
Closing as there haven't been more reports since.
