### ISSUE TITLE
Docs fail to build for packages that require GHC 8.2.1

### ISSUE THREAD

**Issue by tfausak** [haskell/hackage-server#645]
I uploaded a package that requires `base >= 4.10.1` and the docs failed to build because it wants to use `base-4.9.1.0` (GHC 8.0.2).

https://hackage.haskell.org/package/rattletrap-3.1.1/reports/3

**Comment by gbaz** [comment]
I upgraded the builder to 8.2.2 a few days ago. New packages won't have this problem. We need to manually remove any older packages we want to retry from the failed queue. I can leave this ticket open for them for now -- will clean the queue again this evening or tomorrow.

**Comment by tfausak** [comment]
Oh, great! Thanks!

**Comment by gbaz** [comment]
Closing, as this should all be sorted afaik.
