### ISSUE TITLE
HTTP error 500 on https://hackage.haskell.org/package/hermes

### ISSUE THREAD

**Issue by koterpillar** [haskell/hackage-server#649]
https://hackage.haskell.org/package/hermes responds with:

```
Happstack 7.5.0.1
Something went wrong here
Internal server error
Everything has stopped

The error was "/srv/hackage/var/server/state/blobs/ba/ba13f08a1e7e99e56a3ab03f01ab7840: openBinaryFile: does not exist (No such file or directory)"
```

https://www.stackage.org/package/hermes says "Deprecated".
https://hackage.haskell.org/package/hermes-1.3.4.3/hermes.cabal shows the Cabal file contents.

**Comment by gbaz** [comment]
cf: https://github.com/haskell/hackage-server/issues/436

arguably we should just not show the page at all?

**Comment by gbaz** [comment]
We now intercept the request to this page and return error 451, with the message "unavailable for legal reasons" which sounds good to me?
