### ISSUE TITLE
Support for reference-style links in readme

### ISSUE THREAD

**Issue by rcook** [haskell/hackage-server#650]
The `README.md` file here http://hackage.haskell.org/package/hidden-char-0.1.0.1 is rendered correctly (see under "Readme for hidden-char-0.1.0.1").

I recently published an updated version of this package at https://hackage.haskell.org/package/hidden-char-0.1.0.2 and the `README.md` content is garbled. Specifically the hyperlinks at the bottom are output to the web page and not rendered as links.

**Comment by hvr** [comment]
You seem to be used footnote-links which seems aren't supported by our markdown processor; hackage currently uses http://hackage.haskell.org/package/cheapskate

**Comment by gbaz** [comment]
cf: https://github.com/haskell/hackage-server/issues/565

I would suggest closing this and adding a comment there as to footnote-links as another feature that it may be worth extending cheapskate with?

**Comment by hvr** [comment]
@gbaz fwiw, I'm keeping an eye on @mrkkrp's https://github.com/mrkkrp/mmark#performance which looks very promising IMO (but it's still evolving)

**Comment by mrkkrp** [comment]
FYI, it's called *reference-style links*:

* http://spec.commonmark.org/0.28/#reference-link
* http://spec.commonmark.org/0.28/#link-reference-definitions

MMark supports these fully, but it has [other compatibility issues](https://github.com/mrkkrp/mmark#quick-start-mmark-vs-github-flavored-markdown) with GitHub-flavored markdown and it's not quite stable enough yet for Hackage. This may change in the future though.

**Comment by gbaz** [comment]
ok closing in favor of the issue i opened on cheapskate

**Comment by gbaz** [comment]
Whoops, reopening as cheapskate isn't going anywhere.
