### ISSUE TITLE
Packages by download not linked to anymore?

### ISSUE THREAD

**Issue by sol** [haskell/hackage-server#656]
I couldn't find a link to https://hackage.haskell.org/packages/top anymore.  Was this removed?  If yes, what is the reason?

**Comment by gbaz** [comment]
The /top and /names links were removed because they are superseded  by the new /browse interface that allows sorting by download, etc. directly.

**Comment by sol** [comment]
@gbaz from my limited experience with the `/browse` interface it does not work that well for me.  It's not only horribly slow but also has data issues (initially I thought due to caching, but for e.g. `hspec` it shows `2017-06-16` as `Last U/L`).  I don't intend to offend anybody, but I would rather not use this interface in its current form + I would also prefer that my packages not be misrepresented on that page.

Is there a publicly visible deploy log for `hackage-server`?  Specifically, I would be interested what revision is currently live?  Do we do CD (say can I assume that `master` is always live)?  I had trouble finding the corresponding commits that introduced those changes.

**Comment by gbaz** [comment]
We've turned on caching for it to improve load speeds. 

The last u/l field not updating is a bug -- and we should fix it! Thanks for reporting.

No we don't do CD. We don't deploy from master, rather we deploy from the central-server branch: https://github.com/haskell/hackage-server/tree/central-server

here's the pr for these changes.

**Comment by gbaz** [comment]
Whoops, didn't list the PR: https://github.com/haskell/hackage-server/pull/552

Also, I created a new ticket to track the u/l field updating issue: https://github.com/haskell/hackage-server/issues/657

I think that suffices to close this ticket out..?
