### ISSUE TITLE
Please delete distribution "Tumbleweed"

### ISSUE THREAD

**Issue by peti** [haskell/hackage-server#664]
I no longer use the distribution name "Tumbleweed". Instead, I prefer the distribution name "openSUSE". I tried executing

    curl --user USER:PASS -X DELETE http://hackage.haskell.org/distro/Tumbleweed

but got a permission denied error.

**Comment by gbaz** [comment]
Done. In general this is probably something best accomplished by emailing the `admin@hackage.h.org` alias in the future :-)
