### ISSUE TITLE
Collapsable metadata sections on package page

### ISSUE THREAD

**Issue by gbaz** [haskell/hackage-server#667]
Metadata should be able to be collapsed en masse.

Also note, from reddit:  "Some of the meta information can also be summarised differently. For example, there could be a small numeric badge saying how many dependency which can then be clicked and expanded to the full glory. Similarly for older versions, it could be a badge saying (42 older versions). Even license information can be badged."

**Comment by hvr** [comment]
I'm strongly against hiding/compacting dependency information by default, as that's one of the core things I look for when looking at a package on Hackage. Having to manually expand it would be a big regression for me.

**Comment by gbaz** [comment]
Another common suggestion on the thread seems to have been multicolumn as per https://www.npmjs.com/package/twitter (or perhaps with the metadata on the lhs instead?)

**Comment by gbaz** [comment]
resolved by the two-col layout imho.
