### ISSUE TITLE
Convenience - view GitHub source

### ISSUE THREAD

**Issue by kanishka-azimi** [haskell/hackage-server#672]
For each haskell module, jumping to the GitHub source file.. this would assume some way to get commit information uploaded with each Hackage upload, to know which commit to link to, or could just default to master branch.

Feel free to close if off topic or not desired.

**Comment by gbaz** [comment]
What is the advantage of this over the source view from haddocks that we already have?

**Comment by kanishka-azimi** [comment]
Normally I use that, and then one of functions is actually defined in a deeper module that isn't exposed

**Comment by kanishka-azimi** [comment]
Alternatively, you could implement a top bar similar to github which would allow moving up/down in source tree, or hyperlink the imports that referencing modules in the same package

**Comment by gbaz** [comment]
The docbuilder should move towards hyperlinked-source sometime soon as per https://github.com/haskell/cabal/issues/4613, so it sounds like that would suffice?

Also, note that the `[browse]` link next to the `.tar.gz` tarball  allows one to browse through all the included source-files of a package...

**Comment by kanishka-azimi** [comment]
Hyperlink should address this.

Having some small folder tree view or cookie crumb trail to where I am would probably stop me from ever going to github.
