### ISSUE TITLE
Explicitly state that the PVP is optional

### ISSUE THREAD

**Issue by tfausak** [haskell/hackage-server#673]
Currently Hackage lists several guidelines for packages. The first of them is that "all packages should follow the Package Versioning Policy (PVP)". The word "should" is an `<abbr>` that, when hovered over, shows this definition:

> [RFC2119] The word 'should' is intended to denote that there may exist valid reasons in particular circumstances to ignore a particular item, but the full implications MUST be understood and carefully weighed before choosing a different course

Here is a screenshot for posterity:

![screen shot 2018-02-18 at 1 30 46 pm](https://user-images.githubusercontent.com/408753/36355375-3c099616-14b0-11e8-83f7-48a6a2820cc1.png)

I am not a fan of the PVP (see for example my [Problematic versioning policy](http://taylor.fausak.me/2016/12/28/problematic-versioning-policy/) post) and would like to see the wording of this guideline change. In particular I would like it to be clearer that the PVP is recommended by Hackage but is by no means a requirement for uploading a package. @snoyberg recently published a post ([Haskell ecosystem requests](https://www.snoyman.com/blog/2018/02/haskell-ecosystem-requests#pvp-adherence-is-optional)) asking for the same thing, so I figured I would open an issue to kick off an official discussion. 

I don't know the exact wording I would like to see, but for the sake of discussion, something like this would be good to me:

> The Hackage trustees recommend that packages follow the Package Versioning Policy (PVP), but it is not required.

**Comment by snoyberg** [comment]
I strongly support this proposal.

**Comment by tomjaguarpaw** [comment]
As a point of information, under [RFC2119](http://www.ietf.org/rfc/rfc2119.txt) "SHOULD" is the modal verb form of the adjective "RECOMMENDED".  As far as the RFC is concerned the current text "all packages should follow the Package Versioning Policy (PVP)" has exactly the same meaning as @tfausak's proposed text "The Hackage trustees recommend that packages follow the Package Versioning Policy (PVP), but it is not required."

I happen to feel that the RFC's choice of words is unfortunate.  "Should" has a stronger connotation than "recommended" in everyday English.  Nonetheless, that is what the RFC says.

**Comment by tfausak** [comment]
I also think the word "should" is unfortunate when you're not reading something in "RFC mode", so to speak. That's why I'm proposing we change the wording to be clearer, even though it technically means the same thing as the current wording.

**Comment by tfausak** [comment]
I can't find the associated commit, but at some point the display of the package guidelines changed:

![image](https://user-images.githubusercontent.com/408753/73136283-e3e4bc80-4019-11ea-89d9-fce7ce1a073b.png)

The "curated" link takes you to: <https://hackage.haskell.org/upload#versioning_and_curation>. And hovering over "should" displays the RFC text. 

Looks good to me. Thanks!
