### ISSUE TITLE
Drop 7.8 and 7.6 support from travis ci?

### ISSUE THREAD

**Issue by gbaz** [haskell/hackage-server#678]
Tired of these needless build failures. I don't see any reason to keep supporting versions that old with the current codebase...

**Comment by gbaz** [comment]
we should probably bump the dep on `base` to exclude them as well.

**Comment by hvr** [comment]
hrm... I put quite some effort into making it possible to support pre-AMP :-/

**Comment by gbaz** [comment]
I mean I'm fine if you want to keep doing that. I just don't think that there's going to be a broad pre-AMP userbase that wants to use hackage-server in particular...

**Comment by hvr** [comment]
If you prefer, we can place the 7.6 and 7.8 on "can fail" in travis, and I'll keep fixing em up; I use this a bit of a canary for dogfooding cabal new-build's support on a non-trivial project for older GHCs

**Comment by gbaz** [comment]
If you make that travis change I'll be happy to consider this resolved.

**Comment by hvr** [comment]
I quickly edited it via the webui... I think this should do it

**Comment by gbaz** [comment]
not sure if it works -- still getting failing checks at e.g. https://github.com/haskell/hackage-server/pull/676

**Comment by hvr** [comment]
@gbaz was #676 rebased against e29138c ?

**Comment by gbaz** [comment]
Ah -- gotcha, this only kicks in with the rebase. Yeah, the newer PR has things under allowed failures as desired. Thanks.

**Comment by hvr** [comment]
oh, now I see; that's because it's a different branch
