### ISSUE TITLE
Custom filtering for /browse and /search pages

### ISSUE THREAD

**Issue by gbaz** [haskell/hackage-server#680]
Something along the lines of https://datatables.net/examples/plug-ins/range_filtering except with boolean-valued checkboxes, etc. These settings should be able to be stored client-side as well.

**Comment by dbaynard** [comment]
It would be good to show latest versions on the search page (I haven't investigated whether this is just a ui thing or if there's significant backend work involved, though given the 'last updated' field is displayed I'd imagine the former).

**Comment by gbaz** [comment]
i think this is resolved by https://github.com/haskell/hackage-server/pull/1021
