### ISSUE TITLE
Revision feed GUIDs aren't unique

### ISSUE THREAD

**Issue by wiz** [haskell/hackage-server#683]
Consider following feed item:

```
<item>
    <title>refresht 0.1.1.0</title>
    <link>https://hackage.haskell.org/package/refresht-0.1.1.0/revisions</link>
    <guid isPermaLink="true">https://hackage.haskell.org/package/refresht-0.1.1.0/revisions</guid>
    <pubDate>Wed, 21 Feb 2018 15:21:20 UTC</pubDate>
    <description>&lt;i&gt;Revised by HiromiIshii, Wed Feb 21 15:21:20 UTC 2018.&lt;/i&gt;&lt;p&gt;Revision #1</description>
</item>
```

The link points to the human readable list of **all** revisions with a change log and that's great.
However, GUID field is the same link and actual revision number isn't present there, making GUID collisions very likely. Someone has to upload two revisions in same 48h window. And, anyway, they're not unique.

That means I'd have to consider extra fields like `pubDate` or parse `description` to check if I'm seeng a new revision or not.

I propose using the cabal URL for that revision as GUID. I.e. https://hackage.haskell.org/package/refresht-0.1.1.0/revision/1

**Comment by gbaz** [comment]
Fair point. Do you feel up to submitting a PR?
