### ISSUE TITLE
Hackage is down

### ISSUE THREAD

**Issue by leohaskell** [haskell/hackage-server#692]
<img width="415" alt="screen shot 2018-03-16 at 14 46 33" src="https://user-images.githubusercontent.com/3736978/37521290-e479bd9e-2928-11e8-89e5-081ac574cd61.png">

**Comment by leohaskell** [comment]
Seems like it's already up and running.

**Comment by hliu1020** [comment]
down again...

**Comment by gbaz** [comment]
Yes, see http://status.haskell.org
