### ISSUE TITLE
new favicon to match new theme

### ISSUE THREAD

**Issue by gbaz** [haskell/hackage-server#707]
It would be nice to update the favicon. Requires someone with a modicum of graphic skill (i.e. not me). @NunoAlexandre do you think you could take a crack at it?

**Comment by gbaz** [comment]
hmm... should we just use the one from haskell.org? https://www.haskell.org/static/img/favicon.ico?etag=-4XQV6tt

**Comment by NunoAlexandre** [comment]
To me, we could indeed just use that one.

**Comment by phadej** [comment]
Small comment: at work we use different color logos for different "subsites". I'd also prefer Hackage to stand out of everything else Haskell related in tabbar

**Comment by NunoAlexandre** [comment]
@gbaz and @phadej, what do you think of this favicon, following the idea of Hackage's signature `[Package]`?


<img width="75" height="75" src="https://user-images.githubusercontent.com/7075260/37822537-0a602ddc-2e87-11e8-9f16-344b4ec44009.png"/>

Example in action:

![inaction](https://user-images.githubusercontent.com/7075260/37822654-57498530-2e87-11e8-88f2-05931547e1bb.png)

**Comment by gbaz** [comment]
Nice idea!
