### ISSUE TITLE
Publishing a candidate does not delete the candidate

### ISSUE THREAD

**Issue by edsko** [haskell/hackage-server#71]
This is strange, because this leaves the database in a state where we have both version `X.Y.Z` of a package in the packages DB and in the candidates DB. There are some provisions in the code for this (`publishCandidate` takes a `doDelete` argument), so I'm not sure what the intention is. But current behaviour seems wrong to me.

Pinging @dcoutts .

**Comment by hvr** [comment]
See #558

**Comment by gbaz** [comment]
resolved by https://github.com/haskell/hackage-server/pull/895
