### ISSUE TITLE
Left-align metadata identifiers

### ISSUE THREAD

**Issue by toonn** [haskell/hackage-server#716]
The lack of a clear distinction between description and metadata makes the pages harder to read for me.
This [comment](https://github.com/haskell/hackage-server/issues/703#issuecomment-374483919) conveniently has two images that show the problem, this is specifically about the readme background color but the effect's the same with a long description, cf. the lens package.

In the first image the border clearly seperates the metadata and all is well, in the second image the lack of a border makes it hard for me to read, the metadata identifiers (Author, Repository, etc.) look like they're part of the text, even though they're bold.

I'd like to suggest left-aligning the identifiers, which would create the impression of a border and thus a clearer seperation.

**Comment by gbaz** [comment]
Here is how it looks right-aligned
![image](https://user-images.githubusercontent.com/1125849/37693139-11ec8612-2c94-11e8-81a8-7fffdc62eb0e.png)

And left-aligned
![image](https://user-images.githubusercontent.com/1125849/37693150-28539bb6-2c94-11e8-9fed-03b1cff6d02a.png)

When it goes to an inline-table at small-enough size, however, I think left-aligned is better:

![image](https://user-images.githubusercontent.com/1125849/37693212-8b844dca-2c94-11e8-9ad8-01d64ea1c199.png)

vs.

![image](https://user-images.githubusercontent.com/1125849/37693220-970aa004-2c94-11e8-8784-952abefc99fa.png)

Not sure what to do about that. I lean towards right-aligned being better in the sidebar. Perhaps we can swap when the table goes inline? Or would that be terribly disconcerting?

**Comment by lspitzner** [comment]
I think left-aligning would not sufficiently serve to separate the two columns. I prefer left-align for one-column and right-align for the two-column case.

**Comment by gbaz** [comment]
I think the vertical table style in https://github.com/haskell/hackage-server/pull/731  would resolve this?

![image](https://user-images.githubusercontent.com/1125849/37944527-f039526a-3149-11e8-88e2-28013dd1da11.png)

**Comment by toonn** [comment]
Yep, probably would. There's still talk in that issue thread of a "horizontal style" with right-aligned headers though.

**Comment by gbaz** [comment]
Right. My suggestion was to do that in the case where the size is small enough that the table moves from two-col to inline, in which case there would be no need of a clearer border, as there would only be a one-col layout.

**Comment by toonn** [comment]
Yes, but nuno seemed to disagree and push for the more confusing style.

**Comment by NunoAlexandre** [comment]
@toonn what is confusing about it?

**Comment by toonn** [comment]
It's very hard for me to seperate it from the body text. It looks like the body runs up to and including the headers. The weird amount of whitespace and the boldness don't matter. The metadata itself is clearly seperated because of the illusory border.
Note that when you stare at the tiny examples from gbaz I don't get the confusion, only when I'm actually reading some docs in this layout, it's a feeling of not knowing where to go more or less, going on seems wrong but so does going to the start of the next line.

**Comment by gbaz** [comment]
To be clear -- the new vertical alignment proposal resolves this, correct? As long as we apply it uniformly?

**Comment by toonn** [comment]
Yes, vertical alignment would solve this, so would left-aligning the headers or a border.

**Comment by gbaz** [comment]
resolved by latest deploy
