### ISSUE TITLE
Don't use nonbreaking hyphens (instead use a nowrap span)

### ISSUE THREAD

**Issue by gbaz** [haskell/hackage-server#720]
as per https://www.reddit.com/r/haskell/comments/85tuly/latest_hackage_deployment/dw22iyp/

> I've noticed a strange little annoyance with the redesign. Hyphens seem to be getting turned into hyphen-like characters that are not your run of the mill hyphens.
> 
> For example, go to http://hackage.haskell.org/package/uuid and CTRL+F for uuid-types. As you can see, it's right there in the dependency list, but CTRL+F won't find it. That's because the text written is actually uuid‑types. Yes that's a different hyphen. It is "U+2011 : NON-BREAKING HYPHEN", instead of "U+002D : HYPHEN-MINUS {hyphen or minus sign}". I can understand that we don't want package names to be broken up across multiple lines, but still.
> 
> The hyperlink is thankfully correct: http://hackage.haskell.org/package/uuid-types
> 
> Since I tend to CTRL+F for dependencies on package pages once in a while, and many packages have hyphenated names, I find this quirk rather annoying.

**Comment by phadej** [comment]
The dependencies list will be very ugly.

**Comment by phadej** [comment]
I don't remember if one can create non breakable "hbox"s in HTML, surely can, but how?

**Comment by gbaz** [comment]
we can just use spans with nowrap set on the text, i think: https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

**Comment by gbaz** [comment]
I'll toss into this issue too the issue that we don't have email addresses break at all. Today I Learned about overflow-wrap which is better than just strict word-wrap for these cases: https://developer.mozilla.org/en-US/docs/Web/CSS/overflow-wrap
