### ISSUE TITLE
Strange warning after uploading

### ISSUE THREAD

**Issue by lspitzner** [haskell/hackage-server#732]
I see this after uploading [brittany-0.10.0.0](https://hackage.haskell.org/package/brittany-0.10.0.0)

>There were some warnings:
>
> * Packages relying on Cabal 1.12 or later should specify a version range of the form 'cabal-version: x.y'. Use 'cabal-version: 1.18'.

while both the local `cabal check` (2.0.0.1) comes clean and the package contains `cabal-version:        >=1.18`.

**Comment by gbaz** [comment]
Hackage server uses warnings from the `Cabal` 2.2 package now. c.f. https://github.com/haskell/cabal/issues/5108 for more details.
