### ISSUE TITLE
Favicon looks pretty ugly

### ISSUE THREAD

**Issue by ndmitchell** [haskell/hackage-server#737]
Can I suggest that you remove the `[ ]` bits at 16x16, since it makes it pretty hard to see any of the details. Kinda looks like a blurry smudge.

![image](https://user-images.githubusercontent.com/1651197/38329996-5317c124-3847-11e8-8fe4-38a29536cd2d.png)

Other than that the overall site looks pretty beautiful!

**Comment by Wizek** [comment]
Yeah, I believe this was mainly designed with high-DPI screens in mind, which AFAIK is not yet used by a majority of people. Could be made much more legible with hand-crafting a pixel-perfect 16x16 version that wouldn't be smudged by image-downscaling.

@NunoAlexandre what do you think about this issue and #739? (I'm more bothered by the latter, but only wanted to ping you once to ask you about both.)

**Comment by NunoAlexandre** [comment]
Hi @ndmitchell 

The goal of the favicon is to identify the website. It's not a design crafted favicon, but I can't see what is _ugly_ about it either. 

Why would you expect to see a lot of detail in it? This is an honest question. Are you not able to see that it is the Haskell logo in between or would you just like to see it bigger? 

The motivation to not have just the Haskell logo was this observation: https://github.com/haskell/hackage-server/issues/707#issuecomment-375086961

> Other than that the overall site looks pretty beautiful!

Thanks, Niel :) 

Let me have your feedback on my questions and response to be better able to help.

**Comment by NunoAlexandre** [comment]
@ndmitchell and @Wizek,

We could also have a new favicon such as the following instead:

![favicon](https://user-images.githubusercontent.com/7075260/38437926-457a9224-39d9-11e8-89b9-adf1617b316a.png)

# Preview

You can see how it looks like and how it compares to the current one.

Light mode:
![tablight1](https://user-images.githubusercontent.com/7075260/38437975-64e863fc-39d9-11e8-9d4c-6af0c473688c.png)

Dark mode:
![tabdark1](https://user-images.githubusercontent.com/7075260/38437968-5e5ae690-39d9-11e8-87ab-8aec0889eb26.png)
![tabdark2](https://user-images.githubusercontent.com/7075260/38437973-6269f230-39d9-11e8-8174-db9ea6303460.png)


What do you guys think? 
@gbaz can you also have a look to this? :)

**Comment by gbaz** [comment]
Looking at my zoo of open tabs, I see that only a few that use a letter as a favicon, and they're all super-well branded with regards to that letter (facebook, g+, ycombinator news, wikipedia, nytimes). Almost everyone else uses a symbol. So I think a symbol is good -- I guess the issue is just a) size, and b) background. 

![image](https://user-images.githubusercontent.com/1125849/38438834-aced224e-39a9-11e8-80e0-8aa5d9af02d6.png)

So here is my strawman idea -- use the haskell logo just as we do in the hackage header (snipped above). This means it comes with a background (so it shows up well on light or dark) and also is larger because it doesn't have the braces. I think the braces are a great idea for hackage branding in general (maybe they can find reuse on a prettied-up homepage), but yeah, I don't see how they fit well into a favicon at constrained size.

**Comment by ocramz** [comment]
I agree with Gershom, using the Haskell logo as favicon would look great and be more readable than the current one.

**Comment by Wizek** [comment]
I like the stylized λ + `>>=` one, I hope we can make that work somehow.

I also like the intention behind `[ ]`, however, to be closer to the truth, shouldn't it be `Map Name Package`? 😄 

Has anyone attempted to create a 16x16 pixel-art version of the `>λ=` logo (perhaps with the square brackets around)? I still have a hunch that it could be made to work even in that space constraint.

**Comment by ndmitchell** [comment]
My complaint is the icon is shown at small size and the current one is loaded with detail - even if pixels can represent the detail it won't look great to humans. All other favicons on the web are conceptually simpler - less lines, just one single thing. Just deleting the [ ] bit would be enough to satisfy me - the rest is design which I am not qualified to comment in. 

That said, I quite like Gershom's one...

**Comment by Wizek** [comment]
I like @gbaz's one as well.

**Comment by NunoAlexandre** [comment]
I also like Gershom's idea better. simple and straight 👌

**Comment by NunoAlexandre** [comment]
@gbaz @Wizek  @ocramz @ndmitchell 

Can you have a look at the favicon in this preview? https://nunoalexandre.com/pets/hackage/home.html

**Comment by Wizek** [comment]
Quite nice, I like it at first glance! 

![image](https://user-images.githubusercontent.com/491672/38464915-b146b63a-3b15-11e8-972c-8887aeaa10ed.png)

**Comment by ndmitchell** [comment]
I like it! Gentle suggestion to round the corners a bit, e.g. like Blogger/Wikipedia/Trello all do (just from the 6 tabs I've got open now).

**Comment by NunoAlexandre** [comment]
@ndmitchell I thought the same actually :) 
I like it: https://nunoalexandre.com/pets/hackage/home.html

What do you think?

**Comment by ndmitchell** [comment]
👍 ❤️
