### ISSUE TITLE
New favicon looks almost invisible with dark tab background style.

### ISSUE THREAD

**Issue by Wizek** [haskell/hackage-server#739]
![image](https://user-images.githubusercontent.com/491672/38405466-50cde266-3970-11e8-994b-c71275427edb.png)

Please add a white/light outline/background, or fix some other way.

Potentially related:
- https://github.com/haskell/hackage-server/issues/737
- https://github.com/haskell/hackage-server/pull/731
- https://github.com/haskell/hackage-server/issues/707

**Comment by NunoAlexandre** [comment]
We don't support dark themes.

I am joking! Thanks for reporting this.
I gave it a try with other haskell websites, like the [haskellbook](https://haskellbook.com) and the [haskell.org](https://haskell.org), and the same happens. 

I will see what I can do :+1:

**Comment by Wizek** [comment]
> We don't support dark themes.

You may not believe what a gloom&mdash;even if only for a moment&mdash;has shadowed over me while reading this.

It's a bit of a cruel thing to joke with `wontfix`, I get that reaction more often than I'd like when I report stuff, it's only serious then.

But all is well, my inner balance almost fully restored when I continued reading.

> haskellbook and the haskell.org

The big difference in comparison to those is that I visit hackage much more often, I often have many tabs open of it, some even pinned for some time. I very rarely visit haskellbook and haskell.org.

> I will see what I can do 👍

Thanks! If you wish I can also try putting a white outline around the logos given the original PSD(?).

**Comment by NunoAlexandre** [comment]
> You may not believe what a gloom—even if only for a moment—has shadowed over me while reading this.

Ahah sorry, I hope you could have laughed a bit as well in the end ;)

> The big difference in comparison to those is that I visit hackage much more often, I often have many tabs open of it, some even pinned for some time. I very rarely visit haskellbook and haskell.org.

Good point and argument, same thing here. I am addressing this in this other issue: #737

**Comment by NunoAlexandre** [comment]
A fix was merged to master today. See more in the referenced PR above.
Thanks for reporting, @Wizek!
