### ISSUE TITLE
Hackage becomes unresponsive when a package is being uploaded

### ISSUE THREAD

**Issue by maoe** [haskell/hackage-server#747]
Recently I uploaded a few packages to Hackage and I got 504 Gateway Time-out on both uploads.

Here is the terminal output of the second upload:
```
% cabal upload --publish dist/sensu-run-0.5.0.1.tar.gz
Uploading dist/sensu-run-0.5.0.1.tar.gz...
Error uploading dist/sensu-run-0.5.0.1.tar.gz: http code 504
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>
```

I suspect Hackage becomes unresponsive when a package is being uploaded and it continues for a minute or two after the timeout. Earlyer today my coworker saw very slow Hackage and it seemed that some other package was being uploaded around that time.

**Comment by gbaz** [comment]
Thanks for the observation! I think this is because we're not running it multicore since the rebuild -- I'd noticed the blips, but hadn't correlated them with uploads. We definitely plan to turn back on the multicore real soon.

**Comment by maoe** [comment]
That's good to know. Thanks for the quick response and your hard work!

**Comment by gbaz** [comment]
optimistically closing.
