### ISSUE TITLE
Windows line endings (CRLF) affect HTML source code rendering?

### ISSUE THREAD

**Issue by mpilgrem** [haskell/hackage-server#750]
#460 and #549 indicate that this sort of an issue arose and was fixed in the past, but it seems to me to be a current problem with source files (see, for example, https://hackage.haskell.org/package/ansi-terminal-0.8.0.3/docs/src/System.Console.ANSI.html, which renders with a blank line between each line of source code).

**Comment by gbaz** [comment]
Those issues were about changelog rendering, which is controlled by hackage. This is about source code rendering, which is controlled by haddock. Can you file the issue at https://github.com/haskell/haddock/issues ?

**Comment by mpilgrem** [comment]
Thanks - will do.

**Comment by gbaz** [comment]
Thanks! I'll close this in favor of that.
