### ISSUE TITLE
Hackage Account Confimation email issue

### ISSUE THREAD

**Issue by waivio** [haskell/hackage-server#759]
The Hackage Account Confirmation email gives a http:\\ link rather than a https:\\ link.
This is a problem because the initial login page is not secure.

**Comment by waivio** [comment]
Perhaps a sensible default for uriScheme in the defaultServerConfig the would be: uriScheme = "https:"

**Comment by gbaz** [comment]
We can't do it in the defaultConfig, but we could do it for the default config in the central-server branch.

I think we had this set manually prior to the rebuild.

**Comment by gbaz** [comment]
fixed by https://github.com/haskell/hackage-server/commit/5f46b2bb5b759aee6fe5bcb595c52e2fcccfc22e

**Comment by andrew-lei** [comment]
I was emailed an http link rather than an https link. Is the fixed code running on hackage.haskell.org?
