### ISSUE TITLE
update to work with 8.4.2

### ISSUE THREAD

**Issue by gbaz** [haskell/hackage-server#760]

**Comment by hvr** [comment]
don't you mean GHC 8.4.3? :)

**Comment by gbaz** [comment]
if malcolm doesn't reply should we just request a nmu?

**Comment by mitchellwrosen** [comment]
It works with 8.4.2 now, but not 8.6 (a few upstream monads do not have `MonadFail` instances)

**Comment by phadej** [comment]
@mitchellwrosen which?

**Comment by mitchellwrosen** [comment]
@phadej Update from acid-state, and ServerE (sp?) from happstack (sorry, away from my computer atm)

**Comment by phadej** [comment]
https://matrix.hackage.haskell.org/#/package/acid-state suggests `acid-state` is ok with GHC-8.6?

**Comment by phadej** [comment]
(I know a person who recently built `hackage-server` with GHC-HEAD, so there shouldn't be much work to do!)

**Comment by mitchellwrosen** [comment]
It does not require it's own MonadFail instance (due to partial pattern
match in do-notation)

**Comment by gbaz** [comment]
we're updated all the way to 8.10.4 now
