### ISSUE TITLE
Remove lowercase-C "cabal" package

### ISSUE THREAD

**Issue by tom-bop** [haskell/hackage-server#773]
Now that https://github.com/haskell/hackage-server/pull/761 has been closed (so a malicious user couldn't re-upload a "cabal" package), and https://github.com/haskell/cabal/4778 has been merged (So the users of newer versions of `cabal-install` will get a nice message: "There is no package named 'cabal'. However, the following package name exists: 'Cabal'."), should we remove this package from Hackage?:

https://hackage.haskell.org/package/cabal

cc @cartazio

**Comment by hvr** [comment]
Well, hard removal of packages from the primary index is a very disruptive operation for several technical reasons; there's been some discussion I can't find right now about variants for implementing support for entry-removal in hackage-security, but that's evidently not been tackled yet.

Moreover, there's plans to restructure things and finally fix the wart that `exe:cabal` ought to be installable via `cabal install cabal` (see haskell/cabal#3965) and I intend to finally move forward with that as it looks like the targetted cabal 3.0 milestone is probably going to be released end of 2018. At that point, we'd end up with a lower-case `cabal` package index entry anyway; so there's little benefit to remove the `cabal` entry now only to re-add it back later again.
