### ISSUE TITLE
Broken Link in Existential Types

### ISSUE THREAD

**Issue by kammitama5** [haskell/hackage-server#780]
Not sure if this is the best place to leave issue, but these two links were broken

```
http://hackage.haskell.org/trac/haskell-prime/wiki/ExistentialQuantification
```
and 

```
http://hackage.haskell.org/trac/haskell-prime/wiki/ExistentialQuantifier
```
found on 

```https://wiki.haskell.org/Existential_type#Dynamic_dispatch_mechanism_of_OOP```

six lines up from the bottom of the page.

**Comment by gbaz** [comment]
the old tracs that used to host things on hackage are long gone. Not sure what's to be done here except fix the wiki links directly to wherever the newer content may be. (likely somewhere here: https://gitlab.haskell.org/haskell/prime/-/wikis/home)
