### ISSUE TITLE
Unknown extensions: NoStarIsType on package upload

### ISSUE THREAD

**Issue by expipiplus1** [haskell/hackage-server#788]
I encounter a "400 Bad Request" error when trying to 'cabal upload'; Cabal tells me "Unknown extensions: NoStarIsType".

I do indeed use the NoStarIsType extension in my package. The use of this extension is guarded with a GHC version check.

The code for my package can be found here: expipiplus1/vector-sized

See also: https://github.com/haskell/hackage-server/issues/140
See also: haskell/cabal#1050

**Comment by hvr** [comment]
`NoStarIsType` is an extension that isn't yet in any released GHC; we traditionally don't allow uploading such packages to Hackage before it's not part of a stable GHC

**Comment by mstksg** [comment]
Hi :) Any news on a potential timeline for support for GHC 8.6 extensions on hackage?  I still get the same errors when uploading on my end.

**Comment by expipiplus1** [comment]
Is it possible to remove this restriction when the extension usage is
guarded by a ghc version check?

**Comment by turion** [comment]
GHC 8.6.2 is now officially released since 5 days. Is this resolved?

**Comment by hvr** [comment]
@turion not yet unfortunately but I've planned to get this done the upcoming weekend

**Comment by hvr** [comment]
This ought to be resolved by today's hackage redeployment; please reopen if this shouldn't be the case
