### ISSUE TITLE
Fix link colors

### ISSUE THREAD

**Issue by ad-si** [haskell/hackage-server#793]
The coloring of links is exactly opposite to the default coloring.
I'd consider this a bug ^^.

<img width="480" alt="screen shot 2018-10-13 at 16 37 59" src="https://user-images.githubusercontent.com/36796532/46907735-97e63500-cf06-11e8-95b9-df4e8de0b925.png">
 
It confuses me every time.

**Comment by gbaz** [comment]
We debated link colors to death here:  https://github.com/haskell/hackage-server/pull/648

**Comment by ad-si** [comment]
> We debated link colors to death here: #648

? I didn't see a single comment on link colors.
Don't get me wrong, I really like the new design and the colors in general.
The colors for visited and unvisited links just happen to be misleading.

> If someone has a concrete proposal that works with the current design, we can discuss it.

Switch the colors for visited and unvisited links. This wouldn't change the overall aesthetics, but fix the problem.

**Comment by ad-si** [comment]
This would be similar to coloring the ok button red and the cancel button green. The colors are so ingrained, it's just no a question of aesthetics anymore, but about usability. For the existence of browsers unvisted links have been blue and visited ones have been purple and this should not be changed (especially not switched).
