### ISSUE TITLE
Make fact of deprecation clearer?

### ISSUE THREAD

**Issue by tomjaguarpaw** [haskell/hackage-server#794]
I erroneously filed [an issue on `uuid`](https://github.com/haskell-hvr/uuid/issues/43) because I could not tell from the Hackage web UI that `binary-0.9.0.0` and `-0.10.0.0` are deprecated.  If you navigate to https://hackage.haskell.org/package/binary-0.10.0.0 you will not see any evidence that it is deprecated. The only slight clue is that the link to `0.9.0.0` has HTML class `deprecated`.

Could the fact of deprecation please be made blindingly obvious on the deprecated version's page?

**Comment by hvr** [comment]
Duplicate of #372

**Comment by tomjaguarpaw** [comment]
Looks like it.  Thanks.
