### ISSUE TITLE
Can't upload to hackage: Duplicate module found

### ISSUE THREAD

**Issue by stites** [haskell/hackage-server#795]
I have an exposed module which is exported conditionally with a cabal flag with a cabal file that is generated via the dhall-lang/dhall-to-cabal project (latest version: 1.3.1.0). The output of dhall-to-cabal compiles to cabal perfectly fine and I can build the project with `cabal v2-build`, but when attempting to upload a Package Candidate, I get `Duplicate modules in library: Torch.FFI.TH.NN.Double`.

Is there a mismatch between cabal and hackage-server that needs to be addressed or should I be filing an issue at the dhall-to-cabal repo?

**Comment by gbaz** [comment]
Building the project with cabal does not force the full range of checks.
You should see if it comes up clean on a local `cabal check` with a
current/recent cabal.

**Comment by hvr** [comment]
@stites does your package description by any chance have this form here: https://github.com/haskell/cabal/issues/4629 ?

**Comment by stites** [comment]
@gbaz -- Thanks for letting me know! `cabal check` does find this error and I was unaware of this feature! 

--

@hvr -- Yes, that is exactly the issue. The generated cabal file looks something like:

```
    if flag(lite)
        
        if flag(with_nn)
            exposed-modules:
                Torch.FFI.TH.NN.Double
        else
    else
        ...
        if flag(with_nn)
            exposed-modules:
                Torch.FFI.TH.NN.Float
                Torch.FFI.TH.NN.Double
        else
```

I'll close this now since it is just a duplicate of https://github.com/haskell/cabal/issues/4629
