### ISSUE TITLE
Package build - No space left on device 

### ISSUE THREAD

**Issue by nhibberd** [haskell/hackage-server#798]
This is probably not the right place to raise this, happy to be redirected elsewhere.

Seeing this on a recently uploaded package:

```
Installing library in /home/builder/hackage-server/build-cache/tmp-install/lib/x86_64-linux-ghc-8.6.1/amazonka-s3-1.6.0-5U8ponBXtdSGesGdgO4FWx
/home/builder/hackage-server/build-cache/tmp-install/lib/x86_64-linux-ghc-8.6.1/amazonka-s3-1.6.0-5U8ponBXtdSGesGdgO4FWx/.copyFile23869-359.tmp: copyFile: resource exhausted (No space left on device)
cabal: Leaving directory '/tmp/cabal-tmp-32213/amazonka-s3-1.6.0'

```

Build logs: 
http://hackage.haskell.org/package/mismi-s3-0.0.3/reports/

**Comment by gbaz** [comment]
This is a fine place to raise builder ops issues. Anyway, I cleaned out some space (caches) and there's now over 6G on the buildbox available, so we're good for another while.

**Comment by nhibberd** [comment]
Is it possible to restart those builds? via an API?

**Comment by gbaz** [comment]
there's only one failed build  -- the one you linked to. because it had a huge dep footprint, it served as an early warning system. otherwise i can do it manually.
