### ISSUE TITLE
Hackage is slow

### ISSUE THREAD

**Issue by flip111** [haskell/hackage-server#799]
Hackage is slow on my computer so i tested with a few websites https://hackage.haskell.org/packages/browse

11.40 https://tools.pingdom.com/#5a002f3e47400000
23.0 https://gtmetrix.com/reports/hackage.haskell.org/w4OFMhLe
42.2 https://developers.google.com/speed/pagespeed/insights/?hl=nl&url=https%3A%2F%2Fhackage.haskell.org%2Fpackages%2Fbrowse
27.4 https://www.webpagetest.org/result/181230_YM_8e95789205ec34e625f30e4518610077/

on average `(11.40 + 23.0 + 42.2 + 27.4) / 4 = 26` seconds.

**Comment by flip111** [comment]
By the way .. just after i tested this hackage got migrated to rackspace. But after migration it's still on the same speed.

**Comment by gbaz** [comment]
The browse page is giant -- it contains a listing of all packages. We already cache it significantly. Not sure what else could be done?

**Comment by gbaz** [comment]
Note also that the table starts rendering before the full page load is done -- most of the slowness is the cost of datatables parsing and rendering the full package list.
