### ISSUE TITLE
Hackage build failing with libtinfo.so issue

### ISSUE THREAD

**Issue by LeventErkok** [haskell/hackage-server#802]
Just uploadod a new version, and build fails with:

> can't load .so/.DLL for: libtinfo.so (libtinfo.so: cannot open shared object file: No such file or directory)

Here's the full log: http://hackage.haskell.org/package/sbv-8.0/reports/1

Is this a temporary problem with the hackage builds? Any help would be appreciated.

**Comment by gbaz** [comment]
new docbuilder box, doesn't have a lot of stuff installed yet. Just added libtinfo-dev to it.

**Comment by LeventErkok** [comment]
Is "clearing the failed status manually" something regular users can do, or does it require some sort of admin privilege? (Asking for next time this happens!)

**Comment by gbaz** [comment]
It means I log onto the box and edit a file :-). There's a GSoC proposal that might improve this situation eventually.

**Comment by LeventErkok** [comment]
Thanks @gbaz; good to know.

Just wanted to mention that even though we often whine and complain as end users, I'm truly appreciative of you and many other volunteer's efforts to keep hackage running as smoothly as it does. Much appreciated!
