### ISSUE TITLE
Account activation mail asks for password via unencrypted HTTP

### ISSUE THREAD

**Issue by asciijungle** [haskell/hackage-server#803]
I've created a hackage account. In the process I received an E-Mail with an account activation link. That link led to a plain HTTP site which requested that I set a password for the account.
That is an issue since the traffic will be unencrypted so anyone on the internet (at least anyone that my traffic is routed by) could see the password that I'm setting for my new account.

One can change the URL in the browser and reload the page since the site does support HTTPS. But some user might not notice this and endanger their accounts security.

Proposed solution: disallow any unencypted HTTP traffic on the hackage webserver. Instead send a redirect (HTTP-301) to the same page using the HTTPS protocol. 

Alternative short term solution: change the protocol in the activation link to say https:// instead of http://

**Comment by tfausak** [comment]
The email part of this sounds similar to #837.

**Comment by gbaz** [comment]
Closing as resolved (also note that we have a more eager http -> https redirect in place)
