### ISSUE TITLE
Do not autofocus search field on package page

### ISSUE THREAD

**Issue by Bodigrim** [haskell/hackage-server#807]
It seems that several month ago the search field in the header on package page (like hackage.haskell.org/package/base) became autofocused. IMHO this is unconvenient, because it makes navigation harder.

1. I cannot scroll a page by pressing arrow down. Instead of scrolling, my browser (Firefox) shows me the list of autocompletions for the search field.

2. I cannot invoke quick search by pressing "S". Obviously, with a text box in focus it just appends letter "S" to its content.

**Comment by juhp** [comment]
+100

Really annoying

**Comment by nschoe** [comment]
oOps sorry guys, it was me who proposed the PR. As explained [here](https://github.com/haskell/hackage-server/commit/5039b04a0d48d205b7f3f2311b486607f04b4e58) in an answer to @juhp , I find it much more convenient to be directly able to type in the name of the package you are searching when you land on the home page and _then_ need to use your mouse to scroll (alternatively you can press `Tab` and then use `PgUp/PgDown`) than needing to _first_ use your mouse to focus the search field, _then_ type, and _then_ use the mouse again to scroll and click on your package.

But well, if this is too cumbersome for a majority of people, let's reverse :)

**Comment by gbaz** [comment]
Well I think the issue is that this change might help on the homepage, but it is inconvenient on other pages, such as package pages. So the "right" patch would be to special-case the homepage, or perhaps the homepage and the browse page or the like, and not apply the same behavior on package pages.

**Comment by nschoe** [comment]
I understand your point, it's not really an issue for me as I either scroll with the mouse on the package pages, or use `tab` + `PgUp/Down`. I initially made the PR because I found this more convenient and was thinking that it would help other people, too.
But if that is causing more discomfort that it solves pain, then let's revert, no worries on my side =)

**Comment by Bodigrim** [comment]
> I find it much more convenient to be directly able to type in the name of the package you are searching when you land on the home page...

One can setup a search engine in his favorite browser to eliminate loading Hackage homepage at all. I just type `h base` in the address bar. Super convenient. 

So, can we please have 5039b04a0d48d205b7f3f2311b486607f04b4e58 reverted?

**Comment by Bodigrim** [comment]
I rarely open homepage of Hackage, but IMO autofocus on search field makes sense only for Google Search and alike, where there is literally nothing else to do. However Hackage homepage has a lot of contents and search field is only a minor part of it. I find frustrating not be able to navigate it by arrows of `PgDown`, because these keystrokes get intercepted by search field.

**Comment by juhp** [comment]
When may this get deployed btw?

**Comment by juhp** [comment]
Ping!

**Comment by Bodigrim** [comment]
@gbaz @hvr can we please have this fix deployed finally?

**Comment by chauchakching** [comment]
the autofocus is still there
hope that this change will be deployed soon

**Comment by phadej** [comment]
@hvr redeployed hackage-server, the autofocus is no more.
