### ISSUE TITLE
docs not building because "no space left on device"

### ISSUE THREAD

**Issue by jgm** [haskell/hackage-server#808]
Pandoc 2.5 haddocks don't build.  The log shows pandoc building successfully. The failure is in the haddock generation phase:
```
 18% (  2 / 11) in 'Text.Pandoc.Writers.OOXML'
  Missing documentation for:
    mknode (src/Text/Pandoc/Writers/OOXML.hs:54)
    nodename (src/Text/Pandoc/Writers/OOXML.hs:58)
    toLazy (src/Text/Pandoc/Writers/OOXML.hs:64)
    renderXml (src/Text/Pandoc/Writers/OOXML.hs:67)
    parseXml (src/Text/Pandoc/Writers/OOXML.hs:71)
    elemToNameSpaces (src/Text/Pan/tmp/ghc16637_0/ghc_862.s: Assembler messages:
/tmp/ghc16637_0/ghc_862.s: Fatal error: can't close /tmp/ghc16637_0/ghc_164.dyn_o: No space left on device
```
I'm not sure how to interpret this, but it looks like a Hackage infrastructure issue rather than a problem with anything in pandoc. (I can build haddocks locally with no problems.)

**Comment by gbaz** [comment]
This was a failed build from last year when we were low on disk space in the builder -- its clear now. I did however just remove  pandoc from the failed queue so the docs will try to rebuild.

**Comment by jgm** [comment]
@gbaz - oh, but I thought I just told Hackage to rebuild today...

**Comment by gbaz** [comment]
You can't actually tell hackage to rebuild :-/. You _can_ delete uploaded docs, but that doesn't suffice because the builder keeps a local "failed cache" so it doesn't retry failed builds indefinitely. It has to be edited by logging into the box. We have a gsoc proposal to improve things.

**Comment by jgm** [comment]
Got it -- thanks!
