### ISSUE TITLE
The new color scheme for haddocks has low contrast

### ISSUE THREAD

**Issue by phadej** [haskell/hackage-server#811]
The background of color block is too close to the default white:

![screenshot from 2019-02-24 21-07-17](https://user-images.githubusercontent.com/51087/53303864-3a7cd000-3878-11e9-9e98-011d15caf44f.png)

The bullet arrow is too subtle, could it be filled?

![screenshot from 2019-02-24 21-15-14](https://user-images.githubusercontent.com/51087/53303994-50d75b80-3879-11e9-82b3-4d72a4110efa.png)

Also the `body` (virtually everything "black") color text is `#333`, which is IMO too light, given the font-family is very light on itself.

**Comment by gbaz** [comment]
this should be filed against haddock, not hackage-server.

**Comment by phadej** [comment]
For `haddock` it's not a "bug" as no-one is forced to use the new style sheet locally?

**Comment by gbaz** [comment]
The docs are built with haddock though, so if the ticket is against the haddocks specifically, then it needs to be changed there.
