### ISSUE TITLE
A way (button?) to retry building haddocks

### ISSUE THREAD

**Issue by NorfairKing** [haskell/hackage-server#816]
https://hackage.haskell.org/package/genvalidity-hspec-0.7.0.0/reports/3

Building haddocks failed for my package because of a problem with a dependency that has since been resolved. Is there a way to restart trying that?

**Comment by gbaz** [comment]
there's no current way to do that. c.f. https://github.com/haskell/hackage-server/issues/515

I went and cleared the failed flag manually for this package though, so it should rebuild.
