### ISSUE TITLE
hackage.haskell.org is down

### ISSUE THREAD

**Issue by igrep** [haskell/hackage-server#822]
https://hackage.haskell.org says:

![image](https://user-images.githubusercontent.com/227057/55527612-cafacb80-56d4-11e9-89ca-fd3c2b742e8d.png)

And http://auto-status.haskell.org/ says:

![image](https://user-images.githubusercontent.com/227057/55527562-8e2ed480-56d4-11e9-9eb6-5fa847c6f890.png)

**Comment by 23Skidoo** [comment]
Admins are aware, see https://status.haskell.org/. I suggest closing this ticket as the incident does not have anything to do with bugs in Hackage server code per se.

**Comment by igrep** [comment]
Okay, sorry.
How should I contact next time when it's down?
Send an email to admin@hackage.haskell.org?

**Comment by ocramz** [comment]
I would guess the Hackage admins get to know about outages right away.

**Comment by phadej** [comment]
Shouting out on `#haskell-infrastructure` or `#hackage` on IRC is not bad idea though, if status.haskell.org doesn't say anything (it's updated manually, so if it's updated, then someone have noticed).
