### ISSUE TITLE
img tags in Markdown are not rendered

### ISSUE THREAD

**Issue by 23Skidoo** [haskell/hackage-server#825]
See e.g. http://hackage.haskell.org/package/hedgehog-0.6.1#readme.

GitHub [shows the image](https://github.com/hedgehogqa/haskell-hedgehog), Hackage shows HTML code. Though it may be a GitHub-only markdown extension...

**Comment by phadej** [comment]
The `cheapskate` library allows raw html. Maybe there's reason for disabling it recorded somewhere. 

> If the markdown input you are converting comes from an untrusted source (e.g. a web form), you should always set sanitize to True. This causes the generated HTML to be filtered through xss-sanitize's sanitizeBalance function. Otherwise you risk a XSS attack from raw HTML or a markdown link or image attribute attribute.
>
> You may also wish to disallow users from entering raw HTML for aesthetic, rather than security reasons. In that case, set allowRawHtml to False, but let sanitize stay True, since it still affects attributes coming from markdown links and images.

**Comment by gbaz** [comment]
prior discussion here: https://github.com/haskell/hackage-server/issues/477

I don't have an immediate objection to allowing raw html but enforcing sanitization. That said, I'd like someone to look over the sanitization code it uses from xss-sanitize to confirm that it seems "sufficiently safe".

**Comment by gbaz** [comment]
(the counterargument arguably is just "using markdown image tags instead of html is more standard and easier to control, so people should just do that, and there's no reason to accommodate an inferior way to do the same thing as well.")

**Comment by phadej** [comment]
@gbaz the markdown's image markup can still cause XSS breakages

>  since it still affects attributes coming from markdown links and images.

**Comment by gbaz** [comment]
I agree -- I didn't say that it was "absolutely safe" but just that it is more standard and easier to control. And I also agree we still rely on the sanitization even now. However, note that if we allow all sorts of raw html (which I think that flag would enable) then we would be _much more_ reliant on it.

**Comment by phadej** [comment]
I’d use a tagsoup phase to process raw html, to allow only some tags; not arbitrary. Would be nice if cheapskate allowed hooks for processing individual raw html blocks. (Maybe it has, I didn’t check the haddocks; on mobile)

**Comment by gbaz** [comment]
if we're going to start really doing custom stuff, might be worth just doing the full cutover as discussed https://github.com/haskell/hackage-server/issues/565 (and perhaps other markdown-tagged tickets?)

**Comment by 23Skidoo** [comment]
@phadej 

> I’d use a tagsoup phase to process raw html, to allow only some tags; not arbitrary. 

From what I can tell, this is what `xss-sanitize` does already. Quoting its README:

> This function removes any HTML tags or attributes that are not in its white-list. [...] TagSoup is used to parse the HTML

@gbaz

> "using markdown image tags instead of html is more standard and easier to control, so people should just do that, and there's no reason to accommodate an inferior way to do the same thing as well."

The reason `hedgehog`'s readme uses the `<img>` tag is that they want to specify the `align="right"` attribute.

**Comment by gbaz** [comment]
I checked the code and it looks reasonable I guess. Here's the defaults it allows through: https://hackage.haskell.org/package/xss-sanitize-0.3.6/docs/src/Text.HTML.SanitizeXSS.html#acceptable_elements

If we're ok with all that, a PR to change this is welcome.

**Comment by phadej** [comment]
I don't think that allowing `input` or `textarea` is good idea; or `sound` and `video`.

**Comment by 23Skidoo** [comment]
`xss-sanitize` allows extending the list of acceptable elements, but `cheapskate` doesn't expose this functionality.

**Comment by 23Skidoo** [comment]
GitHub doesn't seem to allow videos in READMEs either, btw.
