### ISSUE TITLE
Server problem when downloading index.tar.gz

### ISSUE THREAD

**Issue by onslaughtq** [haskell/hackage-server#831]
Starting sometime on June 7th, numerous attempts to run `cabal update` have resulted in `cabal: Codec.Compression.Zlib: premature end of compressed stream`.   I attempted to do a straight download of the file using `wget http://hackage.haskell.org/packages/archive/00-index.tar.gz` but get a 503 error when it nears completion of the download.

**Comment by hvr** [comment]
This appears to coincide with a recent change in our CDN configuration which seems to have broken the legacy 00-index.tar.gz HTTP download endpoint. I have reverted the configuration; can you please try again and let us know whether it works again now (or not)?

Btw, you seem to be using a somewhat older `cabal` release (pre 2.0). Is there any particular reason you aren't using a more recent `cabal` 2.x release?

**Comment by onslaughtq** [comment]
It appears to be fixed now, thank you!

As for your question about our use older cabal, we have planned to upgrade
but just haven't gotten to it yet.
