### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by v0d1ch** [haskell/hackage-server#832]
I see there are a couple of closed tickets that mention the same error but I still experience it. 
I am trying to upload a package that is 39.7 mb in size since I depend on some bundled C library. Is it possible to upload a package of that size on Hackage?

**Comment by phadej** [comment]
39 Mb of Haskell + C code? That’s a lot.

**Comment by v0d1ch** [comment]
Well it is 2019 :) On the serious note I should add it as a submodule instead.

**Comment by phadej** [comment]
Sorry, I should been more clear and verbose:

Please provide more information: as you are trying to upload a source tarball to a *public* service to be stored *forever*, you probably have it somewhere publicly available already (github, gitlab, etc).

39.7mb is suspiciously big

```
-rw-rw-r--  1 phadej phadej 2,3M kesä  23 23:06  Agda-2.6.0.1.tar.gz
-rw-rw-r--  1 phadej phadej 1,6M kesä  23 23:00  ghc-lib-parser-8.8.0.20190424.tar.gz
-rw-rw-r--  1 phadej phadej 159M kesä  23 23:04  linux-5.2-rc6.tar.gz
```

`Agda` and `ghc-lib-parser` are quite big packages, but legit ones. `linux` is ridiculously big C-code base (but only 5x times your package). so even it's 2019 39mb of code is ridiculous amount.

I *hope* that there's something easy we can do to get your library on Hackage, but not stressing all the infrastructure which is (implicitly) optimised for <1Mb packages.

**Comment by v0d1ch** [comment]
The lib I was using has bunch of examples in the docs folder which add too much weight. I will add only necessary things for my lib to work so closing this issue now. Sorry for wasting your time.

**Comment by phadej** [comment]
@v0d1ch no need to be sorry about that. For the next time, please don't be secretive, but try to provide as much of relevant information as possible. Someone could pointed you to that solution (bundling irrelevant stuff) directly. Or if you need to keep some details in secret, please briefly explain the reasons.

Anyway, bundling C-library should be the last resort. (Windows, I'm looking at you). I'd advice against  doing so, if there's any way to avoid dealing with non-trivial C-code.

**Comment by v0d1ch** [comment]
@phadej I wasn't trying to be secretive at all. I am trying to add a library for creating excel files that has some FFI calls to https://github.com/jmcnamara/libxlsxwriter. This is the repo https://github.com/green-lambda/HExcel . 
I ended up adding just the C source folders I need for the lib to work but now I noticed some additional problems on MacOs so I don't think I will add this to Hackage until I find the solution. 

The excel file creation works just fine when you try to invoke it from repl but compilation fails:
```Undefined symbols for architecture x86_64:
  "_lxw_chartsheet_assemble_xml_file", referenced from:
      _lxw_create_package in libHSHExcel-0.0.1.0-Apv8gLE6VnSHCUH5Wu0rtb.a(packager.o)
  "_lxw_chartsheet_free", referenced from:
      _lxw_workbook_free in libHSHExcel-0.0.1.0-Apv8gLE6VnSHCUH5Wu0rtb.a(workbook.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`gcc' failed in phase `Linker'. (Exit code: 1)
```

**Comment by phadej** [comment]
It seems that there is (up to date) brew formula for https://formulae.brew.sh/formula/libxlsxwriter. So i'd just ask user to install the lib, and use

```
extra-libraries: xlsxwriter
```

(see: https://cabal.readthedocs.io/en/latest/developing-packages.html#pkg-field-extra-libraries)

**Comment by v0d1ch** [comment]
Thanks, this is the simplest and by far better solution to the ones I had before. I will put that library on hackage after all, thanks a lot!

**Comment by v0d1ch** [comment]
https://hackage.haskell.org/package/HExcel ❤️
