### ISSUE TITLE
Account confirmation email links to insecure page (http instead of https)

### ISSUE THREAD

**Issue by glebec** [haskell/hackage-server#837]
When signing up for an account, the email sends me to a password creation page via an `http` link. Manually changing it to an `https` link appears to work, so the email form should use that instead.

Diff:

```diff
Dear [USER NAME HERE], 

We received a request to create a Hackage account 
for you. To create a Hackage account, please follow 
this link: 

- http://hackage.haskell.org/users/register-request/[REDACTED] 
+ https://hackage.haskell.org/users/register-request/[REDACTED]

After your account is created, you cannot upload until you…
```

---

Quick initial research: the template is located at: https://github.com/haskell/hackage-server/blob/c812ec1f6dd8fb4d997354c862f92bf2f050c75e/datafiles/templates/UserSignupReset/SignupConfirmation.email.st#L7

The `$confirmlink$` template variable is populated by: https://github.com/haskell/hackage-server/blob/c812ec1f6dd8fb4d997354c862f92bf2f050c75e/Distribution/Server/Features/UserSignup.hs#L448-L455

I haven't looked further than this yet.

**Comment by maxthomas** [comment]
just ran into this issue myself, so would definitely like to see this tackled/merged

**Comment by gbaz** [comment]
There's nothing to merge. We need to configure the base-uri properly in the script that manages running the hackage server to be an https uri. This used to be done, but the change must have been reverted in some migration...

**Comment by gbaz** [comment]
Ok. We've tweaked the config so on next hackage restart (they aren't that frequent) the base-uri should be set correctly.

**Comment by utgarda** [comment]
It's still there, don't know how exactly infrequent those restarts are.

**Comment by gbaz** [comment]
Checked and its resolved for now at least.
