### ISSUE TITLE
Microsoft Edge: 'Synopsis' pane content always displayed

### ISSUE THREAD

**Issue by mpilgrem** [haskell/hackage-server#842]
If not specific to me, this may be an upstream issue. On Microsoft Edge (build 18362), the 'Synopsis' pane content is always displayed 'open' on top of (masking) other content. The 'to open' 'Synopsis' pane tab icon '<<' is displayed, not the 'to close' pane tab icon '>>'. The pane cannot be 'closed' by clicking on the pane tab.

(In Google Chrome on Windows 10, the 'Synopsis' pane toggles open and closed as intended, when the pane tab is clicked on.)

**Comment by harpocrates** [comment]
This is a known Haddock issue. I’m cramped by being on mobile, but there should be an existing github issue for this too.

IIRC this is because Edges support of summary/details is incomplete. I could be thinking of something else though.

**Comment by mpilgrem** [comment]
Thank you. After your explanation and a little further investigation, I understand that the feature is implemented using `<details>` and `<summary>` tags, introduced in HTML 5 and supported in all of the most popular browsers other than Microsoft's (https://www.w3schools.com/tags/tag_details.asp).

This [blog entry](https://developer.microsoft.com/en-us/microsoft-edge/platform/status/detailssummary/?q=details) states that its implementation is under consideration by Microsoft for Edge, with high priority.

The [beta version of Microsoft Edge](https://support.microsoft.com/en-gb/help/4501095/download-microsoft-edge-based-on-chromium) based on Chromium (77.0.235.20) does seem to have implemented `<details>` and `<summary>`.
