### ISSUE TITLE
"No cached index available for target repo" while mirroring

### ISSUE THREAD

**Issue by ozzzzz** [haskell/hackage-server#846]
We have `hackage-server` instance in docker with shared volume to the disk. Then we start `hackage-mirror` instance in another docker that linked to the `hackage-server` and have the same shared volume. Then we have the message from [this](https://github.com/haskell/hackage-server/blob/c812ec1f6dd8fb4d997354c862f92bf2f050c75e/Distribution/Client/Mirror/Repo.hs#L138) line:
```
No cached index available for target repo
94031 packages to mirror.
mirroring AC-HalfInteger-1.1.1
mirroring AC-HalfInteger-1.2.1
...
```

And we do not know: is this a normal reaction or something goes wrong? Because it looks like that when we restart `hackage-mirror` it starts to sync libraries that synced already.

**Comment by ozzzzz** [comment]
This is log from two runs. First:
```
Up to date
No cached index available for target repo
115848 packages to mirror.
mirroring AC-HalfInteger-1.1.1
mirroring AC-HalfInteger-1.2.1
mirroring AC-MiniTest-1.1.1
mirroring AC-Terminal-1.0
mirroring AC-Vector-2.0.0
```
Second:
```
Up to date
No cached index available for target repo
115848 packages to mirror.
mirroring AC-HalfInteger-1.1.1
mirroring AC-HalfInteger-1.2.1
mirroring AC-MiniTest-1.1.1
mirroring AC-Terminal-1.0
mirroring AC-Vector-2.0.0
mirroring AC-Vector-2.1.0
...
```

**Comment by gbaz** [comment]
The first time its fine to say. The second time it should only occur if there's no stored data from the first fun.

**Comment by ozzzzz** [comment]
So it means that we did something wrong and second attempt shouldn't download packages AC-..., right?

**Comment by gbaz** [comment]
try running something in a dev setup outside of docker to get a feel for how it operates without that extra container packaging in the mix, and that will give you a feel for how things work...

**Comment by ozzzzz** [comment]
Sadly, we have not success on this way. We tried every possible configurations and on all of them some errors occurs.

**Comment by gbaz** [comment]
"some error occurs" is not very useful. i'd like to be able to give some advice, but there's not a lot to go on here..
