### ISSUE TITLE
Documentation is not generated when packages depend on `markdown-unlit`

### ISSUE THREAD

**Issue by chshersh** [haskell/hackage-server#847]
If I have a package with a tutorial as `README` using `markdown-unlit` package, then documentation on Hackage is not generated fu such packages. See the build log for `shellmet` for example:

* https://hackage.haskell.org/package/shellmet-0.0.3.0/reports/1

However, using `cabal` locally, I can generate and see documentation without any problems. `markdown-unlit` is specified as `build-tool-depends`. You can see how it's specified here:

* https://github.com/kowainik/shellmet/blob/37d66d19e3a3614175f7def7305737df559df178/shellmet.cabal#L60-L68

**Comment by hvr** [comment]
This is because the doc-builder isn't using the v2-* build-logic yet, and therefore can't yet provision the build-time requirements specified by `build-tool-depends`

**Comment by gromakovsky** [comment]
I suppose this issue is a specific instance of the more broad issue #821. Apparently you can't use any build tool.

**Comment by andreasabel** [comment]
Closing as duplicate.
