### ISSUE TITLE
Candidates index being served incomplete

### ISSUE THREAD

**Issue by phlummox** [haskell/hackage-server#856]
(This doesn't seem to be a browser caching issue, as I've confirmed it occurs in different browsers, as well as using `wget`, and from hosts in different geographical locations.)

The Hackage "Package candidates" page (at <http://hackage.haskell.org/packages/candidates/>) seems to be being incompletely served - the HTML served up ends partway through a `<li>` element.

It only lists package candidates up to "NestedFunctor" - the final HTML fragment I get is (line breaks inserted for readability):

```html
<li><a href="/package/NestedFunctor/candidates/">NestedFunctor</a>: 
<a href="/package/NestedFunctor-0.2.0.1/candidate">0.2.0.1</a>. 
Nested composition of functors with a type index tracking nesting.</li>
<li><a href="/package/NetSNMP
```
- and in the browser, the end of the page looks like this:

![hackage-scrn](https://user-images.githubusercontent.com/18113700/70653712-f5534e80-1c8f-11ea-9c15-61ea0b1f1645.png)

If anyone else could confirm that this isn't just me, I'd appreciate it!

**Comment by phlummox** [comment]
Just commenting to add: the index was apparently fine on 12 May 2019, as the Wayback Machine shows it apparently listing candidates in full: <https://web.archive.org/web/20190512184850/http://hackage.haskell.org/packages/candidates/>.

**Comment by tfausak** [comment]
> If anyone else could confirm that this isn't just me, I'd appreciate it!

Yup, happens for me too. Cuts off at the `Naperian` package.

**Comment by gbaz** [comment]
It looks like someone uploaded a really screwy named candidate as a stress-test or something and it breaks the rendering. Haven't been able to dig in further, since the rendering for the candidates page is really ancient and grotty.

**Comment by gbaz** [comment]
There's something named "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-9223372036854775807.9223372036854775807.9223372036854775807" but we can't reach it to edit it without fixing the server, because it somehow breaks the parsing code :-/

**Comment by gbaz** [comment]
the full candidate list is here from a different rendering process, which is how i checked this http://hackage.haskell.org/packages/candidates/docs.json

**Comment by gbaz** [comment]
The code that seems to choke on it is probably around here:  https://github.com/haskell/hackage-server/blob/master/Distribution/Server/Features/Html.hs#L1177

**Comment by tfausak** [comment]
I uploaded that goofy package forever ago. If you want to simply delete it, that's fine with me.

**Comment by gbaz** [comment]
Fixed by gsoc work and the redeploy.

**Comment by gbaz** [comment]
I swear I saw this fixed, but now looks busted again *facepalm*.

**Comment by gbaz** [comment]
ok now this is finally fixed for real.
