### ISSUE TITLE
Add GNU Guix to the list of distributions that package a library

### ISSUE THREAD

**Issue by brown121407** [haskell/hackage-server#857]
GNU Guix has a great importer for Haskell packages and its number of available libraries is steadily increasing. I suggest adding Guix in the list of distributions that ship a package along with the package's version on that system (below "Uploaded by..." on the right side of a package's page on Hackage).

**Comment by gbaz** [comment]
This is not a hackage issue. Guix can request an account with perms to do distro notifications, and utilize the hackage api to do this. Its up to their maintainers!
