### ISSUE TITLE
Unknown architecture name 'wasm32'

### ISSUE THREAD

**Issue by 3noch** [haskell/hackage-server#869]
The time has come. `wasm32` for Haskell is actually a thing. But `cabal upload` won't have it.

I have this in my cabal file:

```cabal
if arch(wasm32)
  build-depends:
    jsaddle >= 0.9.6 && < 0.10,
    jsaddle-wasm >= 0.1 && < 0.2
```

Why does `cabal upload` refuse to let me upload this package with `Unknown architecture name 'wasm32'`?

Moved from https://github.com/haskell/cabal/issues/6796

**Comment by 3noch** [comment]
I'm switich to `flag(wasm32)` as a temporary stop-gap but we want to think about a long-term solution to this problem.

**Comment by gbaz** [comment]
I'm going to close this as I think the real solution remains adding wasm to the known arches of cabal. Sorry for the ping-pong.
