### ISSUE TITLE
Tables in readme markdown

### ISSUE THREAD

**Issue by expipiplus1** [haskell/hackage-server#877]
Is it possible to render tables in the markdown readmes of packages. At the moment they don't render at all well

An example: https://hackage.haskell.org/package/orbits-0.3 (from https://github.com/expipiplus1/orbits#nomenclature)

**Comment by Bodigrim** [comment]
More examples:
https://hackage.haskell.org/package/random-1.2.0#readme
https://hackage.haskell.org/package/mod-0.1.1.0#readme
https://hackage.haskell.org/package/poly-0.4.0.0#readme

**Comment by lehins** [comment]
I think it might be a duplicate of #565 

Markdown files, such as changelog.md and readme.md are viewed on both Github and Hackage. It would be nice to have a consistent looking pages between the two. 

With more and more packages relying on tables, I think this issue does deserve some attention.

**Comment by phadej** [comment]
There is a plan in #565, either vendor in `commonmark-...` packages, or we can depend on `pandoc`.

Closing this as duplicate.

**Comment by expipiplus1** [comment]
Cool, thanks @phadej

**Comment by andreasabel** [comment]
There is PR #904.  Hope this will go live soon and fix the problem.

**Comment by expipiplus1** [comment]
thanks！
