### ISSUE TITLE
Provide libsodium on the docs builder

### ISSUE THREAD

**Issue by sjakobi** [haskell/hackage-server#882]
The docs builder currently fails to build `saltine` and its reverse dependencies due to a missing `libsodium` system package. See http://hackage.haskell.org/package/hnix-store-core-0.2.0.0/reports/2 for an example.

Interestingly, the matrix builder seems to build the same packages just fine, e.g. https://matrix.hackage.haskell.org/#/package/hnix-store-core

Could the docs builder be somewhat aligned with the matrix builder, and also provide `libsodium`?

CC @Anton-Latukha, @sorki

**Comment by gbaz** [comment]
The two are totally different machines with totally different setups. Not sure if there's a great path to alignment in the near-future. That said, libsodium is now added.

**Comment by sjakobi** [comment]
Many thanks, @gbaz! :)

This will much simplify releases for a small bunch of packages!
