### ISSUE TITLE
libxml2 on documentation builder

### ISSUE THREAD

**Issue by mbg** [haskell/hackage-server#886]
I recently published [`c14n`](http://hackage.haskell.org/package/c14n) which has a dependency on `libxml-2.0`. The builds on Hackage CI work fine, but Hackage fails to build the documentation:
```
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] next goal: c14n (user goal)
[__0] rejecting: c14n-0.1.0.1 (conflict: pkg-config package libxml-2.0-any,
not found in the pkg-config database)
[__0] rejecting: c14n-0.1.0.0 (constraint from user target requires ==0.1.0.1)
[__0] fail (backjumping, conflict set: c14n)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: c14n
```
I have uploaded the documentation manually, but it means documentation also fails to build for packages which depend on `c14n` (such as [`wai-saml2`](http://hackage.haskell.org/package/wai-saml2) which I made `c14n` for).

Would it be possible to install `libxml-2.0`?

**Comment by gbaz** [comment]
done.
