### ISSUE TITLE
Trouble with cabal update

### ISSUE THREAD

**Issue by zoeronen** [haskell/hackage-server#887]
I just installed ghc and cabal on an Ubuntu MATE system. I can't seem to be able to download the repositories. Here is a full report from running `cabal new-update --verbose`:

Project settings changed, reconfiguring...
Trying to locate mirrors via DNS for initial bootstrap of secure repository
'http://hackage.haskell.org/' ...
located 2 mirrors for http://hackage.haskell.org/ :
 http://hackage.fpcomplete.com/
 http://objects-us-east-1.dream.io/hackage-mirror/
Selected mirror http://hackage.haskell.org/
Downloading root
/usr/bin/wget '--input-file=-' '--output-document=/tmp/transportAdapterGet18412-1' '--user-agent=cabal-install/2.4.0.0 (linux; x86_64)' '--tries=5' '--timeout=15' --server-response '--header=Cache-Control: no-transform'
Downloading the latest package list from hackage.haskell.org
Warning: The package list for 'hackage.haskell.org' does not exist. Run 'cabal
update' to download it.
Selected mirror http://hackage.haskell.org/
Downloading timestamp
/usr/bin/wget '--input-file=-' '--output-document=/tmp/transportAdapterGet18412-3' '--user-agent=cabal-install/2.4.0.0 (linux; x86_64)' '--tries=5' '--timeout=15' --server-response '--header=Cache-Control: no-transform'
Downloading snapshot
/usr/bin/wget '--input-file=-' '--output-document=/tmp/transportAdapterGet18412-5' '--user-agent=cabal-install/2.4.0.0 (linux; x86_64)' '--tries=5' '--timeout=15' --server-response '--header=Cache-Control: no-transform'
Downloading mirrors
/usr/bin/wget '--input-file=-' '--output-document=/tmp/transportAdapterGet18412-7' '--user-agent=cabal-install/2.4.0.0 (linux; x86_64)' '--tries=5' '--timeout=15' --server-response '--header=Cache-Control: no-transform'
Cannot update index (no local copy)
Downloading index
/usr/bin/wget '--input-file=-' '--output-document=/tmp/transportAdapterGet18412-9' '--user-agent=cabal-install/2.4.0.0 (linux; x86_64)' '--tries=5' '--timeout=15' --server-response '--header=Cache-Control: no-transform'
Exception dieVerbatim: user error (CallStack (from HasCallStack):
die', called at ./Distribution/Client/HttpUtils.hs:519:16 in
main:Distribution.Client.HttpUtils
cabal: '/usr/bin/wget' exited with an error:
--2020-07-05 00:11:08-- http://hackage.haskell.org/01-index.tar.gz
Resolving hackage.haskell.org (hackage.haskell.org)... 151.101.192.68,
151.101.128.68, 151.101.64.68, ...
Connecting to hackage.haskell.org (hackage.haskell.org)|151.101.192.68|:80...
connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in
headers.
Retrying.

--2020-07-05 00:11:24-- (try: 2) http://hackage.haskell.org/01-index.tar.gz
Connecting to hackage.haskell.org (hackage.haskell.org)|151.101.192.68|:80...
connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in
headers.
Retrying.

--2020-07-05 00:11:41-- (try: 3) http://hackage.haskell.org/01-index.tar.gz
Connecting to hackage.haskell.org (hackage.haskell.org)|151.101.192.68|:80...
connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in
headers.
Retrying.

--2020-07-05 00:11:59-- (try: 4) http://hackage.haskell.org/01-index.tar.gz
Connecting to hackage.haskell.org (hackage.haskell.org)|151.101.192.68|:80...
connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in
headers.
Retrying.

--2020-07-05 00:12:18-- (try: 5) http://hackage.haskell.org/01-index.tar.gz
Connecting to hackage.haskell.org (hackage.haskell.org)|151.101.192.68|:80...
connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in
headers.
Giving up.

) when using mirror http://hackage.haskell.org/
Selected mirror http://hackage.fpcomplete.com/
Downloading timestamp
/usr/bin/wget '--input-file=-' '--output-document=/tmp/transportAdapterGet18412-11' '--user-agent=cabal-install/2.4.0.0 (linux; x86_64)' '--tries=5' '--timeout=15' --server-response '--header=Cache-Control: no-transform'
Downloading snapshot
/usr/bin/wget '--input-file=-' '--output-document=/tmp/transportAdapterGet18412-13' '--user-agent=cabal-install/2.4.0.0 (linux; x86_64)' '--tries=5' '--timeout=15' --server-response '--header=Cache-Control: no-transform'
Downloading mirrors
/usr/bin/wget '--input-file=-' '--output-document=/tmp/transportAdapterGet18412-15' '--user-agent=cabal-install/2.4.0.0 (linux; x86_64)' '--tries=5' '--timeout=15' --server-response '--header=Cache-Control: no-transform'
Cannot update index (no local copy)
Downloading index
/usr/bin/wget '--input-file=-' '--output-document=/tmp/transportAdapterGet18412-17' '--user-agent=cabal-install/2.4.0.0 (linux; x86_64)' '--tries=5' '--timeout=15' --server-response '--header=Cache-Control: no-transform'
Exception dieVerbatim: user error (CallStack (from HasCallStack):
die', called at ./Distribution/Client/HttpUtils.hs:519:16 in
main:Distribution.Client.HttpUtils
cabal: '/usr/bin/wget' exited with an error:
--2020-07-05 00:12:34-- http://hackage.fpcomplete.com/01-index.tar.gz
Resolving hackage.fpcomplete.com (hackage.fpcomplete.com)... 52.216.24.195
Connecting to hackage.fpcomplete.com
(hackage.fpcomplete.com)|52.216.24.195|:80... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in
headers.
Retrying.

--2020-07-05 00:12:51-- (try: 2) http://hackage.fpcomplete.com/01-index.tar.gz
Connecting to hackage.fpcomplete.com
(hackage.fpcomplete.com)|52.216.24.195|:80... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in
headers.
Retrying.

--2020-07-05 00:13:08-- (try: 3) http://hackage.fpcomplete.com/01-index.tar.gz
Connecting to hackage.fpcomplete.com
(hackage.fpcomplete.com)|52.216.24.195|:80... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in
headers.
Retrying.

--2020-07-05 00:13:26-- (try: 4) http://hackage.fpcomplete.com/01-index.tar.gz
Connecting to hackage.fpcomplete.com
(hackage.fpcomplete.com)|52.216.24.195|:80... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in
headers.
Retrying.

--2020-07-05 00:13:45-- (try: 5) http://hackage.fpcomplete.com/01-index.tar.gz
Connecting to hackage.fpcomplete.com
(hackage.fpcomplete.com)|52.216.24.195|:80... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in
headers.
Giving up.

) when using mirror http://hackage.fpcomplete.com/
Selected mirror http://objects-us-east-1.dream.io/hackage-mirror/
Downloading timestamp
/usr/bin/wget '--input-file=-' '--output-document=/tmp/transportAdapterGet18412-19' '--user-agent=cabal-install/2.4.0.0 (linux; x86_64)' '--tries=5' '--timeout=15' --server-response '--header=Cache-Control: no-transform'
Downloading snapshot
/usr/bin/wget '--input-file=-' '--output-document=/tmp/transportAdapterGet18412-21' '--user-agent=cabal-install/2.4.0.0 (linux; x86_64)' '--tries=5' '--timeout=15' --server-response '--header=Cache-Control: no-transform'
Downloading mirrors
/usr/bin/wget '--input-file=-' '--output-document=/tmp/transportAdapterGet18412-23' '--user-agent=cabal-install/2.4.0.0 (linux; x86_64)' '--tries=5' '--timeout=15' --server-response '--header=Cache-Control: no-transform'
Cannot update index (no local copy)
Downloading index
/usr/bin/wget '--input-file=-' '--output-document=/tmp/transportAdapterGet18412-25' '--user-agent=cabal-install/2.4.0.0 (linux; x86_64)' '--tries=5' '--timeout=15' --server-response '--header=Cache-Control: no-transform'
dieVerbatim: user error (CallStack (from HasCallStack):
  die', called at ./Distribution/Client/HttpUtils.hs:519:16 in main:Distribution.Client.HttpUtils
cabal: '/usr/bin/wget' exited with an error:
--2020-07-05 00:14:01--
http://objects-us-east-1.dream.io/hackage-mirror/01-index.tar.gz
Resolving objects-us-east-1.dream.io (objects-us-east-1.dream.io)...
208.113.201.33, 2607:f298:5:ee00::33
Connecting to objects-us-east-1.dream.io
(objects-us-east-1.dream.io)|208.113.201.33|:80... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in
headers.
Retrying.

--2020-07-05 00:14:17-- (try: 2)
http://objects-us-east-1.dream.io/hackage-mirror/01-index.tar.gz
Connecting to objects-us-east-1.dream.io
(objects-us-east-1.dream.io)|208.113.201.33|:80... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in
headers.
Retrying.

--2020-07-05 00:14:34-- (try: 3)
http://objects-us-east-1.dream.io/hackage-mirror/01-index.tar.gz
Connecting to objects-us-east-1.dream.io
(objects-us-east-1.dream.io)|208.113.201.33|:80... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in
headers.
Retrying.

--2020-07-05 00:14:52-- (try: 4)
http://objects-us-east-1.dream.io/hackage-mirror/01-index.tar.gz
Connecting to objects-us-east-1.dream.io
(objects-us-east-1.dream.io)|208.113.201.33|:80... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in
headers.
Retrying.

--2020-07-05 00:15:11-- (try: 5)
http://objects-us-east-1.dream.io/hackage-mirror/01-index.tar.gz
Connecting to objects-us-east-1.dream.io
(objects-us-east-1.dream.io)|208.113.201.33|:80... connected.
HTTP request sent, awaiting response... Read error (Connection timed out) in
headers.
Giving up.

)

**Comment by gbaz** [comment]
can you wget that location or curl it? (i.e. http://hackage.haskell.org/01-index.tar.gz).

**Comment by zoeronen** [comment]
@gbaz doesn't cabal invoke wget in trying to connect to the server? I also tried installing curl and running it again, same problem

**Comment by gbaz** [comment]
I'm asking if you can connect to that location from that particular box by any means at all. I and others can connect, so its either a problem local to your box, or a network problem, I imagine.

**Comment by gbaz** [comment]
also are/were you accessing from in/around mumbai https://status.fastly.com/incidents/f57f7zz7bhtj

**Comment by zoeronen** [comment]
@gbaz thanks for clarifying. It appears that I can't access the location at all. And no not in Mumbai.

**Comment by gbaz** [comment]
Ok, I am going to close this as it appears to be a localized network connectivity issue that I hope will resolve in relatively short order. For reference, can you paste the ip that `nslookup` resolves to for hackage?

**Comment by zoeronen** [comment]
`nslookup http://hackage.haskell.org/01-index.tar.gz`
`Server:		127.0.0.53`
`Address:	127.0.0.53#53`

`** server can't find http://hackage.haskell.org/01-index.tar.gz: NXDOMAIN`

**Comment by zoeronen** [comment]
`nslookup http://hackage.haskell.org`
`Server:		127.0.0.53`
`Address:	127.0.0.53#53`

`** server can't find http://hackage.haskell.org: SERVFAIL`

**Comment by gbaz** [comment]
try just ‘nslookup hackage.haskell.org’

**Comment by zoeronen** [comment]
OK
`nslookup hackage.haskell.org`
`Server:		127.0.0.53`
`Address:	127.0.0.53#53`

`Non-authoritative answer:`
`hackage.haskell.org	canonical name = j.global-ssl.fastly.net.`
`Name:	j.global-ssl.fastly.net`
`Address: 151.101.192.68`
`Name:	j.global-ssl.fastly.net`
`Address: 151.101.128.68`
`Name:	j.global-ssl.fastly.net`
`Address: 151.101.64.68`
`Name:	j.global-ssl.fastly.net`
`Address: 151.101.0.68`

Thank you for your promptness and patience, I appreciate it.
