### ISSUE TITLE
Hackage rejects package using the extension StandaloneKindSignatures

### ISSUE THREAD

**Issue by nilsalex** [haskell/hackage-server#888]
Error uploading dist-newstyle/sdist/safe-tensor-0.1.0.0.tar.gz: http code 400
    Error: Invalid package
    
    Unknown extensions: StandaloneKindSignatures

I'm aware that this is an extension only added recently with ghc 8.10. Is there any way to tell when uploading my package using StandaloneKindSignatures will be possible?

**Comment by phadej** [comment]
It will be when `hackage-server` is updated to use `Cabal-3.2` or later.

**Comment by noinia** [comment]
Is there an ETA on when that will happen? Just hit this issue as well, (and explicitly including StandaloneKindSignatures in all modules is kind of annoying)

**Comment by noinia** [comment]
Considering that I was now able to upload my package to hackage I think this may have been resolved

**Comment by gbaz** [comment]
Great! Indeed the new hackage deploy is now built against an up-to-date version of the Cabal library...
