### ISSUE TITLE
cabal update: unexpected response 400 for http://hackage.haskell.org/01-index.tar.gz

### ISSUE THREAD

**Issue by PierreManos** [haskell/hackage-server#891]
The above unexpected response in the title is the message I get after `downloading the latest package list from hackage.haskell.org`
Cabal Version installed: 3.2.0.0
Is it a normal message and can I carry on with the build?

**Comment by gbaz** [comment]
i assume this was a local network issue that was fixed?

**Comment by PierreManos** [comment]
Yes it is fixed now. Thank you!
