### ISSUE TITLE
possibility of mitm attacks?

### ISSUE THREAD

**Issue by tim2CF** [haskell/hackage-server#897]
I’m not sure it’s bug or not, but uploading page of Hackage (and Hackage website in general) does not redirect to https automatically http://hackage.haskell.org/packages/upload
It might make uploading packages vulnerable to mitm attacks I guess

**Comment by gbaz** [comment]
since we use digest rather than basic auth, there's plenty of security even without https https://github.com/haskell/cabal/pull/2563
