### ISSUE TITLE
Issue submitting module with OS-specific code

### ISSUE THREAD

**Issue by david-janssen** [haskell/hackage-server#898]
Hello hackage,

Hope this is the right place for this issue, if not, I'd be very happy to hear where else I should be.

I am trying to to submit kmonad (https://github.com/david-janssen/kmonad) to hackage. The code, however, contains a little bit of C-code, and that C-code is also different if you're compiling on Windows, Linux, or Mac. Currently, the hackage website complains that it cannot find 1 of the Mac-specific code directories ('include-dirs: c_src/mac/Karabiner-VirtualHIDDevice/dist/include' directory does not exist.), I'm assuming because I am generating the package using `stack sdist` under Linux.

I tried Googling this issue, but it is so specific, so I didn't find anything. Anyone have any advice/guidance?

Thanks,

D

**Comment by phadej** [comment]
Most likely you are missing some files from the final sdist. https://cabal.readthedocs.io/en/3.4/cabal-package.html?highlight=extra-source-files#pkg-field-extra-source-files

When you do `cabal sdist`, you'll get a tarball. It's a good idea to unzip it and try to build it before uploading.

FWIW, that's how https://github.com/haskell-ci/haskell-ci is done. It first makes sdist, and tests that one, to be sure packaging works.

**Comment by david-janssen** [comment]
Thanks for the headsup. I had a further look, and I think it has to do with including directory for the header-files for some 3d party plugin we use. If I remove that line from the 'include-dirs' field, everything works, and I think we can always just use the '--extra-include-dirs' flag under MacOS to be sure to include those header files.

Marking as closed.
