### ISSUE TITLE
Hackage Build GHC upgrade

### ISSUE THREAD

**Issue by parsonsmatt** [haskell/hackage-server#903]
I have a library which fails to build because it depends on GHC 8.8 via `template-haskell >= 2.15`. Currently the compiler is 8.6.3.

[Build Log](https://hackage.haskell.org/package/prairie-0.0.1.0/reports/3)

Can we get 8.10 on the builder?

**Comment by simonmichael** [comment]
Related, I have a library which requires GHC 8.8+, and the haddock docs are not generated because hackage [tries](http://hackage.haskell.org/package/FunGEn-1.1/reports/2) to generate them using GHC 8.6.

**Comment by piq9117** [comment]
I'm guessing esqueleto is in a similar situation, it doesn't have docs on hackage right now but it does in stackage.

**Comment by gbaz** [comment]
Updated the builder to 8.10.2, will monitor a bit to see if everything is ok.

**Comment by gbaz** [comment]
ok, closing as it seems to be working. i reset docs on some of the failed stuff and it worked...

**Comment by parsonsmatt** [comment]
Thanks so much! :heart:
