### ISSUE TITLE
Access denied by Hackage S3 (=stack unusable)

### ISSUE THREAD

**Issue by Kitanotori** [haskell/hackage-server#905]
Hackage S3 URL, which is also used by stack, returns AccessDenied:

```
curl https://s3.amazonaws.com/hackage.fpcomplete.com
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>260E72308DAAB81C</RequestId><HostId>muAldte6suoccNCvuZfdETxg9I0FzvNxLFnuk37QON2nlelOsw8NhQAmbX+JE47XZqcEN0TQnxo=</HostId></Error>
```

See also: https://github.com/commercialhaskell/stack/issues/5417

**Comment by gbaz** [comment]
That's the fpcomplete hackage mirror. I don't know why its not working, or why stack is hardcoded to it, or how that might be fixed. In any case its entirely not under the control of hackage admins.

That said, you won't be able to get a top level listing anyway. I.e. the "access denied" is expected for a listing, you need to specify a particular file. And in fact, https://s3.amazonaws.com/hackage.fpcomplete.com/root.json works for me. If it fails for you, that may be a local network issue...

**Comment by Kitanotori** [comment]
I see. I guess this is an issue of latest stack.
