### ISSUE TITLE
Error when uploading candidate package with "license-files" instead of "license-file"

### ISSUE THREAD

**Issue by sjshuck** [haskell/hackage-server#908]
I don't have a license-file field in my Cabal file.  I have license-files, because I am redistributing others' C sources in my package in addition to my own C and Haskell code.

This is the page I get trying to upload a candidate tarball:
```
Invalid package

mypackage-1.0.0/mypackage.cabal:5:0: [v2.0] Parse of field 'license-file' failed.
```

**Comment by phadej** [comment]
Could you attach your `.cabal` file here?

**Comment by sjshuck** [comment]
Okay so my Cabal file is generated by Stack/hpack and looks like this:
```
...
 license-files:  LICENSE,
                 src/c/pcre2/LICENCE
...
```
But when I unzipped the dist tarball that Stack made that has the Cabal file with the auto-generated dependency PVP ranges, it looks like this:
```
...
license-file:       LICENSE src/c/pcre2/LICENCE
...
```
The bottom one is what I uploaded to Hackage to get that error.  So yeah, that's probably a Stack or hpack issue.
