### ISSUE TITLE
Package upload description is outdated as `sdist` has been removed

### ISSUE THREAD

**Issue by timo-a** [haskell/hackage-server#909]
https://hackage.haskell.org/ says:

> Packages must be in the standard compressed tarball form produced by Cabal's sdist command.

and links to http://www.haskell.org/cabal/users-guide/installing-packages.html#setup-sdist  
This link is dead. Maybe this is the correct one?  
https://cabal.readthedocs.io/en/3.4/cabal-commands.html#cabal-v2-sdist

The same dead link occurs on https://hackage.haskell.org/upload

**Comment by andreasabel** [comment]
> Maybe this is the correct one?
> [cabal.readthedocs.io/en/3.4/cabal-commands.html#cabal-v2-sdist](https://cabal.readthedocs.io/en/3.4/cabal-commands.html#cabal-v2-sdist)

I suppose so.

**Comment by autophagy** [comment]
It seems that the same content now exists in the Setup.hs commands section:

- 2.0: https://cabal.readthedocs.io/en/2.0/installing-packages.html#setup-sdist
- 3.4: https://cabal.readthedocs.io/en/3.4/setup-commands.html#runhaskell-setup-hs-sdist

But yeah, I think linking to https://cabal.readthedocs.io/en/3.4/cabal-commands.html#cabal-v2-sdist makes more sense

**Comment by timo-a** [comment]
@autophagy I just checked again, the link target is still http://www.haskell.org/cabal/users-guide/installing-packages.html#setup-sdist
which redirects to https://cabal.readthedocs.io/installing-packages.html#setup-sdist which does not exist.
Maybe it needs to be changed some other place as well?

**Comment by autophagy** [comment]
@timo-a I'm not actually sure where that particular index page is defined! When I build hackage locally, the index page is very different, being the one defined in https://github.com/haskell/hackage-server/blob/master/datafiles/templates/index.html.st, and I couldn't find any of the text on the live index anywhere in this project. Could be that it's defined somewhere else, or is part of some nginx configuration somewhere :sweat_smile:

**Comment by gbaz** [comment]
I think the issue may just be that there has not been a hackage redeploy in some time to pick up the change. Note that the branch to build locally to get all of the correct text and index pages for the central server is not the master branch, but the `central-server` branch.

**Comment by gbaz** [comment]
Argh this is still wrong... will try to get to it soonish.

**Comment by gbaz** [comment]
fixed by https://github.com/haskell/hackage-server/commit/9ba24c0c8fb23618f4e07ef344ed82c2f80397f1#diff-120048c6ff9905bc8da35a0bd11b1021547b5f19c96a5d8b863141d99b039ffb
