### ISSUE TITLE
Source code parser breaks on language pragmas

### ISSUE THREAD

**Issue by liftM** [haskell/hackage-server#911]
This is a really frustrating bug. Here's an example: https://hackage.haskell.org/package/megaparsec-9.0.1/docs/src/Text.Megaparsec.Char.Lexer.html.

Notice the error pop-up:

```
Error: Parse error on line 1:
{-# LANGUAGE Flexible
-^
Expecting 'STRING', '}'
```

The reason this is so _especially_ frustrating is that the JavaScript that displays this error jumps you back to the top of the page, overriding any anchor tag that you used. For example, try to go to https://hackage.haskell.org/package/megaparsec-9.0.1/docs/src/Text.Megaparsec.Char.Lexer.html#decimal. Instead of going to the definition of `decimal`, it will jump back to the top of the page. This is extraordinarily confusing for newcomers.

If fixing the parser is too much work, just disabling the jump-on-error would be amazing.

**Comment by phadej** [comment]
This is haddock issue, not `hackage-server`s.

**Comment by phadej** [comment]
Oh wait. It isn't.

You have some JSON viewer extension (I remember this issue!) which tries to reparse the `text/plain` of the sources.

So maybe if `hackage-server` served these fancy source files with `text/html` instead the issue will go away.

**Comment by liftM** [comment]
Huh, you're right! It looks like this is being caused by [JSONView](https://chrome.google.com/webstore/detail/jsonview/chklaanhfefbnpoihckbnefhakgolnmc). Unfortunately, there doesn't seem to be a way to _blacklist_ Hackage for this extension - I can only configure JSONView to none, all, or a whitelist of sites.

Still, great catch @phadej - at least now I have a workaround.
