### ISSUE TITLE
Open Graph description is outdated on package pages

### ISSUE THREAD

**Issue by MorrowM** [haskell/hackage-server#912]
The `og:description` meta tag recommends using `cabal install package-name` for installing packages.
https://github.com/haskell/hackage-server/blob/4039daa37203c1db08c7053ae2751bcf24ae0674/datafiles/templates/Html/package-page.html.st#L15-L16
As of Cabal 3.0 with the new v2-* commands being default this is no longer the recommended way to install packages. It might confuse new Haskell users who see Discord embeds still recommending to use `cabal install` to install dependencies, a matter that already trips them up.
I'm not sure what should be put here instead, suggestions?

**Comment by tomjaguarpaw** [comment]
>  I'm not sure what should be put here instead, suggestions?

The property is called "description" so how about actually the package description? That seems to be a more appropriate fit than install instructions anyway.
