### ISSUE TITLE
http should redirect to https

### ISSUE THREAD

**Issue by AlistairB** [haskell/hackage-server#916]
Hi,

One thing that mildly bugs me is that [http](http://hackage.haskell.org/package/lens) + [https](https://hackage.haskell.org/package/lens) both work for hackage. Https is more secure and if #915 is done more performant.

Also http is now flagged as insecure by browsers and penalised in search page ranking.

Looks to be as simple as https://www.nginx.com/blog/nginx-1-9-5/

```nginx
server {
    listen 80;
    location / {
        return 301 https://$host$request_uri;
    }
}
```

Happy to help if possible.

**Comment by gbaz** [comment]
I believe we've now changed this so http redirects to https for webpages, but not for tgzs (so as not to break older tooling that may not be able to handle https).

**Comment by AlistairB** [comment]
Hi, FYI this is not working for me. http://hackage.haskell.org/package/req does not redirect for example.

**Comment by gbaz** [comment]
Ok weird, it happens in firefox but not chrome, and in firefox on https I get mixed content warnings, but not on chrome. @davean any ideas?

**Comment by gbaz** [comment]
Ok I think it wasn't configured as we thought, and firefox was just being eagerly helpful. Reopening for now...

**Comment by gbaz** [comment]
Mystery solved! The redirect is done in the fastly proxy config, and it works by detecting "human agent" as `req.http.User-Agent ~ ".*Mozilla/5\.0.*"` -- i.e. its based (narrowly) on agent rather than url. I'm ok with agent based, but it obviously needs a better detection string. 🤦

**Comment by AlistairB** [comment]
Interesting. Personally I would be inclined to always redirect as with http you are vulnerable to MITM attacks. I think only minor benefit of http is avoiding the minor ssl handshake overhead, but more security always trumps that.

**Comment by gbaz** [comment]
We can't always redirect. There are programmatic tools that rely on hackage and do not use ssl capable transports. (I only know of some tools, couldn't even tell you all). It would break some number of existing integrations.

Further there is no attack of concern I know of that http leaves us vulnerable to here. The hackage-security setup ensures safety of products regardless of transport, and from the user-to-hackage side there's digest auth. 

That said, I am sympathetic. Https is nicer, and more expected these days, and certainly a way to direct humans to it more generally but not automated systems, would be good to have. So if you want to suggest a better varnish rule, I'm all ears.

**Comment by AlistairB** [comment]
I think relying on the UserAgent can be problematic. There is a general plan to move away from it https://www.infoq.com/news/2020/03/chrome-phasing-user-agent/ . Although I wonder if fastly has a feature to identify browsers so hackage doesn't need to figure out exact UA matching.

An alternative might be to only redirect for a whitelist of pages that are the HTML pages, but not redirect for pages that tools might access. Ie. endpoints or cabal files. I know in some cases it is the one page ie. https://hackage.haskell.org/package/these/revisions/ , but providing `Accept: application/json` will give you json, so I guess if you request json, you should also not get the rediect. Not sure how easy it might be to set up something like this.

**Comment by gbaz** [comment]
Ok, so it turns out that at least for now, _all major browsers_ will start with Mozilla/5.0 for historical reasons that are very funny. Our config was correct but some characteristics of some browsers and not others made other rules fire first and prevented it from firing for chrome. I increased the priority of the rule, and it seems... ok for now? Hopefully nothing new breaks and this fixes it for the time being.

**Comment by AlistairB** [comment]
Works for me :) Thanks!
