### ISSUE TITLE
Enhancement: direct link to list of maintainers

### ISSUE THREAD

**Issue by andreasabel** [haskell/hackage-server#918]
When I want to see the users with upload permissions for a package _X_ I can only get there indirectly, afaik.  
- click on the user that _Uploaded_ the last version
- on the `user` page showing a list "Maintainer for _Y_", click on the _Maintainer_ for _X_

Feature request:  _Add a direct link to the page with the current maintainers_.

Suggestion:  In the part

> ### Maintainer's Corner
>
> For package maintainers and hackage trustees
>
>  * edit package information

make _package maintainers_ clickable to target the list of current maintainers.

**Comment by int-e** [comment]
I just had the same thought on haskell-cafe. It's not obvious where to best put such a link. Quoting [myself](https://mail.haskell.org/pipermail/haskell-cafe/2021-March/133619.html):

> A direct link from the package description page could work, though it's not obvious where the best place is. An unobtrusive but perhaps too subtle place would be the "package maintainers" phrase under "Maintainer's Corner". The obvious place to look is in the summary box, but that is already very crowded.

**Comment by Bodigrim** [comment]
> When I want to see the users with upload permissions for a package X I can only get there indirectly, afaik.

There are at least two places, where this information is displayed directly:
http://hackage.haskell.org/packages/search?terms=agda (Maintainer column)
http://hackage.haskell.org/package/Agda/maintainers/

It would be nice to make the second link more visible indeed.

**Comment by gbaz** [comment]
resolved by #966
