### ISSUE TITLE
If Hayoo is dead, remove the link to it.

### ISSUE THREAD

**Issue by Jasagredo** [haskell/hackage-server#919]
It’s not a big deal but I happened to notice that at the bottom of a package search there is this message:
```
Alternatively, if you are looking for a particular function then try Hayoo or Hoogle
```
With links to both. The Hayoo link doesn’t work as Hayoo has been dead for about 2 years already?

Correct me if I’m wrong and Hayoo still is served as a web (I think you can only run it locally) but if it is dead then probably that link can be removed.

**Comment by gbaz** [comment]
resolved by #922
