### ISSUE TITLE
HTTP Digest Auth makes it impossible to implement several features

### ISSUE THREAD

**Issue by tibbe** [haskell/hackage-server#92]
By using Digest Auth we cannot easily detect if a user is logged in and adapt the UI for that case, leading to us having links users must not click (as they don't have the authorization to see the content they lead to) and not being able to add contextual actions inline on pages for users that do have access.

**Comment by gbaz** [comment]
@hvr implemented a patch for this that's deployed now where it uses a cookie alongside the auth to track auth status. I think that resolves this?
