### ISSUE TITLE
Package distributions missing Stackage link

### ISSUE THREAD

**Issue by TravisCardwell** [haskell/hackage-server#921]
The distributions for package [ttc](https://hackage.haskell.org/package/ttc) no longer lists Stackage, including older versions that previously had Stackage links.  What might be causing this issue?

Stackage links:

* [ttc on Stackage](https://www.stackage.org/package/ttc)
    * [Snapshots](https://www.stackage.org/package/ttc/snapshots)

Here is a summary of the versions included in LTS snapshots:

* [ttc-0.2.0.0](https://hackage.haskell.org/package/ttc-0.2.0.0) is in [LTS 15.0](https://www.stackage.org/lts-15.0/package/ttc-0.2.0.0) through [LTS 15.11](https://www.stackage.org/lts-15.11/package/ttc-0.2.0.0)
* [ttc-0.2.1.0](https://hackage.haskell.org/package/ttc-0.2.1.0) is in [LTS 15.12](https://www.stackage.org/lts-15.12/package/ttc-0.2.1.0) through [LTS 15.13](https://www.stackage.org/lts-15.13/package/ttc-0.2.1.0)
* [ttc-0.2.2.0](https://hackage.haskell.org/package/ttc-0.2.2.0) is in [LTS 15.14](https://www.stackage.org/lts-15.12/package/ttc-0.2.2.0) through [LTS 15.16](https://www.stackage.org/lts-15.13/package/ttc-0.2.2.0) and [LTS 16.0](https://www.stackage.org/lts-16.0/package/ttc-0.2.2.0) through [LTS 16.15](https://www.stackage.org/lts-16.15/package/ttc-0.2.2.0)
* [ttc-0.2.3.0](https://hackage.haskell.org/package/ttc-0.2.3.0) is in [LTS 16.16](https://www.stackage.org/lts-16.16/package/ttc-0.2.3.0) through [LTS 16.31](https://www.stackage.org/lts-16.31/package/ttc-0.2.3.0)
* [ttc-0.3.0.0](https://hackage.haskell.org/package/ttc-0.3.0.0) is in [LTS 17.0](https://www.stackage.org/lts-17.0/package/ttc-0.3.0.0) through [LTS 17.7](https://www.stackage.org/lts-17.7/package/ttc-0.3.0.0)

**Comment by gbaz** [comment]
You'll have to ping the stackage maintainers on this. Here are the packages stackage has listed as current: https://hackage.haskell.org/distro/Stackage/packages

Stackage has a process which uses a special account with auth to push the list thru the server api (https://hackage.haskell.org/api#distro). Their process may not be running properly, beats me?

**Comment by TravisCardwell** [comment]
> You'll have to ping the stackage maintainers on this. Here are the packages stackage has listed as current: https://hackage.haskell.org/distro/Stackage/packages
> 
> Stackage has a process which uses a special account with auth to push the list thru the server api (https://hackage.haskell.org/api#distro). Their process may not be running properly, beats me?

Thank you very much!  I created an issue in the stackage repo (linked above).

**Comment by gbaz** [comment]
Ok,I'm closing. That said, I suspect if your package is not in the latest nightly it will not be listed, because likely that's how they configured their bot.

**Comment by juhp** [comment]
We have been try to fix this for a long time - please reopen

**Comment by gbaz** [comment]
Ok sure. What's the issue? Nothing changed on the hackage server api side afaik? If you look at e.g. bytestring (https://hackage.haskell.org/package/bytestring) its pretty clear nixos has been able to push updates through the api.

**Comment by TravisCardwell** [comment]
I learned that the Stackage infrastructure has stopped uploading `LTSHaskell` and `Stackage` distribution information from February 9, 2020 due to the uploads failing with "inscrutable error messages."  This affects the distributions listings for all packages that have had Stackage updates since that date.  For example, the [bytestring](https://hackage.haskell.org/package/bytestring) page lists `LTSHaskell:0.10.8.2` and `Stackage:0.10.8.2` while recent LTS and nightly snapshots on [Stackage](https://www.stackage.org/package/bytestring) use version `0.10.12.0`.

I do not yet understand why the `LTSHaskell` and `Stackage` links for package [ttc](https://hackage.haskell.org/package/ttc) have completely disappeared.

**Comment by juhp** [comment]
The last ghc version in the Stackage/LTS distro date is 8.6.5:
https://hackage.haskell.org/package/ghc

Poking around at the versions: 

https://www.stackage.org/nightly-2019-06-20 seems a close match to `Stackage` (but `salak` mismatches somehow?).

https://www.stackage.org/lts-13.30 seems a good match for last `LTSHaskell` (dunno what is going on with salak;)

**Comment by juhp** [comment]
I need to find some time on the Stackage build server to debug the Hackage distro data again, though last time I looked I could not find anything obviously wrong with it (and it works just fine for me for Fedora - though different code is being used to generate that of course).

**Comment by juhp** [comment]
> I learned that the Stackage infrastructure has stopped uploading `LTSHaskell` and `Stackage` distribution information from February 9, 2020 due to the uploads failing with "inscrutable error messages." This affects the distributions listings for all packages that have had Stackage updates since that date. For example, the [bytestring](https://hackage.haskell.org/package/bytestring) page lists `LTSHaskell:0.10.8.2` and `Stackage:0.10.8.2` while recent LTS and nightly snapshots on [Stackage](https://www.stackage.org/package/bytestring) use version `0.10.12.0`.
> 
> I do not yet understand why the `LTSHaskell` and `Stackage` links for package [ttc](https://hackage.haskell.org/package/ttc) have completely disappeared.

https://www.stackage.org/package/ttc/snapshots

**Comment by TravisCardwell** [comment]
> The last ghc version in the Stackage/LTS distro date is 8.6.5:
> https://hackage.haskell.org/package/ghc
>
> Poking around at the versions:
>
> https://www.stackage.org/nightly-2019-06-20 seems a close match to `Stackage` (but `salak` mismatches somehow?).
>
> https://www.stackage.org/lts-13.30 (or earliest 13.28) seems a good match for last `LTSHaskell` (dunno what is going on with salak;)
>
> (I actually thought it had been broken longer than that...)

The `ttc` package has been in Stack since the following snapshots:

* [nightly-2019-12-07](https://www.stackage.org/nightly-2019-12-07/package/ttc-0.1.0.1)
* [LTS 15.0](https://www.stackage.org/lts-15.0/package/ttc-0.2.0.0), published 2020-02-16

At the time, I confirmed that `Stackage` and `LTSHaskell` links appeared on the Hackage page.  The GHC versions/dates that you found above may explain why the `Stackage` and `LTSHaskell` links have all disappeared from the `ttc` Hackage page: perhaps the `Stackage` and `LTSHaskell` information on the Hackage server has reverted to information that is from before `ttc` was released.

If the distribution package information (`packages.csv`) is stored on the filesystem, perhaps it would be worthwhile to compare the permissions of the `Stackage` and `LTSHaskell` locations with the permissions of the locations for distributions that continue to work (such as `NixOS` or `Fedora`).

Investigating [curator](https://github.com/commercialhaskell/curator), the [Curator.HackageDistro](https://github.com/commercialhaskell/curator/blob/master/src/Curator/HackageDistro.hs) module has not been changed since it was [Ported from prev curatror command for Hackage distros](https://github.com/commercialhaskell/curator/commit/bc7c0c9d6639b8739cf3ae1db2b936ee550459d9) on March 11, 2019.

**Comment by juhp** [comment]
(Well I found a Stackage team chat message from 22 July 2019 where I already had noticed the Hackage data was out of date.
Anyway I guess the actual date is less important unless it could help to track down the cause - the main thing is to fix it. :-)

**Comment by TravisCardwell** [comment]
Indeed.  Thank you!

My purpose in investigating the dates was to try to determine if the change that caused the issue was on the Hackage side or the Stackage side.  If there were no changes on the Stackage side since before the problems started, it might be worthwile to check for non-code changes on the Hackage side, such as filesystem permissions.

I now understand that the issue had already existed for a long time when the `curator hackage-distro` command was disabled.  I think I remember confirming `LTSHaskell` and `Stackage` links for the `ttc` package in early 2020, but memory if fallable and I may be mistaken.  Perhaps the issue was introduced when [curator](https://github.com/commercialhaskell/curator) replaced [stackage-curator](https://github.com/fpco/stackage-curator)...  I just checked out the upload code and the port looks straightforward/correct, however.

Perhaps `curator hackage-distro` could be executed manually to see what happens?

**Comment by juhp** [comment]
No progress yet alas, but this is the error on the stackage side:

```
Uploading Hackage distro for snapshot.yaml
Uploading as Hackage distro: Stackage
curator: HttpExceptionRequest Request {
  host                 = "hackage.haskell.org"
  port                 = 443
  secure               = True
  requestHeaders       = [("Authorization","<REDACTED>"),("Content-Type","text/csv")]
  path                 = "/distro/Stackage/packages.csv"
  queryString          = ""
  method               = "PUT"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
 InvalidChunkHeaders
Mon Apr 19 03:15:31 UTC 2021
```

**Comment by juhp** [comment]
I tried again by hand and got a different error:
```
responseBody = "Could not parse CSV File: \"PUT input\" (line 1, column 15):\nunexpected 'A'\nexpecting \",\" or end of input"
```

**Comment by TravisCardwell** [comment]
In the current CSV file ([packages.csv](https://hackage.haskell.org/distro/Stackage/packages.csv)), the first line is as follows:

```
"ALUT","2.4.0.3","https://www.stackage.org/package/ALUT"
```

The error message looks like one that is caused by incorrect quoting, but that line looks fine to me.  I do not see an "A" character near column 15, however, so perhaps the file being processed is different...  Perhaps a file with an additional first column is being sent when running manually?

The code that parses the CSV content and returns that error message is in [Distribution.Server.Features.Distro](https://github.com/haskell/hackage-server/blob/c40bc16ff221505c6a9cd1099460cf72af56228f/Distribution/Server/Features/Distro.hs#L249).  It is using the [csv](https://hackage.haskell.org/package/csv) package, which has not changed in over 10 years.  I did a quick test to see if that package can parse the above `packages.csv` file, and it parsed successfully.

----

Test script:

```haskell
#!/usr/bin/env stack
{- stack
  script
  --resolver lts-14.27
  --package csv
 -}

module Main (main) where

-- https://hackage.haskell.org/package/csv
import qualified Text.CSV as CSV

------------------------------------------------------------------------------

main :: IO ()
main =
    putStrLn . either show (const "success")
      =<< CSV.parseCSVFromFile "packages.csv"
```

**Comment by juhp** [comment]
Thanks, Travis - I have been doing some debugging, unfortunately this seems to be completely curator's fault: the uploaded csv data is using raw Show strings for PackageName and Version... oh dear.

Feel free to close this ticket again - I will continue work in commercialhaskell/curator#8 with a PR.

**Comment by TravisCardwell** [comment]
No problem, Jens.  I am happy to help.  I am glad to hear that you found the issue!  I have subscribed to your `curator` ticket and will continue to follow along there.

I am closing this issue since the problem is not on the `hackage-server` side.

**Comment by juhp** [comment]
Okay we have a successful manual upload:

eg see https://hackage.haskell.org/package/ttc
