### ISSUE TITLE
Compilation on Windows?

### ISSUE THREAD

**Issue by LaurentRDC** [haskell/hackage-server#926]
Hello,

I wanted to contribute to `hackage-server` but it appears that it cannot be compiled on Windows due to a reliance on the `unix` library and POSIX signals.

I would like to inquire if modifications to support Windows is a hard no?

There are a few things that can be made cross-platform (e.g. [`fsync`](https://github.com/haskell/hackage-server/blob/c40bc16ff221505c6a9cd1099460cf72af56228f/Distribution/Server/Framework/BlobStorage.hs#L211) has a Windows equivalent, `flushFileBuffers`) , but the reliance on the [SIGUSR1 and SIGUSR2 signals is problematic](https://github.com/haskell/hackage-server/blob/c40bc16ff221505c6a9cd1099460cf72af56228f/exes/Main.hs#L347) as there are no Windows-equivalent for arbitrary signals. That would have to change.

If maintainers are open to supporting Windows, I can contribute time to get it done.

Edit: yes I could use the Windows Subsystem for Linux in theory, but a bug has prevented me from upgrading to Ubuntu 20.10 which means I'm stuck on Cabal 2.4.

**Comment by gbaz** [comment]
Is cabal 2.4 a hard no for hackage server? I'm not sure...

I'd say an openness to adding windows equivs for things like fsync is certainly there, but I'm not necessarily keen on getting rid of the signals stuff in the core architecture. Maybe it could be conditionally compiled out for windows?

(you could also develop on windows using virtualbox -- far from ideal, i know)

**Comment by LaurentRDC** [comment]
`hackage-server.cabal` requires cabal 3.0. Trying to build with cabal 2.4.0.0 yields:

```
CabalFileParseError "./hackage-server.cabal" [PError (Position 30 21) "\nunexpected \"{\"\nexpecting space or integral\n\nGHC == { 8.6.5, 8.4.4, 8.2.2, 8.0.2, 7.10.3, 7.8.4, 7.6.3 }\n",PError (Position 0 0) "Unsupported cabal-version. See https://github.com/haskell/cabal/issues/4899."] (Just (mkVersion [3,0])) []
```

After looking at the code a bit more, there are lots of POSIX signal uses. It would be very messy to add CPP macros everywhere. I'll keep trying to get it working on Linux.

**Comment by andreasabel** [comment]
I am closing this since there hasn't been any activity in 2 years.  Of course, feel free to reopen with new information...
