### ISSUE TITLE
Does "search in package by name" for TUI browsers like lynx, eww exist?

### ISSUE THREAD

**Issue by madjestic** [haskell/hackage-server#927]
Hey guys,
When I use chrome browser or similar and open a package page on hackage.haskell.org, I am usually able to press `s` for a very handy `Search in package by name` window pop up:
![image](https://user-images.githubusercontent.com/3270083/116796815-c8e7de80-aadf-11eb-996e-116b4f253a93.png)

I wonder if something similar is achievable, using a text-based browser like eww or lynx, etc.?

Regards,
Vladimir

**Comment by gbaz** [comment]
I think this is unlikely as the feature is driven by javascript. Sorry...
