### ISSUE TITLE
Hackage revisions endpoint no longer using iso 8601 for `time`

### ISSUE THREAD

**Issue by AlistairB** [haskell/hackage-server#933]
Hi,

Not sure if this is an actual issue, but I thought I would raise it just in case. Prior to the hackage maintenance the revisions endpoint would return the following JSON.

```json
[
 {
    "user": "phadej",
    "number": 0,
    "time": "2020-07-14T18:40:29Z"
  }
]
```

The `time` is in iso 8601 format. However, after the maintenance it now is ` "time": "2020-07-14T18:40:29UTC"`, which is not iso 8601. This actually fails to decode with the default `aeson` decoder for `UTCTime`. As such I am using `parseTimeM False defaultTimeLocale "%Y-%-m-%-dT%H:%M:%SUTC"`.

You can reproduce with `curl -H "Accept: application/json" https://hackage.haskell.org/package/these/revisions/`

I think this should probably still be iso 8601 format?

**Comment by gbaz** [comment]
Good catch! This is definitely a reversion, though I don't know what may have introduced it... 

https://github.com/haskell/hackage-server/pull/866/files#diff-6da5db5bf62c0ccfb81438d7159d0aa698ca708e0460316653107d3d8ef91d25R716 is where the current line that I think generates this was introduced...

I suspect the problem isn't in hackage code per se, but that it links against a newer version of the time lib, and the correct output formats now would come from using functions in https://hackage.haskell.org/package/time-1.11.1.2/docs/Data-Time-Format-ISO8601.html

Likely everywhere else the above PR touched would need to be fixed as well. PR's welcome :-) Also cc @phadej

**Comment by AlistairB** [comment]
Ok good to know, I might do some investigation and attempt a PR :)
