### ISSUE TITLE
413 Request Entity Too Large

### ISSUE THREAD

**Issue by jgm** [haskell/hackage-server#935]
Trying to upload the latest release of pandoc (2.14), I get:
```
Error uploading /Users/jgm/src/pandoc/dist-newstyle/sdist/pandoc-2.14.tar.gz:
http code 413
<html>
<head><title>413 Request Entity Too Large</title></head>
<body>
<center><h1>413 Request Entity Too Large</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
```
The tarball is 13221798 bytes.
Is this expected?  Can the size limit be increased?

**Comment by phadej** [comment]
Why `pandoc` is so large?

Contents of tarball are

```
4,0K	app
8,0K	AUTHORS.md
4,0K	benchmark
4,0K	BUGS
4,0K	cabal.project
848K	changelog.md
200K	citeproc
20K	CONTRIBUTING.md
20K	COPYING.md
12K	COPYRIGHT
936K	data
16K	INSTALL.md
244K	man
220K	MANUAL.txt
40K	pandoc.cabal
4,0K	prelude
12K	README.md
4,0K	Setup.hs
3,3M	src
4,0K	stack.yaml
20M	test
16K	trypandoc
```

Note the 20M in `tests`, can they be distributed off-Hackage? Also almost a megabyte large changelog is suspicious, maybe trim it a bit.

I'd be :+1: to give `pandoc` special rights to be big, but in general 10MB source distributions is very suspicious, so I'm :-1: on general limit increase.

**Comment by jgm** [comment]
For reference, pandoc 2.13's tarball was 12959060 bytes.
That uploaded without trouble.  I wonder if the Hackage service that was supposed to happen this week changed something?

**Comment by jgm** [comment]
I can see what can be done about trimming tests.  But keep in mind that pandoc is a very big package.  If it were split up into smaller packages, it would occupy the same amount of space on the Hackage server but not go beyond the size limit.  There may be valid reasons for splitting up the package (and that's something we're considering), but a size limit on the server shouldn't be one of them if it doesn't make any difference to the amount of data stored on the server.

**Comment by jgm** [comment]
I don't really see how I can trim the changelog without removing historical data about the changes that have been made. This is a package that has been going since 2006...

**Comment by jgm** [comment]
It looks like the powerpoint tests contain a large number of big files.  I think we could reduce this quite a bit (megabytes).

**Comment by jgm** [comment]
It looks like the pptx tests all contain `_templated` variants which are 300K+!
Unfortunately, I don't know much about why this was needed, but it should be easy to get substantial reductions.  Pinging @jkr (author of this code) -- can you comment on why we need the `_templated` variants, and whether they could be reduced?

**Comment by jgm** [comment]
Looks like all the `_templated` pptx files contain a 300K image that is just a color gradient!
So that will be an easy way to trim the fat.

**Comment by phadej** [comment]
> I don't really see how I can trim the changelog without removing historical data about the changes that have been made. This is a package that has been going since 2006...

One way is to have the full changelog in repository and only have a file with a link to it in the uploaded source distrubution. Or a trimmed version, e.g. what changed in the last year or two.

**Comment by jgm** [comment]
Just changing the pptx tests gets the tarball down to 5.4 MB.

**Comment by jgm** [comment]
I'd be inclined to keep the changelog as it is for now, if that's okay.

**Comment by gbaz** [comment]
Great! Also there's a regression here in that when we performed the server migration, we didn't tweak the nix config to allow larger file sizes as we have in the past... On it now.

**Comment by gbaz** [comment]
Should be bumped to a 10MB limit (was 20 on the old server, I'm being increasingly conservative). Lmk if there's something still wrong.

**Comment by jgm** [comment]
Great, I just uploaded, after whittling it down to < 5 MB.
