### ISSUE TITLE
Cpphs dependency not found for hackage CI but works fine locally

### ISSUE THREAD

**Issue by j-mie6** [haskell/hackage-server#944]
The builds on a package I maintain are failing because `cpphs >=1.19` ~~cannot be satisfied during the dependency resolution~~ does not seem to be requested during dependencies, and then fails in configuration. Except this is not a problem when the package is used on any of the 3 machines I've tried it on (all of which installing via cabal and hackage), it only appears to occur on hackage's build server. Here is the relevant report: https://hackage.haskell.org/package/parsley-0.1.0.1/reports/1.

I could be mistaken that there is an issue with Hackage at play here, however!

**Comment by gbaz** [comment]
Well indeed there's no cpphs installed in the docbuilder box in a findable way (i.e. in a default path). If you're using v2-build (the default on newer cabals) then the build-tool-depends will fetch it for you. Unfortunately, the docbuilder is stuck on v1-build. Its possible to install cpphs on the system directly -- however, I have to ask why you're not just using the `{-# LANGUAGE CPP #-}` pragama, which is the much more standard way to do things?

**Comment by j-mie6** [comment]
The default C Pre-Processor doesn't work on my code-base, if I remember correctly it's because of `MagicHash`, but it might have also been a `TemplateHaskell` issue (`MagicHash` seems more likely, given that `#` is used for C macros...)

**Comment by gbaz** [comment]
Ok, cpphs should be installed directly on the machine now (I tested out a build requiring it and it worked).

**Comment by j-mie6** [comment]
Looks like this has regressed recently. The most recent build of `parsley` and `parsley-core` are both failing because `cpphs` is not found
