### ISSUE TITLE
Banner "documentation unavailable" displayed for executables

### ISSUE THREAD

**Issue by andreasabel** [haskell/hackage-server#945]
If you look e.g. at https://hackage.haskell.org/package/alex , it flags in red "Documentation Unavailable".  However, this is an executable-only package which does not ship with haddockumentation.  It is probably better to not put the red banner up in such cases, as it suggests that something is missing/does not work when in reality everything is fine.

**Comment by hsek** [comment]
I added a check if it doesn't have a library component but has executables. It'll just hide the doc banner if that's the case. Are there any other conditions to be aware of?

**Comment by gbaz** [comment]
I think that condition suffices!
