### ISSUE TITLE
usernames should not be easily discoverable

### ISSUE THREAD

**Issue by ketzacoatl** [haskell/hackage-server#948]
We use our login credentials to access protected functions and so the system knows who we are when performing those functions. Hackage is a database of packages used by the Haskell ecosystem. Package supply chain attacks are a real thing. Protecting packages, is important. As part of that, we need to protect admins (hackage users) who manage those packages. There should be no public list of usernames. If a username must be looked up, a user should have a form where they provide an email address, and if the system has a username associated with that email, an email is sent to the address with the username noted therein. At the very least, we could provide the list of users without their usernames, eg using the "display name". The list of usernames should not be discoverable as they are.

**Comment by phadej** [comment]
I don't understand what concrete changes you are requesting to be done.

Who uploaded packages, and who are the maintainers off a package is important information for the livehood of the ecosystem. (i.e *Uploaded by* and the package maintainers list (which AFAIK there is no direct link)).

If you are worried about https://hackage.haskell.org/users/, I agree, that endpoint is completely useless.

**Comment by ketzacoatl** [comment]
The issue is not about who maintains a given package, but rather the fact that usernames for _all_ users of hackage are so easily discoverable. Dropping the users endpoint would be a great start. The other update is to use the user's display name rather than their username (when referring to the user in packages/etc).

**Comment by hsek** [comment]
Should I keep the users endpoint for admins only, or do I just remove it entirely?

**Comment by phadej** [comment]
> but rather the fact that usernames for all users 

What is a usecase to have an account on Hackage if person is not planning to become a package maintainer? There are probably many such user accounts, but IMO they can be just dropped.

**Comment by ketzacoatl** [comment]
@phadej again, the issue is about how easily discoverable the actual usernames are, for all users, and is relevant for phishing and security and privacy in general.

**Comment by phadej** [comment]
For uploader, it's very simple, index file has everything already:

```
% tar -tzvf /cabal/packages/hackage.haskell.org/01-index.tar.gz|head -n 30
-rw-r--r-- IanLynagh/Hackage 779 2006-09-06 02:37 iconv/0.2/iconv.cabal
-rw-r--r-- IsaacJones/Hackage 4541 2006-09-24 22:15 Crypto/3.0.3/Crypto.cabal
-rw-r--r-- IsaacJones/Hackage  481 2006-09-24 22:15 HDBC/1.0.1/HDBC.cabal
-rw-r--r-- IsaacJones/Hackage  704 2006-09-24 22:15 HDBC-odbc/1.0.1.0/HDBC-odbc.cabal
-rw-r--r-- IsaacJones/Hackage  757 2006-09-24 22:15 HDBC-postgresql/1.0.1.0/HDBC-postgresql.cabal
-rw-r--r-- IsaacJones/Hackage  618 2006-09-24 22:15 HDBC-sqlite3/1.0.1.0/HDBC-sqlite3.cabal
-rw-r--r-- IsaacJones/Hackage  376 2006-09-24 22:15 darcs-graph/0.1/darcs-graph.cabal
-rw-r--r-- IsaacJones/Hackage  530 2006-09-24 22:15 hask-home/2006.3.23/hask-home.cabal
-rw-r--r-- IsaacJones/Hackage  890 2006-09-24 22:15 hmp3/1.1/hmp3.cabal
-rw-r--r-- IsaacJones/Hackage 2143 2006-09-24 22:15 lambdabot/4.0/lambdabot.cabal
-rw-r--r-- IsaacJones/Hackage  446 2006-09-24 22:15 parsedate/2006.6.4/parsedate.cabal
-rw-r--r-- IsaacJones/Hackage 1161 2006-09-24 22:15 plugins/1.0/plugins.cabal
-rw-r--r-- DuncanCoutts/Hackage 595 2006-09-24 22:29 zlib/0.2/zlib.cabal
-rw-r--r-- DuncanCoutts/Hackage 504 2006-09-24 22:30 bzlib/0.2/bzlib.cabal
-rw-r--r-- DavidHimmelstrup/Hackage 638 2006-09-27 00:08 libxml/0.1/libxml.cabal
-rw-r--r-- DavidHimmelstrup/Hackage 491 2006-09-27 00:10 xslt/0.1/xslt.cabal
-rw-r--r-- DavidHimmelstrup/Hackage 732 2006-09-27 00:13 hxweb/0.1/hxweb.cabal
```

I don't see how removing `/users` endpoint would make figuring out usernames of (active) uploaders considerably harder.

**Comment by ketzacoatl** [comment]
I did not realize that. Good point. I guess that's unfortunate, but understandable.
