### ISSUE TITLE
maintainer group should be explicitly listed on package page

### ISSUE THREAD

**Issue by gbaz** [haskell/hackage-server#953]
its a bit inconvenient to only be able to click through to the user page of the last uploader, and not all maintainers (and also harder to discover).

**Comment by phadej** [comment]
There are plenty of packages, with "honorary past" maintainers, e.g. https://hackage.haskell.org/package/aeson/maintainers/

I don't have any need to remove others from that list, but OTOH having Bryan mentioned on the aeson package won't serve any good.

There is `maintainer: ` field in the `.cabal` metadata (which can be updated via revision). How to avoid confusion between that and *people with upload rights* on Hackage?

i don't think this is good first issue as the spec is not clear.

**Comment by andreasabel** [comment]
Maybe #918 would be enough for now...

**Comment by gbaz** [comment]
closing as dup of https://github.com/haskell/hackage-server/issues/637 (which should be resolved by gsoc work)
