### ISSUE TITLE
"docs pending"

### ISSUE THREAD

**Issue by chris-martin** [haskell/hackage-server#954]
I published [a package](https://hackage.haskell.org/package/lazy-async) about twelve hours ago, and there are still no haddocks; it says "Docs pending, Build status unknown". What does that mean? Is there a long doc-building queue, or has the doc building failed? I have no visibility into what's going on here or whether there's something wrong that I need to fix.

**Comment by gbaz** [comment]
Thanks for the ticket. It looks like the docbuilder got wedged some time ago. I just unstuck it...
