### ISSUE TITLE
Add archive feature

### ISSUE THREAD

**Issue by jappeace** [haskell/hackage-server#969]
Several packages on hackage have their github repositories archived, for example:

+ https://hackage.haskell.org/package/monomorphic-0.0.3.3
  with the related github https://github.com/konn/monomorphic
+ https://hackage.haskell.org/package/convert
   with the github https://github.com/enso-org/convert
   
 It be nice if maintainers could indicate to users that something is no longer is maintained trough an archive flag.
 This should also make the process of taking over a package easier.

**Comment by gbaz** [comment]
Maintainers can deprecate packages (e.g. https://hackage.haskell.org/packages/deprecated) to indicate they are no longer maintained. Deprecated packages also have an easier takeover process. In other words, I think the deprecation flag is already the feature you're asking for? 

See the "taking over a package" link on the hackage homepage.

If you think there's a particular place to document it better, feel free to open an issue or submit a pr, etc.

**Comment by jappeace** [comment]
Thanks, that's pretty much exactly it.
