### ISSUE TITLE
Outdated instructions in opengraph metadata

### ISSUE THREAD

**Issue by fgaz** [haskell/hackage-server#971]
The description of every package page tells the user to install it via `cabal install $pkg`, while (at least for libraries) the correct advice would be "add `$pkg` to the `build-depends` section of your .cabal file"

![image](https://user-images.githubusercontent.com/8182846/131224006-ebc948d2-f85e-4283-8ecf-9c20ef0544ea.png)

**Comment by Mikolaj** [comment]
Right. And if the text is longer and includes `cabal install`, it should qualify it's only for installing exes, while for toying with libraries in ghci, one needs to do `cabal repl --build-depends foo` instead.

**Comment by gbaz** [comment]
Dup of #912, resolved by https://github.com/haskell/hackage-server/pull/962, deploying Real Soon Now (tm)
