### ISSUE TITLE
Readme update

### ISSUE THREAD

**Issue by Boarders** [haskell/hackage-server#974]
The readme recommends installing via:
```
cabal install -j --enable-tests
```
When I do this I get:
```
cabal: --enable-tests was specified, but tests can't be enabled in a remote
package
```

Would it be equivalent in current `cabal` to do something like:
```
cabal configure --enable-tests
cabal install -j
```

**Comment by gbaz** [comment]
i'm not sure why we even really want to recommend with enable tests on install? seems a bit odd to me. also we don't really need to tell people to use `-j` since they can build in parallel or not if they want -- not our business. I'd be happy with a pr that just said "cabal install," lol.
