### ISSUE TITLE
Make account upgrade possible without password

### ISSUE THREAD

**Issue by mruegenberg** [haskell/hackage-server#98]
Hi,
anyone who forgot their password from the old Hackage has a problem, since they need to [upgrade their account](http://hackage.haskell.org/users/htpasswd-upgrade) to use the new Hackage, but the [password reset form](http://hackage.haskell.org/users/password-reset) apparently only works with updated accounts.

Suggestion: Make it possible to upgrade accounts without the password, by sending a confirmation e-mail.

Also, it would be helpful if `guardSuitableAccountType` (in Distribution/Server/Features/UserSignup.hs) had some reference to the account update form.

**Comment by greenrd** [comment]
Can someone reset my password please? My username is RobinGreen.

**Comment by hesselink** [comment]
@greenrd I've sent you a password reset.

For other people finding this: please send an email to admin@hackage.haskell.org instead of posting to this bug tracker.

**Comment by gbaz** [comment]
I think we should close this as won'tfix, especially as there are increasingly few legacy accounts over time, so the pain diminishes...

**Comment by gbaz** [comment]
at this point there are very few legacy accounts left to migrate. going to close.

**Comment by hesselink** [comment]
Sounds good. I think for future migrations like this, actually writing the code to make it work would be a good idea; this ended up costing quite a bit of time (although spread out over time).
