### ISSUE TITLE
Triggering a docs rebuild doesn't work

### ISSUE THREAD

**Issue by sjakobi** [haskell/hackage-server#988]
The docs build for https://hackage.haskell.org/package/dhall-toml-1.0.0 didn't succeed. I've tried triggering another build about 20h ago, but no build report for a third build has shown up in https://hackage.haskell.org/package/dhall-toml-1.0.0/reports/.

**Comment by gbaz** [comment]
the docs rebuild does work. the problem was it works in reverse-chron order and kept getting stuck behind and idris build that's been timing out. resolved manually. thanks for the report!

**Comment by sjakobi** [comment]
Thanks! Do you have a suggestion on how to debug the build? https://hackage.haskell.org/package/dhall-toml-1.0.0/reports/3 says

```
cabal: Error: some packages failed to install:
dhall-toml-1.0.0-JZavZh9mUig7VChQJx37n depends on dhall-toml-1.0.0 which
failed to install.
tomland-1.3.3.0-FijESnmJn7i3Cvr3ofvX5I failed during the building phase. The
exception was:
ExitFailure 1
```

How do I figure out what the problem with `tomland` is? (CC @chshersh, @vrom911)

**Comment by sjakobi** [comment]
Ah, I think I've found it. The build log says:

```
Building executable 'readme' for tomland-1.3.3.0..
ghc: could not execute: markdown-unlit
```

@chshersh, @vrom911, is that something that you could fix, so packages that depend on `tomland` can use the automatic docs build again?

**Comment by sjakobi** [comment]
For example, the `readme` executable could be enabled with a flag that is off by default.

**Comment by chshersh** [comment]
@sjakobi I believe it shouldn't be `tomland`'s job. This will increase the maintainability cost for `tomland`. We use `markdown-unlit` only in the executable so it shouldn't affect the generation of documentation.

If you need to have documentation on Hackage urgently, you can upload it manually with the following two commands:

```shell
cabal haddock --enable-documentation --haddock-for-hackage
cabal upload -d <path_from_previous_command> --publish -u <user> -p <password>
```

**Comment by sjakobi** [comment]
@gbaz Could you clarify why the docs builder attempts to build `tomland`'s `readme` executable, and why running `markdown-unlit` fails?

Since `markdown-unlit`'s build doesn't show up in the build log, is it possible that the docs builder simply doesn't support `build-tool-depends`?

In any case, it would be nice to get a fix for building `tomland` in the docs builder, since until then both `tomland` maintainers and maintainers of packages that depend on `tomland` will need to upload docs manually.

**Comment by gbaz** [comment]
cf: https://github.com/haskell/hackage-server/issues/821

There's a patch in cabal master which should enable the eventual v2 migration.
