### ISSUE TITLE
Uploaders should be notified when the docs build fails

### ISSUE THREAD

**Issue by sjakobi** [haskell/hackage-server#989]
This would make it easier to discover and fix missing-docs issues in a timely manner.

**Comment by gbaz** [comment]
pr that started on notification email work: https://github.com/haskell/hackage-server/pull/622

**Comment by gbaz** [comment]
should be resolved by https://github.com/haskell/hackage-server/pull/1110 ?

**Comment by sjakobi** [comment]
> should be resolved by #1110 ?

Wow, this looks great! When will this go live? Also, will there be a setting "notify me about docbuilder failures, but not about successes"?

**Comment by gbaz** [comment]
Hopefully this should all be rounded out and deployed with the other gsoc stuff at the end of summer. Good proposal about notify on failures only. @AliasQli

**Comment by andreasabel** [comment]
I'd guess this has been deployed by now.
