### ISSUE TITLE
Mathjax messes up hackage docs for operators containing `$$$$`

### ISSUE THREAD

**Issue by 414owen** [haskell/hackage-server#998]
[Some haskell operators](https://hackage.haskell.org/package/functor-infix-0.0.5/docs/Data-Functor-Infix.html) contain a few `$$` symbols.

Mathjax seems to be taking it upon itself to reformat these.

I think we should probably add our Mathjax ignore class to type signatures.

**Comment by gbaz** [comment]
I'd encourage you to open a ticket (and better yet a PR) in the haddock repo for this. The hackage server repo just uses haddock under the hood :-)

**Comment by ulysses4ever** [comment]
@414owen this [has been fixed in Haddock](https://github.com/haskell/haddock/pull/960) somewhere around late 2018, and the doc you reference comes from a release in 2017. They would need a new release of the package to fix that I think.
